import devicebeans.DeviceButtons;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @author Cesare
 */
public class ACQIPPSETUPSetup extends DeviceSetup{
    /**
     *
     */
    private static final long  serialVersionUID = -2926448048485819965L;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons      deviceButtons1;
    private DeviceChoice       deviceChoice1;
    private DeviceChoice       deviceChoice2;
    private DeviceChoice       deviceChoice3;
    private DeviceDispatch     deviceDispatch1;
    private DeviceField        deviceField1;
    private DeviceField        deviceField10;
    private DeviceField        deviceField11;
    private DeviceField        deviceField2;
    private DeviceField        deviceField3;
    private DeviceField        deviceField4;
    private DeviceField        deviceField5;
    private DeviceField        deviceField6;
    private DeviceField        deviceField7;
    private DeviceField        deviceField8;
    private DeviceField        deviceField9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;

    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form ACQIPPSETUPSetup
     */
    public ACQIPPSETUPSetup(){
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.deviceButtons1 = new DeviceButtons();
        this.jPanel1 = new javax.swing.JPanel();
        this.jPanel7 = new javax.swing.JPanel();
        this.jPanel2 = new javax.swing.JPanel();
        this.deviceField1 = new DeviceField();
        this.deviceDispatch1 = new DeviceDispatch();
        this.jPanel3 = new javax.swing.JPanel();
        this.deviceField2 = new DeviceField();
        this.deviceField3 = new DeviceField();
        this.deviceField4 = new DeviceField();
        this.deviceChoice1 = new DeviceChoice();
        this.jPanel5 = new javax.swing.JPanel();
        this.deviceField8 = new DeviceField();
        this.deviceField9 = new DeviceField();
        this.deviceField10 = new DeviceField();
        this.deviceChoice3 = new DeviceChoice();
        this.jPanel4 = new javax.swing.JPanel();
        this.jPanel6 = new javax.swing.JPanel();
        this.deviceField5 = new DeviceField();
        this.deviceField6 = new DeviceField();
        this.deviceField7 = new DeviceField();
        this.deviceChoice2 = new DeviceChoice();
        this.deviceField11 = new DeviceField();
        this.setDeviceProvider("localhost");
        this.setDeviceTitle("Probes & TC  Acquisition Setup");
        this.setDeviceType("ACQIPPSETUP");
        this.setHeight(400);
        this.setWidth(850);
        this.getContentPane().add(this.deviceButtons1, java.awt.BorderLayout.PAGE_END);
        this.jPanel1.setLayout(new java.awt.GridLayout(2, 0));
        this.jPanel7.setLayout(new java.awt.GridLayout(3, 0));
        this.jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        this.jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceField1.setIdentifier("");
        this.deviceField1.setLabelString("Comment:");
        this.deviceField1.setNumCols(50);
        this.deviceField1.setOffsetNid(1);
        this.deviceField1.setTextOnly(true);
        this.jPanel2.add(this.deviceField1);
        this.jPanel2.add(this.deviceDispatch1);
        this.jPanel7.add(this.jPanel2);
        this.jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Probe Acquisition"));
        this.jPanel3.setName("Probe Acquisition"); // NOI18N
        this.deviceField2.setIdentifier("");
        this.deviceField2.setLabelString("Start Time (s):");
        this.deviceField2.setOffsetNid(3);
        this.jPanel3.add(this.deviceField2);
        this.deviceField3.setIdentifier("");
        this.deviceField3.setLabelString("End Time (s):");
        this.deviceField3.setOffsetNid(4);
        this.jPanel3.add(this.deviceField3);
        this.deviceField4.setIdentifier("");
        this.deviceField4.setLabelString("Frequency (Hz):");
        this.deviceField4.setOffsetNid(5);
        this.jPanel3.add(this.deviceField4);
        this.deviceChoice1.setChoiceItems(new String[]{"EXTERNAL", "INTERNAL"});
        this.deviceChoice1.setIdentifier("");
        this.deviceChoice1.setLabelString("Trig. Mode:");
        this.deviceChoice1.setOffsetNid(6);
        this.deviceChoice1.setUpdateIdentifier("");
        this.jPanel3.add(this.deviceChoice1);
        this.jPanel7.add(this.jPanel3);
        this.jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thermocouples Acquisition"));
        this.deviceField8.setIdentifier("");
        this.deviceField8.setLabelString("Start Time (s):");
        this.deviceField8.setOffsetNid(16);
        this.jPanel5.add(this.deviceField8);
        this.deviceField9.setIdentifier("");
        this.deviceField9.setLabelString("End Time (s):");
        this.deviceField9.setOffsetNid(17);
        this.jPanel5.add(this.deviceField9);
        this.deviceField10.setIdentifier("");
        this.deviceField10.setLabelString("Frequency (Hz):");
        this.deviceField10.setOffsetNid(18);
        this.jPanel5.add(this.deviceField10);
        this.deviceChoice3.setChoiceItems(new String[]{"EXTERNAL", "INTERNAL"});
        this.deviceChoice3.setIdentifier("");
        this.deviceChoice3.setLabelString("Trig. Mode:");
        this.deviceChoice3.setOffsetNid(19);
        this.deviceChoice3.setUpdateIdentifier("");
        this.jPanel5.add(this.deviceChoice3);
        this.jPanel7.add(this.jPanel5);
        this.jPanel1.add(this.jPanel7);
        this.jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sweep Voltage Configuration"));
        this.jPanel4.setLayout(new java.awt.GridLayout(3, 0));
        this.jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        this.deviceField5.setIdentifier("");
        this.deviceField5.setLabelString("Min Value (V):");
        this.deviceField5.setOffsetNid(11);
        this.jPanel6.add(this.deviceField5);
        this.deviceField6.setIdentifier("");
        this.deviceField6.setLabelString("Max Value (V):");
        this.deviceField6.setOffsetNid(12);
        this.jPanel6.add(this.deviceField6);
        this.deviceField7.setIdentifier("");
        this.deviceField7.setLabelString("Frequency (Hz):");
        this.deviceField7.setOffsetNid(13);
        this.jPanel6.add(this.deviceField7);
        this.deviceChoice2.setChoiceItems(new String[]{"EXTERNAL", "INTERNAL"});
        this.deviceChoice2.setIdentifier("");
        this.deviceChoice2.setLabelString("Trig. Mode:");
        this.deviceChoice2.setOffsetNid(14);
        this.deviceChoice2.setUpdateIdentifier("");
        this.jPanel6.add(this.deviceChoice2);
        this.jPanel4.add(this.jPanel6);
        this.deviceField11.setIdentifier("");
        this.deviceField11.setLabelString("Expression:");
        this.deviceField11.setNumCols(60);
        this.deviceField11.setOffsetNid(22);
        this.jPanel4.add(this.deviceField11);
        this.jPanel1.add(this.jPanel4);
        this.getContentPane().add(this.jPanel1, java.awt.BorderLayout.CENTER);
        this.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents
}
