/*
 * A basic implementation of the DeviceSetup class.
 */
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JFrame;
import devicebeans.DeviceButtons;
import devicebeans.DeviceChannel;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

public class ADC265Setup extends DeviceSetup{
    /**
     * 
     */
    private static final long serialVersionUID = 8048392877318773219L;

    static public void main(final String args[]) {
        (new ADC265Setup()).setVisible(true);
    }
    DeviceButtons           deviceButtons1    = new DeviceButtons();
    DeviceChannel           deviceChannel1    = new DeviceChannel();
    DeviceChannel           deviceChannel2    = new DeviceChannel();
    DeviceChannel           deviceChannel3    = new DeviceChannel();
    DeviceChannel           deviceChannel4    = new DeviceChannel();
    DeviceChoice            deviceChoice1     = new DeviceChoice();
    DeviceChoice            deviceChoice10    = new DeviceChoice();
    DeviceChoice            deviceChoice11    = new DeviceChoice();
    DeviceChoice            deviceChoice12    = new DeviceChoice();
    DeviceChoice            deviceChoice13    = new DeviceChoice();
    DeviceChoice            deviceChoice2     = new DeviceChoice();
    DeviceChoice            deviceChoice3     = new DeviceChoice();
    DeviceChoice            deviceChoice4     = new DeviceChoice();
    DeviceChoice            deviceChoice5     = new DeviceChoice();
    DeviceChoice            deviceChoice6     = new DeviceChoice();
    DeviceChoice            deviceChoice7     = new DeviceChoice();
    DeviceChoice            deviceChoice8     = new DeviceChoice();
    DeviceChoice            deviceChoice9     = new DeviceChoice();
    DeviceDispatch          deviceDispatch1   = new DeviceDispatch();
    // }}
    // {{DECLARE_CONTROLS
    DeviceField             deviceField1      = new DeviceField();
    DeviceField             deviceField10     = new DeviceField();
    DeviceField             deviceField11     = new DeviceField();
    DeviceField             deviceField12     = new DeviceField();
    DeviceField             deviceField13     = new DeviceField();
    DeviceField             deviceField14     = new DeviceField();
    DeviceField             deviceField15     = new DeviceField();
    DeviceField             deviceField16     = new DeviceField();
    DeviceField             deviceField17     = new DeviceField();
    DeviceField             deviceField18     = new DeviceField();
    DeviceField             deviceField19     = new DeviceField();
    DeviceField             deviceField2      = new DeviceField();
    DeviceField             deviceField3      = new DeviceField();
    DeviceField             deviceField4      = new DeviceField();
    DeviceField             deviceField5      = new DeviceField();
    DeviceField             deviceField6      = new DeviceField();
    DeviceField             deviceField7      = new DeviceField();
    DeviceField             deviceField8      = new DeviceField();
    DeviceField             deviceField9      = new DeviceField();
    // Used by addNotify
    boolean                 frameSizeAdjusted = false;
    javax.swing.JPanel      JPanel1           = new javax.swing.JPanel();
    javax.swing.JPanel      JPanel2           = new javax.swing.JPanel();
    javax.swing.JPanel      JPanel3           = new javax.swing.JPanel();
    javax.swing.JPanel      JPanel4           = new javax.swing.JPanel();
    javax.swing.JTabbedPane JTabbedPane1      = new javax.swing.JTabbedPane();

    public ADC265Setup(){
        this((JFrame)null);
    }

    public ADC265Setup(final JFrame parent){
        super(parent);
        // This code is automatically generated by Visual Cafe when you add
        // components to the visual environment. It instantiates and initializes
        // the components. To modify the code, only use code syntax that matches
        // what Visual Cafe can generate, or Visual Cafe may be unable to back
        // parse your Java file into its visual environment.
        // {{INIT_CONTROLS
        getContentPane().setLayout(null);
        setSize(533, 505);
        this.deviceField1.setNumCols(30);
        this.deviceField1.setTextOnly(true);
        this.deviceField1.setOffsetNid(3);
        this.deviceField1.setLabelString("Comment: ");
        getContentPane().add(this.deviceField1);
        this.deviceField1.setBounds(12, 12, 516, 36);
        this.deviceField2.setNumCols(15);
        this.deviceField2.setTextOnly(true);
        this.deviceField2.setOffsetNid(2);
        this.deviceField2.setLabelString("Name: ");
        getContentPane().add(this.deviceField2);
        this.deviceField2.setBounds(12, 60, 228, 36);
        this.deviceChoice1.setOffsetNid(5);
        {
            final String[] tempString = new String[3];
            tempString[0] = "INTERNAL";
            tempString[1] = "EXTERNAL";
            tempString[2] = "EXT_REF_10MHz";
            this.deviceChoice1.setChoiceItems(tempString);
        }
        this.deviceChoice1.setLabelString("Clock Mode:");
        getContentPane().add(this.deviceChoice1);
        this.deviceChoice1.setBounds(12, 108, 216, 36);
        this.deviceChoice2.setChoiceFloatValues(new float[]{(float)100.0, (float)200.0, (float)250.0, (float)400.0, (float)500.0, (float)1000.0, (float)2000.0, (float)2500.0, (float)4000.0, (float)5000.0, (float)10000.0, (float)20000.0, (float)25000.0, (float)40000.0, (float)50000.0, (float)100000.0, (float)200000.0, (float)250000.0, (float)400000.0, (float)500000.0, (float)1000000.0, (float)2000000.0, (float)2500000.0, (float)4000000.0, (float)5000000.0, (float)1.0E7, (float)2.0E7, (float)2.5E7, (float)4.0E7, (float)5.0E7, (float)1.0E8, (float)2.0E8, (float)2.5E8, (float)4.0E8, (float)5.0E8});
        this.deviceChoice2.setOffsetNid(12);
        {
            final String[] tempString = new String[35];
            tempString[0] = "100";
            tempString[1] = "200";
            tempString[2] = "250";
            tempString[3] = "400";
            tempString[4] = "500";
            tempString[5] = "1E3";
            tempString[6] = "2E3";
            tempString[7] = "2.5E3";
            tempString[8] = "4E3";
            tempString[9] = "5E3";
            tempString[10] = "10E3";
            tempString[11] = "20E3";
            tempString[12] = "25E3";
            tempString[13] = "40E3";
            tempString[14] = "50E3";
            tempString[15] = "100E3";
            tempString[16] = "200E3";
            tempString[17] = "250E3";
            tempString[18] = "400E3";
            tempString[19] = "500E3";
            tempString[20] = "1E6";
            tempString[21] = "2E6";
            tempString[22] = "2.5E6";
            tempString[23] = "4E6";
            tempString[24] = "5E6";
            tempString[25] = "10E6";
            tempString[26] = "20E6";
            tempString[27] = "25E6";
            tempString[28] = "40E6";
            tempString[29] = "50E6";
            tempString[30] = "100E6";
            tempString[31] = "200E6";
            tempString[32] = "250E6";
            tempString[33] = "400E6";
            tempString[34] = "500E6";
            this.deviceChoice2.setChoiceItems(tempString);
        }
        this.deviceChoice2.setLabelString("Freq:");
        getContentPane().add(this.deviceChoice2);
        this.deviceChoice2.setBounds(228, 108, 120, 36);
        this.deviceField4.setNumCols(20);
        this.deviceField4.setOffsetNid(11);
        this.deviceField4.setLabelString("Clock Source:");
        getContentPane().add(this.deviceField4);
        this.deviceField4.setBounds(0, 156, 336, 36);
        this.deviceField5.setOffsetNid(4);
        this.deviceField5.setLabelString("Delay:");
        getContentPane().add(this.deviceField5);
        this.deviceField5.setBounds(348, 156, 180, 36);
        this.deviceChoice3.setOffsetNid(6);
        {
            final String[] tempString = new String[5];
            tempString[0] = "EXTERNAL";
            tempString[1] = "CH1";
            tempString[2] = "CH2";
            tempString[3] = "CH3";
            tempString[4] = "CH4";
            this.deviceChoice3.setChoiceItems(tempString);
        }
        this.deviceChoice3.setLabelString("Trig. Chan.");
        getContentPane().add(this.deviceChoice3);
        this.deviceChoice3.setBounds(0, 204, 180, 36);
        this.deviceChoice4.setOffsetNid(8);
        {
            final String[] tempString = new String[2];
            tempString[0] = "TRIG_DC";
            tempString[1] = "TRIG_AC";
            this.deviceChoice4.setChoiceItems(tempString);
        }
        this.deviceChoice4.setLabelString("Trig. Coupl.");
        getContentPane().add(this.deviceChoice4);
        this.deviceChoice4.setBounds(180, 204, 156, 36);
        this.deviceChoice5.setOffsetNid(9);
        {
            final String[] tempString = new String[2];
            tempString[0] = "POSITIVE";
            tempString[1] = "NEGATIVE";
            this.deviceChoice5.setChoiceItems(tempString);
        }
        this.deviceChoice5.setLabelString("Trig. Slope:");
        getContentPane().add(this.deviceChoice5);
        this.deviceChoice5.setBounds(336, 204, 180, 36);
        this.deviceField6.setNumCols(20);
        this.deviceField6.setOffsetNid(7);
        this.deviceField6.setLabelString("Trig. Source");
        getContentPane().add(this.deviceField6);
        this.deviceField6.setBounds(12, 264, 312, 36);
        this.deviceField7.setOffsetNid(10);
        this.deviceField7.setLabelString("Trig. Level");
        getContentPane().add(this.deviceField7);
        this.deviceField7.setBounds(324, 264, 204, 36);
        getContentPane().add(this.JTabbedPane1);
        this.JTabbedPane1.setBounds(24, 312, 492, 132);
        this.JPanel1.setLayout(new BorderLayout(0, 0));
        this.JTabbedPane1.add(this.JPanel1);
        this.JPanel1.setBounds(2, 24, 487, 105);
        this.JPanel1.setVisible(false);
        this.deviceChannel1.setLines(2);
        this.deviceChannel1.setOffsetNid(15);
        this.deviceChannel1.setLabelString("State");
        this.JPanel1.add(BorderLayout.CENTER, this.deviceChannel1);
        this.deviceField8.setNumCols(12);
        this.deviceField8.setOffsetNid(16);
        this.deviceField8.setLabelString("Start Time:");
        this.deviceChannel1.add(this.deviceField8);
        this.deviceField9.setNumCols(12);
        this.deviceField9.setOffsetNid(17);
        this.deviceField9.setLabelString("End Time:");
        this.deviceChannel1.add(this.deviceField9);
        this.deviceChoice6.setOffsetNid(20);
        {
            final String[] tempString = new String[4];
            tempString[0] = "DC1M";
            tempString[1] = "AC1M";
            tempString[2] = "DC50";
            tempString[3] = "AC50";
            this.deviceChoice6.setChoiceItems(tempString);
        }
        this.deviceChoice6.setLabelString("Coupling:");
        this.deviceChannel1.add(this.deviceChoice6);
        this.deviceChoice7.setChoiceFloatValues(new float[]{(float)0.05, (float)0.1, (float)0.5, (float)1.0, (float)2.0, (float)5.0});
        this.deviceChoice7.setOffsetNid(21);
        {
            final String[] tempString = new String[6];
            tempString[0] = "50E-3";
            tempString[1] = "100E-3";
            tempString[2] = "500E-3";
            tempString[3] = "1.";
            tempString[4] = "2.";
            tempString[5] = "5.";
            this.deviceChoice7.setChoiceItems(tempString);
        }
        this.deviceChoice7.setLabelString("Range");
        this.deviceChannel1.add(this.deviceChoice7);
        this.deviceField10.setOffsetNid(22);
        this.deviceField10.setLabelString("Offest:");
        this.deviceChannel1.add(this.deviceField10);
        this.JPanel2.setLayout(new BorderLayout(0, 0));
        this.JTabbedPane1.add(this.JPanel2);
        this.JPanel2.setBounds(2, 24, 487, 105);
        this.JPanel2.setVisible(false);
        this.deviceChannel2.setOffsetNid(24);
        this.deviceChannel2.setLabelString("State");
        this.JPanel2.add(BorderLayout.CENTER, this.deviceChannel2);
        this.deviceField11.setNumCols(12);
        this.deviceField11.setOffsetNid(25);
        this.deviceField11.setLabelString("Start Time:");
        this.deviceChannel2.add(this.deviceField11);
        this.deviceField12.setNumCols(12);
        this.deviceField12.setOffsetNid(26);
        this.deviceField12.setLabelString("End Time:");
        this.deviceChannel2.add(this.deviceField12);
        this.deviceChoice8.setOffsetNid(29);
        {
            final String[] tempString = new String[4];
            tempString[0] = "DC1M";
            tempString[1] = "AC1M";
            tempString[2] = "DC50";
            tempString[3] = "AC50";
            this.deviceChoice8.setChoiceItems(tempString);
        }
        this.deviceChoice8.setLabelString("Coupling:");
        this.deviceChannel2.add(this.deviceChoice8);
        this.deviceChoice9.setChoiceFloatValues(new float[]{(float)0.05, (float)0.1, (float)0.5, (float)1.0, (float)2.0, (float)5.0});
        this.deviceChoice9.setOffsetNid(30);
        {
            final String[] tempString = new String[6];
            tempString[0] = "50E-3";
            tempString[1] = "100E-3";
            tempString[2] = "500E-3";
            tempString[3] = "1.";
            tempString[4] = "2.";
            tempString[5] = "5.";
            this.deviceChoice9.setChoiceItems(tempString);
        }
        this.deviceChoice9.setLabelString("Range");
        this.deviceChannel2.add(this.deviceChoice9);
        this.deviceField13.setOffsetNid(31);
        this.deviceField13.setLabelString("Offest:");
        this.deviceChannel2.add(this.deviceField13);
        this.JPanel3.setLayout(new BorderLayout(0, 0));
        this.JTabbedPane1.add(this.JPanel3);
        this.JPanel3.setBounds(2, 24, 487, 105);
        this.JPanel3.setVisible(false);
        this.deviceChannel3.setOffsetNid(33);
        this.deviceChannel3.setLabelString("State");
        this.JPanel3.add(BorderLayout.CENTER, this.deviceChannel3);
        this.deviceField14.setNumCols(12);
        this.deviceField14.setOffsetNid(34);
        this.deviceField14.setLabelString("Start Time:");
        this.deviceChannel3.add(this.deviceField14);
        this.deviceField15.setNumCols(12);
        this.deviceField15.setOffsetNid(35);
        this.deviceField15.setLabelString("End Time:");
        this.deviceChannel3.add(this.deviceField15);
        this.deviceChoice10.setOffsetNid(38);
        {
            final String[] tempString = new String[4];
            tempString[0] = "DC1M";
            tempString[1] = "AC1M";
            tempString[2] = "DC50";
            tempString[3] = "AC50";
            this.deviceChoice10.setChoiceItems(tempString);
        }
        this.deviceChoice10.setLabelString("Coupling:");
        this.deviceChannel3.add(this.deviceChoice10);
        this.deviceChoice11.setChoiceFloatValues(new float[]{(float)0.05, (float)0.1, (float)0.5, (float)1.0, (float)2.0, (float)5.0});
        this.deviceChoice11.setOffsetNid(39);
        {
            final String[] tempString = new String[6];
            tempString[0] = "50E-3";
            tempString[1] = "100E-3";
            tempString[2] = "500E-3";
            tempString[3] = "1.";
            tempString[4] = "2.";
            tempString[5] = "5.";
            this.deviceChoice11.setChoiceItems(tempString);
        }
        this.deviceChoice11.setLabelString("Range");
        this.deviceChannel3.add(this.deviceChoice11);
        this.deviceField16.setOffsetNid(40);
        this.deviceField16.setLabelString("Offest:");
        this.deviceChannel3.add(this.deviceField16);
        this.JPanel4.setLayout(new BorderLayout(0, 0));
        this.JTabbedPane1.add(this.JPanel4);
        this.JPanel4.setBounds(2, 24, 487, 105);
        this.JPanel4.setVisible(false);
        this.deviceChannel4.setOffsetNid(42);
        this.deviceChannel4.setLabelString("State");
        this.JPanel4.add(BorderLayout.CENTER, this.deviceChannel4);
        this.deviceField17.setNumCols(12);
        this.deviceField17.setOffsetNid(43);
        this.deviceField17.setLabelString("Start Time:");
        this.deviceChannel4.add(this.deviceField17);
        this.deviceField18.setNumCols(12);
        this.deviceField18.setOffsetNid(44);
        this.deviceField18.setLabelString("End Time:");
        this.deviceChannel4.add(this.deviceField18);
        this.deviceChoice12.setOffsetNid(47);
        {
            final String[] tempString = new String[4];
            tempString[0] = "DC1M";
            tempString[1] = "AC1M";
            tempString[2] = "DC50";
            tempString[3] = "AC50";
            this.deviceChoice12.setChoiceItems(tempString);
        }
        this.deviceChoice12.setLabelString("Coupling:");
        this.deviceChannel4.add(this.deviceChoice12);
        this.deviceChoice13.setChoiceFloatValues(new float[]{(float)0.05, (float)0.1, (float)0.5, (float)1.0, (float)2.0, (float)5.0});
        this.deviceChoice13.setOffsetNid(48);
        {
            final String[] tempString = new String[6];
            tempString[0] = "50E-3";
            tempString[1] = "100E-3";
            tempString[2] = "500E-3";
            tempString[3] = "1.";
            tempString[4] = "2.";
            tempString[5] = "5.";
            this.deviceChoice13.setChoiceItems(tempString);
        }
        this.deviceChoice13.setLabelString("Range");
        this.deviceChannel4.add(this.deviceChoice13);
        this.deviceField19.setOffsetNid(49);
        this.deviceField19.setLabelString("Offest:");
        this.deviceChannel4.add(this.deviceField19);
        this.JTabbedPane1.setSelectedIndex(0);
        this.JTabbedPane1.setSelectedComponent(this.JPanel1);
        this.JTabbedPane1.setTitleAt(0, "Channel 1");
        this.JTabbedPane1.setTitleAt(1, "Channel 2");
        this.JTabbedPane1.setTitleAt(2, "Channel 3");
        this.JTabbedPane1.setTitleAt(3, "Channel 4");
        getContentPane().add(this.deviceButtons1);
        this.deviceButtons1.setBounds(132, 456, 281, 40);
        this.deviceField3.setNumCols(15);
        this.deviceField3.setShowState(true);
        this.deviceField3.setTextOnly(true);
        this.deviceField3.setOffsetNid(1);
        this.deviceField3.setLabelString("IP addr.: ");
        getContentPane().add(this.deviceField3);
        this.deviceField3.setBounds(240, 60, 288, 36);
        getContentPane().add(this.deviceDispatch1);
        this.deviceDispatch1.setBounds(372, 108, 131, 40);
        // }}
    }

    public ADC265Setup(final String sTitle){
        this();
        setTitle(sTitle);
    }

    public void addNotify() {
        // Record the size of the window prior to calling parents addNotify.
        final Dimension size = getSize();
        super.addNotify();
        if(this.frameSizeAdjusted) return;
        this.frameSizeAdjusted = true;
        // Adjust size of frame according to the insets
        final Insets insets = getInsets();
        setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
    }

    public void setVisible(final boolean b) {
        if(b) setLocation(50, 50);
        super.setVisible(b);
    }
}
