/*
 * A basic implementation of the DeviceSetup class.
 */
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Insets;
import javax.swing.JFrame;
import devicebeans.DeviceButtons;
import devicebeans.DeviceChannel;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

public class Aurora14Setup extends DeviceSetup{
    /**
     * 
     */
    private static final long serialVersionUID = -601744563261879272L;

    static public void main(final String args[]) {
        (new Aurora14Setup()).setVisible(true);
    }
    DeviceButtons           deviceButtons1    = new DeviceButtons();
    // }}
    DeviceChannel           deviceChannel1    = new DeviceChannel();
    DeviceChannel           deviceChannel10   = new DeviceChannel();
    DeviceChannel           deviceChannel11   = new DeviceChannel();
    DeviceChannel           deviceChannel12   = new DeviceChannel();
    DeviceChannel           deviceChannel2    = new DeviceChannel();
    DeviceChannel           deviceChannel3    = new DeviceChannel();
    DeviceChannel           deviceChannel4    = new DeviceChannel();
    DeviceChannel           deviceChannel5    = new DeviceChannel();
    DeviceChannel           deviceChannel6    = new DeviceChannel();
    DeviceChannel           deviceChannel7    = new DeviceChannel();
    DeviceChannel           deviceChannel8    = new DeviceChannel();
    DeviceChannel           deviceChannel9    = new DeviceChannel();
    DeviceChoice            deviceChoice1     = new DeviceChoice();
    DeviceChoice            deviceChoice2     = new DeviceChoice();
    DeviceChoice            deviceChoice3     = new DeviceChoice();
    DeviceChoice            deviceChoice4     = new DeviceChoice();
    DeviceChoice            deviceChoice5     = new DeviceChoice();
    DeviceDispatch          deviceDispatch1   = new DeviceDispatch();
    // {{DECLARE_CONTROLS
    DeviceField             deviceField1      = new DeviceField();
    DeviceField             deviceField10     = new DeviceField();
    DeviceField             deviceField11     = new DeviceField();
    DeviceField             deviceField12     = new DeviceField();
    DeviceField             deviceField13     = new DeviceField();
    DeviceField             deviceField14     = new DeviceField();
    DeviceField             deviceField15     = new DeviceField();
    DeviceField             deviceField16     = new DeviceField();
    DeviceField             deviceField17     = new DeviceField();
    DeviceField             deviceField18     = new DeviceField();
    DeviceField             deviceField19     = new DeviceField();
    DeviceField             deviceField2      = new DeviceField();
    DeviceField             deviceField20     = new DeviceField();
    DeviceField             deviceField21     = new DeviceField();
    DeviceField             deviceField22     = new DeviceField();
    DeviceField             deviceField23     = new DeviceField();
    DeviceField             deviceField24     = new DeviceField();
    DeviceField             deviceField25     = new DeviceField();
    DeviceField             deviceField26     = new DeviceField();
    DeviceField             deviceField27     = new DeviceField();
    DeviceField             deviceField28     = new DeviceField();
    DeviceField             deviceField29     = new DeviceField();
    DeviceField             deviceField3      = new DeviceField();
    DeviceField             deviceField4      = new DeviceField();
    DeviceField             deviceField5      = new DeviceField();
    DeviceField             deviceField6      = new DeviceField();
    DeviceField             deviceField7      = new DeviceField();
    DeviceField             deviceField8      = new DeviceField();
    DeviceField             deviceField9      = new DeviceField();
    // Used by addNotify
    boolean                 frameSizeAdjusted = false;
    javax.swing.JPanel      JPanel1           = new javax.swing.JPanel();
    javax.swing.JPanel      JPanel2           = new javax.swing.JPanel();
    javax.swing.JScrollPane JScrollPane1      = new javax.swing.JScrollPane();
    javax.swing.JScrollPane JScrollPane2      = new javax.swing.JScrollPane();
    javax.swing.JTabbedPane JTabbedPane1      = new javax.swing.JTabbedPane();

    public Aurora14Setup(){
        this((JFrame)null);
    }

    public Aurora14Setup(final JFrame parent){
        super(parent);
        // This code is automatically generated by Visual Cafe when you add
        // components to the visual environment. It instantiates and initializes
        // the components. To modify the code, only use code syntax that matches
        // what Visual Cafe can generate, or Visual Cafe may be unable to back
        // parse your Java file into its visual environment.
        // {{INIT_CONTROLS
        setDeviceProvider("150.178.3.112");
        setDeviceTitle("Aurora 14 Transient Recorder");
        setDeviceType("Aurora14");
        getContentPane().setLayout(null);
        setSize(550, 456);
        this.deviceField1.setTextOnly(true);
        this.deviceField1.setOffsetNid(1);
        this.deviceField1.setLabelString("Camac Name: ");
        getContentPane().add(this.deviceField1);
        this.deviceField1.setBounds(-12, 12, 252, 40);
        getContentPane().add(this.deviceDispatch1);
        this.deviceDispatch1.setBounds(408, 12, 131, 40);
        this.deviceField2.setNumCols(33);
        this.deviceField2.setTextOnly(true);
        this.deviceField2.setOffsetNid(2);
        this.deviceField2.setLabelString("Comment: ");
        getContentPane().add(this.deviceField2);
        this.deviceField2.setBounds(12, 48, 504, 40);
        this.deviceChoice1.setOffsetNid(3);
        {
            final String[] tempString = new String[2];
            tempString[0] = "SOFTWARE";
            tempString[1] = "EXTERNAL";
            this.deviceChoice1.setChoiceItems(tempString);
        }
        this.deviceChoice1.setLabelString("Trig. Mode: ");
        getContentPane().add(this.deviceChoice1);
        this.deviceChoice1.setBounds(0, 84, 204, 40);
        this.deviceChoice2.setOffsetNid(5);
        {
            final String[] tempString = new String[2];
            tempString[0] = "EXTERNAL";
            tempString[1] = "INTERNAL";
            this.deviceChoice2.setChoiceItems(tempString);
        }
        this.deviceChoice2.setLabelString("Clock Mode: ");
        getContentPane().add(this.deviceChoice2);
        this.deviceChoice2.setBounds(204, 84, 180, 40);
        this.deviceChoice3.setChoiceFloatValues(new float[]{(float)1000000.0, (float)500000.0, (float)250000.0, (float)100000.0, (float)50000.0, (float)25000.0, (float)10000.0});
        this.deviceChoice3.setOffsetNid(7);
        {
            final String[] tempString = new String[7];
            tempString[0] = "1E6";
            tempString[1] = "0.5E6";
            tempString[2] = "0.25E6";
            tempString[3] = "0.1E6";
            tempString[4] = "0.5E5";
            tempString[5] = "0.25E5";
            tempString[6] = "0.1E5";
            this.deviceChoice3.setChoiceItems(tempString);
        }
        this.deviceChoice3.setLabelString("Frequency:");
        getContentPane().add(this.deviceChoice3);
        this.deviceChoice3.setBounds(384, 84, 156, 40);
        this.deviceChoice4.setOffsetNid(8);
        {
            final String[] tempString = new String[2];
            tempString[0] = "NORMAL";
            tempString[1] = "BURST";
            this.deviceChoice4.setChoiceItems(tempString);
        }
        this.deviceChoice4.setLabelString("Op. Mode: ");
        getContentPane().add(this.deviceChoice4);
        this.deviceChoice4.setBounds(228, 12, 180, 40);
        this.deviceField3.setNumCols(20);
        this.deviceField3.setOffsetNid(4);
        this.deviceField3.setLabelString("     Trig. Source: ");
        getContentPane().add(this.deviceField3);
        this.deviceField3.setBounds(0, 132, 348, 40);
        this.deviceField4.setOffsetNid(10);
        this.deviceField4.setLabelString("PTS: ");
        getContentPane().add(this.deviceField4);
        this.deviceField4.setBounds(372, 132, 168, 40);
        this.deviceField5.setNumCols(20);
        this.deviceField5.setOffsetNid(6);
        this.deviceField5.setLabelString("Clock Source: ");
        getContentPane().add(this.deviceField5);
        this.deviceField5.setBounds(12, 168, 336, 40);
        this.deviceChoice5.setOffsetNid(9);
        {
            final String[] tempString = new String[2];
            tempString[0] = "TRUE";
            tempString[1] = "FALSE";
            this.deviceChoice5.setChoiceItems(tempString);
        }
        this.deviceChoice5.setLabelString("Use Time: ");
        getContentPane().add(this.deviceChoice5);
        this.deviceChoice5.setBounds(360, 168, 180, 40);
        getContentPane().add(this.JTabbedPane1);
        this.JTabbedPane1.setBounds(12, 204, 516, 192);
        this.JScrollPane1.setOpaque(true);
        this.JTabbedPane1.add(this.JScrollPane1);
        this.JScrollPane1.setBounds(2, 24, 511, 165);
        this.JScrollPane1.setVisible(false);
        this.JPanel1.setLayout(new GridLayout(6, 1, 0, 0));
        this.JScrollPane1.getViewport().add(this.JPanel1);
        this.JPanel1.setBounds(0, 0, 493, 246);
        this.deviceChannel1.setInSameLine(true);
        this.deviceChannel1.setOffsetNid(11);
        this.deviceChannel1.setLabelString("Ch1: ");
        this.deviceChannel1.setBorderVisible(true);
        this.deviceChannel1.setLayout(new BorderLayout(0, 0));
        this.JPanel1.add(this.deviceChannel1);
        this.deviceField6.setOffsetNid(14);
        this.deviceField6.setLabelString("Start Time: ");
        this.deviceChannel1.add(this.deviceField6);
        this.deviceField7.setOffsetNid(15);
        this.deviceField7.setLabelString("End Time: ");
        this.deviceChannel1.add(this.deviceField7);
        this.deviceChannel2.setInSameLine(true);
        this.deviceChannel2.setOffsetNid(19);
        this.deviceChannel2.setLabelString("Ch2: ");
        this.deviceChannel2.setBorderVisible(true);
        this.deviceChannel2.setLayout(new BorderLayout(0, 0));
        this.JPanel1.add(this.deviceChannel2);
        this.deviceField8.setOffsetNid(22);
        this.deviceField8.setLabelString("Start Time: ");
        this.deviceChannel2.add(this.deviceField8);
        this.deviceField9.setOffsetNid(23);
        this.deviceField9.setLabelString("End Time: ");
        this.deviceChannel2.add(this.deviceField9);
        this.deviceChannel3.setInSameLine(true);
        this.deviceChannel3.setOffsetNid(27);
        this.deviceChannel3.setLabelString("Ch3: ");
        this.deviceChannel3.setBorderVisible(true);
        this.deviceChannel3.setLayout(new BorderLayout(0, 0));
        this.JPanel1.add(this.deviceChannel3);
        this.deviceField10.setOffsetNid(30);
        this.deviceField10.setLabelString("Start Time: ");
        this.deviceChannel3.add(this.deviceField10);
        this.deviceField11.setOffsetNid(31);
        this.deviceField11.setLabelString("End Time: ");
        this.deviceChannel3.add(this.deviceField11);
        this.deviceChannel4.setInSameLine(true);
        this.deviceChannel4.setOffsetNid(35);
        this.deviceChannel4.setLabelString("Ch4: ");
        this.deviceChannel4.setBorderVisible(true);
        this.deviceChannel4.setLayout(new BorderLayout(0, 0));
        this.JPanel1.add(this.deviceChannel4);
        this.deviceField12.setOffsetNid(38);
        this.deviceField12.setLabelString("Start Time: ");
        this.deviceChannel4.add(this.deviceField12);
        this.deviceField13.setOffsetNid(39);
        this.deviceField13.setLabelString("End Time: ");
        this.deviceChannel4.add(this.deviceField13);
        this.deviceChannel5.setInSameLine(true);
        this.deviceChannel5.setOffsetNid(43);
        this.deviceChannel5.setLabelString("Ch5: ");
        this.deviceChannel5.setBorderVisible(true);
        this.deviceChannel5.setLayout(new BorderLayout(0, 0));
        this.JPanel1.add(this.deviceChannel5);
        this.deviceField14.setOffsetNid(46);
        this.deviceField14.setLabelString("Start Time: ");
        this.deviceChannel5.add(this.deviceField14);
        this.deviceField15.setOffsetNid(47);
        this.deviceField15.setLabelString("End Time: ");
        this.deviceChannel5.add(this.deviceField15);
        this.deviceChannel6.setInSameLine(true);
        this.deviceChannel6.setOffsetNid(51);
        this.deviceChannel6.setLabelString("Ch6: ");
        this.deviceChannel6.setBorderVisible(true);
        this.deviceChannel6.setLayout(new BorderLayout(0, 0));
        this.JPanel1.add(this.deviceChannel6);
        this.deviceField16.setOffsetNid(54);
        this.deviceField16.setLabelString("Start Time: ");
        this.deviceChannel6.add(this.deviceField16);
        this.deviceField17.setOffsetNid(55);
        this.deviceField17.setLabelString("End Time: ");
        this.deviceChannel6.add(this.deviceField17);
        this.JScrollPane2.setOpaque(true);
        this.JTabbedPane1.add(this.JScrollPane2);
        this.JScrollPane2.setBounds(2, 24, 511, 165);
        this.JScrollPane2.setVisible(false);
        this.JPanel2.setLayout(new GridLayout(6, 1, 0, 0));
        this.JScrollPane2.getViewport().add(this.JPanel2);
        this.JPanel2.setBounds(0, 0, 493, 246);
        this.deviceChannel7.setInSameLine(true);
        this.deviceChannel7.setOffsetNid(11);
        this.deviceChannel7.setLabelString("Ch1: ");
        this.deviceChannel7.setBorderVisible(true);
        this.deviceChannel7.setLayout(new BorderLayout(0, 0));
        this.JPanel2.add(this.deviceChannel7);
        this.deviceField18.setOffsetNid(16);
        this.deviceField18.setLabelString("Start Idx: ");
        this.deviceChannel7.add(this.deviceField18);
        this.deviceField19.setOffsetNid(17);
        this.deviceField19.setLabelString("End Idx: ");
        this.deviceChannel7.add(this.deviceField19);
        this.deviceChannel8.setInSameLine(true);
        this.deviceChannel8.setOffsetNid(19);
        this.deviceChannel8.setLabelString("Ch2: ");
        this.deviceChannel8.setBorderVisible(true);
        this.deviceChannel8.setLayout(new BorderLayout(0, 0));
        this.JPanel2.add(this.deviceChannel8);
        this.deviceField20.setOffsetNid(24);
        this.deviceField20.setLabelString("Start Idx: ");
        this.deviceChannel8.add(this.deviceField20);
        this.deviceField21.setOffsetNid(25);
        this.deviceField21.setLabelString("End Idx: ");
        this.deviceChannel8.add(this.deviceField21);
        this.deviceChannel9.setInSameLine(true);
        this.deviceChannel9.setOffsetNid(27);
        this.deviceChannel9.setLabelString("Ch3: ");
        this.deviceChannel9.setBorderVisible(true);
        this.deviceChannel9.setLayout(new BorderLayout(0, 0));
        this.JPanel2.add(this.deviceChannel9);
        this.deviceField22.setOffsetNid(32);
        this.deviceField22.setLabelString("Start Idx: ");
        this.deviceChannel9.add(this.deviceField22);
        this.deviceField23.setOffsetNid(33);
        this.deviceField23.setLabelString("End Idx: ");
        this.deviceChannel9.add(this.deviceField23);
        this.deviceChannel10.setInSameLine(true);
        this.deviceChannel10.setOffsetNid(35);
        this.deviceChannel10.setLabelString("Ch4: ");
        this.deviceChannel10.setBorderVisible(true);
        this.deviceChannel10.setLayout(new BorderLayout(0, 0));
        this.JPanel2.add(this.deviceChannel10);
        this.deviceField24.setOffsetNid(40);
        this.deviceField24.setLabelString("Start Idx: ");
        this.deviceChannel10.add(this.deviceField24);
        this.deviceField25.setOffsetNid(41);
        this.deviceField25.setLabelString("End Idx: ");
        this.deviceChannel10.add(this.deviceField25);
        this.deviceChannel11.setInSameLine(true);
        this.deviceChannel11.setOffsetNid(43);
        this.deviceChannel11.setLabelString("Ch5: ");
        this.deviceChannel11.setBorderVisible(true);
        this.deviceChannel11.setLayout(new BorderLayout(0, 0));
        this.JPanel2.add(this.deviceChannel11);
        this.deviceField26.setOffsetNid(48);
        this.deviceField26.setLabelString("Start Idx: ");
        this.deviceChannel11.add(this.deviceField26);
        this.deviceField27.setOffsetNid(49);
        this.deviceField27.setLabelString("End Idx: ");
        this.deviceChannel11.add(this.deviceField27);
        this.deviceChannel12.setInSameLine(true);
        this.deviceChannel12.setOffsetNid(51);
        this.deviceChannel12.setLabelString("Ch6: ");
        this.deviceChannel12.setBorderVisible(true);
        this.deviceChannel12.setLayout(new BorderLayout(0, 0));
        this.JPanel2.add(this.deviceChannel12);
        this.deviceField28.setOffsetNid(56);
        this.deviceField28.setLabelString("Start Idx: ");
        this.deviceChannel12.add(this.deviceField28);
        this.deviceField29.setOffsetNid(57);
        this.deviceField29.setLabelString("End Idx: ");
        this.deviceChannel12.add(this.deviceField29);
        this.JTabbedPane1.setSelectedIndex(0);
        this.JTabbedPane1.setSelectedComponent(this.JScrollPane1);
        this.JTabbedPane1.setTitleAt(0, "Channels (Time)");
        this.JTabbedPane1.setTitleAt(1, "Channels (Samples)");
        getContentPane().add(this.deviceButtons1);
        this.deviceButtons1.setBounds(96, 408, 336, 40);
        // }}
    }

    public Aurora14Setup(final String sTitle){
        this();
        setTitle(sTitle);
    }

    public void addNotify() {
        // Record the size of the window prior to calling parents addNotify.
        final Dimension size = getSize();
        super.addNotify();
        if(this.frameSizeAdjusted) return;
        this.frameSizeAdjusted = true;
        // Adjust size of frame according to the insets
        final Insets insets = getInsets();
        setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
    }

    public void setVisible(final boolean b) {
        if(b) setLocation(50, 50);
        super.setVisible(b);
    }
}
