import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import devicebeans.DeviceButtons;
import devicebeans.DeviceChannel;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 * 
 * @author not attributable
 * @version 1.0
 */
public class BUILD_VERSIONSetup extends DeviceSetup{
    /**
     * 
     */
    private static final long serialVersionUID = -777039949917476055L;
    BorderLayout  borderLayout1  = new BorderLayout();
    BorderLayout  borderLayout10 = new BorderLayout();
    BorderLayout  borderLayout2  = new BorderLayout();
    BorderLayout  borderLayout3  = new BorderLayout();
    BorderLayout  borderLayout4  = new BorderLayout();
    BorderLayout  borderLayout5  = new BorderLayout();
    BorderLayout  borderLayout6  = new BorderLayout();
    BorderLayout  borderLayout7  = new BorderLayout();
    BorderLayout  borderLayout8  = new BorderLayout();
    BorderLayout  borderLayout9  = new BorderLayout();
    DeviceButtons deviceButtons1 = new DeviceButtons();
    DeviceChannel deviceChannel1 = new DeviceChannel();
    DeviceChannel deviceChannel2 = new DeviceChannel();
    DeviceChannel deviceChannel3 = new DeviceChannel();
    DeviceChannel deviceChannel4 = new DeviceChannel();
    DeviceChannel deviceChannel5 = new DeviceChannel();
    DeviceChannel deviceChannel6 = new DeviceChannel();
    DeviceChannel deviceChannel7 = new DeviceChannel();
    DeviceChannel deviceChannel8 = new DeviceChannel();
    DeviceField   deviceField1   = new DeviceField();
    DeviceField   deviceField10  = new DeviceField();
    DeviceField   deviceField11  = new DeviceField();
    DeviceField   deviceField110 = new DeviceField();
    DeviceField   deviceField111 = new DeviceField();
    DeviceField   deviceField112 = new DeviceField();
    DeviceField   deviceField113 = new DeviceField();
    DeviceField   deviceField114 = new DeviceField();
    DeviceField   deviceField115 = new DeviceField();
    DeviceField   deviceField116 = new DeviceField();
    DeviceField   deviceField117 = new DeviceField();
    DeviceField   deviceField12  = new DeviceField();
    DeviceField   deviceField13  = new DeviceField();
    DeviceField   deviceField14  = new DeviceField();
    DeviceField   deviceField15  = new DeviceField();
    DeviceField   deviceField16  = new DeviceField();
    DeviceField   deviceField17  = new DeviceField();
    DeviceField   deviceField18  = new DeviceField();
    DeviceField   deviceField19  = new DeviceField();
    DeviceField   deviceField2   = new DeviceField();
    DeviceField   deviceField20  = new DeviceField();
    DeviceField   deviceField21  = new DeviceField();
    DeviceField   deviceField22  = new DeviceField();
    DeviceField   deviceField23  = new DeviceField();
    DeviceField   deviceField24  = new DeviceField();
    DeviceField   deviceField25  = new DeviceField();
    DeviceField   deviceField26  = new DeviceField();
    DeviceField   deviceField27  = new DeviceField();
    DeviceField   deviceField3   = new DeviceField();
    DeviceField   deviceField4   = new DeviceField();
    DeviceField   deviceField5   = new DeviceField();
    DeviceField   deviceField6   = new DeviceField();
    DeviceField   deviceField7   = new DeviceField();
    DeviceField   deviceField8   = new DeviceField();
    DeviceField   deviceField9   = new DeviceField();
    FlowLayout    flowLayout1    = new FlowLayout();
    FlowLayout    flowLayout10   = new FlowLayout();
    FlowLayout    flowLayout12   = new FlowLayout();
    FlowLayout    flowLayout14   = new FlowLayout();
    FlowLayout    flowLayout16   = new FlowLayout();
    FlowLayout    flowLayout18   = new FlowLayout();
    FlowLayout    flowLayout2    = new FlowLayout();
    FlowLayout    flowLayout3    = new FlowLayout();
    FlowLayout    flowLayout6    = new FlowLayout();
    FlowLayout    flowLayout8    = new FlowLayout();
    GridLayout    gridLayout1    = new GridLayout();
    GridLayout    gridLayout10   = new GridLayout();
    GridLayout    gridLayout11   = new GridLayout();
    GridLayout    gridLayout110  = new GridLayout();
    GridLayout    gridLayout111  = new GridLayout();
    GridLayout    gridLayout112  = new GridLayout();
    GridLayout    gridLayout113  = new GridLayout();
    GridLayout    gridLayout114  = new GridLayout();
    GridLayout    gridLayout115  = new GridLayout();
    GridLayout    gridLayout12   = new GridLayout();
    GridLayout    gridLayout13   = new GridLayout();
    GridLayout    gridLayout14   = new GridLayout();
    GridLayout    gridLayout15   = new GridLayout();
    GridLayout    gridLayout16   = new GridLayout();
    GridLayout    gridLayout17   = new GridLayout();
    GridLayout    gridLayout18   = new GridLayout();
    GridLayout    gridLayout19   = new GridLayout();
    GridLayout    gridLayout2    = new GridLayout();
    GridLayout    gridLayout3    = new GridLayout();
    GridLayout    gridLayout4    = new GridLayout();
    GridLayout    gridLayout5    = new GridLayout();
    GridLayout    gridLayout6    = new GridLayout();
    GridLayout    gridLayout7    = new GridLayout();
    GridLayout    gridLayout8    = new GridLayout();
    GridLayout    gridLayout9    = new GridLayout();
    JPanel        jPanel1        = new JPanel();
    JPanel        jPanel10       = new JPanel();
    JPanel        jPanel111      = new JPanel();
    JPanel        jPanel112      = new JPanel();
    JPanel        jPanel114      = new JPanel();
    JPanel        jPanel115      = new JPanel();
    JPanel        jPanel117      = new JPanel();
    JPanel        jPanel118      = new JPanel();
    JPanel        jPanel12       = new JPanel();
    JPanel        jPanel13       = new JPanel();
    JPanel        jPanel15       = new JPanel();
    JPanel        jPanel16       = new JPanel();
    JPanel        jPanel18       = new JPanel();
    JPanel        jPanel19       = new JPanel();
    JPanel        jPanel2        = new JPanel();
    JPanel        jPanel20       = new JPanel();
    JPanel        jPanel21       = new JPanel();
    JPanel        jPanel210      = new JPanel();
    JPanel        jPanel211      = new JPanel();
    JPanel        jPanel212      = new JPanel();
    JPanel        jPanel213      = new JPanel();
    JPanel        jPanel214      = new JPanel();
    JPanel        jPanel22       = new JPanel();
    JPanel        jPanel23       = new JPanel();
    JPanel        jPanel24       = new JPanel();
    JPanel        jPanel25       = new JPanel();
    JPanel        jPanel26       = new JPanel();
    JPanel        jPanel27       = new JPanel();
    JPanel        jPanel28       = new JPanel();
    JPanel        jPanel29       = new JPanel();
    JPanel        jPanel3        = new JPanel();
    JPanel        jPanel4        = new JPanel();
    JPanel        jPanel5        = new JPanel();
    JPanel        jPanel6        = new JPanel();
    JPanel        jPanel7        = new JPanel();
    JPanel        jPanel9        = new JPanel();
    JTabbedPane   jTabbedPane1   = new JTabbedPane();

    public BUILD_VERSIONSetup(){
        try{
            this.jbInit();
        }catch(final Exception e){
            e.printStackTrace();
        }
    }

    private void jbInit() throws Exception {
        this.setWidth(700);
        this.setHeight(250);
        this.setDeviceType("BUILD_VERSION");
        this.setDeviceProvider("150.178.3.33");
        this.setDeviceTitle("Build new RFX experiment version ");
        this.getContentPane().setLayout(this.borderLayout1);
        this.jPanel1.setLayout(this.gridLayout1);
        this.gridLayout1.setRows(2);
        this.deviceField1.setOffsetNid(1);
        this.deviceField1.setTextOnly(true);
        this.deviceField1.setLabelString("Comment");
        this.deviceField1.setNumCols(50);
        this.deviceField1.setIdentifier("");
        this.jPanel2.setLayout(this.flowLayout1);
        this.flowLayout1.setAlignment(FlowLayout.LEFT);
        this.flowLayout2.setAlignment(FlowLayout.LEFT);
        this.deviceField2.setOffsetNid(3);
        this.deviceField2.setTextOnly(false);
        this.deviceField2.setLabelString("Shots: ");
        this.deviceField2.setNumCols(20);
        this.deviceField2.setIdentifier("");
        this.jPanel3.setLayout(this.flowLayout2);
        this.deviceField3.setNumCols(10);
        this.deviceField3.setIdentifier("");
        this.deviceField3.setLabelString("Version: ");
        this.deviceField3.setOffsetNid(2);
        this.deviceField3.setTextOnly(false);
        this.jPanel4.setLayout(this.borderLayout2);
        this.jPanel5.setLayout(this.gridLayout2);
        this.deviceButtons1.setMethods(new String[]{"start"});
        this.deviceChannel1.setLabelString("");
        this.deviceChannel1.setOffsetNid(4);
        this.deviceChannel1.setInSameLine(true);
        this.deviceChannel1.setUpdateIdentifier("");
        this.deviceChannel1.setShowVal("");
        this.deviceChannel1.setLayout(this.borderLayout3);
        this.jPanel20.setLayout(this.gridLayout10);
        this.flowLayout3.setAlignment(FlowLayout.LEFT);
        this.deviceField5.setOffsetNid(6);
        this.deviceField5.setTextOnly(true);
        this.deviceField5.setLabelString("Experiment");
        this.deviceField5.setIdentifier("");
        this.deviceField5.setEditable(false);
        this.jPanel6.setLayout(this.flowLayout3);
        this.deviceField4.setNumCols(25);
        this.deviceField4.setIdentifier("");
        this.deviceField4.setLabelString("Comment");
        this.deviceField4.setTextOnly(true);
        this.deviceField4.setOffsetNid(5);
        this.deviceField6.setOffsetNid(7);
        this.deviceField6.setTextOnly(false);
        this.deviceField6.setLabelString("Pre Program:");
        this.deviceField6.setNumCols(50);
        this.deviceField6.setIdentifier("");
        this.jPanel7.setLayout(this.gridLayout18);
        this.gridLayout10.setRows(2);
        this.deviceField7.setIdentifier("");
        this.deviceField7.setEditable(true);
        this.deviceField7.setLabelString("Experiment");
        this.deviceField7.setTextOnly(true);
        this.deviceField7.setOffsetNid(11);
        this.gridLayout11.setRows(2);
        this.jPanel21.setLayout(this.gridLayout11);
        this.deviceChannel2.setLabelString("");
        this.deviceChannel2.setOffsetNid(9);
        this.deviceChannel2.setInSameLine(true);
        this.deviceChannel2.setUpdateIdentifier("");
        this.deviceChannel2.setShowVal("");
        this.deviceChannel2.setLayout(this.borderLayout4);
        this.flowLayout6.setAlignment(FlowLayout.LEFT);
        this.jPanel9.setLayout(this.gridLayout3);
        this.jPanel10.setLayout(this.flowLayout6);
        this.deviceField9.setNumCols(25);
        this.deviceField9.setIdentifier("");
        this.deviceField9.setLabelString("Comment");
        this.deviceField9.setTextOnly(true);
        this.deviceField9.setOffsetNid(10);
        this.deviceField10.setIdentifier("");
        this.deviceField10.setEditable(true);
        this.deviceField10.setLabelString("Experiment");
        this.deviceField10.setTextOnly(true);
        this.deviceField10.setOffsetNid(16);
        this.gridLayout12.setRows(2);
        this.jPanel22.setLayout(this.gridLayout12);
        this.deviceChannel3.setLabelString("");
        this.deviceChannel3.setOffsetNid(14);
        this.deviceChannel3.setInSameLine(true);
        this.deviceChannel3.setUpdateIdentifier("");
        this.deviceChannel3.setShowVal("");
        this.deviceChannel3.setLayout(this.borderLayout5);
        this.flowLayout8.setAlignment(FlowLayout.LEFT);
        this.jPanel12.setLayout(this.gridLayout4);
        this.jPanel13.setLayout(this.flowLayout8);
        this.deviceField12.setNumCols(25);
        this.deviceField12.setIdentifier("");
        this.deviceField12.setLabelString("Comment");
        this.deviceField12.setTextOnly(true);
        this.deviceField12.setOffsetNid(15);
        this.deviceField13.setIdentifier("");
        this.deviceField13.setEditable(true);
        this.deviceField13.setLabelString("Experiment");
        this.deviceField13.setTextOnly(true);
        this.deviceField13.setOffsetNid(21);
        this.gridLayout13.setRows(2);
        this.jPanel23.setLayout(this.gridLayout13);
        this.deviceChannel4.setLabelString("");
        this.deviceChannel4.setOffsetNid(19);
        this.deviceChannel4.setInSameLine(true);
        this.deviceChannel4.setUpdateIdentifier("");
        this.deviceChannel4.setShowVal("");
        this.deviceChannel4.setLayout(this.borderLayout6);
        this.flowLayout10.setAlignment(FlowLayout.LEFT);
        this.jPanel15.setLayout(this.gridLayout5);
        this.jPanel16.setLayout(this.flowLayout10);
        this.deviceField15.setNumCols(25);
        this.deviceField15.setIdentifier("");
        this.deviceField15.setLabelString("Comment");
        this.deviceField15.setTextOnly(true);
        this.deviceField15.setOffsetNid(20);
        this.deviceField16.setIdentifier("");
        this.deviceField16.setEditable(true);
        this.deviceField16.setLabelString("Experiment");
        this.deviceField16.setTextOnly(true);
        this.deviceField16.setOffsetNid(26);
        this.gridLayout14.setRows(2);
        this.jPanel24.setLayout(this.gridLayout14);
        this.deviceChannel5.setLabelString("");
        this.deviceChannel5.setOffsetNid(24);
        this.deviceChannel5.setInSameLine(true);
        this.deviceChannel5.setUpdateIdentifier("");
        this.deviceChannel5.setShowVal("");
        this.deviceChannel5.setLayout(this.borderLayout7);
        this.flowLayout12.setAlignment(FlowLayout.LEFT);
        this.jPanel18.setLayout(this.gridLayout6);
        this.jPanel19.setLayout(this.flowLayout12);
        this.deviceField19.setIdentifier("");
        this.deviceField19.setEditable(true);
        this.deviceField19.setLabelString("Experiment");
        this.deviceField19.setTextOnly(true);
        this.deviceField19.setOffsetNid(31);
        this.gridLayout15.setRows(2);
        this.jPanel25.setLayout(this.gridLayout15);
        this.deviceChannel6.setLabelString("");
        this.deviceChannel6.setOffsetNid(29);
        this.deviceChannel6.setInSameLine(true);
        this.deviceChannel6.setUpdateIdentifier("");
        this.deviceChannel6.setShowVal("");
        this.deviceChannel6.setLayout(this.borderLayout8);
        this.flowLayout14.setAlignment(FlowLayout.LEFT);
        this.jPanel111.setLayout(this.gridLayout7);
        this.jPanel112.setLayout(this.flowLayout14);
        this.deviceField111.setNumCols(25);
        this.deviceField111.setIdentifier("");
        this.deviceField111.setLabelString("Comment");
        this.deviceField111.setTextOnly(true);
        this.deviceField111.setOffsetNid(30);
        this.deviceField112.setIdentifier("");
        this.deviceField112.setEditable(true);
        this.deviceField112.setLabelString("Experiment");
        this.deviceField112.setTextOnly(true);
        this.deviceField112.setOffsetNid(37);
        this.gridLayout16.setRows(2);
        this.jPanel26.setLayout(this.gridLayout16);
        this.deviceChannel7.setLabelString("");
        this.deviceChannel7.setOffsetNid(34);
        this.deviceChannel7.setInSameLine(true);
        this.deviceChannel7.setUpdateIdentifier("");
        this.deviceChannel7.setShowVal("");
        this.deviceChannel7.setLayout(this.borderLayout9);
        this.flowLayout16.setAlignment(FlowLayout.LEFT);
        this.jPanel114.setLayout(this.gridLayout8);
        this.jPanel115.setLayout(this.flowLayout16);
        this.deviceField114.setNumCols(25);
        this.deviceField114.setIdentifier("");
        this.deviceField114.setLabelString("Comment");
        this.deviceField114.setTextOnly(true);
        this.deviceField114.setOffsetNid(36);
        this.deviceField115.setIdentifier("");
        this.deviceField115.setLabelString("Experiment");
        this.deviceField115.setTextOnly(true);
        this.deviceField115.setOffsetNid(41);
        this.gridLayout17.setRows(2);
        this.jPanel27.setLayout(this.gridLayout17);
        this.deviceChannel8.setLabelString("");
        this.deviceChannel8.setOffsetNid(39);
        this.deviceChannel8.setInSameLine(true);
        this.deviceChannel8.setUpdateIdentifier("");
        this.deviceChannel8.setShowVal("");
        this.deviceChannel8.setLayout(this.borderLayout10);
        this.flowLayout18.setAlignment(FlowLayout.LEFT);
        this.jPanel117.setLayout(this.gridLayout9);
        this.jPanel118.setLayout(this.flowLayout18);
        this.deviceField117.setNumCols(25);
        this.deviceField117.setIdentifier("");
        this.deviceField117.setLabelString("Comment");
        this.deviceField117.setTextOnly(true);
        this.deviceField117.setOffsetNid(40);
        this.deviceField18.setNumCols(25);
        this.deviceField18.setIdentifier("");
        this.deviceField18.setLabelString("Comment");
        this.deviceField18.setTextOnly(true);
        this.deviceField18.setOffsetNid(25);
        this.gridLayout18.setRows(2);
        this.deviceField20.setIdentifier("");
        this.deviceField20.setNumCols(50);
        this.deviceField20.setLabelString("Programs:");
        this.deviceField20.setTextOnly(false);
        this.deviceField20.setOffsetNid(8);
        this.gridLayout19.setRows(2);
        this.deviceField8.setIdentifier("");
        this.deviceField8.setNumCols(50);
        this.deviceField8.setLabelString("Pre Program:");
        this.deviceField8.setTextOnly(false);
        this.deviceField8.setOffsetNid(12);
        this.jPanel28.setLayout(this.gridLayout19);
        this.deviceField21.setOffsetNid(13);
        this.deviceField21.setTextOnly(false);
        this.deviceField21.setLabelString("Programs:");
        this.deviceField21.setNumCols(50);
        this.deviceField21.setIdentifier("");
        this.deviceField22.setOffsetNid(18);
        this.deviceField22.setTextOnly(false);
        this.deviceField22.setLabelString("Programs:");
        this.deviceField22.setNumCols(50);
        this.deviceField22.setIdentifier("");
        this.deviceField11.setIdentifier("");
        this.deviceField11.setNumCols(50);
        this.deviceField11.setLabelString("Pre Program:");
        this.deviceField11.setTextOnly(false);
        this.deviceField11.setOffsetNid(17);
        this.gridLayout110.setRows(2);
        this.jPanel29.setLayout(this.gridLayout110);
        this.deviceField14.setIdentifier("");
        this.deviceField14.setNumCols(50);
        this.deviceField14.setLabelString("Pre Program:");
        this.deviceField14.setTextOnly(false);
        this.deviceField14.setOffsetNid(22);
        this.gridLayout111.setRows(2);
        this.deviceField23.setOffsetNid(23);
        this.deviceField23.setTextOnly(false);
        this.deviceField23.setLabelString("Programs:");
        this.deviceField23.setNumCols(50);
        this.deviceField23.setIdentifier("");
        this.jPanel210.setLayout(this.gridLayout111);
        this.deviceField24.setOffsetNid(28);
        this.deviceField24.setTextOnly(false);
        this.deviceField24.setLabelString("Programs:");
        this.deviceField24.setNumCols(50);
        this.deviceField24.setIdentifier("");
        this.deviceField17.setIdentifier("");
        this.deviceField17.setNumCols(50);
        this.deviceField17.setLabelString("Pre Program:");
        this.deviceField17.setTextOnly(false);
        this.deviceField17.setOffsetNid(27);
        this.jPanel211.setLayout(this.gridLayout112);
        this.gridLayout112.setRows(2);
        this.jPanel212.setLayout(this.gridLayout113);
        this.deviceField110.setIdentifier("");
        this.deviceField110.setNumCols(50);
        this.deviceField110.setLabelString("Pre Program:");
        this.deviceField110.setTextOnly(false);
        this.deviceField110.setOffsetNid(32);
        this.gridLayout113.setRows(2);
        this.deviceField25.setOffsetNid(33);
        this.deviceField25.setTextOnly(false);
        this.deviceField25.setLabelString("Programs:");
        this.deviceField25.setNumCols(50);
        this.deviceField25.setIdentifier("");
        this.jPanel213.setLayout(this.gridLayout114);
        this.deviceField113.setIdentifier("");
        this.deviceField113.setNumCols(50);
        this.deviceField113.setLabelString("Pre Program:");
        this.deviceField113.setTextOnly(false);
        this.deviceField113.setOffsetNid(38);
        this.gridLayout114.setRows(2);
        this.deviceField26.setOffsetNid(39);
        this.deviceField26.setTextOnly(false);
        this.deviceField26.setLabelString("Programs:");
        this.deviceField26.setNumCols(50);
        this.deviceField26.setIdentifier("");
        this.gridLayout115.setRows(2);
        this.deviceField27.setIdentifier("");
        this.deviceField27.setNumCols(50);
        this.deviceField27.setLabelString("Programs:");
        this.deviceField27.setTextOnly(false);
        this.deviceField27.setOffsetNid(43);
        this.jPanel214.setLayout(this.gridLayout115);
        this.deviceField116.setIdentifier("");
        this.deviceField116.setNumCols(50);
        this.deviceField116.setLabelString("Pre Program:");
        this.deviceField116.setTextOnly(false);
        this.deviceField116.setOffsetNid(42);
        this.getContentPane().add(this.deviceButtons1, BorderLayout.SOUTH);
        this.getContentPane().add(this.jPanel1, BorderLayout.NORTH);
        this.jPanel1.add(this.jPanel2, null);
        this.jPanel2.add(this.deviceField1, null);
        this.jPanel1.add(this.jPanel3, null);
        this.jPanel3.add(this.deviceField3, null);
        this.jPanel3.add(this.deviceField2, null);
        this.getContentPane().add(this.jPanel4, BorderLayout.CENTER);
        this.jPanel4.add(this.jTabbedPane1, BorderLayout.CENTER);
        this.jTabbedPane1.add(this.jPanel5, "Sub-tree A");
        this.jPanel5.add(this.deviceChannel1, null);
        this.deviceChannel1.add(this.jPanel20, BorderLayout.CENTER);
        this.jPanel20.add(this.jPanel6, null);
        this.jPanel6.add(this.deviceField4, null);
        this.jPanel6.add(this.deviceField5, null);
        this.jPanel20.add(this.jPanel7, null);
        this.jPanel7.add(this.deviceField6, null);
        this.jPanel7.add(this.deviceField20, null);
        this.jTabbedPane1.add(this.jPanel9, "Sub-tree 2");
        this.jPanel9.add(this.deviceChannel2, null);
        this.deviceChannel2.add(this.jPanel21, BorderLayout.CENTER);
        this.jPanel21.add(this.jPanel10, null);
        this.jPanel10.add(this.deviceField9, null);
        this.jPanel10.add(this.deviceField7, null);
        this.jPanel21.add(this.jPanel28, null);
        this.jPanel28.add(this.deviceField8, null);
        this.jPanel28.add(this.deviceField21, null);
        this.jTabbedPane1.add(this.jPanel12, "Sub-tree 3");
        this.jPanel12.add(this.deviceChannel3, null);
        this.deviceChannel3.add(this.jPanel22, BorderLayout.CENTER);
        this.jPanel22.add(this.jPanel13, null);
        this.jPanel13.add(this.deviceField12, null);
        this.jPanel13.add(this.deviceField10, null);
        this.jPanel22.add(this.jPanel29, null);
        this.jPanel29.add(this.deviceField11, null);
        this.jPanel29.add(this.deviceField22, null);
        this.jTabbedPane1.add(this.jPanel15, "Sub-tree 4");
        this.jPanel15.add(this.deviceChannel4, null);
        this.deviceChannel4.add(this.jPanel23, BorderLayout.CENTER);
        this.jPanel23.add(this.jPanel16, null);
        this.jPanel16.add(this.deviceField15, null);
        this.jPanel16.add(this.deviceField13, null);
        this.jPanel23.add(this.jPanel210, null);
        this.jPanel210.add(this.deviceField14, null);
        this.jPanel210.add(this.deviceField23, null);
        this.jTabbedPane1.add(this.jPanel18, "Sub-tree 5");
        this.jPanel18.add(this.deviceChannel5, null);
        this.deviceChannel5.add(this.jPanel24, BorderLayout.CENTER);
        this.jPanel24.add(this.jPanel19, null);
        this.jPanel19.add(this.deviceField18, null);
        this.jPanel19.add(this.deviceField16, null);
        this.jPanel24.add(this.jPanel211, null);
        this.jPanel211.add(this.deviceField17, null);
        this.jPanel211.add(this.deviceField24, null);
        this.jTabbedPane1.add(this.jPanel111, "Sub-tree 6");
        this.jPanel111.add(this.deviceChannel6, null);
        this.deviceChannel6.add(this.jPanel25, BorderLayout.CENTER);
        this.jPanel25.add(this.jPanel112, null);
        this.jPanel112.add(this.deviceField111, null);
        this.jPanel112.add(this.deviceField19, null);
        this.jPanel25.add(this.jPanel212, null);
        this.jPanel212.add(this.deviceField110, null);
        this.jPanel212.add(this.deviceField25, null);
        this.jTabbedPane1.add(this.jPanel114, "Sub-tree 7");
        this.jPanel114.add(this.deviceChannel7, null);
        this.deviceChannel7.add(this.jPanel26, BorderLayout.CENTER);
        this.jPanel26.add(this.jPanel115, null);
        this.jPanel115.add(this.deviceField114, null);
        this.jPanel115.add(this.deviceField112, null);
        this.jPanel26.add(this.jPanel213, null);
        this.jPanel213.add(this.deviceField113, null);
        this.jPanel213.add(this.deviceField26, null);
        this.jTabbedPane1.add(this.jPanel117, "Sub-tree 8");
        this.jPanel117.add(this.deviceChannel8, null);
        this.deviceChannel8.add(this.jPanel27, BorderLayout.CENTER);
        this.jPanel27.add(this.jPanel118, null);
        this.jPanel118.add(this.deviceField117, null);
        this.jPanel118.add(this.deviceField115, null);
        this.jPanel27.add(this.jPanel214, null);
        this.jPanel214.add(this.deviceField116, null);
        this.jPanel214.add(this.deviceField27, null);
    }
}