import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import devicebeans.DeviceButtons;
import devicebeans.DeviceChannel;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 * 
 * @author not attributable
 * @version 1.0
 */
public class CADHSetup extends DeviceSetup{
    /**
     * 
     */
    private static final long serialVersionUID = -4036447935442505545L;
    BorderLayout   borderLayout1   = new BorderLayout();
    BorderLayout   borderLayout2   = new BorderLayout();
    DeviceButtons  deviceButtons1  = new DeviceButtons();
    DeviceChannel  deviceChannel1  = new DeviceChannel();
    DeviceChannel  deviceChannel2  = new DeviceChannel();
    DeviceChannel  deviceChannel3  = new DeviceChannel();
    DeviceChannel  deviceChannel4  = new DeviceChannel();
    DeviceChannel  deviceChannel5  = new DeviceChannel();
    DeviceChannel  deviceChannel6  = new DeviceChannel();
    DeviceChannel  deviceChannel7  = new DeviceChannel();
    DeviceChannel  deviceChannel8  = new DeviceChannel();
    DeviceChoice   deviceChoice1   = new DeviceChoice();
    DeviceChoice   deviceChoice2   = new DeviceChoice();
    DeviceChoice   deviceChoice3   = new DeviceChoice();
    DeviceChoice   deviceChoice4   = new DeviceChoice();
    DeviceDispatch deviceDispatch1 = new DeviceDispatch();
    DeviceField    deviceField1    = new DeviceField();
    DeviceField    deviceField10   = new DeviceField();
    DeviceField    deviceField11   = new DeviceField();
    DeviceField    deviceField12   = new DeviceField();
    DeviceField    deviceField13   = new DeviceField();
    DeviceField    deviceField14   = new DeviceField();
    DeviceField    deviceField15   = new DeviceField();
    DeviceField    deviceField16   = new DeviceField();
    DeviceField    deviceField17   = new DeviceField();
    DeviceField    deviceField18   = new DeviceField();
    DeviceField    deviceField19   = new DeviceField();
    DeviceField    deviceField2    = new DeviceField();
    DeviceField    deviceField20   = new DeviceField();
    DeviceField    deviceField3    = new DeviceField();
    DeviceField    deviceField4    = new DeviceField();
    DeviceField    deviceField5    = new DeviceField();
    DeviceField    deviceField6    = new DeviceField();
    DeviceField    deviceField7    = new DeviceField();
    DeviceField    deviceField8    = new DeviceField();
    DeviceField    deviceField9    = new DeviceField();
    FlowLayout     flowLayout1     = new FlowLayout();
    FlowLayout     flowLayout10    = new FlowLayout();
    FlowLayout     flowLayout11    = new FlowLayout();
    FlowLayout     flowLayout12    = new FlowLayout();
    FlowLayout     flowLayout13    = new FlowLayout();
    FlowLayout     flowLayout14    = new FlowLayout();
    FlowLayout     flowLayout15    = new FlowLayout();
    FlowLayout     flowLayout16    = new FlowLayout();
    FlowLayout     flowLayout2     = new FlowLayout();
    FlowLayout     flowLayout3     = new FlowLayout();
    FlowLayout     flowLayout4     = new FlowLayout();
    FlowLayout     flowLayout5     = new FlowLayout();
    FlowLayout     flowLayout6     = new FlowLayout();
    FlowLayout     flowLayout7     = new FlowLayout();
    FlowLayout     flowLayout8     = new FlowLayout();
    FlowLayout     flowLayout9     = new FlowLayout();
    GridLayout     gridLayout1     = new GridLayout();
    GridLayout     gridLayout2     = new GridLayout();
    GridLayout     gridLayout3     = new GridLayout();
    JPanel         jPanel1         = new JPanel();
    JPanel         jPanel10        = new JPanel();
    JPanel         jPanel11        = new JPanel();
    JPanel         jPanel12        = new JPanel();
    JPanel         jPanel13        = new JPanel();
    JPanel         jPanel14        = new JPanel();
    JPanel         jPanel15        = new JPanel();
    JPanel         jPanel16        = new JPanel();
    JPanel         jPanel2         = new JPanel();
    JPanel         jPanel3         = new JPanel();
    JPanel         jPanel4         = new JPanel();
    JPanel         jPanel5         = new JPanel();
    JPanel         jPanel6         = new JPanel();
    JPanel         jPanel7         = new JPanel();
    JPanel         jPanel8         = new JPanel();
    JPanel         jPanel9         = new JPanel();
    JTabbedPane    jTabbedPane1    = new JTabbedPane();

    public CADHSetup(){
        try{
            this.jbInit();
        }catch(final Exception e){
            e.printStackTrace();
        }
    }

    private void jbInit() throws Exception {
        this.setWidth(580);
        this.setHeight(450);
        this.setDeviceType("CADH");
        this.setDeviceProvider("localhost");
        this.setDeviceTitle("INCAA CADH 4 Channels Transient Recorder");
        this.getContentPane().setLayout(this.borderLayout1);
        this.jPanel1.setLayout(this.borderLayout2);
        this.deviceChannel1.setLabelString("Ch1:  ");
        this.deviceChannel1.setOffsetNid(10);
        this.deviceChannel1.setBorderVisible(true);
        this.deviceChannel1.setInSameLine(true);
        this.deviceChannel1.setUpdateIdentifier("");
        this.deviceChannel1.setShowVal("");
        this.deviceChannel1.setLayout(this.flowLayout1);
        this.jPanel3.setLayout(this.gridLayout1);
        this.gridLayout1.setColumns(1);
        this.gridLayout1.setRows(4);
        this.jPanel5.setLayout(this.flowLayout2);
        this.deviceField2.setOffsetNid(11);
        this.deviceField2.setLabelString("Start: ");
        this.deviceField2.setIdentifier("");
        this.deviceField1.setOffsetNid(12);
        this.deviceField1.setLabelString("End: ");
        this.deviceField1.setIdentifier("");
        this.deviceField3.setIdentifier("");
        this.deviceField3.setLabelString("End: ");
        this.deviceField3.setOffsetNid(30);
        this.deviceChannel2.setLayout(this.flowLayout3);
        this.deviceChannel2.setShowVal("");
        this.deviceChannel2.setUpdateIdentifier("");
        this.deviceChannel2.setInSameLine(true);
        this.deviceChannel2.setBorderVisible(true);
        this.deviceChannel2.setOffsetNid(28);
        this.deviceChannel2.setLabelString("Ch4:  ");
        this.jPanel6.setLayout(this.flowLayout4);
        this.deviceField4.setOffsetNid(29);
        this.deviceField4.setLabelString("Start: ");
        this.deviceField4.setIdentifier("");
        this.deviceField5.setIdentifier("");
        this.deviceField5.setLabelString("End: ");
        this.deviceField5.setOffsetNid(24);
        this.deviceChannel3.setLayout(this.flowLayout5);
        this.deviceChannel3.setShowVal("");
        this.deviceChannel3.setUpdateIdentifier("");
        this.deviceChannel3.setInSameLine(true);
        this.deviceChannel3.setBorderVisible(true);
        this.deviceChannel3.setOffsetNid(22);
        this.deviceChannel3.setLabelString("Ch3:  ");
        this.jPanel7.setLayout(this.flowLayout6);
        this.deviceField6.setOffsetNid(23);
        this.deviceField6.setLabelString("Start: ");
        this.deviceField6.setIdentifier("");
        this.deviceField7.setIdentifier("");
        this.deviceField7.setLabelString("End: ");
        this.deviceField7.setOffsetNid(18);
        this.deviceChannel4.setLayout(this.flowLayout7);
        this.deviceChannel4.setShowVal("");
        this.deviceChannel4.setUpdateIdentifier("");
        this.deviceChannel4.setInSameLine(true);
        this.deviceChannel4.setBorderVisible(true);
        this.deviceChannel4.setOffsetNid(16);
        this.deviceChannel4.setLabelString("Ch2:  ");
        this.jPanel8.setLayout(this.flowLayout8);
        this.deviceField8.setOffsetNid(17);
        this.deviceField8.setLabelString("Start: ");
        this.deviceField8.setIdentifier("");
        this.jPanel4.setLayout(this.gridLayout2);
        this.gridLayout2.setColumns(1);
        this.gridLayout2.setRows(4);
        this.deviceChannel5.setLabelString("Ch1: ");
        this.deviceChannel5.setOffsetNid(10);
        this.deviceChannel5.setBorderVisible(true);
        this.deviceChannel5.setInSameLine(true);
        this.deviceChannel5.setUpdateIdentifier("");
        this.deviceChannel5.setShowVal("");
        this.deviceChannel5.setLayout(this.flowLayout14);
        this.jPanel9.setLayout(this.flowLayout9);
        this.deviceField10.setOffsetNid(13);
        this.deviceField10.setLabelString("Start Idx: ");
        this.deviceField10.setIdentifier("");
        this.deviceField9.setOffsetNid(14);
        this.deviceField9.setLabelString("End Idx: ");
        this.deviceField9.setIdentifier("");
        this.deviceField11.setIdentifier("");
        this.deviceField11.setLabelString("Start Idx: ");
        this.deviceField11.setOffsetNid(31);
        this.deviceField12.setIdentifier("");
        this.deviceField12.setLabelString("End Idx: ");
        this.deviceField12.setOffsetNid(32);
        this.jPanel10.setLayout(this.flowLayout10);
        this.deviceChannel6.setLabelString("Ch4: ");
        this.deviceChannel6.setOffsetNid(28);
        this.deviceChannel6.setBorderVisible(true);
        this.deviceChannel6.setInSameLine(true);
        this.deviceChannel6.setUpdateIdentifier("");
        this.deviceChannel6.setShowVal("");
        this.deviceChannel6.setLayout(this.flowLayout16);
        this.deviceField13.setIdentifier("");
        this.deviceField13.setLabelString("Start Idx: ");
        this.deviceField13.setOffsetNid(25);
        this.deviceField14.setIdentifier("");
        this.deviceField14.setLabelString("End Idx: ");
        this.deviceField14.setOffsetNid(26);
        this.jPanel11.setLayout(this.flowLayout11);
        this.deviceChannel7.setLabelString("Ch3: ");
        this.deviceChannel7.setOffsetNid(22);
        this.deviceChannel7.setBorderVisible(true);
        this.deviceChannel7.setInSameLine(true);
        this.deviceChannel7.setUpdateIdentifier("");
        this.deviceChannel7.setShowVal("");
        this.deviceChannel7.setLayout(this.flowLayout15);
        this.deviceField15.setIdentifier("");
        this.deviceField15.setLabelString("Start Idx: ");
        this.deviceField15.setOffsetNid(19);
        this.deviceField16.setIdentifier("");
        this.deviceField16.setLabelString("End Idx: ");
        this.deviceField16.setOffsetNid(20);
        this.jPanel12.setLayout(this.flowLayout12);
        this.deviceChannel8.setLabelString("Ch2: ");
        this.deviceChannel8.setOffsetNid(16);
        this.deviceChannel8.setBorderVisible(true);
        this.deviceChannel8.setInSameLine(true);
        this.deviceChannel8.setUpdateIdentifier("");
        this.deviceChannel8.setShowVal("");
        this.deviceChannel8.setLayout(this.flowLayout13);
        this.jPanel2.setLayout(this.gridLayout3);
        this.gridLayout3.setColumns(1);
        this.gridLayout3.setRows(4);
        this.deviceField17.setOffsetNid(1);
        this.deviceField17.setTextOnly(true);
        this.deviceField17.setLabelString("CAMAC Name: ");
        this.deviceField17.setIdentifier("");
        this.deviceChoice1.setChoiceIntValues(null);
        this.deviceChoice1.setChoiceFloatValues(null);
        this.deviceChoice1.setOffsetNid(8);
        this.deviceChoice1.setLabelString("Use Time: ");
        this.deviceChoice1.setChoiceItems(new String[]{"TRUE", "FALSE"});
        this.deviceChoice1.setUpdateIdentifier("");
        this.deviceChoice1.setIdentifier("");
        this.deviceField18.setOffsetNid(2);
        this.deviceField18.setTextOnly(true);
        this.deviceField18.setLabelString("Comment: ");
        this.deviceField18.setNumCols(35);
        this.deviceField18.setIdentifier("");
        this.deviceField20.setOffsetNid(6);
        this.deviceField20.setLabelString("Clock Source: ");
        this.deviceField20.setNumCols(15);
        this.deviceField20.setIdentifier("");
        this.deviceField19.setOffsetNid(5);
        this.deviceField19.setLabelString("Trig. Source: ");
        this.deviceField19.setNumCols(15);
        this.deviceField19.setIdentifier("");
        this.deviceChoice4.setChoiceIntValues(null);
        this.deviceChoice4.setChoiceFloatValues(null);
        this.deviceChoice4.setOffsetNid(4);
        this.deviceChoice4.setLabelString("Clock Mode: ");
        this.deviceChoice4.setChoiceItems(new String[]{"INTERNAL", "EXTERNAL"});
        this.deviceChoice4.setUpdateIdentifier("");
        this.deviceChoice4.setIdentifier("");
        this.deviceChoice3.setChoiceIntValues(null);
        this.deviceChoice3.setChoiceFloatValues(new float[]{(float)500000.0, (float)250000.0, (float)125000.0, (float)50000.0, (float)10000.0, (float)5000.0, (float)1000.0, (float)500.0});
        this.deviceChoice3.setOffsetNid(7);
        this.deviceChoice3.setLabelString("Frequency: ");
        this.deviceChoice3.setChoiceItems(new String[]{"500E3", "250E3", "125E3", "50E3", "10E3", "5E3", "1E3", "500"});
        this.deviceChoice3.setUpdateIdentifier("");
        this.deviceChoice3.setIdentifier("");
        this.deviceChoice2.setChoiceIntValues(new int[]{1, 2, 4});
        this.deviceChoice2.setChoiceFloatValues(null);
        this.deviceChoice2.setOffsetNid(3);
        this.deviceChoice2.setLabelString("Num. Channels: ");
        this.deviceChoice2.setChoiceItems(new String[]{"1", "2", "4"});
        this.deviceChoice2.setUpdateIdentifier("");
        this.deviceChoice2.setIdentifier("");
        this.deviceButtons1.setCheckExpressions(null);
        this.deviceButtons1.setCheckMessages(null);
        this.deviceButtons1.setMethods(new String[]{"INIT", "TRIGGER", "STORE"});
        this.getContentPane().add(this.deviceButtons1, BorderLayout.SOUTH);
        this.getContentPane().add(this.jPanel1, BorderLayout.NORTH);
        this.jPanel1.add(this.jPanel2, BorderLayout.CENTER);
        this.jPanel2.add(this.jPanel13, null);
        this.jPanel13.add(this.deviceField17, null);
        this.jPanel13.add(this.deviceDispatch1, null);
        this.jPanel13.add(this.deviceChoice1, null);
        this.jPanel2.add(this.jPanel16, null);
        this.jPanel16.add(this.deviceField18, null);
        this.jPanel2.add(this.jPanel15, null);
        this.jPanel15.add(this.deviceField20, null);
        this.jPanel15.add(this.deviceField19, null);
        this.jPanel2.add(this.jPanel14, null);
        this.jPanel14.add(this.deviceChoice4, null);
        this.jPanel14.add(this.deviceChoice3, null);
        this.jPanel14.add(this.deviceChoice2, null);
        this.jPanel1.add(this.jTabbedPane1, BorderLayout.SOUTH);
        this.jTabbedPane1.add(this.jPanel3, "Channels (Time)");
        this.jPanel3.add(this.deviceChannel1, null);
        this.deviceChannel1.add(this.jPanel5, null);
        this.jPanel5.add(this.deviceField2, null);
        this.jPanel5.add(this.deviceField1, null);
        this.jPanel3.add(this.deviceChannel4, null);
        this.deviceChannel4.add(this.jPanel8, null);
        this.jPanel8.add(this.deviceField8, null);
        this.jPanel8.add(this.deviceField7, null);
        this.jPanel3.add(this.deviceChannel3, null);
        this.deviceChannel3.add(this.jPanel7, null);
        this.jPanel7.add(this.deviceField6, null);
        this.jPanel7.add(this.deviceField5, null);
        this.jPanel3.add(this.deviceChannel2, null);
        this.deviceChannel2.add(this.jPanel6, null);
        this.jPanel6.add(this.deviceField4, null);
        this.jPanel6.add(this.deviceField3, null);
        this.jTabbedPane1.add(this.jPanel4, "Channels (Samples)");
        this.jPanel4.add(this.deviceChannel5, null);
        this.deviceChannel5.add(this.jPanel9, null);
        this.jPanel9.add(this.deviceField10, null);
        this.jPanel9.add(this.deviceField9, null);
        this.jPanel4.add(this.deviceChannel8, null);
        this.deviceChannel8.add(this.jPanel12, null);
        this.jPanel12.add(this.deviceField15, null);
        this.jPanel12.add(this.deviceField16, null);
        this.jPanel4.add(this.deviceChannel7, null);
        this.deviceChannel7.add(this.jPanel11, null);
        this.jPanel11.add(this.deviceField13, null);
        this.jPanel11.add(this.deviceField14, null);
        this.jPanel4.add(this.deviceChannel6, null);
        this.deviceChannel6.add(this.jPanel10, null);
        this.jPanel10.add(this.deviceField11, null);
        this.jPanel10.add(this.deviceField12, null);
    }
}