import devicebeans.DeviceButtons;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

/*
 * CAENV1731Setup.java
 * Created on 18 aprile 2008, 15.42
 */
/**
 * @author manduchi
 */
public class CAENV1731Setup extends DeviceSetup{
    /**
     * 
     */
    private static final long serialVersionUID = -1235895520479043519L;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons           deviceButtons1;
    private DeviceChoice            deviceChoice1;
    private DeviceChoice            deviceChoice10;
    private DeviceChoice            deviceChoice11;
    private DeviceChoice            deviceChoice12;
    private DeviceChoice            deviceChoice13;
    private DeviceChoice            deviceChoice14;
    private DeviceChoice            deviceChoice15;
    private DeviceChoice            deviceChoice16;
    private DeviceChoice            deviceChoice17;
    private DeviceChoice            deviceChoice18;
    private DeviceChoice            deviceChoice19;
    private DeviceChoice            deviceChoice2;
    private DeviceChoice            deviceChoice20;
    private DeviceChoice            deviceChoice21;
    private DeviceChoice            deviceChoice22;
    private DeviceChoice            deviceChoice23;
    private DeviceChoice            deviceChoice3;
    private DeviceChoice            deviceChoice4;
    private DeviceChoice            deviceChoice5;
    private DeviceChoice            deviceChoice6;
    private DeviceChoice            deviceChoice7;
    private DeviceChoice            deviceChoice8;
    private DeviceChoice            deviceChoice9;
    private DeviceDispatch          deviceDispatch1;
    private DeviceField             deviceField1;
    private DeviceField             deviceField10;
    private DeviceField             deviceField11;
    private DeviceField             deviceField12;
    private DeviceField             deviceField13;
    private DeviceField             deviceField14;
    private DeviceField             deviceField15;
    private DeviceField             deviceField16;
    private DeviceField             deviceField17;
    private DeviceField             deviceField18;
    private DeviceField             deviceField19;
    private DeviceField             deviceField2;
    private DeviceField             deviceField20;
    private DeviceField             deviceField21;
    private DeviceField             deviceField22;
    private DeviceField             deviceField23;
    private DeviceField             deviceField24;
    private DeviceField             deviceField25;
    private DeviceField             deviceField26;
    private DeviceField             deviceField27;
    private DeviceField             deviceField28;
    private DeviceField             deviceField29;
    private DeviceField             deviceField3;
    private DeviceField             deviceField30;
    private DeviceField             deviceField31;
    private DeviceField             deviceField32;
    private DeviceField             deviceField33;
    private DeviceField             deviceField34;
    private DeviceField             deviceField35;
    private DeviceField             deviceField4;
    private DeviceField             deviceField5;
    private DeviceField             deviceField6;
    private DeviceField             deviceField7;
    private DeviceField             deviceField8;
    private DeviceField             deviceField9;
    private javax.swing.JPanel      jPanel1;
    private javax.swing.JPanel      jPanel10;
    private javax.swing.JPanel      jPanel11;
    private javax.swing.JPanel      jPanel12;
    private javax.swing.JPanel      jPanel13;
    private javax.swing.JPanel      jPanel14;
    private javax.swing.JPanel      jPanel15;
    private javax.swing.JPanel      jPanel16;
    private javax.swing.JPanel      jPanel17;
    private javax.swing.JPanel      jPanel18;
    private javax.swing.JPanel      jPanel19;
    private javax.swing.JPanel      jPanel2;
    private javax.swing.JPanel      jPanel20;
    private javax.swing.JPanel      jPanel21;
    private javax.swing.JPanel      jPanel22;
    private javax.swing.JPanel      jPanel23;
    private javax.swing.JPanel      jPanel24;
    private javax.swing.JPanel      jPanel25;
    private javax.swing.JPanel      jPanel26;
    private javax.swing.JPanel      jPanel27;
    private javax.swing.JPanel      jPanel28;
    private javax.swing.JPanel      jPanel29;
    private javax.swing.JPanel      jPanel3;
    private javax.swing.JPanel      jPanel30;
    private javax.swing.JPanel      jPanel31;
    private javax.swing.JPanel      jPanel32;
    private javax.swing.JPanel      jPanel33;
    private javax.swing.JPanel      jPanel34;
    private javax.swing.JPanel      jPanel35;
    private javax.swing.JPanel      jPanel36;
    private javax.swing.JPanel      jPanel4;
    private javax.swing.JPanel      jPanel5;
    private javax.swing.JPanel      jPanel6;
    private javax.swing.JPanel      jPanel7;
    private javax.swing.JPanel      jPanel8;
    private javax.swing.JPanel      jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;

    // End of variables declaration//GEN-END:variables
    /** Creates new form CAENV1731Setup */
    public CAENV1731Setup(){
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.deviceButtons1 = new DeviceButtons();
        this.jPanel1 = new javax.swing.JPanel();
        this.deviceField1 = new DeviceField();
        this.deviceField2 = new DeviceField();
        this.deviceField13 = new DeviceField();
        this.deviceDispatch1 = new DeviceDispatch();
        this.jPanel2 = new javax.swing.JPanel();
        this.jPanel3 = new javax.swing.JPanel();
        this.jPanel7 = new javax.swing.JPanel();
        this.deviceChoice1 = new DeviceChoice();
        this.deviceChoice2 = new DeviceChoice();
        this.deviceChoice3 = new DeviceChoice();
        this.jPanel8 = new javax.swing.JPanel();
        this.deviceField4 = new DeviceField();
        this.jPanel6 = new javax.swing.JPanel();
        this.deviceChoice4 = new DeviceChoice();
        this.deviceField5 = new DeviceField();
        this.jPanel4 = new javax.swing.JPanel();
        this.jPanel11 = new javax.swing.JPanel();
        this.deviceChoice5 = new DeviceChoice();
        this.deviceField6 = new DeviceField();
        this.jPanel10 = new javax.swing.JPanel();
        this.jPanel12 = new javax.swing.JPanel();
        this.deviceChoice6 = new DeviceChoice();
        this.deviceField8 = new DeviceField();
        this.deviceChoice23 = new DeviceChoice();
        this.jPanel13 = new javax.swing.JPanel();
        this.deviceField9 = new DeviceField();
        this.deviceField10 = new DeviceField();
        this.deviceField11 = new DeviceField();
        this.deviceField12 = new DeviceField();
        this.jPanel5 = new javax.swing.JPanel();
        this.jTabbedPane1 = new javax.swing.JTabbedPane();
        this.jPanel23 = new javax.swing.JPanel();
        this.jPanel9 = new javax.swing.JPanel();
        this.deviceChoice7 = new DeviceChoice();
        this.deviceChoice8 = new DeviceChoice();
        this.deviceField3 = new DeviceField();
        this.jPanel14 = new javax.swing.JPanel();
        this.deviceField7 = new DeviceField();
        this.deviceField14 = new DeviceField();
        this.jPanel24 = new javax.swing.JPanel();
        this.jPanel15 = new javax.swing.JPanel();
        this.deviceChoice9 = new DeviceChoice();
        this.deviceChoice10 = new DeviceChoice();
        this.deviceField15 = new DeviceField();
        this.jPanel16 = new javax.swing.JPanel();
        this.deviceField16 = new DeviceField();
        this.deviceField17 = new DeviceField();
        this.jPanel25 = new javax.swing.JPanel();
        this.jPanel17 = new javax.swing.JPanel();
        this.deviceChoice11 = new DeviceChoice();
        this.deviceChoice12 = new DeviceChoice();
        this.deviceField18 = new DeviceField();
        this.jPanel18 = new javax.swing.JPanel();
        this.deviceField19 = new DeviceField();
        this.deviceField20 = new DeviceField();
        this.jPanel26 = new javax.swing.JPanel();
        this.jPanel19 = new javax.swing.JPanel();
        this.deviceChoice13 = new DeviceChoice();
        this.deviceChoice14 = new DeviceChoice();
        this.deviceField21 = new DeviceField();
        this.jPanel20 = new javax.swing.JPanel();
        this.deviceField22 = new DeviceField();
        this.deviceField23 = new DeviceField();
        this.jPanel27 = new javax.swing.JPanel();
        this.jPanel21 = new javax.swing.JPanel();
        this.deviceChoice15 = new DeviceChoice();
        this.deviceChoice16 = new DeviceChoice();
        this.deviceField24 = new DeviceField();
        this.jPanel22 = new javax.swing.JPanel();
        this.deviceField25 = new DeviceField();
        this.deviceField26 = new DeviceField();
        this.jPanel28 = new javax.swing.JPanel();
        this.jPanel29 = new javax.swing.JPanel();
        this.deviceChoice17 = new DeviceChoice();
        this.deviceChoice18 = new DeviceChoice();
        this.deviceField27 = new DeviceField();
        this.jPanel30 = new javax.swing.JPanel();
        this.deviceField28 = new DeviceField();
        this.deviceField29 = new DeviceField();
        this.jPanel31 = new javax.swing.JPanel();
        this.jPanel32 = new javax.swing.JPanel();
        this.deviceChoice19 = new DeviceChoice();
        this.deviceChoice20 = new DeviceChoice();
        this.deviceField30 = new DeviceField();
        this.jPanel33 = new javax.swing.JPanel();
        this.deviceField31 = new DeviceField();
        this.deviceField32 = new DeviceField();
        this.jPanel34 = new javax.swing.JPanel();
        this.jPanel35 = new javax.swing.JPanel();
        this.deviceChoice21 = new DeviceChoice();
        this.deviceChoice22 = new DeviceChoice();
        this.deviceField33 = new DeviceField();
        this.jPanel36 = new javax.swing.JPanel();
        this.deviceField34 = new DeviceField();
        this.deviceField35 = new DeviceField();
        setDeviceProvider("localhost");
        setDeviceTitle("CAEN V1731 Transient Recorder");
        setDeviceType("CAENV1731");
        setHeight(620);
        setWidth(700);
        getContentPane().add(this.deviceButtons1, java.awt.BorderLayout.SOUTH);
        this.deviceField1.setIdentifier("");
        this.deviceField1.setLabelString("Comment:");
        this.deviceField1.setNumCols(20);
        this.deviceField1.setOffsetNid(1);
        this.deviceField1.setTextOnly(true);
        this.jPanel1.add(this.deviceField1);
        this.deviceField2.setIdentifier("");
        this.deviceField2.setLabelString("VME Addr.:");
        this.deviceField2.setNumCols(6);
        this.deviceField2.setOffsetNid(2);
        this.jPanel1.add(this.deviceField2);
        this.deviceField13.setIdentifier("");
        this.deviceField13.setLabelString("Board Id: ");
        this.deviceField13.setNumCols(2);
        this.deviceField13.setOffsetNid(19);
        this.jPanel1.add(this.deviceField13);
        this.jPanel1.add(this.deviceDispatch1);
        getContentPane().add(this.jPanel1, java.awt.BorderLayout.NORTH);
        this.jPanel2.setLayout(new java.awt.BorderLayout());
        this.jPanel3.setLayout(new java.awt.GridLayout(2, 1));
        this.jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Trigger"));
        this.deviceChoice1.setChoiceItems(new String[]{"OVER TRESHOLD", "UNDER THERSHOLD"});
        this.deviceChoice1.setIdentifier("");
        this.deviceChoice1.setLabelString("Mode: ");
        this.deviceChoice1.setOffsetNid(3);
        this.deviceChoice1.setUpdateIdentifier("");
        this.jPanel7.add(this.deviceChoice1);
        this.deviceChoice2.setChoiceItems(new String[]{"ENABLED", "DISBLED"});
        this.deviceChoice2.setIdentifier("");
        this.deviceChoice2.setLabelString("Soft. Trig.:");
        this.deviceChoice2.setOffsetNid(4);
        this.deviceChoice2.setUpdateIdentifier("");
        this.jPanel7.add(this.deviceChoice2);
        this.deviceChoice3.setChoiceItems(new String[]{"ENABLED", "DISBLED"});
        this.deviceChoice3.setIdentifier("");
        this.deviceChoice3.setLabelString("Ext. Trig.:");
        this.deviceChoice3.setOffsetNid(5);
        this.deviceChoice3.setUpdateIdentifier("");
        this.jPanel7.add(this.deviceChoice3);
        this.jPanel3.add(this.jPanel7);
        this.deviceField4.setIdentifier("");
        this.deviceField4.setLabelString("Trigger time: ");
        this.deviceField4.setNumCols(35);
        this.deviceField4.setOffsetNid(6);
        this.jPanel8.add(this.deviceField4);
        this.jPanel3.add(this.jPanel8);
        this.jPanel2.add(this.jPanel3, java.awt.BorderLayout.NORTH);
        this.jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clock"));
        this.deviceChoice4.setChoiceItems(new String[]{"500 MHz", "1 GHz", "EXTERNAL"});
        this.deviceChoice4.setIdentifier("");
        this.deviceChoice4.setLabelString("Clock Mode:");
        this.deviceChoice4.setOffsetNid(8);
        this.deviceChoice4.setUpdateIdentifier("");
        this.jPanel6.add(this.deviceChoice4);
        this.deviceField5.setIdentifier("");
        this.deviceField5.setLabelString("Clock source:");
        this.deviceField5.setNumCols(20);
        this.deviceField5.setOffsetNid(9);
        this.jPanel6.add(this.deviceField5);
        this.jPanel2.add(this.jPanel6, java.awt.BorderLayout.CENTER);
        this.jPanel4.setLayout(new java.awt.BorderLayout());
        this.jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Monitor"));
        this.deviceChoice5.setChoiceItems(new String[]{"MAJORITY", "SAWTOOTH", "BUF. OCCUPANCY", "SELECTED LEVEL"});
        this.deviceChoice5.setIdentifier("");
        this.deviceChoice5.setLabelString("Mode: ");
        this.deviceChoice5.setOffsetNid(10);
        this.deviceChoice5.setUpdateIdentifier("");
        this.jPanel11.add(this.deviceChoice5);
        this.deviceField6.setIdentifier("");
        this.deviceField6.setLabelString("Level(V): ");
        this.deviceField6.setNumCols(5);
        this.deviceField6.setOffsetNid(11);
        this.jPanel11.add(this.deviceField6);
        this.jPanel4.add(this.jPanel11, java.awt.BorderLayout.NORTH);
        this.jPanel10.setLayout(new java.awt.GridLayout(2, 1));
        this.jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        this.deviceChoice6.setChoiceItems(new String[]{"YES", "NO"});
        this.deviceChoice6.setIdentifier("");
        this.deviceChoice6.setLabelString("Use Time:");
        this.deviceChoice6.setOffsetNid(13);
        this.deviceChoice6.setUpdateIdentifier("");
        this.jPanel12.add(this.deviceChoice6);
        this.deviceField8.setIdentifier("");
        this.deviceField8.setLabelString("PTS");
        this.deviceField8.setOffsetNid(14);
        this.jPanel12.add(this.deviceField8);
        this.deviceChoice23.setChoiceIntValues(new int[]{1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024});
        this.deviceChoice23.setChoiceItems(new String[]{"1", "2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"});
        this.deviceChoice23.setIdentifier("");
        this.deviceChoice23.setLabelString("Num Segments: ");
        this.deviceChoice23.setOffsetNid(12);
        this.deviceChoice23.setUpdateIdentifier("");
        this.jPanel12.add(this.deviceChoice23);
        this.jPanel10.add(this.jPanel12);
        this.deviceField9.setIdentifier("");
        this.deviceField9.setLabelString("Start Time: ");
        this.deviceField9.setNumCols(8);
        this.deviceField9.setOffsetNid(17);
        this.jPanel13.add(this.deviceField9);
        this.deviceField10.setIdentifier("");
        this.deviceField10.setLabelString("End Time: ");
        this.deviceField10.setNumCols(8);
        this.deviceField10.setOffsetNid(18);
        this.jPanel13.add(this.deviceField10);
        this.deviceField11.setIdentifier("");
        this.deviceField11.setLabelString("Start Idx: ");
        this.deviceField11.setNumCols(8);
        this.deviceField11.setOffsetNid(15);
        this.jPanel13.add(this.deviceField11);
        this.deviceField12.setIdentifier("");
        this.deviceField12.setLabelString("End Idx: ");
        this.deviceField12.setNumCols(8);
        this.deviceField12.setOffsetNid(16);
        this.jPanel13.add(this.deviceField12);
        this.jPanel10.add(this.jPanel13);
        this.jPanel4.add(this.jPanel10, java.awt.BorderLayout.CENTER);
        this.jPanel5.setLayout(new java.awt.BorderLayout());
        this.jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Channels"));
        this.jPanel23.setLayout(new java.awt.GridLayout(2, 1));
        this.deviceChoice7.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice7.setIdentifier("");
        this.deviceChoice7.setLabelString("State: ");
        this.deviceChoice7.setOffsetNid(21);
        this.deviceChoice7.setUpdateIdentifier("");
        this.jPanel9.add(this.deviceChoice7);
        this.deviceChoice8.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice8.setIdentifier("");
        this.deviceChoice8.setLabelString("Trig. State: ");
        this.deviceChoice8.setOffsetNid(22);
        this.deviceChoice8.setUpdateIdentifier("");
        this.jPanel9.add(this.deviceChoice8);
        this.deviceField3.setIdentifier("");
        this.deviceField3.setLabelString("DAC Offset: ");
        this.deviceField3.setNumCols(6);
        this.deviceField3.setOffsetNid(25);
        this.jPanel9.add(this.deviceField3);
        this.jPanel23.add(this.jPanel9);
        this.deviceField7.setIdentifier("");
        this.deviceField7.setLabelString("Trig. Treshold  Level: ");
        this.deviceField7.setNumCols(6);
        this.deviceField7.setOffsetNid(23);
        this.jPanel14.add(this.deviceField7);
        this.deviceField14.setIdentifier("");
        this.deviceField14.setLabelString("Trig. Treshold Samples: ");
        this.deviceField14.setNumCols(6);
        this.deviceField14.setOffsetNid(24);
        this.jPanel14.add(this.deviceField14);
        this.jPanel23.add(this.jPanel14);
        this.jTabbedPane1.addTab("Ch1", this.jPanel23);
        this.jPanel24.setLayout(new java.awt.GridLayout(2, 1));
        this.deviceChoice9.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice9.setIdentifier("");
        this.deviceChoice9.setLabelString("State: ");
        this.deviceChoice9.setOffsetNid(28);
        this.deviceChoice9.setUpdateIdentifier("");
        this.jPanel15.add(this.deviceChoice9);
        this.deviceChoice10.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice10.setIdentifier("");
        this.deviceChoice10.setLabelString("Trig. State: ");
        this.deviceChoice10.setOffsetNid(29);
        this.deviceChoice10.setUpdateIdentifier("");
        this.jPanel15.add(this.deviceChoice10);
        this.deviceField15.setIdentifier("");
        this.deviceField15.setLabelString("DAC Offset: ");
        this.deviceField15.setNumCols(6);
        this.deviceField15.setOffsetNid(32);
        this.jPanel15.add(this.deviceField15);
        this.jPanel24.add(this.jPanel15);
        this.deviceField16.setIdentifier("");
        this.deviceField16.setLabelString("Trig. Treshold  Level: ");
        this.deviceField16.setNumCols(6);
        this.deviceField16.setOffsetNid(30);
        this.jPanel16.add(this.deviceField16);
        this.deviceField17.setIdentifier("");
        this.deviceField17.setLabelString("Trig. Treshold Samples: ");
        this.deviceField17.setNumCols(6);
        this.deviceField17.setOffsetNid(31);
        this.jPanel16.add(this.deviceField17);
        this.jPanel24.add(this.jPanel16);
        this.jTabbedPane1.addTab("Ch2", this.jPanel24);
        this.jPanel25.setLayout(new java.awt.GridLayout(2, 1));
        this.deviceChoice11.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice11.setIdentifier("");
        this.deviceChoice11.setLabelString("State: ");
        this.deviceChoice11.setOffsetNid(35);
        this.deviceChoice11.setUpdateIdentifier("");
        this.jPanel17.add(this.deviceChoice11);
        this.deviceChoice12.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice12.setIdentifier("");
        this.deviceChoice12.setLabelString("Trig. State: ");
        this.deviceChoice12.setOffsetNid(36);
        this.deviceChoice12.setUpdateIdentifier("");
        this.jPanel17.add(this.deviceChoice12);
        this.deviceField18.setIdentifier("");
        this.deviceField18.setLabelString("DAC Offset: ");
        this.deviceField18.setNumCols(6);
        this.deviceField18.setOffsetNid(39);
        this.jPanel17.add(this.deviceField18);
        this.jPanel25.add(this.jPanel17);
        this.deviceField19.setIdentifier("");
        this.deviceField19.setLabelString("Trig. Treshold  Level: ");
        this.deviceField19.setNumCols(6);
        this.deviceField19.setOffsetNid(37);
        this.jPanel18.add(this.deviceField19);
        this.deviceField20.setIdentifier("");
        this.deviceField20.setLabelString("Trig. Treshold Samples: ");
        this.deviceField20.setNumCols(6);
        this.deviceField20.setOffsetNid(38);
        this.jPanel18.add(this.deviceField20);
        this.jPanel25.add(this.jPanel18);
        this.jTabbedPane1.addTab("Ch3", this.jPanel25);
        this.jPanel26.setLayout(new java.awt.GridLayout(2, 1));
        this.deviceChoice13.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice13.setIdentifier("");
        this.deviceChoice13.setLabelString("State: ");
        this.deviceChoice13.setOffsetNid(42);
        this.deviceChoice13.setUpdateIdentifier("");
        this.jPanel19.add(this.deviceChoice13);
        this.deviceChoice14.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice14.setIdentifier("");
        this.deviceChoice14.setLabelString("Trig. State: ");
        this.deviceChoice14.setOffsetNid(43);
        this.deviceChoice14.setUpdateIdentifier("");
        this.jPanel19.add(this.deviceChoice14);
        this.deviceField21.setIdentifier("");
        this.deviceField21.setLabelString("DAC Offset: ");
        this.deviceField21.setNumCols(6);
        this.deviceField21.setOffsetNid(46);
        this.jPanel19.add(this.deviceField21);
        this.jPanel26.add(this.jPanel19);
        this.deviceField22.setIdentifier("");
        this.deviceField22.setLabelString("Trig. Treshold  Level: ");
        this.deviceField22.setNumCols(6);
        this.deviceField22.setOffsetNid(44);
        this.jPanel20.add(this.deviceField22);
        this.deviceField23.setIdentifier("");
        this.deviceField23.setLabelString("Trig. Treshold Samples: ");
        this.deviceField23.setNumCols(6);
        this.deviceField23.setOffsetNid(45);
        this.jPanel20.add(this.deviceField23);
        this.jPanel26.add(this.jPanel20);
        this.jTabbedPane1.addTab("Ch4", this.jPanel26);
        this.jPanel27.setLayout(new java.awt.GridLayout(2, 1));
        this.deviceChoice15.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice15.setIdentifier("");
        this.deviceChoice15.setLabelString("State: ");
        this.deviceChoice15.setOffsetNid(49);
        this.deviceChoice15.setUpdateIdentifier("");
        this.jPanel21.add(this.deviceChoice15);
        this.deviceChoice16.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice16.setIdentifier("");
        this.deviceChoice16.setLabelString("Trig. State: ");
        this.deviceChoice16.setOffsetNid(50);
        this.deviceChoice16.setUpdateIdentifier("");
        this.jPanel21.add(this.deviceChoice16);
        this.deviceField24.setIdentifier("");
        this.deviceField24.setLabelString("DAC Offset: ");
        this.deviceField24.setNumCols(6);
        this.deviceField24.setOffsetNid(53);
        this.jPanel21.add(this.deviceField24);
        this.jPanel27.add(this.jPanel21);
        this.deviceField25.setIdentifier("");
        this.deviceField25.setLabelString("Trig. Treshold  Level: ");
        this.deviceField25.setNumCols(6);
        this.deviceField25.setOffsetNid(51);
        this.jPanel22.add(this.deviceField25);
        this.deviceField26.setIdentifier("");
        this.deviceField26.setLabelString("Trig. Treshold Samples: ");
        this.deviceField26.setNumCols(6);
        this.deviceField26.setOffsetNid(52);
        this.jPanel22.add(this.deviceField26);
        this.jPanel27.add(this.jPanel22);
        this.jTabbedPane1.addTab("Ch5", this.jPanel27);
        this.jPanel28.setLayout(new java.awt.GridLayout(2, 1));
        this.deviceChoice17.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice17.setIdentifier("");
        this.deviceChoice17.setLabelString("State: ");
        this.deviceChoice17.setOffsetNid(56);
        this.deviceChoice17.setUpdateIdentifier("");
        this.jPanel29.add(this.deviceChoice17);
        this.deviceChoice18.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice18.setIdentifier("");
        this.deviceChoice18.setLabelString("Trig. State: ");
        this.deviceChoice18.setOffsetNid(57);
        this.deviceChoice18.setUpdateIdentifier("");
        this.jPanel29.add(this.deviceChoice18);
        this.deviceField27.setIdentifier("");
        this.deviceField27.setLabelString("DAC Offset: ");
        this.deviceField27.setNumCols(6);
        this.deviceField27.setOffsetNid(60);
        this.jPanel29.add(this.deviceField27);
        this.jPanel28.add(this.jPanel29);
        this.deviceField28.setIdentifier("");
        this.deviceField28.setLabelString("Trig. Treshold  Level: ");
        this.deviceField28.setNumCols(6);
        this.deviceField28.setOffsetNid(58);
        this.jPanel30.add(this.deviceField28);
        this.deviceField29.setIdentifier("");
        this.deviceField29.setLabelString("Trig. Treshold Samples: ");
        this.deviceField29.setNumCols(6);
        this.deviceField29.setOffsetNid(59);
        this.jPanel30.add(this.deviceField29);
        this.jPanel28.add(this.jPanel30);
        this.jTabbedPane1.addTab("Ch6", this.jPanel28);
        this.jPanel31.setLayout(new java.awt.GridLayout(2, 1));
        this.deviceChoice19.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice19.setIdentifier("");
        this.deviceChoice19.setLabelString("State: ");
        this.deviceChoice19.setOffsetNid(63);
        this.deviceChoice19.setUpdateIdentifier("");
        this.jPanel32.add(this.deviceChoice19);
        this.deviceChoice20.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice20.setIdentifier("");
        this.deviceChoice20.setLabelString("Trig. State: ");
        this.deviceChoice20.setOffsetNid(64);
        this.deviceChoice20.setUpdateIdentifier("");
        this.jPanel32.add(this.deviceChoice20);
        this.deviceField30.setIdentifier("");
        this.deviceField30.setLabelString("DAC Offset: ");
        this.deviceField30.setNumCols(6);
        this.deviceField30.setOffsetNid(67);
        this.jPanel32.add(this.deviceField30);
        this.jPanel31.add(this.jPanel32);
        this.deviceField31.setIdentifier("");
        this.deviceField31.setLabelString("Trig. Treshold  Level: ");
        this.deviceField31.setNumCols(6);
        this.deviceField31.setOffsetNid(65);
        this.jPanel33.add(this.deviceField31);
        this.deviceField32.setIdentifier("");
        this.deviceField32.setLabelString("Trig. Treshold Samples: ");
        this.deviceField32.setNumCols(6);
        this.deviceField32.setOffsetNid(66);
        this.jPanel33.add(this.deviceField32);
        this.jPanel31.add(this.jPanel33);
        this.jTabbedPane1.addTab("Ch7", this.jPanel31);
        this.jPanel34.setLayout(new java.awt.GridLayout(2, 1));
        this.deviceChoice21.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice21.setIdentifier("");
        this.deviceChoice21.setLabelString("State: ");
        this.deviceChoice21.setOffsetNid(70);
        this.deviceChoice21.setUpdateIdentifier("");
        this.jPanel35.add(this.deviceChoice21);
        this.deviceChoice22.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice22.setIdentifier("");
        this.deviceChoice22.setLabelString("Trig. State: ");
        this.deviceChoice22.setOffsetNid(71);
        this.deviceChoice22.setUpdateIdentifier("");
        this.jPanel35.add(this.deviceChoice22);
        this.deviceField33.setIdentifier("");
        this.deviceField33.setLabelString("DAC Offset: ");
        this.deviceField33.setNumCols(6);
        this.deviceField33.setOffsetNid(74);
        this.jPanel35.add(this.deviceField33);
        this.jPanel34.add(this.jPanel35);
        this.deviceField34.setIdentifier("");
        this.deviceField34.setLabelString("Trig. Treshold  Level: ");
        this.deviceField34.setNumCols(6);
        this.deviceField34.setOffsetNid(72);
        this.jPanel36.add(this.deviceField34);
        this.deviceField35.setIdentifier("");
        this.deviceField35.setLabelString("Trig. Treshold Samples: ");
        this.deviceField35.setNumCols(6);
        this.deviceField35.setOffsetNid(73);
        this.jPanel36.add(this.deviceField35);
        this.jPanel34.add(this.jPanel36);
        this.jTabbedPane1.addTab("Ch8", this.jPanel34);
        this.jPanel5.add(this.jTabbedPane1, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.getAccessibleContext().setAccessibleName("Ch 2");
        this.jPanel4.add(this.jPanel5, java.awt.BorderLayout.SOUTH);
        this.jPanel2.add(this.jPanel4, java.awt.BorderLayout.SOUTH);
        getContentPane().add(this.jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
}
