import devicebeans.DeviceButtons;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

/*
 * CAENV1740Setup.java
 * Created on 27 novembre 2008, 15.25
 */
/**
 * @author manduchi
 */
public class CAENV1740Setup extends DeviceSetup{
    /**
     *
     */
    private static final long       serialVersionUID = -4905360822719535660L;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons           deviceButtons1;
    private DeviceChoice            deviceChoice1;
    private DeviceChoice            deviceChoice10;
    private DeviceChoice            deviceChoice11;
    private DeviceChoice            deviceChoice12;
    private DeviceChoice            deviceChoice13;
    private DeviceChoice            deviceChoice14;
    private DeviceChoice            deviceChoice15;
    private DeviceChoice            deviceChoice16;
    private DeviceChoice            deviceChoice17;
    private DeviceChoice            deviceChoice18;
    private DeviceChoice            deviceChoice19;
    private DeviceChoice            deviceChoice2;
    private DeviceChoice            deviceChoice20;
    private DeviceChoice            deviceChoice21;
    private DeviceChoice            deviceChoice22;
    private DeviceChoice            deviceChoice23;
    private DeviceChoice            deviceChoice24;
    private DeviceChoice            deviceChoice3;
    private DeviceChoice            deviceChoice4;
    private DeviceChoice            deviceChoice5;
    private DeviceChoice            deviceChoice6;
    private DeviceChoice            deviceChoice7;
    private DeviceChoice            deviceChoice8;
    private DeviceChoice            deviceChoice9;
    private DeviceDispatch          deviceDispatch1;
    private DeviceField             deviceField1;
    private DeviceField             deviceField10;
    private DeviceField             deviceField11;
    private DeviceField             deviceField12;
    private DeviceField             deviceField13;
    private DeviceField             deviceField14;
    private DeviceField             deviceField15;
    private DeviceField             deviceField16;
    private DeviceField             deviceField17;
    private DeviceField             deviceField18;
    private DeviceField             deviceField19;
    private DeviceField             deviceField2;
    private DeviceField             deviceField20;
    private DeviceField             deviceField21;
    private DeviceField             deviceField22;
    private DeviceField             deviceField23;
    private DeviceField             deviceField24;
    private DeviceField             deviceField25;
    private DeviceField             deviceField26;
    private DeviceField             deviceField27;
    private DeviceField             deviceField28;
    private DeviceField             deviceField29;
    private DeviceField             deviceField3;
    private DeviceField             deviceField30;
    private DeviceField             deviceField31;
    private DeviceField             deviceField32;
    private DeviceField             deviceField33;
    private DeviceField             deviceField34;
    private DeviceField             deviceField35;
    private DeviceField             deviceField4;
    private DeviceField             deviceField5;
    private DeviceField             deviceField6;
    private DeviceField             deviceField7;
    private DeviceField             deviceField8;
    private DeviceField             deviceField9;
    private javax.swing.JPanel      jPanel1;
    private javax.swing.JPanel      jPanel10;
    private javax.swing.JPanel      jPanel11;
    private javax.swing.JPanel      jPanel12;
    private javax.swing.JPanel      jPanel13;
    private javax.swing.JPanel      jPanel14;
    private javax.swing.JPanel      jPanel15;
    private javax.swing.JPanel      jPanel16;
    private javax.swing.JPanel      jPanel17;
    private javax.swing.JPanel      jPanel18;
    private javax.swing.JPanel      jPanel19;
    private javax.swing.JPanel      jPanel2;
    private javax.swing.JPanel      jPanel20;
    private javax.swing.JPanel      jPanel21;
    private javax.swing.JPanel      jPanel22;
    private javax.swing.JPanel      jPanel23;
    private javax.swing.JPanel      jPanel24;
    private javax.swing.JPanel      jPanel25;
    private javax.swing.JPanel      jPanel26;
    private javax.swing.JPanel      jPanel27;
    private javax.swing.JPanel      jPanel28;
    private javax.swing.JPanel      jPanel29;
    private javax.swing.JPanel      jPanel3;
    private javax.swing.JPanel      jPanel30;
    private javax.swing.JPanel      jPanel31;
    private javax.swing.JPanel      jPanel32;
    private javax.swing.JPanel      jPanel33;
    private javax.swing.JPanel      jPanel34;
    private javax.swing.JPanel      jPanel35;
    private javax.swing.JPanel      jPanel36;
    private javax.swing.JPanel      jPanel4;
    private javax.swing.JPanel      jPanel5;
    private javax.swing.JPanel      jPanel6;
    private javax.swing.JPanel      jPanel7;
    private javax.swing.JPanel      jPanel8;
    private javax.swing.JPanel      jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;

    // End of variables declaration//GEN-END:variables
    /** Creates new form CAENV1740Setup */
    public CAENV1740Setup(){
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.deviceButtons1 = new DeviceButtons();
        this.jPanel2 = new javax.swing.JPanel();
        this.jPanel4 = new javax.swing.JPanel();
        this.deviceField1 = new DeviceField();
        this.deviceField2 = new DeviceField();
        this.deviceField3 = new DeviceField();
        this.deviceDispatch1 = new DeviceDispatch();
        this.jPanel3 = new javax.swing.JPanel();
        this.jPanel11 = new javax.swing.JPanel();
        this.deviceChoice1 = new DeviceChoice();
        this.deviceChoice4 = new DeviceChoice();
        this.deviceChoice2 = new DeviceChoice();
        this.deviceChoice3 = new DeviceChoice();
        this.jPanel12 = new javax.swing.JPanel();
        this.deviceField4 = new DeviceField();
        this.jPanel1 = new javax.swing.JPanel();
        this.jPanel6 = new javax.swing.JPanel();
        this.jPanel8 = new javax.swing.JPanel();
        this.deviceChoice5 = new DeviceChoice();
        this.deviceField5 = new DeviceField();
        this.deviceField6 = new DeviceField();
        this.jPanel7 = new javax.swing.JPanel();
        this.jPanel14 = new javax.swing.JPanel();
        this.deviceChoice6 = new DeviceChoice();
        this.deviceField7 = new DeviceField();
        this.deviceChoice7 = new DeviceChoice();
        this.deviceChoice8 = new DeviceChoice();
        this.jPanel13 = new javax.swing.JPanel();
        this.deviceField8 = new DeviceField();
        this.deviceField9 = new DeviceField();
        this.deviceField10 = new DeviceField();
        this.deviceField11 = new DeviceField();
        this.jPanel5 = new javax.swing.JPanel();
        this.jTabbedPane1 = new javax.swing.JTabbedPane();
        this.jPanel10 = new javax.swing.JPanel();
        this.jPanel15 = new javax.swing.JPanel();
        this.deviceChoice9 = new DeviceChoice();
        this.deviceChoice10 = new DeviceChoice();
        this.deviceField12 = new DeviceField();
        this.jPanel9 = new javax.swing.JPanel();
        this.deviceField13 = new DeviceField();
        this.deviceField14 = new DeviceField();
        this.jPanel16 = new javax.swing.JPanel();
        this.jPanel17 = new javax.swing.JPanel();
        this.deviceChoice11 = new DeviceChoice();
        this.deviceChoice12 = new DeviceChoice();
        this.deviceField15 = new DeviceField();
        this.jPanel18 = new javax.swing.JPanel();
        this.deviceField16 = new DeviceField();
        this.deviceField17 = new DeviceField();
        this.jPanel19 = new javax.swing.JPanel();
        this.jPanel20 = new javax.swing.JPanel();
        this.deviceChoice13 = new DeviceChoice();
        this.deviceChoice14 = new DeviceChoice();
        this.deviceField18 = new DeviceField();
        this.jPanel21 = new javax.swing.JPanel();
        this.deviceField19 = new DeviceField();
        this.deviceField20 = new DeviceField();
        this.jPanel22 = new javax.swing.JPanel();
        this.jPanel23 = new javax.swing.JPanel();
        this.deviceChoice15 = new DeviceChoice();
        this.deviceChoice16 = new DeviceChoice();
        this.deviceField21 = new DeviceField();
        this.jPanel24 = new javax.swing.JPanel();
        this.deviceField22 = new DeviceField();
        this.deviceField23 = new DeviceField();
        this.jPanel25 = new javax.swing.JPanel();
        this.jPanel26 = new javax.swing.JPanel();
        this.deviceChoice17 = new DeviceChoice();
        this.deviceChoice18 = new DeviceChoice();
        this.deviceField24 = new DeviceField();
        this.jPanel27 = new javax.swing.JPanel();
        this.deviceField25 = new DeviceField();
        this.deviceField26 = new DeviceField();
        this.jPanel28 = new javax.swing.JPanel();
        this.jPanel29 = new javax.swing.JPanel();
        this.deviceChoice19 = new DeviceChoice();
        this.deviceChoice20 = new DeviceChoice();
        this.deviceField27 = new DeviceField();
        this.jPanel30 = new javax.swing.JPanel();
        this.deviceField28 = new DeviceField();
        this.deviceField29 = new DeviceField();
        this.jPanel31 = new javax.swing.JPanel();
        this.jPanel32 = new javax.swing.JPanel();
        this.deviceChoice21 = new DeviceChoice();
        this.deviceChoice22 = new DeviceChoice();
        this.deviceField30 = new DeviceField();
        this.jPanel33 = new javax.swing.JPanel();
        this.deviceField31 = new DeviceField();
        this.deviceField32 = new DeviceField();
        this.jPanel34 = new javax.swing.JPanel();
        this.jPanel35 = new javax.swing.JPanel();
        this.deviceChoice23 = new DeviceChoice();
        this.deviceChoice24 = new DeviceChoice();
        this.deviceField33 = new DeviceField();
        this.jPanel36 = new javax.swing.JPanel();
        this.deviceField34 = new DeviceField();
        this.deviceField35 = new DeviceField();
        this.setDeviceProvider("localhost");
        this.setDeviceTitle(" CAEN V1740");
        this.setDeviceType("CAENV1740");
        this.setHeight(500);
        this.setWidth(800);
        this.getContentPane().add(this.deviceButtons1, java.awt.BorderLayout.PAGE_END);
        this.jPanel2.setLayout(new java.awt.BorderLayout());
        this.deviceField1.setIdentifier("");
        this.deviceField1.setLabelString("Comment:");
        this.deviceField1.setNumCols(20);
        this.deviceField1.setOffsetNid(1);
        this.deviceField1.setTextOnly(true);
        this.jPanel4.add(this.deviceField1);
        this.deviceField2.setIdentifier("");
        this.deviceField2.setLabelString("VME Addr: ");
        this.deviceField2.setNumCols(4);
        this.deviceField2.setOffsetNid(3);
        this.jPanel4.add(this.deviceField2);
        this.deviceField3.setIdentifier("");
        this.deviceField3.setLabelString("Board ID: ");
        this.deviceField3.setNumCols(4);
        this.deviceField3.setOffsetNid(2);
        this.jPanel4.add(this.deviceField3);
        this.jPanel4.add(this.deviceDispatch1);
        this.jPanel2.add(this.jPanel4, java.awt.BorderLayout.PAGE_START);
        this.jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Trigger"));
        this.jPanel3.setLayout(new java.awt.BorderLayout());
        this.deviceChoice1.setChoiceItems(new String[]{"OVER THRESHOLD", "UNDER THRESHOLD"});
        this.deviceChoice1.setIdentifier("");
        this.deviceChoice1.setLabelString("Mode");
        this.deviceChoice1.setOffsetNid(4);
        this.deviceChoice1.setUpdateIdentifier("");
        this.jPanel11.add(this.deviceChoice1);
        this.deviceChoice4.setChoiceItems(new String[]{"YES", "NO"});
        this.deviceChoice4.setIdentifier("");
        this.deviceChoice4.setLabelString("Use Int. Counter:");
        this.deviceChoice4.setOffsetNid(8);
        this.deviceChoice4.setUpdateIdentifier("");
        this.jPanel11.add(this.deviceChoice4);
        this.deviceChoice2.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice2.setIdentifier("");
        this.deviceChoice2.setLabelString("Soft. Trig:");
        this.deviceChoice2.setOffsetNid(5);
        this.deviceChoice2.setUpdateIdentifier("");
        this.jPanel11.add(this.deviceChoice2);
        this.deviceChoice3.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice3.setIdentifier("");
        this.deviceChoice3.setLabelString("Ext. Trig:");
        this.deviceChoice3.setOffsetNid(6);
        this.deviceChoice3.setUpdateIdentifier("");
        this.jPanel11.add(this.deviceChoice3);
        this.jPanel3.add(this.jPanel11, java.awt.BorderLayout.NORTH);
        this.deviceField4.setIdentifier("");
        this.deviceField4.setLabelString("Trig. Source: ");
        this.deviceField4.setNumCols(40);
        this.deviceField4.setOffsetNid(7);
        this.jPanel12.add(this.deviceField4);
        this.jPanel3.add(this.jPanel12, java.awt.BorderLayout.CENTER);
        this.jPanel2.add(this.jPanel3, java.awt.BorderLayout.CENTER);
        this.getContentPane().add(this.jPanel2, java.awt.BorderLayout.PAGE_START);
        this.jPanel1.setLayout(new java.awt.BorderLayout());
        this.jPanel6.setLayout(new java.awt.BorderLayout());
        this.jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Clock"));
        this.deviceChoice5.setChoiceItems(new String[]{"62.5 MHz", "EXTERNAL"});
        this.deviceChoice5.setIdentifier("");
        this.deviceChoice5.setLabelString("Clock Mode:");
        this.deviceChoice5.setOffsetNid(9);
        this.deviceChoice5.setUpdateIdentifier("");
        this.jPanel8.add(this.deviceChoice5);
        this.deviceField5.setIdentifier("");
        this.deviceField5.setLabelString("Clock division:");
        this.deviceField5.setNumCols(4);
        this.deviceField5.setOffsetNid(10);
        this.jPanel8.add(this.deviceField5);
        this.deviceField6.setIdentifier("");
        this.deviceField6.setLabelString("Clock Source");
        this.deviceField6.setNumCols(30);
        this.deviceField6.setOffsetNid(11);
        this.jPanel8.add(this.deviceField6);
        this.jPanel6.add(this.jPanel8, java.awt.BorderLayout.PAGE_START);
        this.jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        this.jPanel7.setLayout(new java.awt.BorderLayout());
        this.deviceChoice6.setChoiceItems(new String[]{"YES", "NO"});
        this.deviceChoice6.setIdentifier("");
        this.deviceChoice6.setLabelString("Use Time: ");
        this.deviceChoice6.setOffsetNid(13);
        this.deviceChoice6.setUpdateIdentifier("");
        this.jPanel14.add(this.deviceChoice6);
        this.deviceField7.setIdentifier("");
        this.deviceField7.setLabelString("PTS:");
        this.deviceField7.setNumCols(6);
        this.deviceField7.setOffsetNid(14);
        this.jPanel14.add(this.deviceField7);
        this.deviceChoice7.setChoiceIntValues(new int[]{1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024});
        this.deviceChoice7.setChoiceItems(new String[]{"1", "2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"});
        this.deviceChoice7.setIdentifier("");
        this.deviceChoice7.setLabelString("Num Segments:");
        this.deviceChoice7.setOffsetNid(12);
        this.deviceChoice7.setUpdateIdentifier("");
        this.jPanel14.add(this.deviceChoice7);
        this.deviceChoice8.setChoiceItems(new String[]{"YES", "NO"});
        this.deviceChoice8.setIdentifier("");
        this.deviceChoice8.setLabelString("Cont. Readout:");
        this.deviceChoice8.setOffsetNid(19);
        this.deviceChoice8.setUpdateIdentifier("");
        this.jPanel14.add(this.deviceChoice8);
        this.jPanel7.add(this.jPanel14, java.awt.BorderLayout.PAGE_START);
        this.deviceField8.setIdentifier("");
        this.deviceField8.setLabelString("Start Time:");
        this.deviceField8.setOffsetNid(17);
        this.jPanel13.add(this.deviceField8);
        this.deviceField9.setIdentifier("");
        this.deviceField9.setLabelString("End Time: ");
        this.deviceField9.setOffsetNid(18);
        this.jPanel13.add(this.deviceField9);
        this.deviceField10.setIdentifier("");
        this.deviceField10.setLabelString("Start Idx: ");
        this.deviceField10.setOffsetNid(15);
        this.jPanel13.add(this.deviceField10);
        this.deviceField11.setIdentifier("");
        this.deviceField11.setLabelString("End Idx: ");
        this.deviceField11.setOffsetNid(16);
        this.jPanel13.add(this.deviceField11);
        this.jPanel7.add(this.jPanel13, java.awt.BorderLayout.CENTER);
        this.jPanel6.add(this.jPanel7, java.awt.BorderLayout.CENTER);
        this.jPanel1.add(this.jPanel6, java.awt.BorderLayout.PAGE_START);
        this.jPanel5.setLayout(new java.awt.BorderLayout());
        this.jPanel10.setLayout(new java.awt.BorderLayout());
        this.deviceChoice9.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice9.setIdentifier("");
        this.deviceChoice9.setLabelString("State:");
        this.deviceChoice9.setOffsetNid(21);
        this.deviceChoice9.setUpdateIdentifier("");
        this.jPanel15.add(this.deviceChoice9);
        this.deviceChoice10.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice10.setIdentifier("");
        this.deviceChoice10.setLabelString("Trig. State: ");
        this.deviceChoice10.setOffsetNid(22);
        this.deviceChoice10.setUpdateIdentifier("");
        this.jPanel15.add(this.deviceChoice10);
        this.deviceField12.setIdentifier("");
        this.deviceField12.setLabelString("DAC Offset: ");
        this.deviceField12.setNumCols(4);
        this.deviceField12.setOffsetNid(25);
        this.jPanel15.add(this.deviceField12);
        this.jPanel10.add(this.jPanel15, java.awt.BorderLayout.PAGE_START);
        this.deviceField13.setIdentifier("");
        this.deviceField13.setLabelString("Trig. Threshold Level: ");
        this.deviceField13.setOffsetNid(23);
        this.jPanel9.add(this.deviceField13);
        this.deviceField14.setIdentifier("");
        this.deviceField14.setLabelString("Trig. Threshold Samples: ");
        this.deviceField14.setOffsetNid(24);
        this.jPanel9.add(this.deviceField14);
        this.jPanel10.add(this.jPanel9, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("Ch 1-8", this.jPanel10);
        this.jPanel16.setLayout(new java.awt.BorderLayout());
        this.deviceChoice11.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice11.setIdentifier("");
        this.deviceChoice11.setLabelString("State:");
        this.deviceChoice11.setOffsetNid(27);
        this.deviceChoice11.setUpdateIdentifier("");
        this.jPanel17.add(this.deviceChoice11);
        this.deviceChoice12.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice12.setIdentifier("");
        this.deviceChoice12.setLabelString("Trig. State: ");
        this.deviceChoice12.setOffsetNid(28);
        this.deviceChoice12.setUpdateIdentifier("");
        this.jPanel17.add(this.deviceChoice12);
        this.deviceField15.setIdentifier("");
        this.deviceField15.setLabelString("DAC Offset: ");
        this.deviceField15.setNumCols(4);
        this.deviceField15.setOffsetNid(31);
        this.jPanel17.add(this.deviceField15);
        this.jPanel16.add(this.jPanel17, java.awt.BorderLayout.PAGE_START);
        this.deviceField16.setIdentifier("");
        this.deviceField16.setLabelString("Trig. Threshold Level: ");
        this.deviceField16.setOffsetNid(29);
        this.jPanel18.add(this.deviceField16);
        this.deviceField17.setIdentifier("");
        this.deviceField17.setLabelString("Trig. Threshold Samples: ");
        this.deviceField17.setOffsetNid(30);
        this.jPanel18.add(this.deviceField17);
        this.jPanel16.add(this.jPanel18, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("Ch 9-16", this.jPanel16);
        this.jPanel19.setLayout(new java.awt.BorderLayout());
        this.deviceChoice13.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice13.setIdentifier("");
        this.deviceChoice13.setLabelString("State:");
        this.deviceChoice13.setOffsetNid(33);
        this.deviceChoice13.setUpdateIdentifier("");
        this.jPanel20.add(this.deviceChoice13);
        this.deviceChoice14.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice14.setIdentifier("");
        this.deviceChoice14.setLabelString("Trig. State: ");
        this.deviceChoice14.setOffsetNid(34);
        this.deviceChoice14.setUpdateIdentifier("");
        this.jPanel20.add(this.deviceChoice14);
        this.deviceField18.setIdentifier("");
        this.deviceField18.setLabelString("DAC Offset: ");
        this.deviceField18.setNumCols(4);
        this.deviceField18.setOffsetNid(37);
        this.jPanel20.add(this.deviceField18);
        this.jPanel19.add(this.jPanel20, java.awt.BorderLayout.PAGE_START);
        this.deviceField19.setIdentifier("");
        this.deviceField19.setLabelString("Trig. Threshold Level: ");
        this.deviceField19.setOffsetNid(35);
        this.jPanel21.add(this.deviceField19);
        this.deviceField20.setIdentifier("");
        this.deviceField20.setLabelString("Trig. Threshold Samples: ");
        this.deviceField20.setOffsetNid(36);
        this.jPanel21.add(this.deviceField20);
        this.jPanel19.add(this.jPanel21, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("Ch 17-24", this.jPanel19);
        this.jPanel22.setLayout(new java.awt.BorderLayout());
        this.deviceChoice15.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice15.setIdentifier("");
        this.deviceChoice15.setLabelString("State:");
        this.deviceChoice15.setOffsetNid(39);
        this.deviceChoice15.setUpdateIdentifier("");
        this.jPanel23.add(this.deviceChoice15);
        this.deviceChoice16.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice16.setIdentifier("");
        this.deviceChoice16.setLabelString("Trig. State: ");
        this.deviceChoice16.setOffsetNid(40);
        this.deviceChoice16.setUpdateIdentifier("");
        this.jPanel23.add(this.deviceChoice16);
        this.deviceField21.setIdentifier("");
        this.deviceField21.setLabelString("DAC Offset: ");
        this.deviceField21.setNumCols(4);
        this.deviceField21.setOffsetNid(43);
        this.jPanel23.add(this.deviceField21);
        this.jPanel22.add(this.jPanel23, java.awt.BorderLayout.PAGE_START);
        this.deviceField22.setIdentifier("");
        this.deviceField22.setLabelString("Trig. Threshold Level: ");
        this.deviceField22.setOffsetNid(41);
        this.jPanel24.add(this.deviceField22);
        this.deviceField23.setIdentifier("");
        this.deviceField23.setLabelString("Trig. Threshold Samples: ");
        this.deviceField23.setOffsetNid(42);
        this.jPanel24.add(this.deviceField23);
        this.jPanel22.add(this.jPanel24, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("Ch25-32", this.jPanel22);
        this.jPanel25.setLayout(new java.awt.BorderLayout());
        this.deviceChoice17.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice17.setIdentifier("");
        this.deviceChoice17.setLabelString("State:");
        this.deviceChoice17.setOffsetNid(45);
        this.deviceChoice17.setUpdateIdentifier("");
        this.jPanel26.add(this.deviceChoice17);
        this.deviceChoice18.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice18.setIdentifier("");
        this.deviceChoice18.setLabelString("Trig. State: ");
        this.deviceChoice18.setOffsetNid(46);
        this.deviceChoice18.setUpdateIdentifier("");
        this.jPanel26.add(this.deviceChoice18);
        this.deviceField24.setIdentifier("");
        this.deviceField24.setLabelString("DAC Offset: ");
        this.deviceField24.setNumCols(4);
        this.deviceField24.setOffsetNid(49);
        this.jPanel26.add(this.deviceField24);
        this.jPanel25.add(this.jPanel26, java.awt.BorderLayout.PAGE_START);
        this.deviceField25.setIdentifier("");
        this.deviceField25.setLabelString("Trig. Threshold Level: ");
        this.deviceField25.setOffsetNid(47);
        this.jPanel27.add(this.deviceField25);
        this.deviceField26.setIdentifier("");
        this.deviceField26.setLabelString("Trig. Threshold Samples: ");
        this.deviceField26.setOffsetNid(48);
        this.jPanel27.add(this.deviceField26);
        this.jPanel25.add(this.jPanel27, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("Ch33-40", this.jPanel25);
        this.jPanel28.setLayout(new java.awt.BorderLayout());
        this.deviceChoice19.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice19.setIdentifier("");
        this.deviceChoice19.setLabelString("State:");
        this.deviceChoice19.setOffsetNid(51);
        this.deviceChoice19.setUpdateIdentifier("");
        this.jPanel29.add(this.deviceChoice19);
        this.deviceChoice20.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice20.setIdentifier("");
        this.deviceChoice20.setLabelString("Trig. State: ");
        this.deviceChoice20.setOffsetNid(52);
        this.deviceChoice20.setUpdateIdentifier("");
        this.jPanel29.add(this.deviceChoice20);
        this.deviceField27.setIdentifier("");
        this.deviceField27.setLabelString("DAC Offset: ");
        this.deviceField27.setNumCols(4);
        this.deviceField27.setOffsetNid(55);
        this.jPanel29.add(this.deviceField27);
        this.jPanel28.add(this.jPanel29, java.awt.BorderLayout.PAGE_START);
        this.deviceField28.setIdentifier("");
        this.deviceField28.setLabelString("Trig. Threshold Level: ");
        this.deviceField28.setOffsetNid(53);
        this.jPanel30.add(this.deviceField28);
        this.deviceField29.setIdentifier("");
        this.deviceField29.setLabelString("Trig. Threshold Samples: ");
        this.deviceField29.setOffsetNid(54);
        this.jPanel30.add(this.deviceField29);
        this.jPanel28.add(this.jPanel30, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("Ch 41-48", this.jPanel28);
        this.jPanel31.setLayout(new java.awt.BorderLayout());
        this.deviceChoice21.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice21.setIdentifier("");
        this.deviceChoice21.setLabelString("State:");
        this.deviceChoice21.setOffsetNid(57);
        this.deviceChoice21.setUpdateIdentifier("");
        this.jPanel32.add(this.deviceChoice21);
        this.deviceChoice22.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice22.setIdentifier("");
        this.deviceChoice22.setLabelString("Trig. State: ");
        this.deviceChoice22.setOffsetNid(58);
        this.deviceChoice22.setUpdateIdentifier("");
        this.jPanel32.add(this.deviceChoice22);
        this.deviceField30.setIdentifier("");
        this.deviceField30.setLabelString("DAC Offset: ");
        this.deviceField30.setNumCols(4);
        this.deviceField30.setOffsetNid(61);
        this.jPanel32.add(this.deviceField30);
        this.jPanel31.add(this.jPanel32, java.awt.BorderLayout.PAGE_START);
        this.deviceField31.setIdentifier("");
        this.deviceField31.setLabelString("Trig. Threshold Level: ");
        this.deviceField31.setOffsetNid(59);
        this.jPanel33.add(this.deviceField31);
        this.deviceField32.setIdentifier("");
        this.deviceField32.setLabelString("Trig. Threshold Samples: ");
        this.deviceField32.setOffsetNid(60);
        this.jPanel33.add(this.deviceField32);
        this.jPanel31.add(this.jPanel33, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("Ch 49-56", this.jPanel31);
        this.jPanel34.setLayout(new java.awt.BorderLayout());
        this.deviceChoice23.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice23.setIdentifier("");
        this.deviceChoice23.setLabelString("State:");
        this.deviceChoice23.setOffsetNid(63);
        this.deviceChoice23.setUpdateIdentifier("");
        this.jPanel35.add(this.deviceChoice23);
        this.deviceChoice24.setChoiceItems(new String[]{"ENABLED", "DISABLED"});
        this.deviceChoice24.setIdentifier("");
        this.deviceChoice24.setLabelString("Trig. State: ");
        this.deviceChoice24.setOffsetNid(64);
        this.deviceChoice24.setUpdateIdentifier("");
        this.jPanel35.add(this.deviceChoice24);
        this.deviceField33.setIdentifier("");
        this.deviceField33.setLabelString("DAC Offset: ");
        this.deviceField33.setNumCols(4);
        this.deviceField33.setOffsetNid(67);
        this.jPanel35.add(this.deviceField33);
        this.jPanel34.add(this.jPanel35, java.awt.BorderLayout.PAGE_START);
        this.deviceField34.setIdentifier("");
        this.deviceField34.setLabelString("Trig. Threshold Level: ");
        this.deviceField34.setOffsetNid(65);
        this.jPanel36.add(this.deviceField34);
        this.deviceField35.setIdentifier("");
        this.deviceField35.setLabelString("Trig. Threshold Samples: ");
        this.deviceField35.setOffsetNid(66);
        this.jPanel36.add(this.deviceField35);
        this.jPanel34.add(this.jPanel36, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("Ch57-64", this.jPanel34);
        this.jPanel5.add(this.jTabbedPane1, java.awt.BorderLayout.CENTER);
        this.jPanel1.add(this.jPanel5, java.awt.BorderLayout.CENTER);
        this.getContentPane().add(this.jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
}
