import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import devicebeans.DeviceButtons;
import devicebeans.DeviceChannel;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 * 
 * @author not attributable
 * @version 1.0
 */
public class CHVPSSetup extends DeviceSetup{
    /**
     * 
     */
    private static final long serialVersionUID = -350495978095332184L;
    BorderLayout   borderLayout1        = new BorderLayout();
    DeviceButtons  deviceButtons1       = new DeviceButtons();
    DeviceChannel  deviceChannel1       = new DeviceChannel();
    DeviceChannel  deviceChannel10      = new DeviceChannel();
    DeviceChannel  deviceChannel11      = new DeviceChannel();
    DeviceChannel  deviceChannel110     = new DeviceChannel();
    DeviceChannel  deviceChannel111     = new DeviceChannel();
    DeviceChannel  deviceChannel1110    = new DeviceChannel();
    DeviceChannel  deviceChannel1111    = new DeviceChannel();
    DeviceChannel  deviceChannel11110   = new DeviceChannel();
    DeviceChannel  deviceChannel1112    = new DeviceChannel();
    DeviceChannel  deviceChannel1113    = new DeviceChannel();
    DeviceChannel  deviceChannel1114    = new DeviceChannel();
    DeviceChannel  deviceChannel1115    = new DeviceChannel();
    DeviceChannel  deviceChannel1116    = new DeviceChannel();
    DeviceChannel  deviceChannel1117    = new DeviceChannel();
    DeviceChannel  deviceChannel1118    = new DeviceChannel();
    DeviceChannel  deviceChannel1119    = new DeviceChannel();
    DeviceChannel  deviceChannel112     = new DeviceChannel();
    DeviceChannel  deviceChannel113     = new DeviceChannel();
    DeviceChannel  deviceChannel114     = new DeviceChannel();
    DeviceChannel  deviceChannel115     = new DeviceChannel();
    DeviceChannel  deviceChannel116     = new DeviceChannel();
    DeviceChannel  deviceChannel117     = new DeviceChannel();
    DeviceChannel  deviceChannel118     = new DeviceChannel();
    DeviceChannel  deviceChannel119     = new DeviceChannel();
    DeviceChannel  deviceChannel12      = new DeviceChannel();
    DeviceChannel  deviceChannel13      = new DeviceChannel();
    DeviceChannel  deviceChannel14      = new DeviceChannel();
    DeviceChannel  deviceChannel15      = new DeviceChannel();
    DeviceChannel  deviceChannel16      = new DeviceChannel();
    DeviceChannel  deviceChannel17      = new DeviceChannel();
    DeviceChannel  deviceChannel18      = new DeviceChannel();
    DeviceChannel  deviceChannel19      = new DeviceChannel();
    DeviceChannel  deviceChannel2       = new DeviceChannel();
    DeviceChannel  deviceChannel3       = new DeviceChannel();
    DeviceChannel  deviceChannel4       = new DeviceChannel();
    DeviceChannel  deviceChannel5       = new DeviceChannel();
    DeviceChannel  deviceChannel6       = new DeviceChannel();
    DeviceChannel  deviceChannel7       = new DeviceChannel();
    DeviceChannel  deviceChannel8       = new DeviceChannel();
    DeviceChannel  deviceChannel9       = new DeviceChannel();
    DeviceChoice   deviceChoice1        = new DeviceChoice();
    DeviceChoice   deviceChoice10       = new DeviceChoice();
    DeviceChoice   deviceChoice11       = new DeviceChoice();
    DeviceChoice   deviceChoice110      = new DeviceChoice();
    DeviceChoice   deviceChoice111      = new DeviceChoice();
    DeviceChoice   deviceChoice1110     = new DeviceChoice();
    DeviceChoice   deviceChoice1111     = new DeviceChoice();
    DeviceChoice   deviceChoice11110    = new DeviceChoice();
    DeviceChoice   deviceChoice1112     = new DeviceChoice();
    DeviceChoice   deviceChoice1113     = new DeviceChoice();
    DeviceChoice   deviceChoice1114     = new DeviceChoice();
    DeviceChoice   deviceChoice1115     = new DeviceChoice();
    DeviceChoice   deviceChoice1116     = new DeviceChoice();
    DeviceChoice   deviceChoice1117     = new DeviceChoice();
    DeviceChoice   deviceChoice1118     = new DeviceChoice();
    DeviceChoice   deviceChoice1119     = new DeviceChoice();
    DeviceChoice   deviceChoice112      = new DeviceChoice();
    DeviceChoice   deviceChoice113      = new DeviceChoice();
    DeviceChoice   deviceChoice114      = new DeviceChoice();
    DeviceChoice   deviceChoice115      = new DeviceChoice();
    DeviceChoice   deviceChoice116      = new DeviceChoice();
    DeviceChoice   deviceChoice117      = new DeviceChoice();
    DeviceChoice   deviceChoice118      = new DeviceChoice();
    DeviceChoice   deviceChoice119      = new DeviceChoice();
    DeviceChoice   deviceChoice12       = new DeviceChoice();
    DeviceChoice   deviceChoice13       = new DeviceChoice();
    DeviceChoice   deviceChoice14       = new DeviceChoice();
    DeviceChoice   deviceChoice15       = new DeviceChoice();
    DeviceChoice   deviceChoice16       = new DeviceChoice();
    DeviceChoice   deviceChoice17       = new DeviceChoice();
    DeviceChoice   deviceChoice18       = new DeviceChoice();
    DeviceChoice   deviceChoice19       = new DeviceChoice();
    DeviceChoice   deviceChoice2        = new DeviceChoice();
    DeviceChoice   deviceChoice3        = new DeviceChoice();
    DeviceChoice   deviceChoice4        = new DeviceChoice();
    DeviceChoice   deviceChoice5        = new DeviceChoice();
    DeviceChoice   deviceChoice6        = new DeviceChoice();
    DeviceChoice   deviceChoice7        = new DeviceChoice();
    DeviceChoice   deviceChoice8        = new DeviceChoice();
    DeviceChoice   deviceChoice9        = new DeviceChoice();
    DeviceDispatch deviceDispatch1      = new DeviceDispatch();
    DeviceField    deviceField1         = new DeviceField();
    DeviceField    deviceField10        = new DeviceField();
    DeviceField    deviceField11        = new DeviceField();
    DeviceField    deviceField110       = new DeviceField();
    DeviceField    deviceField111       = new DeviceField();
    DeviceField    deviceField1110      = new DeviceField();
    DeviceField    deviceField1111      = new DeviceField();
    DeviceField    deviceField11110     = new DeviceField();
    DeviceField    deviceField11111     = new DeviceField();
    DeviceField    deviceField111110    = new DeviceField();
    DeviceField    deviceField111111    = new DeviceField();
    DeviceField    deviceField1111110   = new DeviceField();
    DeviceField    deviceField1111111   = new DeviceField();
    DeviceField    deviceField11111110  = new DeviceField();
    DeviceField    deviceField11111111  = new DeviceField();
    DeviceField    deviceField111111110 = new DeviceField();
    DeviceField    deviceField111111111 = new DeviceField();
    DeviceField    deviceField111111112 = new DeviceField();
    DeviceField    deviceField111111113 = new DeviceField();
    DeviceField    deviceField11111112  = new DeviceField();
    DeviceField    deviceField11111113  = new DeviceField();
    DeviceField    deviceField11111114  = new DeviceField();
    DeviceField    deviceField11111115  = new DeviceField();
    DeviceField    deviceField11111116  = new DeviceField();
    DeviceField    deviceField11111117  = new DeviceField();
    DeviceField    deviceField11111118  = new DeviceField();
    DeviceField    deviceField11111119  = new DeviceField();
    DeviceField    deviceField1111112   = new DeviceField();
    DeviceField    deviceField1111113   = new DeviceField();
    DeviceField    deviceField1111114   = new DeviceField();
    DeviceField    deviceField1111115   = new DeviceField();
    DeviceField    deviceField1111116   = new DeviceField();
    DeviceField    deviceField1111117   = new DeviceField();
    DeviceField    deviceField1111118   = new DeviceField();
    DeviceField    deviceField1111119   = new DeviceField();
    DeviceField    deviceField111112    = new DeviceField();
    DeviceField    deviceField111113    = new DeviceField();
    DeviceField    deviceField111114    = new DeviceField();
    DeviceField    deviceField111115    = new DeviceField();
    DeviceField    deviceField111116    = new DeviceField();
    DeviceField    deviceField111117    = new DeviceField();
    DeviceField    deviceField111118    = new DeviceField();
    DeviceField    deviceField111119    = new DeviceField();
    DeviceField    deviceField11112     = new DeviceField();
    DeviceField    deviceField11113     = new DeviceField();
    DeviceField    deviceField11114     = new DeviceField();
    DeviceField    deviceField11115     = new DeviceField();
    DeviceField    deviceField11116     = new DeviceField();
    DeviceField    deviceField11117     = new DeviceField();
    DeviceField    deviceField11118     = new DeviceField();
    DeviceField    deviceField11119     = new DeviceField();
    DeviceField    deviceField1112      = new DeviceField();
    DeviceField    deviceField1113      = new DeviceField();
    DeviceField    deviceField1114      = new DeviceField();
    DeviceField    deviceField1115      = new DeviceField();
    DeviceField    deviceField1116      = new DeviceField();
    DeviceField    deviceField1117      = new DeviceField();
    DeviceField    deviceField1118      = new DeviceField();
    DeviceField    deviceField1119      = new DeviceField();
    DeviceField    deviceField112       = new DeviceField();
    DeviceField    deviceField113       = new DeviceField();
    DeviceField    deviceField114       = new DeviceField();
    DeviceField    deviceField115       = new DeviceField();
    DeviceField    deviceField116       = new DeviceField();
    DeviceField    deviceField117       = new DeviceField();
    DeviceField    deviceField118       = new DeviceField();
    DeviceField    deviceField119       = new DeviceField();
    DeviceField    deviceField12        = new DeviceField();
    DeviceField    deviceField13        = new DeviceField();
    DeviceField    deviceField14        = new DeviceField();
    DeviceField    deviceField15        = new DeviceField();
    DeviceField    deviceField16        = new DeviceField();
    DeviceField    deviceField17        = new DeviceField();
    DeviceField    deviceField18        = new DeviceField();
    DeviceField    deviceField19        = new DeviceField();
    DeviceField    deviceField2         = new DeviceField();
    DeviceField    deviceField3         = new DeviceField();
    DeviceField    deviceField4         = new DeviceField();
    DeviceField    deviceField5         = new DeviceField();
    DeviceField    deviceField6         = new DeviceField();
    DeviceField    deviceField7         = new DeviceField();
    DeviceField    deviceField8         = new DeviceField();
    DeviceField    deviceField9         = new DeviceField();
    FlowLayout     flowLayout1          = new FlowLayout();
    FlowLayout     flowLayout10         = new FlowLayout();
    FlowLayout     flowLayout11         = new FlowLayout();
    FlowLayout     flowLayout110        = new FlowLayout();
    FlowLayout     flowLayout111        = new FlowLayout();
    FlowLayout     flowLayout1110       = new FlowLayout();
    FlowLayout     flowLayout1111       = new FlowLayout();
    FlowLayout     flowLayout11110      = new FlowLayout();
    FlowLayout     flowLayout11111      = new FlowLayout();
    FlowLayout     flowLayout111110     = new FlowLayout();
    FlowLayout     flowLayout111111     = new FlowLayout();
    FlowLayout     flowLayout1111110    = new FlowLayout();
    FlowLayout     flowLayout1111111    = new FlowLayout();
    FlowLayout     flowLayout11111110   = new FlowLayout();
    FlowLayout     flowLayout11111111   = new FlowLayout();
    FlowLayout     flowLayout111111110  = new FlowLayout();
    FlowLayout     flowLayout111111111  = new FlowLayout();
    FlowLayout     flowLayout111111112  = new FlowLayout();
    FlowLayout     flowLayout111111113  = new FlowLayout();
    FlowLayout     flowLayout11111112   = new FlowLayout();
    FlowLayout     flowLayout11111113   = new FlowLayout();
    FlowLayout     flowLayout11111114   = new FlowLayout();
    FlowLayout     flowLayout11111115   = new FlowLayout();
    FlowLayout     flowLayout11111116   = new FlowLayout();
    FlowLayout     flowLayout11111117   = new FlowLayout();
    FlowLayout     flowLayout11111118   = new FlowLayout();
    FlowLayout     flowLayout11111119   = new FlowLayout();
    FlowLayout     flowLayout1111112    = new FlowLayout();
    FlowLayout     flowLayout1111113    = new FlowLayout();
    FlowLayout     flowLayout1111114    = new FlowLayout();
    FlowLayout     flowLayout1111115    = new FlowLayout();
    FlowLayout     flowLayout1111116    = new FlowLayout();
    FlowLayout     flowLayout1111117    = new FlowLayout();
    FlowLayout     flowLayout1111118    = new FlowLayout();
    FlowLayout     flowLayout1111119    = new FlowLayout();
    FlowLayout     flowLayout111112     = new FlowLayout();
    FlowLayout     flowLayout111113     = new FlowLayout();
    FlowLayout     flowLayout111114     = new FlowLayout();
    FlowLayout     flowLayout111115     = new FlowLayout();
    FlowLayout     flowLayout111116     = new FlowLayout();
    FlowLayout     flowLayout111117     = new FlowLayout();
    FlowLayout     flowLayout111118     = new FlowLayout();
    FlowLayout     flowLayout111119     = new FlowLayout();
    FlowLayout     flowLayout11112      = new FlowLayout();
    FlowLayout     flowLayout11113      = new FlowLayout();
    FlowLayout     flowLayout11114      = new FlowLayout();
    FlowLayout     flowLayout11115      = new FlowLayout();
    FlowLayout     flowLayout11116      = new FlowLayout();
    FlowLayout     flowLayout11117      = new FlowLayout();
    FlowLayout     flowLayout11118      = new FlowLayout();
    FlowLayout     flowLayout11119      = new FlowLayout();
    FlowLayout     flowLayout1112       = new FlowLayout();
    FlowLayout     flowLayout1113       = new FlowLayout();
    FlowLayout     flowLayout1114       = new FlowLayout();
    FlowLayout     flowLayout1115       = new FlowLayout();
    FlowLayout     flowLayout1116       = new FlowLayout();
    FlowLayout     flowLayout1117       = new FlowLayout();
    FlowLayout     flowLayout1118       = new FlowLayout();
    FlowLayout     flowLayout1119       = new FlowLayout();
    FlowLayout     flowLayout112        = new FlowLayout();
    FlowLayout     flowLayout113        = new FlowLayout();
    FlowLayout     flowLayout114        = new FlowLayout();
    FlowLayout     flowLayout115        = new FlowLayout();
    FlowLayout     flowLayout116        = new FlowLayout();
    FlowLayout     flowLayout117        = new FlowLayout();
    FlowLayout     flowLayout118        = new FlowLayout();
    FlowLayout     flowLayout119        = new FlowLayout();
    FlowLayout     flowLayout12         = new FlowLayout();
    FlowLayout     flowLayout13         = new FlowLayout();
    FlowLayout     flowLayout14         = new FlowLayout();
    FlowLayout     flowLayout15         = new FlowLayout();
    FlowLayout     flowLayout16         = new FlowLayout();
    FlowLayout     flowLayout17         = new FlowLayout();
    FlowLayout     flowLayout18         = new FlowLayout();
    FlowLayout     flowLayout19         = new FlowLayout();
    FlowLayout     flowLayout2          = new FlowLayout();
    FlowLayout     flowLayout3          = new FlowLayout();
    FlowLayout     flowLayout4          = new FlowLayout();
    FlowLayout     flowLayout5          = new FlowLayout();
    FlowLayout     flowLayout6          = new FlowLayout();
    FlowLayout     flowLayout7          = new FlowLayout();
    FlowLayout     flowLayout8          = new FlowLayout();
    FlowLayout     flowLayout9          = new FlowLayout();
    GridLayout     gridLayout1          = new GridLayout();
    GridLayout     gridLayout2          = new GridLayout();
    JLabel         jLabel1              = new JLabel();
    JPanel         jPanel1              = new JPanel();
    JPanel         jPanel10             = new JPanel();
    JPanel         jPanel11             = new JPanel();
    JPanel         jPanel110            = new JPanel();
    JPanel         jPanel111            = new JPanel();
    JPanel         jPanel1110           = new JPanel();
    JPanel         jPanel1111           = new JPanel();
    JPanel         jPanel11110          = new JPanel();
    JPanel         jPanel11111          = new JPanel();
    JPanel         jPanel11112          = new JPanel();
    JPanel         jPanel11113          = new JPanel();
    JPanel         jPanel11114          = new JPanel();
    JPanel         jPanel11115          = new JPanel();
    JPanel         jPanel1112           = new JPanel();
    JPanel         jPanel1113           = new JPanel();
    JPanel         jPanel1114           = new JPanel();
    JPanel         jPanel1115           = new JPanel();
    JPanel         jPanel1116           = new JPanel();
    JPanel         jPanel1117           = new JPanel();
    JPanel         jPanel1118           = new JPanel();
    JPanel         jPanel1119           = new JPanel();
    JPanel         jPanel112            = new JPanel();
    JPanel         jPanel113            = new JPanel();
    JPanel         jPanel114            = new JPanel();
    JPanel         jPanel115            = new JPanel();
    JPanel         jPanel116            = new JPanel();
    JPanel         jPanel117            = new JPanel();
    JPanel         jPanel118            = new JPanel();
    JPanel         jPanel119            = new JPanel();
    JPanel         jPanel12             = new JPanel();
    JPanel         jPanel13             = new JPanel();
    JPanel         jPanel14             = new JPanel();
    JPanel         jPanel15             = new JPanel();
    JPanel         jPanel16             = new JPanel();
    JPanel         jPanel17             = new JPanel();
    JPanel         jPanel18             = new JPanel();
    JPanel         jPanel19             = new JPanel();
    JPanel         jPanel2              = new JPanel();
    JPanel         jPanel3              = new JPanel();
    JPanel         jPanel4              = new JPanel();
    JPanel         jPanel5              = new JPanel();
    JPanel         jPanel6              = new JPanel();
    JPanel         jPanel7              = new JPanel();
    JPanel         jPanel8              = new JPanel();
    JPanel         jPanel9              = new JPanel();
    JScrollPane    jScrollPane1         = new JScrollPane();

    public CHVPSSetup(){
        try{
            this.jbInit();
        }catch(final Exception e){
            e.printStackTrace();
        }
    }

    private void jbInit() throws Exception {
        this.setWidth(660);
        this.setHeight(614);
        this.setDeviceType("CHVPS");
        this.setDeviceProvider("150.178.3.33");
        this.setDeviceTitle("CHVPS - CAEN High Voltage Power Supply");
        this.getContentPane().setLayout(this.borderLayout1);
        this.jPanel1.setDebugGraphicsOptions(0);
        this.jPanel1.setLayout(this.gridLayout1);
        this.gridLayout1.setRows(3);
        this.deviceField1.setOffsetNid(1);
        this.deviceField1.setTextOnly(true);
        this.deviceField1.setLabelString("Comment: ");
        this.deviceField1.setNumCols(35);
        this.deviceField1.setIdentifier("");
        this.deviceField2.setOffsetNid(2);
        this.deviceField2.setTextOnly(true);
        this.deviceField2.setLabelString("Name: ");
        this.deviceField2.setNumCols(20);
        this.deviceField2.setIdentifier("");
        this.deviceField3.setOffsetNid(3);
        this.deviceField3.setLabelString("Crate num. :");
        this.deviceField3.setIdentifier("");
        this.jPanel2.setLayout(this.flowLayout1);
        this.flowLayout1.setAlignment(FlowLayout.LEFT);
        this.flowLayout1.setVgap(0);
        this.jPanel3.setLayout(this.flowLayout2);
        this.flowLayout2.setAlignment(FlowLayout.LEFT);
        this.flowLayout2.setVgap(0);
        this.jPanel4.setLayout(this.gridLayout2);
        this.gridLayout2.setRows(40);
        this.deviceChannel1.setLabelString("00");
        this.deviceChannel1.setOffsetNid(4);
        this.deviceChannel1.setInSameLine(true);
        this.deviceChannel1.setUpdateIdentifier("");
        this.deviceChannel1.setShowVal("");
        this.deviceChannel1.setLayout(this.flowLayout3);
        this.flowLayout3.setAlignment(FlowLayout.LEFT);
        this.flowLayout3.setVgap(0);
        this.jPanel5.setLayout(this.flowLayout4);
        this.flowLayout4.setAlignment(FlowLayout.LEFT);
        this.flowLayout4.setVgap(0);
        this.deviceField4.setOffsetNid(5);
        this.deviceField4.setNumCols(25);
        this.deviceField4.setIdentifier("");
        this.deviceField5.setOffsetNid(6);
        this.deviceField5.setNumCols(15);
        this.deviceField5.setIdentifier("");
        this.jLabel1.setText("SET                                          COMMENT             " + "                                           CHANNELS              " + "                     TYPE");
        this.jPanel6.setLayout(this.flowLayout5);
        this.flowLayout5.setAlignment(FlowLayout.LEFT);
        this.flowLayout5.setHgap(5);
        this.flowLayout5.setVgap(0);
        this.deviceChoice1.setChoiceIntValues(null);
        this.deviceChoice1.setChoiceFloatValues(null);
        this.deviceChoice1.setOffsetNid(7);
        this.deviceChoice1.setLabelString(" ");
        this.deviceChoice1.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1.setUpdateIdentifier("");
        this.deviceChoice1.setIdentifier("");
        this.flowLayout6.setVgap(0);
        this.flowLayout6.setAlignment(FlowLayout.LEFT);
        this.deviceField6.setIdentifier("");
        this.deviceField6.setNumCols(15);
        this.deviceField6.setOffsetNid(474);
        this.deviceChannel2.setLayout(this.flowLayout6);
        this.deviceChannel2.setInSameLine(true);
        this.deviceChannel2.setLabelString("39");
        this.deviceChannel2.setOffsetNid(472);
        this.flowLayout7.setAlignment(FlowLayout.LEFT);
        this.flowLayout7.setVgap(0);
        this.jPanel7.setLayout(this.flowLayout7);
        this.deviceChoice2.setChoiceIntValues(null);
        this.deviceChoice2.setChoiceFloatValues(null);
        this.deviceChoice2.setOffsetNid(475);
        this.deviceChoice2.setLabelString(" ");
        this.deviceChoice2.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice2.setUpdateIdentifier("");
        this.deviceChoice2.setIdentifier("");
        this.deviceField7.setOffsetNid(473);
        this.deviceField7.setNumCols(25);
        this.deviceField7.setIdentifier("");
        this.flowLayout8.setVgap(0);
        this.flowLayout8.setAlignment(FlowLayout.LEFT);
        this.deviceField8.setIdentifier("");
        this.deviceField8.setNumCols(15);
        this.deviceField8.setOffsetNid(462);
        this.deviceChannel3.setLayout(this.flowLayout8);
        this.deviceChannel3.setInSameLine(true);
        this.deviceChannel3.setLabelString("38");
        this.deviceChannel3.setOffsetNid(460);
        this.flowLayout9.setAlignment(FlowLayout.LEFT);
        this.flowLayout9.setVgap(0);
        this.jPanel8.setLayout(this.flowLayout9);
        this.deviceChoice3.setChoiceIntValues(null);
        this.deviceChoice3.setChoiceFloatValues(null);
        this.deviceChoice3.setOffsetNid(463);
        this.deviceChoice3.setLabelString(" ");
        this.deviceChoice3.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice3.setUpdateIdentifier("");
        this.deviceChoice3.setIdentifier("");
        this.deviceField9.setOffsetNid(461);
        this.deviceField9.setNumCols(25);
        this.deviceField9.setIdentifier("");
        this.flowLayout10.setVgap(0);
        this.flowLayout10.setAlignment(FlowLayout.LEFT);
        this.deviceField10.setIdentifier("");
        this.deviceField10.setNumCols(15);
        this.deviceField10.setOffsetNid(450);
        this.deviceChannel4.setLayout(this.flowLayout10);
        this.deviceChannel4.setInSameLine(true);
        this.deviceChannel4.setLabelString("37");
        this.deviceChannel4.setOffsetNid(448);
        this.flowLayout11.setAlignment(FlowLayout.LEFT);
        this.flowLayout11.setVgap(0);
        this.jPanel9.setLayout(this.flowLayout11);
        this.deviceChoice4.setChoiceIntValues(null);
        this.deviceChoice4.setChoiceFloatValues(null);
        this.deviceChoice4.setOffsetNid(451);
        this.deviceChoice4.setLabelString(" ");
        this.deviceChoice4.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice4.setUpdateIdentifier("");
        this.deviceChoice4.setIdentifier("");
        this.deviceField11.setOffsetNid(449);
        this.deviceField11.setNumCols(25);
        this.deviceField11.setIdentifier("");
        this.flowLayout12.setVgap(0);
        this.flowLayout12.setAlignment(FlowLayout.LEFT);
        this.deviceField12.setIdentifier("");
        this.deviceField12.setNumCols(15);
        this.deviceField12.setOffsetNid(438);
        this.deviceChannel5.setLayout(this.flowLayout12);
        this.deviceChannel5.setInSameLine(true);
        this.deviceChannel5.setLabelString("36");
        this.deviceChannel5.setOffsetNid(436);
        this.flowLayout13.setAlignment(FlowLayout.LEFT);
        this.flowLayout13.setVgap(0);
        this.jPanel10.setLayout(this.flowLayout13);
        this.deviceChoice5.setChoiceIntValues(null);
        this.deviceChoice5.setChoiceFloatValues(null);
        this.deviceChoice5.setOffsetNid(439);
        this.deviceChoice5.setLabelString(" ");
        this.deviceChoice5.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice5.setUpdateIdentifier("");
        this.deviceChoice5.setIdentifier("");
        this.deviceField13.setOffsetNid(437);
        this.deviceField13.setNumCols(25);
        this.deviceField13.setIdentifier("");
        this.flowLayout14.setVgap(0);
        this.flowLayout14.setAlignment(FlowLayout.LEFT);
        this.deviceField14.setIdentifier("");
        this.deviceField14.setNumCols(15);
        this.deviceField14.setOffsetNid(426);
        this.deviceChannel6.setLayout(this.flowLayout14);
        this.deviceChannel6.setInSameLine(true);
        this.deviceChannel6.setLabelString("35");
        this.deviceChannel6.setOffsetNid(424);
        this.flowLayout15.setAlignment(FlowLayout.LEFT);
        this.flowLayout15.setVgap(0);
        this.jPanel11.setLayout(this.flowLayout15);
        this.deviceChoice6.setChoiceIntValues(null);
        this.deviceChoice6.setChoiceFloatValues(null);
        this.deviceChoice6.setOffsetNid(427);
        this.deviceChoice6.setLabelString(" ");
        this.deviceChoice6.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice6.setUpdateIdentifier("");
        this.deviceChoice6.setIdentifier("");
        this.deviceField15.setOffsetNid(425);
        this.deviceField15.setNumCols(25);
        this.deviceField15.setIdentifier("");
        this.flowLayout16.setVgap(0);
        this.flowLayout16.setAlignment(FlowLayout.LEFT);
        this.deviceField16.setIdentifier("");
        this.deviceField16.setNumCols(15);
        this.deviceField16.setOffsetNid(414);
        this.deviceChannel7.setLayout(this.flowLayout16);
        this.deviceChannel7.setInSameLine(true);
        this.deviceChannel7.setLabelString("34");
        this.deviceChannel7.setOffsetNid(412);
        this.flowLayout17.setAlignment(FlowLayout.LEFT);
        this.flowLayout17.setVgap(0);
        this.jPanel12.setLayout(this.flowLayout17);
        this.deviceChoice7.setChoiceIntValues(null);
        this.deviceChoice7.setChoiceFloatValues(null);
        this.deviceChoice7.setOffsetNid(415);
        this.deviceChoice7.setLabelString(" ");
        this.deviceChoice7.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice7.setUpdateIdentifier("");
        this.deviceChoice7.setIdentifier("");
        this.deviceField17.setOffsetNid(413);
        this.deviceField17.setNumCols(25);
        this.deviceField17.setIdentifier("");
        this.flowLayout18.setVgap(0);
        this.flowLayout18.setAlignment(FlowLayout.LEFT);
        this.deviceField18.setIdentifier("");
        this.deviceField18.setNumCols(15);
        this.deviceField18.setOffsetNid(402);
        this.deviceChannel8.setLayout(this.flowLayout18);
        this.deviceChannel8.setInSameLine(true);
        this.deviceChannel8.setLabelString("33");
        this.deviceChannel8.setOffsetNid(400);
        this.flowLayout19.setAlignment(FlowLayout.LEFT);
        this.flowLayout19.setVgap(0);
        this.jPanel13.setLayout(this.flowLayout19);
        this.deviceChoice8.setChoiceIntValues(null);
        this.deviceChoice8.setChoiceFloatValues(null);
        this.deviceChoice8.setOffsetNid(403);
        this.deviceChoice8.setLabelString(" ");
        this.deviceChoice8.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice8.setUpdateIdentifier("");
        this.deviceChoice8.setIdentifier("");
        this.deviceField19.setOffsetNid(401);
        this.deviceField19.setNumCols(25);
        this.deviceField19.setIdentifier("");
        this.flowLayout110.setVgap(0);
        this.flowLayout110.setAlignment(FlowLayout.LEFT);
        this.deviceField110.setIdentifier("");
        this.deviceField110.setNumCols(15);
        this.deviceField110.setOffsetNid(390);
        this.deviceChannel9.setLayout(this.flowLayout110);
        this.deviceChannel9.setInSameLine(true);
        this.deviceChannel9.setLabelString("32");
        this.deviceChannel9.setOffsetNid(388);
        this.flowLayout111.setAlignment(FlowLayout.LEFT);
        this.flowLayout111.setVgap(0);
        this.jPanel14.setLayout(this.flowLayout111);
        this.deviceChoice9.setChoiceIntValues(null);
        this.deviceChoice9.setChoiceFloatValues(null);
        this.deviceChoice9.setOffsetNid(391);
        this.deviceChoice9.setLabelString(" ");
        this.deviceChoice9.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice9.setUpdateIdentifier("");
        this.deviceChoice9.setIdentifier("");
        this.deviceField111.setOffsetNid(389);
        this.deviceField111.setNumCols(25);
        this.deviceField111.setIdentifier("");
        this.flowLayout112.setVgap(0);
        this.flowLayout112.setAlignment(FlowLayout.LEFT);
        this.deviceField112.setIdentifier("");
        this.deviceField112.setNumCols(15);
        this.deviceField112.setOffsetNid(378);
        this.deviceChannel10.setLayout(this.flowLayout112);
        this.deviceChannel10.setInSameLine(true);
        this.deviceChannel10.setLabelString("31");
        this.deviceChannel10.setOffsetNid(376);
        this.flowLayout113.setAlignment(FlowLayout.LEFT);
        this.flowLayout113.setVgap(0);
        this.jPanel15.setLayout(this.flowLayout113);
        this.deviceChoice10.setChoiceIntValues(null);
        this.deviceChoice10.setChoiceFloatValues(null);
        this.deviceChoice10.setOffsetNid(379);
        this.deviceChoice10.setLabelString(" ");
        this.deviceChoice10.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice10.setUpdateIdentifier("");
        this.deviceChoice10.setIdentifier("");
        this.deviceField113.setOffsetNid(377);
        this.deviceField113.setNumCols(25);
        this.deviceField113.setIdentifier("");
        this.flowLayout114.setVgap(0);
        this.flowLayout114.setAlignment(FlowLayout.LEFT);
        this.deviceField114.setIdentifier("");
        this.deviceField114.setNumCols(15);
        this.deviceField114.setOffsetNid(366);
        this.deviceChannel11.setLayout(this.flowLayout114);
        this.deviceChannel11.setInSameLine(true);
        this.deviceChannel11.setLabelString("30");
        this.deviceChannel11.setOffsetNid(364);
        this.flowLayout115.setAlignment(FlowLayout.LEFT);
        this.flowLayout115.setVgap(0);
        this.jPanel16.setLayout(this.flowLayout115);
        this.deviceChoice11.setChoiceIntValues(null);
        this.deviceChoice11.setChoiceFloatValues(null);
        this.deviceChoice11.setOffsetNid(367);
        this.deviceChoice11.setLabelString(" ");
        this.deviceChoice11.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice11.setUpdateIdentifier("");
        this.deviceChoice11.setIdentifier("");
        this.deviceField115.setOffsetNid(365);
        this.deviceField115.setNumCols(25);
        this.deviceField115.setIdentifier("");
        this.flowLayout116.setVgap(0);
        this.flowLayout116.setAlignment(FlowLayout.LEFT);
        this.deviceField116.setIdentifier("");
        this.deviceField116.setNumCols(15);
        this.deviceField116.setOffsetNid(354);
        this.deviceChannel12.setLayout(this.flowLayout116);
        this.deviceChannel12.setInSameLine(true);
        this.deviceChannel12.setLabelString("29");
        this.deviceChannel12.setOffsetNid(352);
        this.flowLayout117.setAlignment(FlowLayout.LEFT);
        this.flowLayout117.setVgap(0);
        this.jPanel17.setLayout(this.flowLayout117);
        this.deviceChoice12.setChoiceIntValues(null);
        this.deviceChoice12.setChoiceFloatValues(null);
        this.deviceChoice12.setOffsetNid(355);
        this.deviceChoice12.setLabelString(" ");
        this.deviceChoice12.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice12.setUpdateIdentifier("");
        this.deviceChoice12.setIdentifier("");
        this.deviceField117.setOffsetNid(353);
        this.deviceField117.setNumCols(25);
        this.deviceField117.setIdentifier("");
        this.flowLayout118.setVgap(0);
        this.flowLayout118.setAlignment(FlowLayout.LEFT);
        this.deviceField118.setIdentifier("");
        this.deviceField118.setNumCols(15);
        this.deviceField118.setOffsetNid(342);
        this.deviceChannel13.setLayout(this.flowLayout118);
        this.deviceChannel13.setInSameLine(true);
        this.deviceChannel13.setLabelString("28");
        this.deviceChannel13.setOffsetNid(340);
        this.flowLayout119.setAlignment(FlowLayout.LEFT);
        this.flowLayout119.setVgap(0);
        this.jPanel18.setLayout(this.flowLayout119);
        this.deviceChoice13.setChoiceIntValues(null);
        this.deviceChoice13.setChoiceFloatValues(null);
        this.deviceChoice13.setOffsetNid(343);
        this.deviceChoice13.setLabelString(" ");
        this.deviceChoice13.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice13.setUpdateIdentifier("");
        this.deviceChoice13.setIdentifier("");
        this.deviceField119.setOffsetNid(341);
        this.deviceField119.setNumCols(25);
        this.deviceField119.setIdentifier("");
        this.flowLayout1110.setVgap(0);
        this.flowLayout1110.setAlignment(FlowLayout.LEFT);
        this.deviceField1110.setIdentifier("");
        this.deviceField1110.setNumCols(15);
        this.deviceField1110.setOffsetNid(330);
        this.deviceChannel14.setLayout(this.flowLayout1110);
        this.deviceChannel14.setInSameLine(true);
        this.deviceChannel14.setLabelString("27");
        this.deviceChannel14.setOffsetNid(328);
        this.flowLayout1111.setAlignment(FlowLayout.LEFT);
        this.flowLayout1111.setVgap(0);
        this.jPanel19.setLayout(this.flowLayout1111);
        this.deviceChoice14.setChoiceIntValues(null);
        this.deviceChoice14.setChoiceFloatValues(null);
        this.deviceChoice14.setOffsetNid(331);
        this.deviceChoice14.setLabelString(" ");
        this.deviceChoice14.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice14.setUpdateIdentifier("");
        this.deviceChoice14.setIdentifier("");
        this.deviceField1111.setOffsetNid(329);
        this.deviceField1111.setNumCols(25);
        this.deviceField1111.setIdentifier("");
        this.flowLayout1112.setVgap(0);
        this.flowLayout1112.setAlignment(FlowLayout.LEFT);
        this.deviceField1112.setIdentifier("");
        this.deviceField1112.setNumCols(15);
        this.deviceField1112.setOffsetNid(318);
        this.deviceChannel15.setLayout(this.flowLayout1112);
        this.deviceChannel15.setInSameLine(true);
        this.deviceChannel15.setLabelString("26");
        this.deviceChannel15.setOffsetNid(316);
        this.flowLayout1113.setAlignment(FlowLayout.LEFT);
        this.flowLayout1113.setVgap(0);
        this.jPanel110.setLayout(this.flowLayout1113);
        this.deviceChoice15.setChoiceIntValues(null);
        this.deviceChoice15.setChoiceFloatValues(null);
        this.deviceChoice15.setOffsetNid(319);
        this.deviceChoice15.setLabelString(" ");
        this.deviceChoice15.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice15.setUpdateIdentifier("");
        this.deviceChoice15.setIdentifier("");
        this.deviceField1113.setOffsetNid(317);
        this.deviceField1113.setNumCols(25);
        this.deviceField1113.setIdentifier("");
        this.flowLayout1114.setVgap(0);
        this.flowLayout1114.setAlignment(FlowLayout.LEFT);
        this.deviceField1114.setIdentifier("");
        this.deviceField1114.setNumCols(15);
        this.deviceField1114.setOffsetNid(306);
        this.deviceChannel16.setLayout(this.flowLayout1114);
        this.deviceChannel16.setInSameLine(true);
        this.deviceChannel16.setLabelString("25");
        this.deviceChannel16.setOffsetNid(304);
        this.flowLayout1115.setAlignment(FlowLayout.LEFT);
        this.flowLayout1115.setVgap(0);
        this.jPanel111.setLayout(this.flowLayout1115);
        this.deviceChoice16.setChoiceIntValues(null);
        this.deviceChoice16.setChoiceFloatValues(null);
        this.deviceChoice16.setOffsetNid(307);
        this.deviceChoice16.setLabelString(" ");
        this.deviceChoice16.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice16.setUpdateIdentifier("");
        this.deviceChoice16.setIdentifier("");
        this.deviceField1115.setOffsetNid(305);
        this.deviceField1115.setNumCols(25);
        this.deviceField1115.setIdentifier("");
        this.flowLayout1116.setVgap(0);
        this.flowLayout1116.setAlignment(FlowLayout.LEFT);
        this.deviceField1116.setIdentifier("");
        this.deviceField1116.setNumCols(15);
        this.deviceField1116.setOffsetNid(294);
        this.deviceChannel17.setLayout(this.flowLayout1116);
        this.deviceChannel17.setInSameLine(true);
        this.deviceChannel17.setLabelString("24");
        this.deviceChannel17.setOffsetNid(292);
        this.flowLayout1117.setAlignment(FlowLayout.LEFT);
        this.flowLayout1117.setVgap(0);
        this.jPanel112.setLayout(this.flowLayout1117);
        this.deviceChoice17.setChoiceIntValues(null);
        this.deviceChoice17.setChoiceFloatValues(null);
        this.deviceChoice17.setOffsetNid(295);
        this.deviceChoice17.setLabelString(" ");
        this.deviceChoice17.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice17.setUpdateIdentifier("");
        this.deviceChoice17.setIdentifier("");
        this.deviceField1117.setOffsetNid(293);
        this.deviceField1117.setNumCols(25);
        this.deviceField1117.setIdentifier("");
        this.flowLayout1118.setVgap(0);
        this.flowLayout1118.setAlignment(FlowLayout.LEFT);
        this.deviceField1118.setIdentifier("");
        this.deviceField1118.setNumCols(15);
        this.deviceField1118.setOffsetNid(282);
        this.deviceChannel18.setLayout(this.flowLayout1118);
        this.deviceChannel18.setInSameLine(true);
        this.deviceChannel18.setLabelString("23");
        this.deviceChannel18.setOffsetNid(280);
        this.flowLayout1119.setAlignment(FlowLayout.LEFT);
        this.flowLayout1119.setVgap(0);
        this.jPanel113.setLayout(this.flowLayout1119);
        this.deviceChoice18.setChoiceIntValues(null);
        this.deviceChoice18.setChoiceFloatValues(null);
        this.deviceChoice18.setOffsetNid(283);
        this.deviceChoice18.setLabelString(" ");
        this.deviceChoice18.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice18.setUpdateIdentifier("");
        this.deviceChoice18.setIdentifier("");
        this.deviceField1119.setOffsetNid(281);
        this.deviceField1119.setNumCols(25);
        this.deviceField1119.setIdentifier("");
        this.flowLayout11110.setVgap(0);
        this.flowLayout11110.setAlignment(FlowLayout.LEFT);
        this.deviceField11110.setIdentifier("");
        this.deviceField11110.setNumCols(15);
        this.deviceField11110.setOffsetNid(270);
        this.deviceChannel19.setLayout(this.flowLayout11110);
        this.deviceChannel19.setInSameLine(true);
        this.deviceChannel19.setLabelString("22");
        this.deviceChannel19.setOffsetNid(268);
        this.flowLayout11111.setAlignment(FlowLayout.LEFT);
        this.flowLayout11111.setVgap(0);
        this.jPanel114.setLayout(this.flowLayout11111);
        this.deviceChoice19.setChoiceIntValues(null);
        this.deviceChoice19.setChoiceFloatValues(null);
        this.deviceChoice19.setOffsetNid(271);
        this.deviceChoice19.setLabelString(" ");
        this.deviceChoice19.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice19.setUpdateIdentifier("");
        this.deviceChoice19.setIdentifier("");
        this.deviceField11111.setOffsetNid(269);
        this.deviceField11111.setNumCols(25);
        this.deviceField11111.setIdentifier("");
        this.flowLayout11112.setVgap(0);
        this.flowLayout11112.setAlignment(FlowLayout.LEFT);
        this.deviceField11112.setIdentifier("");
        this.deviceField11112.setNumCols(15);
        this.deviceField11112.setOffsetNid(258);
        this.deviceChannel110.setLayout(this.flowLayout11112);
        this.deviceChannel110.setInSameLine(true);
        this.deviceChannel110.setLabelString("21");
        this.deviceChannel110.setOffsetNid(256);
        this.flowLayout11113.setAlignment(FlowLayout.LEFT);
        this.flowLayout11113.setVgap(0);
        this.jPanel115.setLayout(this.flowLayout11113);
        this.deviceChoice110.setChoiceIntValues(null);
        this.deviceChoice110.setChoiceFloatValues(null);
        this.deviceChoice110.setOffsetNid(259);
        this.deviceChoice110.setLabelString(" ");
        this.deviceChoice110.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice110.setUpdateIdentifier("");
        this.deviceChoice110.setIdentifier("");
        this.deviceField11113.setOffsetNid(257);
        this.deviceField11113.setNumCols(25);
        this.deviceField11113.setIdentifier("");
        this.flowLayout11114.setVgap(0);
        this.flowLayout11114.setAlignment(FlowLayout.LEFT);
        this.deviceField11114.setIdentifier("");
        this.deviceField11114.setNumCols(15);
        this.deviceField11114.setOffsetNid(246);
        this.deviceChannel111.setLayout(this.flowLayout11114);
        this.deviceChannel111.setInSameLine(true);
        this.deviceChannel111.setLabelString("20");
        this.deviceChannel111.setOffsetNid(244);
        this.flowLayout11115.setAlignment(FlowLayout.LEFT);
        this.flowLayout11115.setVgap(0);
        this.jPanel116.setLayout(this.flowLayout11115);
        this.deviceChoice111.setChoiceIntValues(null);
        this.deviceChoice111.setChoiceFloatValues(null);
        this.deviceChoice111.setOffsetNid(247);
        this.deviceChoice111.setLabelString(" ");
        this.deviceChoice111.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice111.setUpdateIdentifier("");
        this.deviceChoice111.setIdentifier("");
        this.deviceField11115.setOffsetNid(245);
        this.deviceField11115.setNumCols(25);
        this.deviceField11115.setIdentifier("");
        this.flowLayout11116.setVgap(0);
        this.flowLayout11116.setAlignment(FlowLayout.LEFT);
        this.deviceField11116.setIdentifier("");
        this.deviceField11116.setNumCols(15);
        this.deviceField11116.setOffsetNid(234);
        this.deviceChannel112.setLayout(this.flowLayout11116);
        this.deviceChannel112.setInSameLine(true);
        this.deviceChannel112.setLabelString("19");
        this.deviceChannel112.setOffsetNid(232);
        this.flowLayout11117.setAlignment(FlowLayout.LEFT);
        this.flowLayout11117.setVgap(0);
        this.jPanel117.setLayout(this.flowLayout11117);
        this.deviceChoice112.setChoiceIntValues(null);
        this.deviceChoice112.setChoiceFloatValues(null);
        this.deviceChoice112.setOffsetNid(235);
        this.deviceChoice112.setLabelString(" ");
        this.deviceChoice112.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice112.setUpdateIdentifier("");
        this.deviceChoice112.setIdentifier("");
        this.deviceField11117.setOffsetNid(233);
        this.deviceField11117.setNumCols(25);
        this.deviceField11117.setIdentifier("");
        this.flowLayout11118.setVgap(0);
        this.flowLayout11118.setAlignment(FlowLayout.LEFT);
        this.deviceField11118.setIdentifier("");
        this.deviceField11118.setNumCols(15);
        this.deviceField11118.setOffsetNid(222);
        this.deviceChannel113.setLayout(this.flowLayout11118);
        this.deviceChannel113.setInSameLine(true);
        this.deviceChannel113.setLabelString("18");
        this.deviceChannel113.setOffsetNid(220);
        this.flowLayout11119.setAlignment(FlowLayout.LEFT);
        this.flowLayout11119.setVgap(0);
        this.jPanel118.setLayout(this.flowLayout11119);
        this.deviceChoice113.setChoiceIntValues(null);
        this.deviceChoice113.setChoiceFloatValues(null);
        this.deviceChoice113.setOffsetNid(223);
        this.deviceChoice113.setLabelString(" ");
        this.deviceChoice113.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice113.setUpdateIdentifier("");
        this.deviceChoice113.setIdentifier("");
        this.deviceField11119.setOffsetNid(221);
        this.deviceField11119.setNumCols(25);
        this.deviceField11119.setIdentifier("");
        this.flowLayout111110.setVgap(0);
        this.flowLayout111110.setAlignment(FlowLayout.LEFT);
        this.deviceField111110.setIdentifier("");
        this.deviceField111110.setNumCols(15);
        this.deviceField111110.setOffsetNid(210);
        this.deviceChannel114.setLayout(this.flowLayout111110);
        this.deviceChannel114.setInSameLine(true);
        this.deviceChannel114.setLabelString("17");
        this.deviceChannel114.setOffsetNid(208);
        this.flowLayout111111.setAlignment(FlowLayout.LEFT);
        this.flowLayout111111.setVgap(0);
        this.jPanel119.setLayout(this.flowLayout111111);
        this.deviceChoice114.setChoiceIntValues(null);
        this.deviceChoice114.setChoiceFloatValues(null);
        this.deviceChoice114.setOffsetNid(211);
        this.deviceChoice114.setLabelString(" ");
        this.deviceChoice114.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice114.setUpdateIdentifier("");
        this.deviceChoice114.setIdentifier("");
        this.deviceField111111.setOffsetNid(209);
        this.deviceField111111.setNumCols(25);
        this.deviceField111111.setIdentifier("");
        this.flowLayout111112.setVgap(0);
        this.flowLayout111112.setAlignment(FlowLayout.LEFT);
        this.deviceField111112.setIdentifier("");
        this.deviceField111112.setNumCols(15);
        this.deviceField111112.setOffsetNid(198);
        this.deviceChannel115.setLayout(this.flowLayout111112);
        this.deviceChannel115.setInSameLine(true);
        this.deviceChannel115.setLabelString("16");
        this.deviceChannel115.setOffsetNid(196);
        this.flowLayout111113.setAlignment(FlowLayout.LEFT);
        this.flowLayout111113.setVgap(0);
        this.jPanel1110.setLayout(this.flowLayout111113);
        this.deviceChoice115.setChoiceIntValues(null);
        this.deviceChoice115.setChoiceFloatValues(null);
        this.deviceChoice115.setOffsetNid(199);
        this.deviceChoice115.setLabelString(" ");
        this.deviceChoice115.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice115.setUpdateIdentifier("");
        this.deviceChoice115.setIdentifier("");
        this.deviceField111113.setOffsetNid(197);
        this.deviceField111113.setNumCols(25);
        this.deviceField111113.setIdentifier("");
        this.flowLayout111114.setVgap(0);
        this.flowLayout111114.setAlignment(FlowLayout.LEFT);
        this.deviceField111114.setIdentifier("");
        this.deviceField111114.setNumCols(15);
        this.deviceField111114.setOffsetNid(186);
        this.deviceChannel116.setLayout(this.flowLayout111114);
        this.deviceChannel116.setInSameLine(true);
        this.deviceChannel116.setLabelString("15");
        this.deviceChannel116.setOffsetNid(184);
        this.flowLayout111115.setAlignment(FlowLayout.LEFT);
        this.flowLayout111115.setVgap(0);
        this.jPanel1111.setLayout(this.flowLayout111115);
        this.deviceChoice116.setChoiceIntValues(null);
        this.deviceChoice116.setChoiceFloatValues(null);
        this.deviceChoice116.setOffsetNid(187);
        this.deviceChoice116.setLabelString(" ");
        this.deviceChoice116.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice116.setUpdateIdentifier("");
        this.deviceChoice116.setIdentifier("");
        this.deviceField111115.setOffsetNid(185);
        this.deviceField111115.setNumCols(25);
        this.deviceField111115.setIdentifier("");
        this.flowLayout111116.setVgap(0);
        this.flowLayout111116.setAlignment(FlowLayout.LEFT);
        this.deviceField111116.setIdentifier("");
        this.deviceField111116.setNumCols(15);
        this.deviceField111116.setOffsetNid(174);
        this.deviceChannel117.setLayout(this.flowLayout111116);
        this.deviceChannel117.setInSameLine(true);
        this.deviceChannel117.setLabelString("14");
        this.deviceChannel117.setOffsetNid(172);
        this.flowLayout111117.setAlignment(FlowLayout.LEFT);
        this.flowLayout111117.setVgap(0);
        this.jPanel1112.setLayout(this.flowLayout111117);
        this.deviceChoice117.setChoiceIntValues(null);
        this.deviceChoice117.setChoiceFloatValues(null);
        this.deviceChoice117.setOffsetNid(175);
        this.deviceChoice117.setLabelString(" ");
        this.deviceChoice117.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice117.setUpdateIdentifier("");
        this.deviceChoice117.setIdentifier("");
        this.deviceField111117.setOffsetNid(173);
        this.deviceField111117.setNumCols(25);
        this.deviceField111117.setIdentifier("");
        this.flowLayout111118.setVgap(0);
        this.flowLayout111118.setAlignment(FlowLayout.LEFT);
        this.deviceField111118.setIdentifier("");
        this.deviceField111118.setNumCols(15);
        this.deviceField111118.setOffsetNid(162);
        this.deviceChannel118.setLayout(this.flowLayout111118);
        this.deviceChannel118.setInSameLine(true);
        this.deviceChannel118.setLabelString("13");
        this.deviceChannel118.setOffsetNid(160);
        this.flowLayout111119.setAlignment(FlowLayout.LEFT);
        this.flowLayout111119.setVgap(0);
        this.jPanel1113.setLayout(this.flowLayout111119);
        this.deviceChoice118.setChoiceIntValues(null);
        this.deviceChoice118.setChoiceFloatValues(null);
        this.deviceChoice118.setOffsetNid(163);
        this.deviceChoice118.setLabelString("");
        this.deviceChoice118.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice118.setUpdateIdentifier("");
        this.deviceChoice118.setIdentifier("");
        this.deviceField111119.setOffsetNid(161);
        this.deviceField111119.setNumCols(25);
        this.deviceField111119.setIdentifier("");
        this.flowLayout1111110.setVgap(0);
        this.flowLayout1111110.setAlignment(FlowLayout.LEFT);
        this.deviceField1111110.setIdentifier("");
        this.deviceField1111110.setNumCols(15);
        this.deviceField1111110.setOffsetNid(150);
        this.deviceChannel119.setLayout(this.flowLayout1111110);
        this.deviceChannel119.setInSameLine(true);
        this.deviceChannel119.setLabelString("12");
        this.deviceChannel119.setOffsetNid(148);
        this.flowLayout1111111.setAlignment(FlowLayout.LEFT);
        this.flowLayout1111111.setVgap(0);
        this.jPanel1114.setLayout(this.flowLayout1111111);
        this.deviceChoice119.setChoiceIntValues(null);
        this.deviceChoice119.setChoiceFloatValues(null);
        this.deviceChoice119.setOffsetNid(151);
        this.deviceChoice119.setLabelString(" ");
        this.deviceChoice119.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice119.setUpdateIdentifier("");
        this.deviceChoice119.setIdentifier("");
        this.deviceField1111111.setOffsetNid(149);
        this.deviceField1111111.setNumCols(25);
        this.deviceField1111111.setIdentifier("");
        this.flowLayout1111112.setVgap(0);
        this.flowLayout1111112.setAlignment(FlowLayout.LEFT);
        this.deviceField1111112.setIdentifier("");
        this.deviceField1111112.setNumCols(15);
        this.deviceField1111112.setOffsetNid(138);
        this.deviceChannel1110.setLayout(this.flowLayout1111112);
        this.deviceChannel1110.setInSameLine(true);
        this.deviceChannel1110.setLabelString("11");
        this.deviceChannel1110.setOffsetNid(136);
        this.flowLayout1111113.setAlignment(FlowLayout.LEFT);
        this.flowLayout1111113.setVgap(0);
        this.jPanel1115.setLayout(this.flowLayout1111113);
        this.deviceChoice1110.setChoiceIntValues(null);
        this.deviceChoice1110.setChoiceFloatValues(null);
        this.deviceChoice1110.setOffsetNid(139);
        this.deviceChoice1110.setLabelString(" ");
        this.deviceChoice1110.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1110.setUpdateIdentifier("");
        this.deviceChoice1110.setIdentifier("");
        this.deviceField1111113.setOffsetNid(137);
        this.deviceField1111113.setNumCols(25);
        this.deviceField1111113.setIdentifier("");
        this.flowLayout1111114.setVgap(0);
        this.flowLayout1111114.setAlignment(FlowLayout.LEFT);
        this.deviceField1111114.setIdentifier("");
        this.deviceField1111114.setNumCols(15);
        this.deviceField1111114.setOffsetNid(126);
        this.deviceChannel1111.setLayout(this.flowLayout1111114);
        this.deviceChannel1111.setInSameLine(true);
        this.deviceChannel1111.setLabelString("10");
        this.deviceChannel1111.setOffsetNid(124);
        this.flowLayout1111115.setAlignment(FlowLayout.LEFT);
        this.flowLayout1111115.setVgap(0);
        this.jPanel1116.setLayout(this.flowLayout1111115);
        this.deviceChoice1111.setChoiceIntValues(null);
        this.deviceChoice1111.setChoiceFloatValues(null);
        this.deviceChoice1111.setOffsetNid(127);
        this.deviceChoice1111.setLabelString(" ");
        this.deviceChoice1111.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1111.setUpdateIdentifier("");
        this.deviceChoice1111.setIdentifier("");
        this.deviceField1111115.setOffsetNid(125);
        this.deviceField1111115.setNumCols(25);
        this.deviceField1111115.setIdentifier("");
        this.flowLayout1111116.setVgap(0);
        this.flowLayout1111116.setAlignment(FlowLayout.LEFT);
        this.deviceField1111116.setIdentifier("");
        this.deviceField1111116.setNumCols(15);
        this.deviceField1111116.setOffsetNid(114);
        this.deviceChannel1112.setLayout(this.flowLayout1111116);
        this.deviceChannel1112.setInSameLine(true);
        this.deviceChannel1112.setLabelString("09");
        this.deviceChannel1112.setOffsetNid(112);
        this.flowLayout1111117.setAlignment(FlowLayout.LEFT);
        this.flowLayout1111117.setVgap(0);
        this.jPanel1117.setLayout(this.flowLayout1111117);
        this.deviceChoice1112.setChoiceIntValues(null);
        this.deviceChoice1112.setChoiceFloatValues(null);
        this.deviceChoice1112.setOffsetNid(115);
        this.deviceChoice1112.setLabelString(" ");
        this.deviceChoice1112.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1112.setUpdateIdentifier("");
        this.deviceChoice1112.setIdentifier("");
        this.deviceField1111117.setOffsetNid(113);
        this.deviceField1111117.setNumCols(25);
        this.deviceField1111117.setIdentifier("");
        this.flowLayout1111118.setVgap(0);
        this.flowLayout1111118.setAlignment(FlowLayout.LEFT);
        this.deviceField1111118.setIdentifier("");
        this.deviceField1111118.setNumCols(15);
        this.deviceField1111118.setOffsetNid(102);
        this.deviceChannel1113.setLayout(this.flowLayout1111118);
        this.deviceChannel1113.setInSameLine(true);
        this.deviceChannel1113.setLabelString("08");
        this.deviceChannel1113.setOffsetNid(100);
        this.flowLayout1111119.setAlignment(FlowLayout.LEFT);
        this.flowLayout1111119.setVgap(0);
        this.jPanel1118.setLayout(this.flowLayout1111119);
        this.deviceChoice1113.setChoiceIntValues(null);
        this.deviceChoice1113.setChoiceFloatValues(null);
        this.deviceChoice1113.setOffsetNid(103);
        this.deviceChoice1113.setLabelString(" ");
        this.deviceChoice1113.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1113.setUpdateIdentifier("");
        this.deviceChoice1113.setIdentifier("");
        this.deviceField1111119.setOffsetNid(101);
        this.deviceField1111119.setNumCols(25);
        this.deviceField1111119.setIdentifier("");
        this.flowLayout11111110.setVgap(0);
        this.flowLayout11111110.setAlignment(FlowLayout.LEFT);
        this.deviceField11111110.setIdentifier("");
        this.deviceField11111110.setNumCols(15);
        this.deviceField11111110.setOffsetNid(90);
        this.deviceChannel1114.setLayout(this.flowLayout11111110);
        this.deviceChannel1114.setInSameLine(true);
        this.deviceChannel1114.setLabelString("07");
        this.deviceChannel1114.setOffsetNid(88);
        this.flowLayout11111111.setAlignment(FlowLayout.LEFT);
        this.flowLayout11111111.setVgap(0);
        this.jPanel1119.setLayout(this.flowLayout11111111);
        this.deviceChoice1114.setChoiceIntValues(null);
        this.deviceChoice1114.setChoiceFloatValues(null);
        this.deviceChoice1114.setOffsetNid(91);
        this.deviceChoice1114.setLabelString(" ");
        this.deviceChoice1114.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1114.setUpdateIdentifier("");
        this.deviceChoice1114.setIdentifier("");
        this.deviceField11111111.setOffsetNid(89);
        this.deviceField11111111.setNumCols(25);
        this.deviceField11111111.setIdentifier("");
        this.flowLayout11111112.setVgap(0);
        this.flowLayout11111112.setAlignment(FlowLayout.LEFT);
        this.deviceField11111112.setIdentifier("");
        this.deviceField11111112.setNumCols(15);
        this.deviceField11111112.setOffsetNid(78);
        this.deviceChannel1115.setLayout(this.flowLayout11111112);
        this.deviceChannel1115.setInSameLine(true);
        this.deviceChannel1115.setLabelString("06");
        this.deviceChannel1115.setOffsetNid(76);
        this.flowLayout11111113.setAlignment(FlowLayout.LEFT);
        this.flowLayout11111113.setVgap(0);
        this.jPanel11110.setLayout(this.flowLayout11111113);
        this.deviceChoice1115.setChoiceIntValues(null);
        this.deviceChoice1115.setChoiceFloatValues(null);
        this.deviceChoice1115.setOffsetNid(79);
        this.deviceChoice1115.setLabelString("");
        this.deviceChoice1115.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1115.setUpdateIdentifier("");
        this.deviceChoice1115.setIdentifier("");
        this.deviceField11111113.setOffsetNid(77);
        this.deviceField11111113.setNumCols(25);
        this.deviceField11111113.setIdentifier("");
        this.flowLayout11111114.setVgap(0);
        this.flowLayout11111114.setAlignment(FlowLayout.LEFT);
        this.deviceField11111114.setIdentifier("");
        this.deviceField11111114.setNumCols(15);
        this.deviceField11111114.setOffsetNid(66);
        this.deviceChannel1116.setLayout(this.flowLayout11111114);
        this.deviceChannel1116.setInSameLine(true);
        this.deviceChannel1116.setLabelString("05");
        this.deviceChannel1116.setOffsetNid(64);
        this.flowLayout11111115.setAlignment(FlowLayout.LEFT);
        this.flowLayout11111115.setVgap(0);
        this.jPanel11111.setLayout(this.flowLayout11111115);
        this.deviceChoice1116.setChoiceIntValues(null);
        this.deviceChoice1116.setChoiceFloatValues(null);
        this.deviceChoice1116.setOffsetNid(67);
        this.deviceChoice1116.setLabelString(" ");
        this.deviceChoice1116.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1116.setUpdateIdentifier("");
        this.deviceChoice1116.setIdentifier("");
        this.deviceField11111115.setOffsetNid(65);
        this.deviceField11111115.setNumCols(25);
        this.deviceField11111115.setIdentifier("");
        this.flowLayout11111116.setVgap(0);
        this.flowLayout11111116.setAlignment(FlowLayout.LEFT);
        this.deviceField11111116.setIdentifier("");
        this.deviceField11111116.setNumCols(15);
        this.deviceField11111116.setOffsetNid(54);
        this.deviceChannel1117.setLayout(this.flowLayout11111116);
        this.deviceChannel1117.setInSameLine(true);
        this.deviceChannel1117.setLabelString("04");
        this.deviceChannel1117.setOffsetNid(52);
        this.flowLayout11111117.setAlignment(FlowLayout.LEFT);
        this.flowLayout11111117.setVgap(0);
        this.jPanel11112.setLayout(this.flowLayout11111117);
        this.deviceChoice1117.setChoiceIntValues(null);
        this.deviceChoice1117.setChoiceFloatValues(null);
        this.deviceChoice1117.setOffsetNid(55);
        this.deviceChoice1117.setLabelString(" ");
        this.deviceChoice1117.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1117.setUpdateIdentifier("");
        this.deviceChoice1117.setIdentifier("");
        this.deviceField11111117.setOffsetNid(53);
        this.deviceField11111117.setNumCols(25);
        this.deviceField11111117.setIdentifier("");
        this.flowLayout11111118.setVgap(0);
        this.flowLayout11111118.setAlignment(FlowLayout.LEFT);
        this.deviceField11111118.setIdentifier("");
        this.deviceField11111118.setNumCols(15);
        this.deviceField11111118.setOffsetNid(42);
        this.deviceChannel1118.setLayout(this.flowLayout11111118);
        this.deviceChannel1118.setInSameLine(true);
        this.deviceChannel1118.setLabelString("03");
        this.deviceChannel1118.setOffsetNid(40);
        this.flowLayout11111119.setAlignment(FlowLayout.LEFT);
        this.flowLayout11111119.setVgap(0);
        this.jPanel11113.setLayout(this.flowLayout11111119);
        this.deviceChoice1118.setChoiceIntValues(null);
        this.deviceChoice1118.setChoiceFloatValues(null);
        this.deviceChoice1118.setOffsetNid(43);
        this.deviceChoice1118.setLabelString(" ");
        this.deviceChoice1118.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1118.setUpdateIdentifier("");
        this.deviceChoice1118.setIdentifier("");
        this.deviceField11111119.setOffsetNid(41);
        this.deviceField11111119.setNumCols(25);
        this.deviceField11111119.setIdentifier("");
        this.flowLayout111111110.setVgap(0);
        this.flowLayout111111110.setAlignment(FlowLayout.LEFT);
        this.deviceField111111110.setIdentifier("");
        this.deviceField111111110.setNumCols(15);
        this.deviceField111111110.setOffsetNid(30);
        this.deviceChannel1119.setLayout(this.flowLayout111111110);
        this.deviceChannel1119.setInSameLine(true);
        this.deviceChannel1119.setLabelString("02");
        this.deviceChannel1119.setOffsetNid(28);
        this.flowLayout111111111.setAlignment(FlowLayout.LEFT);
        this.flowLayout111111111.setVgap(0);
        this.jPanel11114.setLayout(this.flowLayout111111111);
        this.deviceChoice1119.setChoiceIntValues(null);
        this.deviceChoice1119.setChoiceFloatValues(null);
        this.deviceChoice1119.setOffsetNid(31);
        this.deviceChoice1119.setLabelString(" ");
        this.deviceChoice1119.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice1119.setUpdateIdentifier("");
        this.deviceChoice1119.setIdentifier("");
        this.deviceField111111111.setOffsetNid(29);
        this.deviceField111111111.setNumCols(25);
        this.deviceField111111111.setIdentifier("");
        this.flowLayout111111112.setVgap(0);
        this.flowLayout111111112.setAlignment(FlowLayout.LEFT);
        this.deviceField111111112.setIdentifier("");
        this.deviceField111111112.setNumCols(15);
        this.deviceField111111112.setOffsetNid(18);
        this.deviceChannel11110.setLayout(this.flowLayout111111112);
        this.deviceChannel11110.setInSameLine(true);
        this.deviceChannel11110.setUpdateIdentifier("");
        this.deviceChannel11110.setShowVal("");
        this.deviceChannel11110.setLabelString("01");
        this.deviceChannel11110.setOffsetNid(16);
        this.flowLayout111111113.setAlignment(FlowLayout.LEFT);
        this.flowLayout111111113.setVgap(0);
        this.jPanel11115.setLayout(this.flowLayout111111113);
        this.deviceChoice11110.setChoiceIntValues(null);
        this.deviceChoice11110.setChoiceFloatValues(null);
        this.deviceChoice11110.setOffsetNid(19);
        this.deviceChoice11110.setLabelString(" ");
        this.deviceChoice11110.setChoiceItems(new String[]{"CA334", "CA332"});
        this.deviceChoice11110.setUpdateIdentifier("");
        this.deviceChoice11110.setIdentifier("");
        this.deviceField111111113.setOffsetNid(17);
        this.deviceField111111113.setNumCols(25);
        this.deviceField111111113.setIdentifier("");
        this.deviceButtons1.setMethods(new String[]{"init", "trigger", "reset", "turn_off"});
        this.getContentPane().add(this.jPanel1, BorderLayout.NORTH);
        this.jPanel1.add(this.jPanel2, null);
        this.jPanel2.add(this.deviceField1, null);
        this.jPanel2.add(this.deviceDispatch1, null);
        this.jPanel1.add(this.jPanel3, null);
        this.jPanel3.add(this.deviceField2, null);
        this.jPanel3.add(this.deviceField3, null);
        this.jPanel1.add(this.jPanel6, null);
        this.jPanel6.add(this.jLabel1, null);
        this.getContentPane().add(this.jScrollPane1, BorderLayout.CENTER);
        this.jScrollPane1.getViewport().add(this.jPanel4, null);
        this.jPanel4.add(this.deviceChannel1, null);
        this.deviceChannel1.add(this.jPanel5, null);
        this.jPanel5.add(this.deviceField4, null);
        this.jPanel5.add(this.deviceField5, null);
        this.jPanel5.add(this.deviceChoice1, null);
        this.jPanel4.add(this.deviceChannel11110, null);
        this.deviceChannel11110.add(this.jPanel11115, null);
        this.jPanel11115.add(this.deviceField111111113, null);
        this.jPanel11115.add(this.deviceField111111112, null);
        this.jPanel11115.add(this.deviceChoice11110, null);
        this.jPanel4.add(this.deviceChannel1119, null);
        this.deviceChannel1119.add(this.jPanel11114, null);
        this.jPanel11114.add(this.deviceField111111111, null);
        this.jPanel11114.add(this.deviceField111111110, null);
        this.jPanel11114.add(this.deviceChoice1119, null);
        this.jPanel4.add(this.deviceChannel1118, null);
        this.deviceChannel1118.add(this.jPanel11113, null);
        this.jPanel11113.add(this.deviceField11111119, null);
        this.jPanel11113.add(this.deviceField11111118, null);
        this.jPanel11113.add(this.deviceChoice1118, null);
        this.jPanel4.add(this.deviceChannel1117, null);
        this.deviceChannel1117.add(this.jPanel11112, null);
        this.jPanel11112.add(this.deviceField11111117, null);
        this.jPanel11112.add(this.deviceField11111116, null);
        this.jPanel11112.add(this.deviceChoice1117, null);
        this.jPanel4.add(this.deviceChannel1116, null);
        this.deviceChannel1116.add(this.jPanel11111, null);
        this.jPanel11111.add(this.deviceField11111115, null);
        this.jPanel11111.add(this.deviceField11111114, null);
        this.jPanel11111.add(this.deviceChoice1116, null);
        this.jPanel4.add(this.deviceChannel1115, null);
        this.deviceChannel1115.add(this.jPanel11110, null);
        this.jPanel11110.add(this.deviceField11111113, null);
        this.jPanel11110.add(this.deviceField11111112, null);
        this.jPanel11110.add(this.deviceChoice1115, null);
        this.jPanel4.add(this.deviceChannel1114, null);
        this.deviceChannel1114.add(this.jPanel1119, null);
        this.jPanel1119.add(this.deviceField11111111, null);
        this.jPanel1119.add(this.deviceField11111110, null);
        this.jPanel1119.add(this.deviceChoice1114, null);
        this.jPanel4.add(this.deviceChannel1113, null);
        this.deviceChannel1113.add(this.jPanel1118, null);
        this.jPanel1118.add(this.deviceField1111119, null);
        this.jPanel1118.add(this.deviceField1111118, null);
        this.jPanel1118.add(this.deviceChoice1113, null);
        this.jPanel4.add(this.deviceChannel1112, null);
        this.deviceChannel1112.add(this.jPanel1117, null);
        this.jPanel1117.add(this.deviceField1111117, null);
        this.jPanel1117.add(this.deviceField1111116, null);
        this.jPanel1117.add(this.deviceChoice1112, null);
        this.jPanel4.add(this.deviceChannel1111, null);
        this.deviceChannel1111.add(this.jPanel1116, null);
        this.jPanel1116.add(this.deviceField1111115, null);
        this.jPanel1116.add(this.deviceField1111114, null);
        this.jPanel1116.add(this.deviceChoice1111, null);
        this.jPanel4.add(this.deviceChannel1110, null);
        this.deviceChannel1110.add(this.jPanel1115, null);
        this.jPanel1115.add(this.deviceField1111113, null);
        this.jPanel1115.add(this.deviceField1111112, null);
        this.jPanel1115.add(this.deviceChoice1110, null);
        this.jPanel4.add(this.deviceChannel119, null);
        this.deviceChannel119.add(this.jPanel1114, null);
        this.jPanel1114.add(this.deviceField1111111, null);
        this.jPanel1114.add(this.deviceField1111110, null);
        this.jPanel1114.add(this.deviceChoice119, null);
        this.jPanel4.add(this.deviceChannel118, null);
        this.deviceChannel118.add(this.jPanel1113, null);
        this.jPanel1113.add(this.deviceField111119, null);
        this.jPanel1113.add(this.deviceField111118, null);
        this.jPanel1113.add(this.deviceChoice118, null);
        this.jPanel4.add(this.deviceChannel117, null);
        this.deviceChannel117.add(this.jPanel1112, null);
        this.jPanel1112.add(this.deviceField111117, null);
        this.jPanel1112.add(this.deviceField111116, null);
        this.jPanel1112.add(this.deviceChoice117, null);
        this.jPanel4.add(this.deviceChannel116, null);
        this.deviceChannel116.add(this.jPanel1111, null);
        this.jPanel1111.add(this.deviceField111115, null);
        this.jPanel1111.add(this.deviceField111114, null);
        this.jPanel1111.add(this.deviceChoice116, null);
        this.jPanel4.add(this.deviceChannel115, null);
        this.deviceChannel115.add(this.jPanel1110, null);
        this.jPanel1110.add(this.deviceField111113, null);
        this.jPanel1110.add(this.deviceField111112, null);
        this.jPanel1110.add(this.deviceChoice115, null);
        this.jPanel4.add(this.deviceChannel114, null);
        this.deviceChannel114.add(this.jPanel119, null);
        this.jPanel119.add(this.deviceField111111, null);
        this.jPanel119.add(this.deviceField111110, null);
        this.jPanel119.add(this.deviceChoice114, null);
        this.jPanel4.add(this.deviceChannel113, null);
        this.deviceChannel113.add(this.jPanel118, null);
        this.jPanel118.add(this.deviceField11119, null);
        this.jPanel118.add(this.deviceField11118, null);
        this.jPanel118.add(this.deviceChoice113, null);
        this.jPanel4.add(this.deviceChannel112, null);
        this.deviceChannel112.add(this.jPanel117, null);
        this.jPanel117.add(this.deviceField11117, null);
        this.jPanel117.add(this.deviceField11116, null);
        this.jPanel117.add(this.deviceChoice112, null);
        this.jPanel4.add(this.deviceChannel111, null);
        this.deviceChannel111.add(this.jPanel116, null);
        this.jPanel116.add(this.deviceField11115, null);
        this.jPanel116.add(this.deviceField11114, null);
        this.jPanel116.add(this.deviceChoice111, null);
        this.jPanel4.add(this.deviceChannel110, null);
        this.deviceChannel110.add(this.jPanel115, null);
        this.jPanel115.add(this.deviceField11113, null);
        this.jPanel115.add(this.deviceField11112, null);
        this.jPanel115.add(this.deviceChoice110, null);
        this.jPanel4.add(this.deviceChannel19, null);
        this.deviceChannel19.add(this.jPanel114, null);
        this.jPanel114.add(this.deviceField11111, null);
        this.jPanel114.add(this.deviceField11110, null);
        this.jPanel114.add(this.deviceChoice19, null);
        this.jPanel4.add(this.deviceChannel18, null);
        this.deviceChannel18.add(this.jPanel113, null);
        this.jPanel113.add(this.deviceField1119, null);
        this.jPanel113.add(this.deviceField1118, null);
        this.jPanel113.add(this.deviceChoice18, null);
        this.jPanel4.add(this.deviceChannel17, null);
        this.deviceChannel17.add(this.jPanel112, null);
        this.jPanel112.add(this.deviceField1117, null);
        this.jPanel112.add(this.deviceField1116, null);
        this.jPanel112.add(this.deviceChoice17, null);
        this.jPanel4.add(this.deviceChannel16, null);
        this.deviceChannel16.add(this.jPanel111, null);
        this.jPanel111.add(this.deviceField1115, null);
        this.jPanel111.add(this.deviceField1114, null);
        this.jPanel111.add(this.deviceChoice16, null);
        this.jPanel4.add(this.deviceChannel15, null);
        this.deviceChannel15.add(this.jPanel110, null);
        this.jPanel110.add(this.deviceField1113, null);
        this.jPanel110.add(this.deviceField1112, null);
        this.jPanel110.add(this.deviceChoice15, null);
        this.jPanel4.add(this.deviceChannel14, null);
        this.deviceChannel14.add(this.jPanel19, null);
        this.jPanel19.add(this.deviceField1111, null);
        this.jPanel19.add(this.deviceField1110, null);
        this.jPanel19.add(this.deviceChoice14, null);
        this.jPanel4.add(this.deviceChannel13, null);
        this.deviceChannel13.add(this.jPanel18, null);
        this.jPanel18.add(this.deviceField119, null);
        this.jPanel18.add(this.deviceField118, null);
        this.jPanel18.add(this.deviceChoice13, null);
        this.jPanel4.add(this.deviceChannel12, null);
        this.deviceChannel12.add(this.jPanel17, null);
        this.jPanel17.add(this.deviceField117, null);
        this.jPanel17.add(this.deviceField116, null);
        this.jPanel17.add(this.deviceChoice12, null);
        this.jPanel4.add(this.deviceChannel11, null);
        this.deviceChannel11.add(this.jPanel16, null);
        this.jPanel16.add(this.deviceField115, null);
        this.jPanel16.add(this.deviceField114, null);
        this.jPanel16.add(this.deviceChoice11, null);
        this.jPanel4.add(this.deviceChannel10, null);
        this.deviceChannel10.add(this.jPanel15, null);
        this.jPanel15.add(this.deviceField113, null);
        this.jPanel15.add(this.deviceField112, null);
        this.jPanel15.add(this.deviceChoice10, null);
        this.jPanel4.add(this.deviceChannel9, null);
        this.deviceChannel9.add(this.jPanel14, null);
        this.jPanel14.add(this.deviceField111, null);
        this.jPanel14.add(this.deviceField110, null);
        this.jPanel14.add(this.deviceChoice9, null);
        this.jPanel4.add(this.deviceChannel8, null);
        this.deviceChannel8.add(this.jPanel13, null);
        this.jPanel13.add(this.deviceField19, null);
        this.jPanel13.add(this.deviceField18, null);
        this.jPanel13.add(this.deviceChoice8, null);
        this.jPanel4.add(this.deviceChannel7, null);
        this.deviceChannel7.add(this.jPanel12, null);
        this.jPanel12.add(this.deviceField17, null);
        this.jPanel12.add(this.deviceField16, null);
        this.jPanel12.add(this.deviceChoice7, null);
        this.jPanel4.add(this.deviceChannel6, null);
        this.deviceChannel6.add(this.jPanel11, null);
        this.jPanel11.add(this.deviceField15, null);
        this.jPanel11.add(this.deviceField14, null);
        this.jPanel11.add(this.deviceChoice6, null);
        this.jPanel4.add(this.deviceChannel5, null);
        this.deviceChannel5.add(this.jPanel10, null);
        this.jPanel10.add(this.deviceField13, null);
        this.jPanel10.add(this.deviceField12, null);
        this.jPanel10.add(this.deviceChoice5, null);
        this.jPanel4.add(this.deviceChannel4, null);
        this.deviceChannel4.add(this.jPanel9, null);
        this.jPanel9.add(this.deviceField11, null);
        this.jPanel9.add(this.deviceField10, null);
        this.jPanel9.add(this.deviceChoice4, null);
        this.jPanel4.add(this.deviceChannel3, null);
        this.deviceChannel3.add(this.jPanel8, null);
        this.jPanel8.add(this.deviceField9, null);
        this.jPanel8.add(this.deviceField8, null);
        this.jPanel8.add(this.deviceChoice3, null);
        this.jPanel4.add(this.deviceChannel2, null);
        this.deviceChannel2.add(this.jPanel7, null);
        this.jPanel7.add(this.deviceField7, null);
        this.jPanel7.add(this.deviceField6, null);
        this.jPanel7.add(this.deviceChoice2, null);
        this.getContentPane().add(this.deviceButtons1, BorderLayout.SOUTH);
    }
}