import devicebeans.DeviceButtons;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @author Cesare
 */
public class CONTIPPSETUPSetup extends DeviceSetup{
    /**
     *
     */
    private static final long  serialVersionUID = -6877134971068082495L;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons      deviceButtons1;
    private DeviceField        deviceField1;
    private DeviceField        deviceField2;
    private DeviceField        deviceField3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;

    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form CONTIPPSETUPSetup
     */
    public CONTIPPSETUPSetup(){
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.deviceButtons1 = new DeviceButtons();
        this.jPanel1 = new javax.swing.JPanel();
        this.jPanel2 = new javax.swing.JPanel();
        this.deviceField1 = new DeviceField();
        this.jPanel3 = new javax.swing.JPanel();
        this.deviceField2 = new DeviceField();
        this.deviceField3 = new DeviceField();
        this.setDeviceProvider("localhost");
        this.setDeviceTitle("Probe temperature control setup");
        this.setDeviceType("CONTIPPSETUP");
        this.setHeight(130);
        this.setWidth(550);
        this.deviceButtons1.setCheckExpressions(new String[]{});
        this.deviceButtons1.setCheckMessages(new String[]{});
        this.deviceButtons1.setMethods(new String[]{"start", "stop", "exit"});
        this.getContentPane().add(this.deviceButtons1, java.awt.BorderLayout.PAGE_END);
        this.jPanel1.setLayout(new java.awt.GridLayout(2, 0));
        this.deviceField1.setIdentifier("");
        this.deviceField1.setLabelString("Comment:");
        this.deviceField1.setNumCols(20);
        this.deviceField1.setOffsetNid(1);
        this.jPanel2.add(this.deviceField1);
        this.jPanel1.add(this.jPanel2);
        this.deviceField2.setIdentifier("");
        this.deviceField2.setLabelString("Set Point Temperature (C):");
        this.deviceField2.setNumCols(4);
        this.deviceField2.setOffsetNid(8);
        this.jPanel3.add(this.deviceField2);
        this.deviceField3.setIdentifier("");
        this.deviceField3.setLabelString("Sample Rate (Hz):");
        this.deviceField3.setNumCols(5);
        this.deviceField3.setOffsetNid(5);
        this.jPanel3.add(this.deviceField3);
        this.jPanel1.add(this.jPanel3);
        this.getContentPane().add(this.jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
}
