import devicebeans.DeviceButtons;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

/**
 * @author manduchi
 */
@SuppressWarnings("serial")
public class DEMOADCSetup extends DeviceSetup{
    public static void main(final String[] args) {
        new DEMOADCSetup().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons           deviceButtons1;
    private DeviceChoice            deviceChoice1;
    private DeviceDispatch          deviceDispatch1;
    private DeviceField             deviceField1;
    private DeviceField             deviceField10;
    private DeviceField             deviceField11;
    private DeviceField             deviceField12;
    private DeviceField             deviceField2;
    private DeviceField             deviceField3;
    private DeviceField             deviceField4;
    private DeviceField             deviceField5;
    private DeviceField             deviceField6;
    private DeviceField             deviceField7;
    private DeviceField             deviceField8;
    private DeviceField             deviceField9;
    private javax.swing.JPanel      jPanel1;
    private javax.swing.JPanel      jPanel2;
    private javax.swing.JPanel      jPanel3;
    private javax.swing.JPanel      jPanel4;
    private javax.swing.JPanel      jPanel5;
    private javax.swing.JPanel      jPanel6;
    private javax.swing.JPanel      jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;

    // End of variables declaration//GEN-END:variables
    /** Creates new form BeanForm */
    public DEMOADCSetup(){
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.deviceButtons1 = new DeviceButtons();
        this.jPanel1 = new javax.swing.JPanel();
        this.jPanel2 = new javax.swing.JPanel();
        this.deviceField1 = new DeviceField();
        this.deviceField2 = new DeviceField();
        this.deviceDispatch1 = new DeviceDispatch();
        this.jPanel3 = new javax.swing.JPanel();
        this.deviceChoice1 = new DeviceChoice();
        this.deviceField3 = new DeviceField();
        this.deviceField4 = new DeviceField();
        this.jTabbedPane1 = new javax.swing.JTabbedPane();
        this.jPanel4 = new javax.swing.JPanel();
        this.deviceField5 = new DeviceField();
        this.deviceField6 = new DeviceField();
        this.jPanel5 = new javax.swing.JPanel();
        this.deviceField7 = new DeviceField();
        this.deviceField8 = new DeviceField();
        this.jPanel6 = new javax.swing.JPanel();
        this.deviceField9 = new DeviceField();
        this.deviceField10 = new DeviceField();
        this.jPanel7 = new javax.swing.JPanel();
        this.deviceField11 = new DeviceField();
        this.deviceField12 = new DeviceField();
        this.setDeviceProvider("localhost");
        this.setDeviceTitle("ADC for MDSplus Tutorial");
        this.setDeviceType("DEMOADC");
        this.setHeight(250);
        this.setWidth(700);
        this.getContentPane().add(this.deviceButtons1, java.awt.BorderLayout.PAGE_END);
        this.jPanel1.setLayout(new java.awt.GridLayout(2, 1));
        this.deviceField1.setIdentifier("");
        this.deviceField1.setLabelString("Name: ");
        this.deviceField1.setOffsetNid(1);
        this.deviceField1.setTextOnly(true);
        this.jPanel2.add(this.deviceField1);
        this.deviceField2.setIdentifier("");
        this.deviceField2.setLabelString("Comment: ");
        this.deviceField2.setNumCols(20);
        this.deviceField2.setOffsetNid(2);
        this.deviceField2.setTextOnly(true);
        this.jPanel2.add(this.deviceField2);
        this.jPanel2.add(this.deviceDispatch1);
        this.jPanel1.add(this.jPanel2);
        this.deviceChoice1.setChoiceIntValues(new int[]{1000, 5000, 10000, 50000, 100000});
        this.deviceChoice1.setChoiceItems(new String[]{"1000", "5000", "10000", "50000", "100000"});
        this.deviceChoice1.setIdentifier("");
        this.deviceChoice1.setLabelString("Clock. Freq. (Hz):");
        this.deviceChoice1.setOffsetNid(3);
        this.deviceChoice1.setUpdateIdentifier("");
        this.jPanel3.add(this.deviceChoice1);
        this.deviceField3.setIdentifier("");
        this.deviceField3.setLabelString("PTS:");
        this.deviceField3.setNumCols(4);
        this.deviceField3.setOffsetNid(5);
        this.jPanel3.add(this.deviceField3);
        this.deviceField4.setIdentifier("");
        this.deviceField4.setLabelString("Trig. Source: ");
        this.deviceField4.setNumCols(20);
        this.deviceField4.setOffsetNid(4);
        this.jPanel3.add(this.deviceField4);
        this.jPanel1.add(this.jPanel3);
        this.getContentPane().add(this.jPanel1, java.awt.BorderLayout.PAGE_START);
        this.deviceField5.setIdentifier("");
        this.deviceField5.setLabelString("Start Idx: ");
        this.deviceField5.setOffsetNid(7);
        this.jPanel4.add(this.deviceField5);
        this.deviceField6.setIdentifier("");
        this.deviceField6.setLabelString("End Idx: ");
        this.deviceField6.setOffsetNid(8);
        this.jPanel4.add(this.deviceField6);
        this.jTabbedPane1.addTab("Chan 1", this.jPanel4);
        this.deviceField7.setIdentifier("");
        this.deviceField7.setLabelString("Start Idx: ");
        this.deviceField7.setOffsetNid(11);
        this.jPanel5.add(this.deviceField7);
        this.deviceField8.setIdentifier("");
        this.deviceField8.setLabelString("End Idx: ");
        this.deviceField8.setOffsetNid(12);
        this.jPanel5.add(this.deviceField8);
        this.jTabbedPane1.addTab("Chan 2", this.jPanel5);
        this.deviceField9.setIdentifier("");
        this.deviceField9.setLabelString("Start Idx: ");
        this.deviceField9.setOffsetNid(15);
        this.jPanel6.add(this.deviceField9);
        this.deviceField10.setIdentifier("");
        this.deviceField10.setLabelString("End Idx: ");
        this.deviceField10.setOffsetNid(16);
        this.jPanel6.add(this.deviceField10);
        this.jTabbedPane1.addTab("Chan 3", this.jPanel6);
        this.deviceField11.setIdentifier("");
        this.deviceField11.setLabelString("Start Idx: ");
        this.deviceField11.setOffsetNid(19);
        this.jPanel7.add(this.deviceField11);
        this.deviceField12.setIdentifier("");
        this.deviceField12.setLabelString("End Idx: ");
        this.deviceField12.setOffsetNid(20);
        this.jPanel7.add(this.deviceField12);
        this.jTabbedPane1.addTab("Chan 4", this.jPanel7);
        this.getContentPane().add(this.jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
}
