import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import devicebeans.DeviceButtons;
import devicebeans.DeviceChannel;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 * 
 * @author not attributable
 * @version 1.0
 */
public class DIO2EncoderSetup extends DeviceSetup{
    /**
     * 
     */
    private static final long serialVersionUID = 223723943321752188L;
    BorderLayout   borderLayout1     = new BorderLayout();
    BorderLayout   borderLayout2     = new BorderLayout();
    DeviceButtons  deviceButtons1    = new DeviceButtons();
    DeviceChannel  deviceChannel1    = new DeviceChannel();
    DeviceChannel  deviceChannel10   = new DeviceChannel();
    DeviceChannel  deviceChannel11   = new DeviceChannel();
    DeviceChannel  deviceChannel12   = new DeviceChannel();
    DeviceChannel  deviceChannel13   = new DeviceChannel();
    DeviceChannel  deviceChannel14   = new DeviceChannel();
    DeviceChannel  deviceChannel15   = new DeviceChannel();
    DeviceChannel  deviceChannel16   = new DeviceChannel();
    DeviceChannel  deviceChannel17   = new DeviceChannel();
    DeviceChannel  deviceChannel2    = new DeviceChannel();
    DeviceChannel  deviceChannel3    = new DeviceChannel();
    DeviceChannel  deviceChannel4    = new DeviceChannel();
    DeviceChannel  deviceChannel5    = new DeviceChannel();
    DeviceChannel  deviceChannel6    = new DeviceChannel();
    DeviceChannel  deviceChannel7    = new DeviceChannel();
    DeviceChannel  deviceChannel8    = new DeviceChannel();
    DeviceChannel  deviceChannel9    = new DeviceChannel();
    DeviceChoice   deviceChoice10    = new DeviceChoice();
    DeviceChoice   deviceChoice11    = new DeviceChoice();
    DeviceChoice   deviceChoice110   = new DeviceChoice();
    DeviceChoice   deviceChoice12    = new DeviceChoice();
    DeviceChoice   deviceChoice13    = new DeviceChoice();
    DeviceChoice   deviceChoice14    = new DeviceChoice();
    DeviceChoice   deviceChoice15    = new DeviceChoice();
    DeviceChoice   deviceChoice16    = new DeviceChoice();
    DeviceChoice   deviceChoice17    = new DeviceChoice();
    DeviceChoice   deviceChoice18    = new DeviceChoice();
    DeviceChoice   deviceChoice19    = new DeviceChoice();
    DeviceChoice   deviceChoice2     = new DeviceChoice();
    DeviceChoice   deviceChoice3     = new DeviceChoice();
    DeviceChoice   deviceChoice4     = new DeviceChoice();
    DeviceChoice   deviceChoice6     = new DeviceChoice();
    DeviceChoice   deviceChoice7     = new DeviceChoice();
    DeviceChoice   deviceChoice8     = new DeviceChoice();
    DeviceChoice   deviceChoice9     = new DeviceChoice();
    DeviceDispatch deviceDispatch1   = new DeviceDispatch();
    DeviceField    deviceField1      = new DeviceField();
    DeviceField    deviceField10     = new DeviceField();
    DeviceField    deviceField11     = new DeviceField();
    DeviceField    deviceField110    = new DeviceField();
    DeviceField    deviceField111    = new DeviceField();
    DeviceField    deviceField1110   = new DeviceField();
    DeviceField    deviceField1111   = new DeviceField();
    DeviceField    deviceField11110  = new DeviceField();
    DeviceField    deviceField11111  = new DeviceField();
    DeviceField    deviceField111110 = new DeviceField();
    DeviceField    deviceField111111 = new DeviceField();
    DeviceField    deviceField111112 = new DeviceField();
    DeviceField    deviceField111113 = new DeviceField();
    DeviceField    deviceField111114 = new DeviceField();
    DeviceField    deviceField11112  = new DeviceField();
    DeviceField    deviceField11113  = new DeviceField();
    DeviceField    deviceField11114  = new DeviceField();
    DeviceField    deviceField11115  = new DeviceField();
    DeviceField    deviceField11116  = new DeviceField();
    DeviceField    deviceField11117  = new DeviceField();
    DeviceField    deviceField11118  = new DeviceField();
    DeviceField    deviceField11119  = new DeviceField();
    DeviceField    deviceField1112   = new DeviceField();
    DeviceField    deviceField1113   = new DeviceField();
    DeviceField    deviceField1114   = new DeviceField();
    DeviceField    deviceField1115   = new DeviceField();
    DeviceField    deviceField1116   = new DeviceField();
    DeviceField    deviceField1117   = new DeviceField();
    DeviceField    deviceField1118   = new DeviceField();
    DeviceField    deviceField1119   = new DeviceField();
    DeviceField    deviceField112    = new DeviceField();
    DeviceField    deviceField113    = new DeviceField();
    DeviceField    deviceField114    = new DeviceField();
    DeviceField    deviceField115    = new DeviceField();
    DeviceField    deviceField116    = new DeviceField();
    DeviceField    deviceField117    = new DeviceField();
    DeviceField    deviceField118    = new DeviceField();
    DeviceField    deviceField119    = new DeviceField();
    DeviceField    deviceField12     = new DeviceField();
    DeviceField    deviceField13     = new DeviceField();
    DeviceField    deviceField14     = new DeviceField();
    DeviceField    deviceField15     = new DeviceField();
    DeviceField    deviceField16     = new DeviceField();
    DeviceField    deviceField17     = new DeviceField();
    DeviceField    deviceField18     = new DeviceField();
    DeviceField    deviceField19     = new DeviceField();
    DeviceField    deviceField2      = new DeviceField();
    DeviceField    deviceField3      = new DeviceField();
    DeviceField    deviceField4      = new DeviceField();
    DeviceField    deviceField5      = new DeviceField();
    DeviceField    deviceField6      = new DeviceField();
    DeviceField    deviceField7      = new DeviceField();
    DeviceField    deviceField8      = new DeviceField();
    DeviceField    deviceField9      = new DeviceField();
    GridLayout     gridLayout1       = new GridLayout();
    GridLayout     gridLayout2       = new GridLayout();
    JPanel         jPanel1           = new JPanel();
    JPanel         jPanel10          = new JPanel();
    JPanel         jPanel11          = new JPanel();
    JPanel         jPanel110         = new JPanel();
    JPanel         jPanel111         = new JPanel();
    JPanel         jPanel112         = new JPanel();
    JPanel         jPanel12          = new JPanel();
    JPanel         jPanel13          = new JPanel();
    JPanel         jPanel14          = new JPanel();
    JPanel         jPanel15          = new JPanel();
    JPanel         jPanel16          = new JPanel();
    JPanel         jPanel17          = new JPanel();
    JPanel         jPanel18          = new JPanel();
    JPanel         jPanel19          = new JPanel();
    JPanel         jPanel2           = new JPanel();
    JPanel         jPanel3           = new JPanel();
    JPanel         jPanel4           = new JPanel();
    JPanel         jPanel5           = new JPanel();
    JPanel         jPanel6           = new JPanel();
    JPanel         jPanel7           = new JPanel();
    JPanel         jPanel8           = new JPanel();
    JPanel         jPanel9           = new JPanel();
    JScrollPane    jScrollPane1      = new JScrollPane();

    public DIO2EncoderSetup(){
        try{
            this.jbInit();
        }catch(final Exception e){
            e.printStackTrace();
        }
    }

    private void jbInit() throws Exception {
        this.setWidth(770);
        this.setHeight(640);
        this.setDeviceType("DIO2Encoder");
        this.setDeviceProvider("localhost");
        this.setDeviceTitle("DIO2 Timing Encoder");
        this.getContentPane().setLayout(this.borderLayout1);
        this.jPanel1.setLayout(this.gridLayout1);
        this.gridLayout1.setColumns(1);
        this.gridLayout1.setRows(2);
        this.deviceField1.setOffsetNid(4);
        this.deviceField1.setTextOnly(true);
        this.deviceField1.setLabelString("Comment: ");
        this.deviceField1.setNumCols(30);
        this.deviceField1.setIdentifier("");
        this.deviceField3.setOffsetNid(1);
        this.deviceField3.setLabelString("Board ID:");
        this.deviceField3.setNumCols(4);
        this.deviceField3.setIdentifier("");
        this.deviceChoice3.setChoiceIntValues(null);
        this.deviceChoice3.setChoiceFloatValues(null);
        this.deviceChoice3.setOffsetNid(2);
        this.deviceChoice3.setLabelString("Mode: ");
        this.deviceChoice3.setChoiceItems(new String[]{"LOCAL", "REMOTE"});
        this.deviceChoice3.setUpdateIdentifier("");
        this.deviceChoice3.setIdentifier("");
        this.deviceField2.setOffsetNid(3);
        this.deviceField2.setTextOnly(true);
        this.deviceField2.setLabelString("Crate IP Addr.: ");
        this.deviceField2.setNumCols(15);
        this.deviceField2.setIdentifier("");
        this.jPanel2.setLayout(this.borderLayout2);
        this.jPanel5.setLayout(this.gridLayout2);
        this.gridLayout2.setColumns(1);
        this.gridLayout2.setRows(17);
        this.deviceChannel1.setLabelString("Ch 1: ");
        this.deviceChannel1.setOffsetNid(6);
        this.deviceChannel1.setBorderVisible(true);
        this.deviceChannel1.setInSameLine(true);
        this.deviceChannel1.setUpdateIdentifier("");
        this.deviceChannel1.setShowVal("");
        this.deviceChoice4.setChoiceIntValues(null);
        this.deviceChoice4.setChoiceFloatValues(null);
        this.deviceChoice4.setOffsetNid(10);
        this.deviceChoice4.setLabelString("Termination: ");
        this.deviceChoice4.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice4.setUpdateIdentifier("");
        this.deviceChoice4.setIdentifier("");
        this.deviceField4.setOffsetNid(9);
        this.deviceField4.setLabelString("Time: ");
        this.deviceField4.setNumCols(15);
        this.deviceField4.setIdentifier("");
        this.deviceField5.setOffsetNid(8);
        this.deviceField5.setLabelString("Event code");
        this.deviceField5.setNumCols(4);
        this.deviceField5.setIdentifier("");
        this.deviceField6.setOffsetNid(7);
        this.deviceField6.setTextOnly(true);
        this.deviceField6.setLabelString("Event name: ");
        this.deviceField6.setIdentifier("");
        this.deviceChoice2.setChoiceIntValues(null);
        this.deviceChoice2.setChoiceFloatValues(null);
        this.deviceChoice2.setOffsetNid(5);
        this.deviceChoice2.setLabelString("Clock source: ");
        this.deviceChoice2.setChoiceItems(new String[]{"INTERNAL", "HIGHWAY"});
        this.deviceChoice2.setUpdateIdentifier("");
        this.deviceChoice2.setIdentifier("");
        this.deviceField7.setIdentifier("");
        this.deviceField7.setNumCols(4);
        this.deviceField7.setLabelString("Event code");
        this.deviceField7.setOffsetNid(88);
        this.deviceChannel2.setLabelString("Ch Software: ");
        this.deviceChannel2.setOffsetNid(86);
        this.deviceChannel2.setBorderVisible(true);
        this.deviceChannel2.setInSameLine(true);
        this.deviceChannel2.setUpdateIdentifier("");
        this.deviceChannel2.setShowVal("");
        this.deviceField8.setOffsetNid(87);
        this.deviceField8.setTextOnly(true);
        this.deviceField8.setLabelString("Event name: ");
        this.deviceField8.setIdentifier("");
        this.deviceField9.setOffsetNid(89);
        this.deviceField9.setLabelString("Time: ");
        this.deviceField9.setNumCols(15);
        this.deviceField9.setIdentifier("");
        this.deviceField10.setIdentifier("");
        this.deviceField10.setNumCols(4);
        this.deviceField10.setLabelString("Event code");
        this.deviceField10.setOffsetNid(83);
        this.deviceChoice6.setIdentifier("");
        this.deviceChoice6.setUpdateIdentifier("");
        this.deviceChoice6.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice6.setLabelString("Termination: ");
        this.deviceChoice6.setOffsetNid(85);
        this.deviceChoice6.setChoiceFloatValues(null);
        this.deviceChoice6.setChoiceIntValues(null);
        this.deviceChannel3.setLabelString("Ch 16: ");
        this.deviceChannel3.setOffsetNid(81);
        this.deviceChannel3.setBorderVisible(true);
        this.deviceChannel3.setInSameLine(true);
        this.deviceChannel3.setUpdateIdentifier("");
        this.deviceChannel3.setShowVal("");
        this.deviceField11.setOffsetNid(82);
        this.deviceField11.setTextOnly(true);
        this.deviceField11.setLabelString("Event name: ");
        this.deviceField11.setIdentifier("");
        this.deviceField12.setOffsetNid(84);
        this.deviceField12.setLabelString("Time: ");
        this.deviceField12.setNumCols(15);
        this.deviceField12.setIdentifier("");
        this.deviceField13.setIdentifier("");
        this.deviceField13.setNumCols(4);
        this.deviceField13.setLabelString("Event code");
        this.deviceField13.setOffsetNid(78);
        this.deviceChoice7.setIdentifier("");
        this.deviceChoice7.setUpdateIdentifier("");
        this.deviceChoice7.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice7.setLabelString("Termination: ");
        this.deviceChoice7.setOffsetNid(80);
        this.deviceChoice7.setChoiceFloatValues(null);
        this.deviceChoice7.setChoiceIntValues(null);
        this.deviceChannel4.setLabelString("Ch 15: ");
        this.deviceChannel4.setOffsetNid(76);
        this.deviceChannel4.setBorderVisible(true);
        this.deviceChannel4.setInSameLine(true);
        this.deviceChannel4.setUpdateIdentifier("");
        this.deviceChannel4.setShowVal("");
        this.deviceField14.setOffsetNid(77);
        this.deviceField14.setTextOnly(true);
        this.deviceField14.setLabelString("Event name: ");
        this.deviceField14.setIdentifier("");
        this.deviceField15.setOffsetNid(79);
        this.deviceField15.setLabelString("Time: ");
        this.deviceField15.setNumCols(15);
        this.deviceField15.setIdentifier("");
        this.deviceField16.setIdentifier("");
        this.deviceField16.setNumCols(4);
        this.deviceField16.setLabelString("Event code");
        this.deviceField16.setOffsetNid(73);
        this.deviceChoice8.setIdentifier("");
        this.deviceChoice8.setUpdateIdentifier("");
        this.deviceChoice8.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice8.setLabelString("Termination: ");
        this.deviceChoice8.setOffsetNid(75);
        this.deviceChoice8.setChoiceFloatValues(null);
        this.deviceChoice8.setChoiceIntValues(null);
        this.deviceChannel5.setLabelString("Ch 14: ");
        this.deviceChannel5.setOffsetNid(71);
        this.deviceChannel5.setBorderVisible(true);
        this.deviceChannel5.setInSameLine(true);
        this.deviceChannel5.setUpdateIdentifier("");
        this.deviceChannel5.setShowVal("");
        this.deviceField17.setOffsetNid(72);
        this.deviceField17.setTextOnly(true);
        this.deviceField17.setLabelString("Event name: ");
        this.deviceField17.setIdentifier("");
        this.deviceField18.setOffsetNid(74);
        this.deviceField18.setLabelString("Time: ");
        this.deviceField18.setNumCols(15);
        this.deviceField18.setIdentifier("");
        this.deviceField19.setIdentifier("");
        this.deviceField19.setNumCols(4);
        this.deviceField19.setLabelString("Event code");
        this.deviceField19.setOffsetNid(68);
        this.deviceChoice9.setIdentifier("");
        this.deviceChoice9.setUpdateIdentifier("");
        this.deviceChoice9.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice9.setLabelString("Termination: ");
        this.deviceChoice9.setOffsetNid(70);
        this.deviceChoice9.setChoiceFloatValues(null);
        this.deviceChoice9.setChoiceIntValues(null);
        this.deviceChannel6.setLabelString("Ch 13: ");
        this.deviceChannel6.setOffsetNid(66);
        this.deviceChannel6.setBorderVisible(true);
        this.deviceChannel6.setInSameLine(true);
        this.deviceChannel6.setUpdateIdentifier("");
        this.deviceChannel6.setShowVal("");
        this.deviceField110.setOffsetNid(67);
        this.deviceField110.setTextOnly(true);
        this.deviceField110.setLabelString("Event name: ");
        this.deviceField110.setIdentifier("");
        this.deviceField111.setOffsetNid(69);
        this.deviceField111.setLabelString("Time: ");
        this.deviceField111.setNumCols(15);
        this.deviceField111.setIdentifier("");
        this.deviceField112.setIdentifier("");
        this.deviceField112.setNumCols(4);
        this.deviceField112.setLabelString("Event code");
        this.deviceField112.setOffsetNid(63);
        this.deviceChoice10.setIdentifier("");
        this.deviceChoice10.setUpdateIdentifier("");
        this.deviceChoice10.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice10.setLabelString("Termination: ");
        this.deviceChoice10.setOffsetNid(65);
        this.deviceChoice10.setChoiceFloatValues(null);
        this.deviceChoice10.setChoiceIntValues(null);
        this.deviceChannel7.setLabelString("Ch 12: ");
        this.deviceChannel7.setOffsetNid(61);
        this.deviceChannel7.setBorderVisible(true);
        this.deviceChannel7.setInSameLine(true);
        this.deviceChannel7.setUpdateIdentifier("");
        this.deviceChannel7.setShowVal("");
        this.deviceField113.setOffsetNid(62);
        this.deviceField113.setTextOnly(true);
        this.deviceField113.setLabelString("Event name: ");
        this.deviceField113.setIdentifier("");
        this.deviceField114.setOffsetNid(64);
        this.deviceField114.setLabelString("Time: ");
        this.deviceField114.setNumCols(15);
        this.deviceField114.setIdentifier("");
        this.deviceField115.setIdentifier("");
        this.deviceField115.setNumCols(4);
        this.deviceField115.setLabelString("Event code");
        this.deviceField115.setOffsetNid(58);
        this.deviceChoice11.setIdentifier("");
        this.deviceChoice11.setUpdateIdentifier("");
        this.deviceChoice11.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice11.setLabelString("Termination: ");
        this.deviceChoice11.setOffsetNid(60);
        this.deviceChoice11.setChoiceFloatValues(null);
        this.deviceChoice11.setChoiceIntValues(null);
        this.deviceChannel8.setLabelString("Ch 11: ");
        this.deviceChannel8.setOffsetNid(56);
        this.deviceChannel8.setBorderVisible(true);
        this.deviceChannel8.setInSameLine(true);
        this.deviceChannel8.setUpdateIdentifier("");
        this.deviceChannel8.setShowVal("");
        this.deviceField116.setOffsetNid(57);
        this.deviceField116.setTextOnly(true);
        this.deviceField116.setLabelString("Event name: ");
        this.deviceField116.setIdentifier("");
        this.deviceField117.setOffsetNid(59);
        this.deviceField117.setLabelString("Time: ");
        this.deviceField117.setNumCols(15);
        this.deviceField117.setIdentifier("");
        this.deviceField118.setIdentifier("");
        this.deviceField118.setNumCols(4);
        this.deviceField118.setLabelString("Event code");
        this.deviceField118.setOffsetNid(53);
        this.deviceChoice12.setIdentifier("");
        this.deviceChoice12.setUpdateIdentifier("");
        this.deviceChoice12.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice12.setLabelString("Termination: ");
        this.deviceChoice12.setOffsetNid(55);
        this.deviceChoice12.setChoiceFloatValues(null);
        this.deviceChoice12.setChoiceIntValues(null);
        this.deviceChannel9.setLabelString("Ch 10: ");
        this.deviceChannel9.setOffsetNid(51);
        this.deviceChannel9.setBorderVisible(true);
        this.deviceChannel9.setInSameLine(true);
        this.deviceChannel9.setUpdateIdentifier("");
        this.deviceChannel9.setShowVal("");
        this.deviceField119.setOffsetNid(52);
        this.deviceField119.setTextOnly(true);
        this.deviceField119.setLabelString("Event name: ");
        this.deviceField119.setIdentifier("");
        this.deviceField1110.setOffsetNid(54);
        this.deviceField1110.setLabelString("Time: ");
        this.deviceField1110.setNumCols(15);
        this.deviceField1110.setIdentifier("");
        this.deviceField1111.setIdentifier("");
        this.deviceField1111.setNumCols(4);
        this.deviceField1111.setLabelString("Event code");
        this.deviceField1111.setOffsetNid(48);
        this.deviceChoice13.setIdentifier("");
        this.deviceChoice13.setUpdateIdentifier("");
        this.deviceChoice13.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice13.setLabelString("Termination: ");
        this.deviceChoice13.setOffsetNid(50);
        this.deviceChoice13.setChoiceFloatValues(null);
        this.deviceChoice13.setChoiceIntValues(null);
        this.deviceChannel10.setLabelString("Ch 9: ");
        this.deviceChannel10.setOffsetNid(46);
        this.deviceChannel10.setBorderVisible(true);
        this.deviceChannel10.setInSameLine(true);
        this.deviceChannel10.setUpdateIdentifier("");
        this.deviceChannel10.setShowVal("");
        this.deviceField1112.setOffsetNid(47);
        this.deviceField1112.setTextOnly(true);
        this.deviceField1112.setLabelString("Event name: ");
        this.deviceField1112.setIdentifier("");
        this.deviceField1113.setOffsetNid(49);
        this.deviceField1113.setLabelString("Time: ");
        this.deviceField1113.setNumCols(15);
        this.deviceField1113.setIdentifier("");
        this.deviceField1114.setIdentifier("");
        this.deviceField1114.setNumCols(4);
        this.deviceField1114.setLabelString("Event code");
        this.deviceField1114.setOffsetNid(43);
        this.deviceChoice14.setIdentifier("");
        this.deviceChoice14.setUpdateIdentifier("");
        this.deviceChoice14.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice14.setLabelString("Termination: ");
        this.deviceChoice14.setOffsetNid(45);
        this.deviceChoice14.setChoiceFloatValues(null);
        this.deviceChoice14.setChoiceIntValues(null);
        this.deviceChannel11.setLabelString("Ch 8: ");
        this.deviceChannel11.setOffsetNid(41);
        this.deviceChannel11.setBorderVisible(true);
        this.deviceChannel11.setInSameLine(true);
        this.deviceChannel11.setUpdateIdentifier("");
        this.deviceChannel11.setShowVal("");
        this.deviceField1115.setOffsetNid(42);
        this.deviceField1115.setTextOnly(true);
        this.deviceField1115.setLabelString("Event name: ");
        this.deviceField1115.setIdentifier("");
        this.deviceField1116.setOffsetNid(44);
        this.deviceField1116.setLabelString("Time: ");
        this.deviceField1116.setNumCols(15);
        this.deviceField1116.setIdentifier("");
        this.deviceField1117.setIdentifier("");
        this.deviceField1117.setNumCols(4);
        this.deviceField1117.setLabelString("Event code");
        this.deviceField1117.setOffsetNid(38);
        this.deviceChoice15.setIdentifier("");
        this.deviceChoice15.setUpdateIdentifier("");
        this.deviceChoice15.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice15.setLabelString("Termination: ");
        this.deviceChoice15.setOffsetNid(40);
        this.deviceChoice15.setChoiceFloatValues(null);
        this.deviceChoice15.setChoiceIntValues(null);
        this.deviceChannel12.setLabelString("Ch 7: ");
        this.deviceChannel12.setOffsetNid(36);
        this.deviceChannel12.setBorderVisible(true);
        this.deviceChannel12.setInSameLine(true);
        this.deviceChannel12.setUpdateIdentifier("");
        this.deviceChannel12.setShowVal("");
        this.deviceField1118.setOffsetNid(37);
        this.deviceField1118.setTextOnly(true);
        this.deviceField1118.setLabelString("Event name: ");
        this.deviceField1118.setIdentifier("");
        this.deviceField1119.setOffsetNid(39);
        this.deviceField1119.setLabelString("Time: ");
        this.deviceField1119.setNumCols(15);
        this.deviceField1119.setIdentifier("");
        this.deviceField11110.setIdentifier("");
        this.deviceField11110.setNumCols(4);
        this.deviceField11110.setLabelString("Event code");
        this.deviceField11110.setOffsetNid(33);
        this.deviceChoice16.setIdentifier("");
        this.deviceChoice16.setUpdateIdentifier("");
        this.deviceChoice16.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice16.setLabelString("Termination: ");
        this.deviceChoice16.setOffsetNid(35);
        this.deviceChoice16.setChoiceFloatValues(null);
        this.deviceChoice16.setChoiceIntValues(null);
        this.deviceChannel13.setLabelString("Ch 6: ");
        this.deviceChannel13.setOffsetNid(31);
        this.deviceChannel13.setBorderVisible(true);
        this.deviceChannel13.setInSameLine(true);
        this.deviceChannel13.setUpdateIdentifier("");
        this.deviceChannel13.setShowVal("");
        this.deviceField11111.setOffsetNid(32);
        this.deviceField11111.setTextOnly(true);
        this.deviceField11111.setLabelString("Event name: ");
        this.deviceField11111.setIdentifier("");
        this.deviceField11112.setOffsetNid(34);
        this.deviceField11112.setLabelString("Time: ");
        this.deviceField11112.setNumCols(15);
        this.deviceField11112.setIdentifier("");
        this.deviceField11113.setIdentifier("");
        this.deviceField11113.setNumCols(4);
        this.deviceField11113.setLabelString("Event code");
        this.deviceField11113.setOffsetNid(28);
        this.deviceChoice17.setIdentifier("25");
        this.deviceChoice17.setUpdateIdentifier("");
        this.deviceChoice17.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice17.setLabelString("Termination: ");
        this.deviceChoice17.setOffsetNid(30);
        this.deviceChoice17.setChoiceFloatValues(null);
        this.deviceChoice17.setChoiceIntValues(null);
        this.deviceChannel14.setLabelString("Ch 5: ");
        this.deviceChannel14.setOffsetNid(26);
        this.deviceChannel14.setBorderVisible(true);
        this.deviceChannel14.setInSameLine(true);
        this.deviceChannel14.setUpdateIdentifier("");
        this.deviceChannel14.setShowVal("");
        this.deviceField11114.setOffsetNid(27);
        this.deviceField11114.setTextOnly(true);
        this.deviceField11114.setLabelString("Event name: ");
        this.deviceField11114.setNumCols(10);
        this.deviceField11114.setIdentifier("");
        this.deviceField11115.setOffsetNid(29);
        this.deviceField11115.setLabelString("Time: ");
        this.deviceField11115.setNumCols(15);
        this.deviceField11115.setIdentifier("");
        this.deviceField11116.setIdentifier("");
        this.deviceField11116.setNumCols(4);
        this.deviceField11116.setLabelString("Event code");
        this.deviceField11116.setOffsetNid(23);
        this.deviceChoice18.setIdentifier("");
        this.deviceChoice18.setUpdateIdentifier("");
        this.deviceChoice18.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice18.setLabelString("Termination: ");
        this.deviceChoice18.setOffsetNid(25);
        this.deviceChoice18.setChoiceFloatValues(null);
        this.deviceChoice18.setChoiceIntValues(null);
        this.deviceChannel15.setLabelString("Ch 4: ");
        this.deviceChannel15.setOffsetNid(21);
        this.deviceChannel15.setBorderVisible(true);
        this.deviceChannel15.setInSameLine(true);
        this.deviceChannel15.setUpdateIdentifier("");
        this.deviceChannel15.setShowVal("");
        this.deviceField11117.setOffsetNid(22);
        this.deviceField11117.setTextOnly(true);
        this.deviceField11117.setLabelString("Event name: ");
        this.deviceField11117.setIdentifier("");
        this.deviceField11118.setOffsetNid(24);
        this.deviceField11118.setLabelString("Time: ");
        this.deviceField11118.setNumCols(15);
        this.deviceField11118.setIdentifier("");
        this.deviceField11119.setIdentifier("");
        this.deviceField11119.setNumCols(4);
        this.deviceField11119.setLabelString("Event code");
        this.deviceField11119.setOffsetNid(18);
        this.deviceChoice19.setIdentifier("");
        this.deviceChoice19.setUpdateIdentifier("");
        this.deviceChoice19.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice19.setLabelString("Termination: ");
        this.deviceChoice19.setOffsetNid(20);
        this.deviceChoice19.setChoiceFloatValues(null);
        this.deviceChoice19.setChoiceIntValues(null);
        this.deviceChannel16.setLabelString("Ch 3: ");
        this.deviceChannel16.setOffsetNid(16);
        this.deviceChannel16.setBorderVisible(true);
        this.deviceChannel16.setInSameLine(true);
        this.deviceChannel16.setUpdateIdentifier("");
        this.deviceChannel16.setShowVal("");
        this.deviceField111110.setOffsetNid(17);
        this.deviceField111110.setTextOnly(true);
        this.deviceField111110.setLabelString("Event name: ");
        this.deviceField111110.setIdentifier("");
        this.deviceField111111.setOffsetNid(19);
        this.deviceField111111.setLabelString("Time: ");
        this.deviceField111111.setNumCols(15);
        this.deviceField111111.setIdentifier("");
        this.deviceField111112.setIdentifier("");
        this.deviceField111112.setNumCols(4);
        this.deviceField111112.setLabelString("Event code");
        this.deviceField111112.setOffsetNid(13);
        this.deviceChoice110.setIdentifier("");
        this.deviceChoice110.setUpdateIdentifier("");
        this.deviceChoice110.setChoiceItems(new String[]{"ON", "OFF"});
        this.deviceChoice110.setLabelString("Termination: ");
        this.deviceChoice110.setOffsetNid(15);
        this.deviceChoice110.setChoiceFloatValues(null);
        this.deviceChoice110.setChoiceIntValues(null);
        this.deviceChannel17.setLabelString("Ch 2: ");
        this.deviceChannel17.setOffsetNid(11);
        this.deviceChannel17.setBorderVisible(true);
        this.deviceChannel17.setInSameLine(true);
        this.deviceChannel17.setUpdateIdentifier("");
        this.deviceChannel17.setShowVal("");
        this.deviceField111113.setOffsetNid(12);
        this.deviceField111113.setTextOnly(true);
        this.deviceField111113.setLabelString("Event name: ");
        this.deviceField111113.setIdentifier("");
        this.deviceField111114.setOffsetNid(14);
        this.deviceField111114.setLabelString("Time: ");
        this.deviceField111114.setNumCols(15);
        this.deviceField111114.setIdentifier("");
        this.getContentPane().add(this.deviceButtons1, BorderLayout.SOUTH);
        this.getContentPane().add(this.jPanel1, BorderLayout.NORTH);
        this.jPanel1.add(this.jPanel3, null);
        this.jPanel3.add(this.deviceField1, null);
        this.jPanel3.add(this.deviceDispatch1, null);
        this.jPanel1.add(this.jPanel4, null);
        this.jPanel4.add(this.deviceField3, null);
        this.jPanel4.add(this.deviceChoice3, null);
        this.jPanel4.add(this.deviceField2, null);
        this.jPanel4.add(this.deviceChoice2, null);
        this.getContentPane().add(this.jPanel2, BorderLayout.CENTER);
        this.jPanel2.add(this.jScrollPane1, BorderLayout.CENTER);
        this.jScrollPane1.getViewport().add(this.jPanel5, null);
        this.jPanel5.add(this.deviceChannel1, null);
        this.deviceChannel1.add(this.jPanel6, BorderLayout.CENTER);
        this.jPanel6.add(this.deviceField6, null);
        this.jPanel6.add(this.deviceField5, null);
        this.jPanel6.add(this.deviceField4, null);
        this.jPanel6.add(this.deviceChoice4, null);
        this.jPanel5.add(this.deviceChannel17, null);
        this.deviceChannel17.add(this.jPanel112, BorderLayout.CENTER);
        this.jPanel112.add(this.deviceField111113, null);
        this.jPanel112.add(this.deviceField111112, null);
        this.jPanel112.add(this.deviceField111114, null);
        this.jPanel112.add(this.deviceChoice110, null);
        this.jPanel5.add(this.deviceChannel16, null);
        this.deviceChannel16.add(this.jPanel111, BorderLayout.CENTER);
        this.jPanel111.add(this.deviceField111110, null);
        this.jPanel111.add(this.deviceField11119, null);
        this.jPanel111.add(this.deviceField111111, null);
        this.jPanel111.add(this.deviceChoice19, null);
        this.jPanel5.add(this.deviceChannel15, null);
        this.deviceChannel15.add(this.jPanel110, BorderLayout.CENTER);
        this.jPanel110.add(this.deviceField11117, null);
        this.jPanel110.add(this.deviceField11116, null);
        this.jPanel110.add(this.deviceField11118, null);
        this.jPanel110.add(this.deviceChoice18, null);
        this.jPanel5.add(this.deviceChannel14, null);
        this.deviceChannel14.add(this.jPanel19, BorderLayout.CENTER);
        this.jPanel19.add(this.deviceField11114, null);
        this.jPanel19.add(this.deviceField11113, null);
        this.jPanel19.add(this.deviceField11115, null);
        this.jPanel19.add(this.deviceChoice17, null);
        this.jPanel5.add(this.deviceChannel13, null);
        this.deviceChannel13.add(this.jPanel18, BorderLayout.CENTER);
        this.jPanel18.add(this.deviceField11111, null);
        this.jPanel18.add(this.deviceField11110, null);
        this.jPanel18.add(this.deviceField11112, null);
        this.jPanel18.add(this.deviceChoice16, null);
        this.jPanel5.add(this.deviceChannel12, null);
        this.deviceChannel12.add(this.jPanel17, BorderLayout.CENTER);
        this.jPanel17.add(this.deviceField1118, null);
        this.jPanel17.add(this.deviceField1117, null);
        this.jPanel17.add(this.deviceField1119, null);
        this.jPanel17.add(this.deviceChoice15, null);
        this.jPanel5.add(this.deviceChannel11, null);
        this.deviceChannel11.add(this.jPanel16, BorderLayout.CENTER);
        this.jPanel16.add(this.deviceField1115, null);
        this.jPanel16.add(this.deviceField1114, null);
        this.jPanel16.add(this.deviceField1116, null);
        this.jPanel16.add(this.deviceChoice14, null);
        this.jPanel5.add(this.deviceChannel10, null);
        this.deviceChannel10.add(this.jPanel15, BorderLayout.CENTER);
        this.jPanel15.add(this.deviceField1112, null);
        this.jPanel15.add(this.deviceField1111, null);
        this.jPanel15.add(this.deviceField1113, null);
        this.jPanel15.add(this.deviceChoice13, null);
        this.jPanel5.add(this.deviceChannel9, null);
        this.deviceChannel9.add(this.jPanel14, BorderLayout.CENTER);
        this.jPanel14.add(this.deviceField119, null);
        this.jPanel14.add(this.deviceField118, null);
        this.jPanel14.add(this.deviceField1110, null);
        this.jPanel14.add(this.deviceChoice12, null);
        this.jPanel5.add(this.deviceChannel8, null);
        this.deviceChannel8.add(this.jPanel13, BorderLayout.CENTER);
        this.jPanel13.add(this.deviceField116, null);
        this.jPanel13.add(this.deviceField115, null);
        this.jPanel13.add(this.deviceField117, null);
        this.jPanel13.add(this.deviceChoice11, null);
        this.jPanel5.add(this.deviceChannel7, null);
        this.deviceChannel7.add(this.jPanel12, BorderLayout.CENTER);
        this.jPanel12.add(this.deviceField113, null);
        this.jPanel12.add(this.deviceField112, null);
        this.jPanel12.add(this.deviceField114, null);
        this.jPanel12.add(this.deviceChoice10, null);
        this.jPanel5.add(this.deviceChannel6, null);
        this.deviceChannel6.add(this.jPanel11, BorderLayout.CENTER);
        this.jPanel11.add(this.deviceField110, null);
        this.jPanel11.add(this.deviceField19, null);
        this.jPanel11.add(this.deviceField111, null);
        this.jPanel11.add(this.deviceChoice9, null);
        this.jPanel5.add(this.deviceChannel5, null);
        this.deviceChannel5.add(this.jPanel10, BorderLayout.CENTER);
        this.jPanel10.add(this.deviceField17, null);
        this.jPanel10.add(this.deviceField16, null);
        this.jPanel10.add(this.deviceField18, null);
        this.jPanel10.add(this.deviceChoice8, null);
        this.jPanel5.add(this.deviceChannel4, null);
        this.deviceChannel4.add(this.jPanel9, BorderLayout.CENTER);
        this.jPanel9.add(this.deviceField14, null);
        this.jPanel9.add(this.deviceField13, null);
        this.jPanel9.add(this.deviceField15, null);
        this.jPanel9.add(this.deviceChoice7, null);
        this.jPanel5.add(this.deviceChannel3, null);
        this.deviceChannel3.add(this.jPanel8, BorderLayout.CENTER);
        this.jPanel8.add(this.deviceField11, null);
        this.jPanel8.add(this.deviceField10, null);
        this.jPanel8.add(this.deviceField12, null);
        this.jPanel8.add(this.deviceChoice6, null);
        this.jPanel5.add(this.deviceChannel2, null);
        this.deviceChannel2.add(this.jPanel7, BorderLayout.CENTER);
        this.jPanel7.add(this.deviceField8, null);
        this.jPanel7.add(this.deviceField7, null);
        this.jPanel7.add(this.deviceField9, null);
    }
}