import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import devicebeans.DeviceButtons;
import devicebeans.DeviceChannel;
import devicebeans.DeviceChoice;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceLabel;
import devicebeans.DeviceSetup;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 *
 * @author not attributable
 * @version 1.0
 */
public class ISIS_GAINSetup extends DeviceSetup{
    /**
     * 
     */
    private static final long serialVersionUID = -6814219083501320972L;
    BorderLayout   borderLayout1       = new BorderLayout();
    BorderLayout   borderLayout2       = new BorderLayout();
    DeviceButtons  deviceButtons1      = new DeviceButtons();
    DeviceChannel  deviceChannel1      = new DeviceChannel();
    DeviceChannel  deviceChannel10     = new DeviceChannel();
    DeviceChannel  deviceChannel11     = new DeviceChannel();
    DeviceChannel  deviceChannel12     = new DeviceChannel();
    DeviceChannel  deviceChannel13     = new DeviceChannel();
    DeviceChannel  deviceChannel14     = new DeviceChannel();
    DeviceChannel  deviceChannel15     = new DeviceChannel();
    DeviceChannel  deviceChannel16     = new DeviceChannel();
    DeviceChannel  deviceChannel17     = new DeviceChannel();
    DeviceChannel  deviceChannel18     = new DeviceChannel();
    DeviceChannel  deviceChannel2      = new DeviceChannel();
    DeviceChannel  deviceChannel3      = new DeviceChannel();
    DeviceChannel  deviceChannel4      = new DeviceChannel();
    DeviceChannel  deviceChannel5      = new DeviceChannel();
    DeviceChannel  deviceChannel6      = new DeviceChannel();
    DeviceChannel  deviceChannel7      = new DeviceChannel();
    DeviceChannel  deviceChannel8      = new DeviceChannel();
    DeviceChannel  deviceChannel9      = new DeviceChannel();
    DeviceChoice   deviceChoice1       = new DeviceChoice();
    DeviceChoice   deviceChoice10      = new DeviceChoice();
    DeviceChoice   deviceChoice11      = new DeviceChoice();
    DeviceChoice   deviceChoice110     = new DeviceChoice();
    DeviceChoice   deviceChoice111     = new DeviceChoice();
    DeviceChoice   deviceChoice1110    = new DeviceChoice();
    DeviceChoice   deviceChoice1111    = new DeviceChoice();
    DeviceChoice   deviceChoice1112    = new DeviceChoice();
    DeviceChoice   deviceChoice1113    = new DeviceChoice();
    DeviceChoice   deviceChoice1114    = new DeviceChoice();
    DeviceChoice   deviceChoice1115    = new DeviceChoice();
    DeviceChoice   deviceChoice1116    = new DeviceChoice();
    DeviceChoice   deviceChoice112     = new DeviceChoice();
    DeviceChoice   deviceChoice113     = new DeviceChoice();
    DeviceChoice   deviceChoice114     = new DeviceChoice();
    DeviceChoice   deviceChoice115     = new DeviceChoice();
    DeviceChoice   deviceChoice116     = new DeviceChoice();
    DeviceChoice   deviceChoice117     = new DeviceChoice();
    DeviceChoice   deviceChoice118     = new DeviceChoice();
    DeviceChoice   deviceChoice119     = new DeviceChoice();
    DeviceChoice   deviceChoice12      = new DeviceChoice();
    DeviceChoice   deviceChoice13      = new DeviceChoice();
    DeviceChoice   deviceChoice14      = new DeviceChoice();
    DeviceChoice   deviceChoice15      = new DeviceChoice();
    DeviceChoice   deviceChoice16      = new DeviceChoice();
    DeviceChoice   deviceChoice17      = new DeviceChoice();
    DeviceChoice   deviceChoice18      = new DeviceChoice();
    DeviceChoice   deviceChoice19      = new DeviceChoice();
    DeviceChoice   deviceChoice2       = new DeviceChoice();
    DeviceChoice   deviceChoice3       = new DeviceChoice();
    DeviceChoice   deviceChoice4       = new DeviceChoice();
    DeviceChoice   deviceChoice5       = new DeviceChoice();
    DeviceChoice   deviceChoice6       = new DeviceChoice();
    DeviceChoice   deviceChoice7       = new DeviceChoice();
    DeviceChoice   deviceChoice8       = new DeviceChoice();
    DeviceChoice   deviceChoice9       = new DeviceChoice();
    DeviceDispatch deviceDispatch1     = new DeviceDispatch();
    DeviceField    deviceField1        = new DeviceField();
    DeviceField    deviceField11       = new DeviceField();
    DeviceField    deviceField110      = new DeviceField();
    DeviceField    deviceField1111     = new DeviceField();
    DeviceField    deviceField11110    = new DeviceField();
    DeviceField    deviceField111111   = new DeviceField();
    DeviceField    deviceField1111110  = new DeviceField();
    DeviceField    deviceField11111111 = new DeviceField();
    DeviceField    deviceField11111112 = new DeviceField();
    DeviceField    deviceField1111113  = new DeviceField();
    DeviceField    deviceField1111114  = new DeviceField();
    DeviceField    deviceField1111117  = new DeviceField();
    DeviceField    deviceField1111118  = new DeviceField();
    DeviceField    deviceField111112   = new DeviceField();
    DeviceField    deviceField111115   = new DeviceField();
    DeviceField    deviceField111116   = new DeviceField();
    DeviceField    deviceField111119   = new DeviceField();
    DeviceField    deviceField11113    = new DeviceField();
    DeviceField    deviceField11114    = new DeviceField();
    DeviceField    deviceField11117    = new DeviceField();
    DeviceField    deviceField11118    = new DeviceField();
    DeviceField    deviceField1112     = new DeviceField();
    DeviceField    deviceField1115     = new DeviceField();
    DeviceField    deviceField1116     = new DeviceField();
    DeviceField    deviceField1119     = new DeviceField();
    DeviceField    deviceField113      = new DeviceField();
    DeviceField    deviceField114      = new DeviceField();
    DeviceField    deviceField117      = new DeviceField();
    DeviceField    deviceField118      = new DeviceField();
    DeviceField    deviceField12       = new DeviceField();
    DeviceField    deviceField15       = new DeviceField();
    DeviceField    deviceField16       = new DeviceField();
    DeviceField    deviceField19       = new DeviceField();
    DeviceField    deviceField2        = new DeviceField();
    DeviceField    deviceField3        = new DeviceField();
    DeviceField    deviceField5        = new DeviceField();
    DeviceField    deviceField7        = new DeviceField();
    DeviceField    deviceField8        = new DeviceField();
    DeviceLabel    deviceLabel1        = new DeviceLabel();
    DeviceLabel    deviceLabel10       = new DeviceLabel();
    DeviceLabel    deviceLabel11       = new DeviceLabel();
    DeviceLabel    deviceLabel12       = new DeviceLabel();
    DeviceLabel    deviceLabel13       = new DeviceLabel();
    DeviceLabel    deviceLabel14       = new DeviceLabel();
    DeviceLabel    deviceLabel15       = new DeviceLabel();
    DeviceLabel    deviceLabel16       = new DeviceLabel();
    DeviceLabel    deviceLabel17       = new DeviceLabel();
    DeviceLabel    deviceLabel18       = new DeviceLabel();
    DeviceLabel    deviceLabel19       = new DeviceLabel();
    DeviceLabel    deviceLabel2        = new DeviceLabel();
    DeviceLabel    deviceLabel20       = new DeviceLabel();
    DeviceLabel    deviceLabel21       = new DeviceLabel();
    DeviceLabel    deviceLabel22       = new DeviceLabel();
    DeviceLabel    deviceLabel23       = new DeviceLabel();
    DeviceLabel    deviceLabel24       = new DeviceLabel();
    DeviceLabel    deviceLabel25       = new DeviceLabel();
    DeviceLabel    deviceLabel26       = new DeviceLabel();
    DeviceLabel    deviceLabel27       = new DeviceLabel();
    DeviceLabel    deviceLabel28       = new DeviceLabel();
    DeviceLabel    deviceLabel29       = new DeviceLabel();
    DeviceLabel    deviceLabel3        = new DeviceLabel();
    DeviceLabel    deviceLabel30       = new DeviceLabel();
    DeviceLabel    deviceLabel31       = new DeviceLabel();
    DeviceLabel    deviceLabel32       = new DeviceLabel();
    DeviceLabel    deviceLabel33       = new DeviceLabel();
    DeviceLabel    deviceLabel34       = new DeviceLabel();
    DeviceLabel    deviceLabel35       = new DeviceLabel();
    DeviceLabel    deviceLabel36       = new DeviceLabel();
    DeviceLabel    deviceLabel4        = new DeviceLabel();
    DeviceLabel    deviceLabel5        = new DeviceLabel();
    DeviceLabel    deviceLabel6        = new DeviceLabel();
    DeviceLabel    deviceLabel7        = new DeviceLabel();
    DeviceLabel    deviceLabel8        = new DeviceLabel();
    DeviceLabel    deviceLabel9        = new DeviceLabel();
    FlowLayout     flowLayout1         = new FlowLayout();
    FlowLayout     flowLayout10        = new FlowLayout();
    FlowLayout     flowLayout11        = new FlowLayout();
    FlowLayout     flowLayout110       = new FlowLayout();
    FlowLayout     flowLayout111       = new FlowLayout();
    FlowLayout     flowLayout1110      = new FlowLayout();
    FlowLayout     flowLayout1111      = new FlowLayout();
    FlowLayout     flowLayout1112      = new FlowLayout();
    FlowLayout     flowLayout1113      = new FlowLayout();
    FlowLayout     flowLayout1114      = new FlowLayout();
    FlowLayout     flowLayout1115      = new FlowLayout();
    FlowLayout     flowLayout1116      = new FlowLayout();
    FlowLayout     flowLayout1117      = new FlowLayout();
    FlowLayout     flowLayout1118      = new FlowLayout();
    FlowLayout     flowLayout112       = new FlowLayout();
    FlowLayout     flowLayout113       = new FlowLayout();
    FlowLayout     flowLayout114       = new FlowLayout();
    FlowLayout     flowLayout115       = new FlowLayout();
    FlowLayout     flowLayout116       = new FlowLayout();
    FlowLayout     flowLayout117       = new FlowLayout();
    FlowLayout     flowLayout118       = new FlowLayout();
    FlowLayout     flowLayout119       = new FlowLayout();
    FlowLayout     flowLayout12        = new FlowLayout();
    FlowLayout     flowLayout13        = new FlowLayout();
    FlowLayout     flowLayout14        = new FlowLayout();
    FlowLayout     flowLayout15        = new FlowLayout();
    FlowLayout     flowLayout16        = new FlowLayout();
    FlowLayout     flowLayout17        = new FlowLayout();
    FlowLayout     flowLayout18        = new FlowLayout();
    FlowLayout     flowLayout19        = new FlowLayout();
    FlowLayout     flowLayout2         = new FlowLayout();
    FlowLayout     flowLayout21        = new FlowLayout();
    FlowLayout     flowLayout3         = new FlowLayout();
    FlowLayout     flowLayout4         = new FlowLayout();
    FlowLayout     flowLayout5         = new FlowLayout();
    FlowLayout     flowLayout6         = new FlowLayout();
    FlowLayout     flowLayout7         = new FlowLayout();
    FlowLayout     flowLayout8         = new FlowLayout();
    FlowLayout     flowLayout9         = new FlowLayout();
    GridLayout     gridLayout1         = new GridLayout();
    GridLayout     gridLayout2         = new GridLayout();
    JLabel         jLabel1             = new JLabel();
    JLabel         jLabel2             = new JLabel();
    JLabel         jLabel3             = new JLabel();
    JLabel         jLabel4             = new JLabel();
    JLabel         jLabel5             = new JLabel();
    JLabel         jLabel6             = new JLabel();
    JLabel         jLabel7             = new JLabel();
    JPanel         jPanel1             = new JPanel();
    JPanel         jPanel10            = new JPanel();
    JPanel         jPanel11            = new JPanel();
    JPanel         jPanel110           = new JPanel();
    JPanel         jPanel111           = new JPanel();
    JPanel         jPanel112           = new JPanel();
    JPanel         jPanel12            = new JPanel();
    JPanel         jPanel13            = new JPanel();
    JPanel         jPanel14            = new JPanel();
    JPanel         jPanel15            = new JPanel();
    JPanel         jPanel16            = new JPanel();
    JPanel         jPanel17            = new JPanel();
    JPanel         jPanel18            = new JPanel();
    JPanel         jPanel19            = new JPanel();
    JPanel         jPanel2             = new JPanel();
    JPanel         jPanel20            = new JPanel();
    JPanel         jPanel21            = new JPanel();
    JPanel         jPanel3             = new JPanel();
    JPanel         jPanel4             = new JPanel();
    JPanel         jPanel5             = new JPanel();
    JPanel         jPanel6             = new JPanel();
    JPanel         jPanel7             = new JPanel();
    JPanel         jPanel8             = new JPanel();
    JPanel         jPanel9             = new JPanel();
    JScrollPane    jScrollPane1        = new JScrollPane();

    public ISIS_GAINSetup(){
        try{
            this.jbInit();
        }catch(final Exception e){
            e.printStackTrace();
        }
    }

    private void jbInit() throws Exception {
        this.setWidth(800);
        this.setHeight(600);
        this.setDeviceType("ISIS_GAIN");
        this.setDeviceProvider("150.178.3.33");
        this.setDeviceTitle("ISIS Front End Gains");
        this.getContentPane().setLayout(this.borderLayout1);
        this.jPanel1.setLayout(this.gridLayout1);
        this.gridLayout1.setRows(3);
        this.deviceField1.setOffsetNid(1);
        this.deviceField1.setLabelString("Comment: ");
        this.deviceField1.setNumCols(30);
        this.deviceField1.setIdentifier("");
        this.jPanel2.setLayout(this.flowLayout1);
        this.flowLayout1.setAlignment(FlowLayout.LEFT);
        this.deviceField2.setOffsetNid(2);
        this.deviceField2.setLabelString("IP address: ");
        this.deviceField2.setNumCols(20);
        this.deviceField2.setIdentifier("");
        this.jPanel3.setLayout(this.flowLayout2);
        this.flowLayout2.setAlignment(FlowLayout.LEFT);
        this.jPanel4.setLayout(this.gridLayout2);
        this.gridLayout2.setRows(18);
        this.gridLayout2.setVgap(0);
        this.deviceChannel1.setLayout(this.flowLayout3);
        this.deviceChannel1.setLabelString("01");
        this.deviceChannel1.setOffsetNid(4);
        this.deviceChannel1.setInSameLine(true);
        this.deviceChannel1.setUpdateIdentifier("");
        this.deviceChannel1.setShowVal("");
        this.jPanel5.setLayout(this.flowLayout4);
        this.deviceChoice2.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice2.setChoiceFloatValues(null);
        this.deviceChoice2.setOffsetNid(7);
        this.deviceChoice2.setLabelString(" ");
        this.deviceChoice2.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice2.setUpdateIdentifier("");
        this.deviceChoice2.setIdentifier("");
        this.deviceChoice1.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice1.setChoiceFloatValues(null);
        this.deviceChoice1.setOffsetNid(12);
        this.deviceChoice1.setLabelString(" ");
        this.deviceChoice1.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice1.setUpdateIdentifier("");
        this.deviceChoice1.setIdentifier("");
        this.deviceField5.setOffsetNid(6);
        this.deviceField5.setIdentifier("");
        this.deviceField3.setOffsetNid(11);
        this.deviceField3.setIdentifier("");
        this.deviceField7.setIdentifier("");
        this.deviceField7.setOffsetNid(193);
        this.deviceField8.setIdentifier("");
        this.deviceField8.setOffsetNid(198);
        this.deviceChoice3.setIdentifier("");
        this.deviceChoice3.setUpdateIdentifier("");
        this.deviceChoice3.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice3.setLabelString("");
        this.deviceChoice3.setOffsetNid(194);
        this.deviceChoice3.setChoiceFloatValues(null);
        this.deviceChoice3.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel2.setShowVal("");
        this.deviceChannel2.setUpdateIdentifier("");
        this.deviceChannel2.setInSameLine(true);
        this.deviceChannel2.setOffsetNid(191);
        this.deviceChannel2.setLabelString("18");
        this.deviceChannel2.setLayout(this.flowLayout5);
        this.jPanel6.setLayout(this.flowLayout6);
        this.deviceChoice4.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice4.setChoiceFloatValues(null);
        this.deviceChoice4.setOffsetNid(199);
        this.deviceChoice4.setLabelString(" ");
        this.deviceChoice4.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice4.setUpdateIdentifier("");
        this.deviceChoice4.setIdentifier("");
        this.deviceField11.setIdentifier("");
        this.deviceField11.setOffsetNid(182);
        this.deviceField12.setIdentifier("");
        this.deviceField12.setOffsetNid(187);
        this.deviceChoice5.setIdentifier("");
        this.deviceChoice5.setUpdateIdentifier("");
        this.deviceChoice5.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice5.setLabelString(" ");
        this.deviceChoice5.setOffsetNid(183);
        this.deviceChoice5.setChoiceFloatValues(null);
        this.deviceChoice5.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel3.setShowVal("");
        this.deviceChannel3.setUpdateIdentifier("");
        this.deviceChannel3.setInSameLine(true);
        this.deviceChannel3.setOffsetNid(180);
        this.deviceChannel3.setLabelString("17");
        this.deviceChannel3.setLayout(this.flowLayout7);
        this.jPanel7.setLayout(this.flowLayout8);
        this.deviceChoice6.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice6.setChoiceFloatValues(null);
        this.deviceChoice6.setOffsetNid(188);
        this.deviceChoice6.setLabelString(" ");
        this.deviceChoice6.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice6.setUpdateIdentifier("");
        this.deviceChoice6.setIdentifier("");
        this.deviceField15.setIdentifier("");
        this.deviceField15.setOffsetNid(171);
        this.deviceField16.setIdentifier("");
        this.deviceField16.setOffsetNid(176);
        this.deviceChoice7.setIdentifier("");
        this.deviceChoice7.setUpdateIdentifier("");
        this.deviceChoice7.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice7.setLabelString(" ");
        this.deviceChoice7.setOffsetNid(172);
        this.deviceChoice7.setChoiceFloatValues(null);
        this.deviceChoice7.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel4.setShowVal("");
        this.deviceChannel4.setUpdateIdentifier("");
        this.deviceChannel4.setInSameLine(true);
        this.deviceChannel4.setOffsetNid(169);
        this.deviceChannel4.setLabelString("16");
        this.deviceChannel4.setLayout(this.flowLayout9);
        this.jPanel8.setLayout(this.flowLayout10);
        this.deviceChoice8.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice8.setChoiceFloatValues(null);
        this.deviceChoice8.setOffsetNid(177);
        this.deviceChoice8.setLabelString(" ");
        this.deviceChoice8.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice8.setUpdateIdentifier("");
        this.deviceChoice8.setIdentifier("");
        this.deviceField19.setIdentifier("");
        this.deviceField19.setOffsetNid(160);
        this.deviceField110.setIdentifier("");
        this.deviceField110.setOffsetNid(165);
        this.deviceChoice9.setIdentifier("");
        this.deviceChoice9.setUpdateIdentifier("");
        this.deviceChoice9.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice9.setLabelString(" ");
        this.deviceChoice9.setOffsetNid(161);
        this.deviceChoice9.setChoiceFloatValues(null);
        this.deviceChoice9.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel5.setShowVal("");
        this.deviceChannel5.setUpdateIdentifier("");
        this.deviceChannel5.setInSameLine(true);
        this.deviceChannel5.setOffsetNid(158);
        this.deviceChannel5.setLabelString("15");
        this.deviceChannel5.setLayout(this.flowLayout11);
        this.jPanel9.setLayout(this.flowLayout12);
        this.deviceChoice10.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice10.setChoiceFloatValues(null);
        this.deviceChoice10.setOffsetNid(166);
        this.deviceChoice10.setLabelString(" ");
        this.deviceChoice10.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice10.setUpdateIdentifier("");
        this.deviceChoice10.setIdentifier("");
        this.deviceField113.setIdentifier("");
        this.deviceField113.setOffsetNid(149);
        this.deviceField114.setIdentifier("");
        this.deviceField114.setOffsetNid(154);
        this.deviceChoice11.setIdentifier("");
        this.deviceChoice11.setUpdateIdentifier("");
        this.deviceChoice11.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice11.setLabelString(" ");
        this.deviceChoice11.setOffsetNid(150);
        this.deviceChoice11.setChoiceFloatValues(null);
        this.deviceChoice11.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel6.setShowVal("");
        this.deviceChannel6.setUpdateIdentifier("");
        this.deviceChannel6.setInSameLine(true);
        this.deviceChannel6.setOffsetNid(147);
        this.deviceChannel6.setLabelString("14");
        this.deviceChannel6.setLayout(this.flowLayout13);
        this.jPanel10.setLayout(this.flowLayout14);
        this.deviceChoice12.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice12.setChoiceFloatValues(null);
        this.deviceChoice12.setOffsetNid(155);
        this.deviceChoice12.setLabelString(" ");
        this.deviceChoice12.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice12.setUpdateIdentifier("");
        this.deviceChoice12.setIdentifier("");
        this.deviceField117.setIdentifier("");
        this.deviceField117.setOffsetNid(138);
        this.deviceField118.setIdentifier("");
        this.deviceField118.setOffsetNid(143);
        this.deviceChoice13.setIdentifier("");
        this.deviceChoice13.setUpdateIdentifier("");
        this.deviceChoice13.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice13.setLabelString(" ");
        this.deviceChoice13.setOffsetNid(139);
        this.deviceChoice13.setChoiceFloatValues(null);
        this.deviceChoice13.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel7.setShowVal("");
        this.deviceChannel7.setUpdateIdentifier("");
        this.deviceChannel7.setInSameLine(true);
        this.deviceChannel7.setOffsetNid(136);
        this.deviceChannel7.setLabelString("13");
        this.deviceChannel7.setLayout(this.flowLayout15);
        this.jPanel11.setLayout(this.flowLayout16);
        this.deviceChoice14.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice14.setChoiceFloatValues(null);
        this.deviceChoice14.setOffsetNid(144);
        this.deviceChoice14.setLabelString("");
        this.deviceChoice14.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice14.setUpdateIdentifier("");
        this.deviceChoice14.setIdentifier("");
        this.deviceField1111.setIdentifier("");
        this.deviceField1111.setOffsetNid(127);
        this.deviceField1112.setIdentifier("");
        this.deviceField1112.setOffsetNid(132);
        this.deviceChoice15.setIdentifier("");
        this.deviceChoice15.setUpdateIdentifier("");
        this.deviceChoice15.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice15.setLabelString(" ");
        this.deviceChoice15.setOffsetNid(128);
        this.deviceChoice15.setChoiceFloatValues(null);
        this.deviceChoice15.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel8.setShowVal("");
        this.deviceChannel8.setUpdateIdentifier("");
        this.deviceChannel8.setInSameLine(true);
        this.deviceChannel8.setOffsetNid(125);
        this.deviceChannel8.setLabelString("12");
        this.deviceChannel8.setLayout(this.flowLayout17);
        this.jPanel12.setLayout(this.flowLayout18);
        this.deviceChoice16.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice16.setChoiceFloatValues(null);
        this.deviceChoice16.setOffsetNid(133);
        this.deviceChoice16.setLabelString(" ");
        this.deviceChoice16.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice16.setUpdateIdentifier("");
        this.deviceChoice16.setIdentifier("");
        this.deviceField1115.setIdentifier("");
        this.deviceField1115.setOffsetNid(116);
        this.deviceField1116.setIdentifier("");
        this.deviceField1116.setOffsetNid(121);
        this.deviceChoice17.setIdentifier("");
        this.deviceChoice17.setUpdateIdentifier("");
        this.deviceChoice17.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice17.setLabelString(" ");
        this.deviceChoice17.setOffsetNid(117);
        this.deviceChoice17.setChoiceFloatValues(null);
        this.deviceChoice17.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel9.setShowVal("");
        this.deviceChannel9.setUpdateIdentifier("");
        this.deviceChannel9.setInSameLine(true);
        this.deviceChannel9.setOffsetNid(114);
        this.deviceChannel9.setLabelString("11");
        this.deviceChannel9.setLayout(this.flowLayout19);
        this.jPanel13.setLayout(this.flowLayout110);
        this.deviceChoice18.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice18.setChoiceFloatValues(null);
        this.deviceChoice18.setOffsetNid(122);
        this.deviceChoice18.setLabelString(" ");
        this.deviceChoice18.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice18.setUpdateIdentifier("");
        this.deviceChoice18.setIdentifier("");
        this.deviceField1119.setIdentifier("");
        this.deviceField1119.setOffsetNid(105);
        this.deviceField11110.setIdentifier("");
        this.deviceField11110.setOffsetNid(110);
        this.deviceChoice19.setIdentifier("");
        this.deviceChoice19.setUpdateIdentifier("");
        this.deviceChoice19.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice19.setLabelString(" ");
        this.deviceChoice19.setOffsetNid(106);
        this.deviceChoice19.setChoiceFloatValues(null);
        this.deviceChoice19.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel10.setShowVal("");
        this.deviceChannel10.setUpdateIdentifier("");
        this.deviceChannel10.setInSameLine(true);
        this.deviceChannel10.setOffsetNid(103);
        this.deviceChannel10.setLabelString("10");
        this.deviceChannel10.setLayout(this.flowLayout111);
        this.jPanel14.setLayout(this.flowLayout112);
        this.deviceChoice110.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice110.setChoiceFloatValues(null);
        this.deviceChoice110.setOffsetNid(111);
        this.deviceChoice110.setLabelString(" ");
        this.deviceChoice110.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice110.setUpdateIdentifier("");
        this.deviceChoice110.setIdentifier("");
        this.deviceField11113.setIdentifier("");
        this.deviceField11113.setOffsetNid(94);
        this.deviceField11114.setIdentifier("");
        this.deviceField11114.setOffsetNid(99);
        this.deviceChoice111.setIdentifier("");
        this.deviceChoice111.setUpdateIdentifier("");
        this.deviceChoice111.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice111.setLabelString("");
        this.deviceChoice111.setOffsetNid(95);
        this.deviceChoice111.setChoiceFloatValues(null);
        this.deviceChoice111.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel11.setShowVal("");
        this.deviceChannel11.setUpdateIdentifier("");
        this.deviceChannel11.setInSameLine(true);
        this.deviceChannel11.setOffsetNid(92);
        this.deviceChannel11.setLabelString("09");
        this.deviceChannel11.setLayout(this.flowLayout113);
        this.jPanel15.setLayout(this.flowLayout114);
        this.deviceChoice112.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice112.setChoiceFloatValues(null);
        this.deviceChoice112.setOffsetNid(100);
        this.deviceChoice112.setLabelString(" ");
        this.deviceChoice112.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice112.setUpdateIdentifier("");
        this.deviceChoice112.setIdentifier("");
        this.deviceField11117.setIdentifier("");
        this.deviceField11117.setOffsetNid(83);
        this.deviceField11118.setIdentifier("");
        this.deviceField11118.setOffsetNid(88);
        this.deviceChoice113.setIdentifier("");
        this.deviceChoice113.setUpdateIdentifier("");
        this.deviceChoice113.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice113.setLabelString(" ");
        this.deviceChoice113.setOffsetNid(84);
        this.deviceChoice113.setChoiceFloatValues(null);
        this.deviceChoice113.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel12.setShowVal("");
        this.deviceChannel12.setUpdateIdentifier("");
        this.deviceChannel12.setInSameLine(true);
        this.deviceChannel12.setOffsetNid(81);
        this.deviceChannel12.setLabelString("08");
        this.deviceChannel12.setLayout(this.flowLayout115);
        this.jPanel16.setLayout(this.flowLayout116);
        this.deviceChoice114.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice114.setChoiceFloatValues(null);
        this.deviceChoice114.setOffsetNid(89);
        this.deviceChoice114.setLabelString(" ");
        this.deviceChoice114.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice114.setUpdateIdentifier("");
        this.deviceChoice114.setIdentifier("");
        this.deviceField111111.setIdentifier("");
        this.deviceField111111.setOffsetNid(72);
        this.deviceField111112.setIdentifier("");
        this.deviceField111112.setOffsetNid(77);
        this.deviceChoice115.setIdentifier("");
        this.deviceChoice115.setUpdateIdentifier("");
        this.deviceChoice115.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice115.setLabelString(" ");
        this.deviceChoice115.setOffsetNid(73);
        this.deviceChoice115.setChoiceFloatValues(null);
        this.deviceChoice115.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel13.setShowVal("");
        this.deviceChannel13.setUpdateIdentifier("");
        this.deviceChannel13.setInSameLine(true);
        this.deviceChannel13.setOffsetNid(70);
        this.deviceChannel13.setLabelString("07");
        this.deviceChannel13.setLayout(this.flowLayout117);
        this.jPanel17.setLayout(this.flowLayout118);
        this.deviceChoice116.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice116.setChoiceFloatValues(null);
        this.deviceChoice116.setOffsetNid(78);
        this.deviceChoice116.setLabelString(" ");
        this.deviceChoice116.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice116.setUpdateIdentifier("");
        this.deviceChoice116.setIdentifier("");
        this.deviceField111115.setIdentifier("");
        this.deviceField111115.setOffsetNid(61);
        this.deviceField111116.setIdentifier("");
        this.deviceField111116.setOffsetNid(66);
        this.deviceChoice117.setIdentifier("");
        this.deviceChoice117.setUpdateIdentifier("");
        this.deviceChoice117.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice117.setLabelString(" ");
        this.deviceChoice117.setOffsetNid(62);
        this.deviceChoice117.setChoiceFloatValues(null);
        this.deviceChoice117.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel14.setShowVal("");
        this.deviceChannel14.setUpdateIdentifier("");
        this.deviceChannel14.setInSameLine(true);
        this.deviceChannel14.setOffsetNid(59);
        this.deviceChannel14.setLabelString("06");
        this.deviceChannel14.setLayout(this.flowLayout119);
        this.jPanel18.setLayout(this.flowLayout1110);
        this.deviceChoice118.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice118.setChoiceFloatValues(null);
        this.deviceChoice118.setOffsetNid(67);
        this.deviceChoice118.setLabelString(" ");
        this.deviceChoice118.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice118.setUpdateIdentifier("");
        this.deviceChoice118.setIdentifier("");
        this.deviceField111119.setIdentifier("");
        this.deviceField111119.setOffsetNid(50);
        this.deviceField1111110.setIdentifier("");
        this.deviceField1111110.setOffsetNid(55);
        this.deviceChoice119.setIdentifier("");
        this.deviceChoice119.setUpdateIdentifier("");
        this.deviceChoice119.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice119.setLabelString(" ");
        this.deviceChoice119.setOffsetNid(51);
        this.deviceChoice119.setChoiceFloatValues(null);
        this.deviceChoice119.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel15.setShowVal("");
        this.deviceChannel15.setUpdateIdentifier("");
        this.deviceChannel15.setInSameLine(true);
        this.deviceChannel15.setOffsetNid(48);
        this.deviceChannel15.setLabelString("05");
        this.deviceChannel15.setLayout(this.flowLayout1111);
        this.jPanel19.setLayout(this.flowLayout1112);
        this.deviceChoice1110.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice1110.setChoiceFloatValues(null);
        this.deviceChoice1110.setOffsetNid(56);
        this.deviceChoice1110.setLabelString("");
        this.deviceChoice1110.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice1110.setUpdateIdentifier("");
        this.deviceChoice1110.setIdentifier("");
        this.deviceField1111113.setIdentifier("");
        this.deviceField1111113.setOffsetNid(39);
        this.deviceField1111114.setIdentifier("");
        this.deviceField1111114.setOffsetNid(44);
        this.deviceChoice1111.setIdentifier("");
        this.deviceChoice1111.setUpdateIdentifier("");
        this.deviceChoice1111.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice1111.setLabelString(" ");
        this.deviceChoice1111.setOffsetNid(40);
        this.deviceChoice1111.setChoiceFloatValues(null);
        this.deviceChoice1111.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel16.setShowVal("");
        this.deviceChannel16.setUpdateIdentifier("");
        this.deviceChannel16.setInSameLine(true);
        this.deviceChannel16.setOffsetNid(37);
        this.deviceChannel16.setLabelString("04");
        this.deviceChannel16.setLayout(this.flowLayout1113);
        this.jPanel110.setLayout(this.flowLayout1114);
        this.deviceChoice1112.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice1112.setChoiceFloatValues(null);
        this.deviceChoice1112.setOffsetNid(45);
        this.deviceChoice1112.setLabelString(" ");
        this.deviceChoice1112.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice1112.setUpdateIdentifier("");
        this.deviceChoice1112.setIdentifier("");
        this.deviceField1111117.setIdentifier("");
        this.deviceField1111117.setOffsetNid(28);
        this.deviceField1111118.setIdentifier("");
        this.deviceField1111118.setOffsetNid(33);
        this.deviceChoice1113.setIdentifier("");
        this.deviceChoice1113.setUpdateIdentifier("");
        this.deviceChoice1113.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice1113.setLabelString("");
        this.deviceChoice1113.setOffsetNid(29);
        this.deviceChoice1113.setChoiceFloatValues(null);
        this.deviceChoice1113.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel17.setShowVal("");
        this.deviceChannel17.setUpdateIdentifier("");
        this.deviceChannel17.setInSameLine(true);
        this.deviceChannel17.setOffsetNid(26);
        this.deviceChannel17.setLabelString("03");
        this.deviceChannel17.setLayout(this.flowLayout1115);
        this.jPanel111.setLayout(this.flowLayout1116);
        this.deviceChoice1114.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice1114.setChoiceFloatValues(null);
        this.deviceChoice1114.setOffsetNid(34);
        this.deviceChoice1114.setLabelString(" ");
        this.deviceChoice1114.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice1114.setUpdateIdentifier("");
        this.deviceChoice1114.setIdentifier("");
        this.deviceField11111111.setIdentifier("");
        this.deviceField11111111.setOffsetNid(17);
        this.deviceField11111112.setIdentifier("");
        this.deviceField11111112.setOffsetNid(22);
        this.deviceChoice1115.setIdentifier("");
        this.deviceChoice1115.setUpdateIdentifier("");
        this.deviceChoice1115.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice1115.setLabelString(" ");
        this.deviceChoice1115.setOffsetNid(18);
        this.deviceChoice1115.setChoiceFloatValues(null);
        this.deviceChoice1115.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChannel18.setShowVal("");
        this.deviceChannel18.setUpdateIdentifier("");
        this.deviceChannel18.setInSameLine(true);
        this.deviceChannel18.setOffsetNid(15);
        this.deviceChannel18.setLabelString("02");
        this.deviceChannel18.setLayout(this.flowLayout1117);
        this.jPanel112.setLayout(this.flowLayout1118);
        this.deviceChoice1116.setChoiceIntValues(new int[]{1, 2, 5, 10});
        this.deviceChoice1116.setChoiceFloatValues(null);
        this.deviceChoice1116.setOffsetNid(23);
        this.deviceChoice1116.setLabelString(" ");
        this.deviceChoice1116.setChoiceItems(new String[]{"1", "2", "5", "10"});
        this.deviceChoice1116.setUpdateIdentifier("");
        this.deviceChoice1116.setIdentifier("");
        this.jPanel19.setAlignmentY((float)0.5);
        this.deviceButtons1.setMethods(new String[]{"init"});
        this.flowLayout1113.setVgap(0);
        this.flowLayout3.setVgap(5);
        this.flowLayout4.setVgap(5);
        this.flowLayout1117.setVgap(5);
        this.flowLayout1118.setVgap(5);
        this.deviceLabel1.setOffsetNid(5);
        this.deviceLabel1.setLabelString("");
        this.deviceLabel1.setNumCols(15);
        this.deviceLabel1.setIdentifier("");
        this.deviceLabel2.setIdentifier("");
        this.deviceLabel2.setNumCols(15);
        this.deviceLabel2.setLabelString("");
        this.deviceLabel2.setOffsetNid(16);
        this.deviceLabel3.setIdentifier("");
        this.deviceLabel3.setNumCols(15);
        this.deviceLabel3.setLabelString("");
        this.deviceLabel3.setOffsetNid(27);
        this.deviceLabel4.setIdentifier("");
        this.deviceLabel4.setNumCols(15);
        this.deviceLabel4.setLabelString("");
        this.deviceLabel4.setOffsetNid(38);
        this.deviceLabel5.setIdentifier("");
        this.deviceLabel5.setNumCols(15);
        this.deviceLabel5.setLabelString("");
        this.deviceLabel5.setOffsetNid(49);
        this.deviceLabel6.setIdentifier("");
        this.deviceLabel6.setNumCols(15);
        this.deviceLabel6.setLabelString("");
        this.deviceLabel6.setOffsetNid(60);
        this.deviceLabel7.setIdentifier("");
        this.deviceLabel7.setNumCols(15);
        this.deviceLabel7.setLabelString("");
        this.deviceLabel7.setOffsetNid(71);
        this.deviceLabel8.setIdentifier("");
        this.deviceLabel8.setNumCols(15);
        this.deviceLabel8.setLabelString("");
        this.deviceLabel8.setOffsetNid(82);
        this.deviceLabel9.setIdentifier("");
        this.deviceLabel9.setNumCols(15);
        this.deviceLabel9.setLabelString("");
        this.deviceLabel9.setOffsetNid(93);
        this.deviceLabel10.setIdentifier("");
        this.deviceLabel10.setNumCols(15);
        this.deviceLabel10.setLabelString("");
        this.deviceLabel10.setOffsetNid(104);
        this.deviceLabel11.setIdentifier("");
        this.deviceLabel11.setNumCols(15);
        this.deviceLabel11.setLabelString("");
        this.deviceLabel11.setOffsetNid(115);
        this.deviceLabel12.setIdentifier("");
        this.deviceLabel12.setNumCols(15);
        this.deviceLabel12.setLabelString("");
        this.deviceLabel12.setOffsetNid(126);
        this.deviceLabel13.setIdentifier("");
        this.deviceLabel13.setNumCols(15);
        this.deviceLabel13.setLabelString("");
        this.deviceLabel13.setOffsetNid(137);
        this.deviceLabel14.setIdentifier("");
        this.deviceLabel14.setNumCols(15);
        this.deviceLabel14.setLabelString("");
        this.deviceLabel14.setOffsetNid(148);
        this.deviceLabel15.setIdentifier("");
        this.deviceLabel15.setNumCols(15);
        this.deviceLabel15.setLabelString("");
        this.deviceLabel15.setOffsetNid(159);
        this.deviceLabel16.setIdentifier("");
        this.deviceLabel16.setNumCols(15);
        this.deviceLabel16.setLabelString("");
        this.deviceLabel16.setOffsetNid(170);
        this.deviceLabel17.setIdentifier("");
        this.deviceLabel17.setNumCols(15);
        this.deviceLabel17.setLabelString("");
        this.deviceLabel17.setOffsetNid(181);
        this.deviceLabel18.setIdentifier("");
        this.deviceLabel18.setNumCols(15);
        this.deviceLabel18.setLabelString("");
        this.deviceLabel18.setOffsetNid(192);
        this.deviceLabel19.setOffsetNid(10);
        this.deviceLabel19.setNumCols(15);
        this.deviceLabel20.setOffsetNid(21);
        this.deviceLabel20.setNumCols(15);
        this.deviceLabel21.setOffsetNid(32);
        this.deviceLabel21.setNumCols(15);
        this.deviceLabel22.setOffsetNid(43);
        this.deviceLabel22.setNumCols(15);
        this.deviceLabel23.setOffsetNid(54);
        this.deviceLabel23.setNumCols(15);
        this.deviceLabel24.setOffsetNid(65);
        this.deviceLabel24.setNumCols(15);
        this.deviceLabel25.setOffsetNid(76);
        this.deviceLabel25.setNumCols(15);
        this.deviceLabel26.setOffsetNid(87);
        this.deviceLabel26.setNumCols(15);
        this.deviceLabel27.setOffsetNid(98);
        this.deviceLabel27.setNumCols(15);
        this.deviceLabel28.setOffsetNid(109);
        this.deviceLabel28.setNumCols(15);
        this.deviceLabel29.setOffsetNid(120);
        this.deviceLabel29.setNumCols(15);
        this.deviceLabel30.setOffsetNid(131);
        this.deviceLabel30.setNumCols(15);
        this.deviceLabel31.setOffsetNid(142);
        this.deviceLabel31.setNumCols(15);
        this.deviceLabel32.setOffsetNid(153);
        this.deviceLabel32.setNumCols(15);
        this.deviceLabel33.setOffsetNid(164);
        this.deviceLabel33.setNumCols(15);
        this.deviceLabel34.setOffsetNid(175);
        this.deviceLabel34.setNumCols(15);
        this.deviceLabel35.setOffsetNid(186);
        this.deviceLabel35.setNumCols(15);
        this.deviceLabel36.setOffsetNid(197);
        this.deviceLabel36.setNumCols(15);
        /*
            deviceLabel1.setTextOnly(true);
            deviceLabel2.setTextOnly(true);
            deviceLabel3.setTextOnly(true);
            deviceLabel4.setTextOnly(true);
            deviceLabel5.setTextOnly(true);
            deviceLabel6.setTextOnly(true);
            deviceLabel7.setTextOnly(true);
            deviceLabel8.setTextOnly(true);
            deviceLabel9.setTextOnly(true);
            deviceLabel10.setTextOnly(true);
            deviceLabel11.setTextOnly(true);
            deviceLabel12.setTextOnly(true);
            deviceLabel13.setTextOnly(true);
            deviceLabel14.setTextOnly(true);
            deviceLabel15.setTextOnly(true);
            deviceLabel16.setTextOnly(true);
            deviceLabel17.setTextOnly(true);
            deviceLabel18.setTextOnly(true);
            deviceLabel19.setTextOnly(true);
            deviceLabel20.setTextOnly(true);
            deviceLabel21.setTextOnly(true);
            deviceLabel22.setTextOnly(true);
            deviceLabel23.setTextOnly(true);
            deviceLabel24.setTextOnly(true);
            deviceLabel25.setTextOnly(true);
            deviceLabel26.setTextOnly(true);
            deviceLabel27.setTextOnly(true);
            deviceLabel28.setTextOnly(true);
            deviceLabel29.setTextOnly(true);
            deviceLabel30.setTextOnly(true);
            deviceLabel31.setTextOnly(true);
            deviceLabel32.setTextOnly(true);
            deviceLabel33.setTextOnly(true);
            deviceLabel34.setTextOnly(true);
            deviceLabel35.setTextOnly(true);
            deviceLabel36.setTextOnly(true);
        */
        this.jPanel20.setLayout(this.borderLayout2);
        this.jLabel7.setText("CHANNEL");
        this.jLabel4.setText("           NAME");
        this.jLabel2.setText("                        CALIB.");
        this.jLabel6.setMaximumSize(new Dimension(29, 15));
        this.jLabel6.setMinimumSize(new Dimension(29, 15));
        this.jLabel6.setText("                  GAIN");
        this.jLabel1.setText("                NAME");
        this.jLabel3.setText("                          CALIB.");
        this.jLabel5.setText("                   GAIN");
        this.jPanel21.setLayout(this.flowLayout21);
        this.getContentPane().add(this.deviceButtons1, BorderLayout.SOUTH);
        this.getContentPane().add(this.jPanel1, BorderLayout.NORTH);
        this.jPanel1.add(this.jPanel2, null);
        this.jPanel2.add(this.deviceField1, null);
        this.jPanel2.add(this.deviceDispatch1, null);
        this.jPanel1.add(this.jPanel3, null);
        this.jPanel3.add(this.deviceField2, null);
        this.jPanel1.add(this.jPanel20, null);
        this.jPanel21.add(this.jLabel4, null);
        this.jPanel21.add(this.jLabel2, null);
        this.jPanel21.add(this.jLabel6, null);
        this.jPanel21.add(this.jLabel1, null);
        this.jPanel21.add(this.jLabel3, null);
        this.jPanel21.add(this.jLabel5, null);
        this.jPanel20.add(this.jLabel7, BorderLayout.WEST);
        this.jPanel20.add(this.jPanel21, BorderLayout.CENTER);
        this.getContentPane().add(this.jScrollPane1, BorderLayout.CENTER);
        this.jScrollPane1.getViewport().add(this.jPanel4, null);
        this.jPanel4.add(this.deviceChannel1, null);
        this.deviceChannel1.add(this.jPanel5, null);
        this.jPanel5.add(this.deviceLabel1, null);
        this.jPanel5.add(this.deviceField5, null);
        this.jPanel5.add(this.deviceChoice2, null);
        this.jPanel5.add(this.deviceLabel19, null);
        this.jPanel5.add(this.deviceField3, null);
        this.jPanel5.add(this.deviceChoice1, null);
        this.jPanel4.add(this.deviceChannel18, null);
        this.deviceChannel18.add(this.jPanel112, null);
        this.jPanel112.add(this.deviceLabel2, null);
        this.jPanel112.add(this.deviceField11111111, null);
        this.jPanel112.add(this.deviceChoice1115, null);
        this.jPanel112.add(this.deviceLabel20, null);
        this.jPanel112.add(this.deviceField11111112, null);
        this.jPanel112.add(this.deviceChoice1116, null);
        this.jPanel4.add(this.deviceChannel17, null);
        this.deviceChannel17.add(this.jPanel111, null);
        this.jPanel111.add(this.deviceLabel3, null);
        this.jPanel111.add(this.deviceField1111117, null);
        this.jPanel111.add(this.deviceChoice1113, null);
        this.jPanel111.add(this.deviceLabel21, null);
        this.jPanel111.add(this.deviceField1111118, null);
        this.jPanel111.add(this.deviceChoice1114, null);
        this.jPanel4.add(this.deviceChannel16, null);
        this.deviceChannel16.add(this.jPanel110, null);
        this.jPanel110.add(this.deviceLabel4, null);
        this.jPanel110.add(this.deviceField1111113, null);
        this.jPanel110.add(this.deviceChoice1111, null);
        this.jPanel110.add(this.deviceLabel22, null);
        this.jPanel110.add(this.deviceField1111114, null);
        this.jPanel110.add(this.deviceChoice1112, null);
        this.jPanel4.add(this.deviceChannel15, null);
        this.deviceChannel15.add(this.jPanel19, null);
        this.jPanel19.add(this.deviceLabel5, null);
        this.jPanel19.add(this.deviceField111119, null);
        this.jPanel19.add(this.deviceChoice119, null);
        this.jPanel19.add(this.deviceLabel23, null);
        this.jPanel19.add(this.deviceField1111110, null);
        this.jPanel19.add(this.deviceChoice1110, null);
        this.jPanel4.add(this.deviceChannel14, null);
        this.deviceChannel14.add(this.jPanel18, null);
        this.jPanel18.add(this.deviceLabel6, null);
        this.jPanel18.add(this.deviceField111115, null);
        this.jPanel18.add(this.deviceChoice117, null);
        this.jPanel18.add(this.deviceLabel24, null);
        this.jPanel18.add(this.deviceField111116, null);
        this.jPanel18.add(this.deviceChoice118, null);
        this.jPanel4.add(this.deviceChannel13, null);
        this.deviceChannel13.add(this.jPanel17, null);
        this.jPanel17.add(this.deviceLabel7, null);
        this.jPanel17.add(this.deviceField111111, null);
        this.jPanel17.add(this.deviceChoice115, null);
        this.jPanel17.add(this.deviceLabel25, null);
        this.jPanel17.add(this.deviceField111112, null);
        this.jPanel17.add(this.deviceChoice116, null);
        this.jPanel4.add(this.deviceChannel12, null);
        this.deviceChannel12.add(this.jPanel16, null);
        this.jPanel16.add(this.deviceLabel8, null);
        this.jPanel16.add(this.deviceField11117, null);
        this.jPanel16.add(this.deviceChoice113, null);
        this.jPanel16.add(this.deviceLabel26, null);
        this.jPanel16.add(this.deviceField11118, null);
        this.jPanel16.add(this.deviceChoice114, null);
        this.jPanel4.add(this.deviceChannel11, null);
        this.deviceChannel11.add(this.jPanel15, null);
        this.jPanel15.add(this.deviceLabel9, null);
        this.jPanel15.add(this.deviceField11113, null);
        this.jPanel15.add(this.deviceChoice111, null);
        this.jPanel15.add(this.deviceLabel27, null);
        this.jPanel15.add(this.deviceField11114, null);
        this.jPanel15.add(this.deviceChoice112, null);
        this.jPanel4.add(this.deviceChannel10, null);
        this.deviceChannel10.add(this.jPanel14, null);
        this.jPanel14.add(this.deviceLabel10, null);
        this.jPanel14.add(this.deviceField1119, null);
        this.jPanel14.add(this.deviceChoice19, null);
        this.jPanel14.add(this.deviceLabel28, null);
        this.jPanel14.add(this.deviceField11110, null);
        this.jPanel14.add(this.deviceChoice110, null);
        this.jPanel4.add(this.deviceChannel9, null);
        this.deviceChannel9.add(this.jPanel13, null);
        this.jPanel13.add(this.deviceLabel11, null);
        this.jPanel13.add(this.deviceField1115, null);
        this.jPanel13.add(this.deviceChoice17, null);
        this.jPanel13.add(this.deviceLabel29, null);
        this.jPanel13.add(this.deviceField1116, null);
        this.jPanel13.add(this.deviceChoice18, null);
        this.jPanel4.add(this.deviceChannel8, null);
        this.deviceChannel8.add(this.jPanel12, null);
        this.jPanel12.add(this.deviceLabel12, null);
        this.jPanel12.add(this.deviceField1111, null);
        this.jPanel12.add(this.deviceChoice15, null);
        this.jPanel12.add(this.deviceLabel30, null);
        this.jPanel12.add(this.deviceField1112, null);
        this.jPanel12.add(this.deviceChoice16, null);
        this.jPanel4.add(this.deviceChannel7, null);
        this.deviceChannel7.add(this.jPanel11, null);
        this.jPanel11.add(this.deviceLabel13, null);
        this.jPanel11.add(this.deviceField117, null);
        this.jPanel11.add(this.deviceChoice13, null);
        this.jPanel11.add(this.deviceLabel31, null);
        this.jPanel11.add(this.deviceField118, null);
        this.jPanel11.add(this.deviceChoice14, null);
        this.jPanel4.add(this.deviceChannel6, null);
        this.deviceChannel6.add(this.jPanel10, null);
        this.jPanel10.add(this.deviceLabel14, null);
        this.jPanel10.add(this.deviceField113, null);
        this.jPanel10.add(this.deviceChoice11, null);
        this.jPanel10.add(this.deviceLabel32, null);
        this.jPanel10.add(this.deviceField114, null);
        this.jPanel10.add(this.deviceChoice12, null);
        this.jPanel4.add(this.deviceChannel5, null);
        this.deviceChannel5.add(this.jPanel9, null);
        this.jPanel9.add(this.deviceLabel15, null);
        this.jPanel9.add(this.deviceField19, null);
        this.jPanel9.add(this.deviceChoice9, null);
        this.jPanel9.add(this.deviceLabel33, null);
        this.jPanel9.add(this.deviceField110, null);
        this.jPanel9.add(this.deviceChoice10, null);
        this.jPanel4.add(this.deviceChannel4, null);
        this.deviceChannel4.add(this.jPanel8, null);
        this.jPanel8.add(this.deviceLabel16, null);
        this.jPanel8.add(this.deviceField15, null);
        this.jPanel8.add(this.deviceChoice7, null);
        this.jPanel8.add(this.deviceLabel34, null);
        this.jPanel8.add(this.deviceField16, null);
        this.jPanel8.add(this.deviceChoice8, null);
        this.jPanel4.add(this.deviceChannel3, null);
        this.deviceChannel3.add(this.jPanel7, null);
        this.jPanel7.add(this.deviceLabel17, null);
        this.jPanel7.add(this.deviceField11, null);
        this.jPanel7.add(this.deviceChoice5, null);
        this.jPanel7.add(this.deviceLabel35, null);
        this.jPanel7.add(this.deviceField12, null);
        this.jPanel7.add(this.deviceChoice6, null);
        this.jPanel4.add(this.deviceChannel2, null);
        this.deviceChannel2.add(this.jPanel6, null);
        this.jPanel6.add(this.deviceLabel18, null);
        this.jPanel6.add(this.deviceField7, null);
        this.jPanel6.add(this.deviceChoice3, null);
        this.jPanel6.add(this.deviceLabel36, null);
        this.jPanel6.add(this.deviceField8, null);
        this.jPanel6.add(this.deviceChoice4, null);
    }
}
