import devicebeans.DeviceButtons;
import devicebeans.DeviceChannel;
import devicebeans.DeviceDispatch;
import devicebeans.DeviceField;
import devicebeans.DeviceLabel;
import devicebeans.DeviceSetup;

/*
 * RFXDnbiSetup.java
 * Created on October 7, 2008, 5:07 PM
 */
/**
 * @author taliercio
 */
public class RFXDnbiSetup extends DeviceSetup{
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons           deviceButtons1;
    private DeviceChannel           deviceChannel1;
    private DeviceChannel           deviceChannel10;
    private DeviceChannel           deviceChannel11;
    private DeviceChannel           deviceChannel12;
    private DeviceChannel           deviceChannel13;
    private DeviceChannel           deviceChannel14;
    private DeviceChannel           deviceChannel15;
    private DeviceChannel           deviceChannel16;
    private DeviceChannel           deviceChannel2;
    private DeviceChannel           deviceChannel3;
    private DeviceChannel           deviceChannel4;
    private DeviceChannel           deviceChannel5;
    private DeviceChannel           deviceChannel6;
    private DeviceChannel           deviceChannel7;
    private DeviceChannel           deviceChannel8;
    private DeviceChannel           deviceChannel9;
    private DeviceDispatch          deviceDispatch1;
    private DeviceField             deviceField1;
    private DeviceField             deviceField10;
    private DeviceField             deviceField11;
    private DeviceField             deviceField12;
    private DeviceField             deviceField13;
    private DeviceField             deviceField14;
    private DeviceField             deviceField15;
    private DeviceField             deviceField16;
    private DeviceField             deviceField17;
    private DeviceField             deviceField18;
    private DeviceField             deviceField19;
    private DeviceField             deviceField2;
    private DeviceField             deviceField20;
    private DeviceField             deviceField21;
    private DeviceField             deviceField22;
    private DeviceField             deviceField23;
    private DeviceField             deviceField24;
    private DeviceField             deviceField25;
    private DeviceField             deviceField26;
    private DeviceField             deviceField27;
    private DeviceField             deviceField28;
    private DeviceField             deviceField29;
    private DeviceField             deviceField3;
    private DeviceField             deviceField30;
    private DeviceField             deviceField31;
    private DeviceField             deviceField32;
    private DeviceField             deviceField33;
    private DeviceField             deviceField34;
    private DeviceField             deviceField35;
    private DeviceField             deviceField36;
    private DeviceField             deviceField37;
    private DeviceField             deviceField38;
    private DeviceField             deviceField39;
    private DeviceField             deviceField4;
    private DeviceField             deviceField40;
    private DeviceField             deviceField41;
    private DeviceField             deviceField42;
    private DeviceField             deviceField43;
    private DeviceField             deviceField44;
    private DeviceField             deviceField45;
    private DeviceField             deviceField46;
    private DeviceField             deviceField47;
    private DeviceField             deviceField48;
    private DeviceField             deviceField49;
    private DeviceField             deviceField5;
    private DeviceField             deviceField50;
    private DeviceField             deviceField51;
    private DeviceField             deviceField52;
    private DeviceField             deviceField53;
    private DeviceField             deviceField54;
    private DeviceField             deviceField55;
    private DeviceField             deviceField56;
    private DeviceField             deviceField57;
    private DeviceField             deviceField58;
    private DeviceField             deviceField59;
    private DeviceField             deviceField6;
    private DeviceField             deviceField60;
    private DeviceField             deviceField61;
    private DeviceField             deviceField62;
    private DeviceField             deviceField63;
    private DeviceField             deviceField64;
    private DeviceField             deviceField65;
    private DeviceField             deviceField66;
    private DeviceField             deviceField67;
    private DeviceField             deviceField68;
    private DeviceField             deviceField69;
    private DeviceField             deviceField7;
    private DeviceField             deviceField70;
    private DeviceField             deviceField71;
    private DeviceField             deviceField72;
    private DeviceField             deviceField73;
    private DeviceField             deviceField74;
    private DeviceField             deviceField75;
    private DeviceField             deviceField76;
    private DeviceField             deviceField77;
    private DeviceField             deviceField78;
    private DeviceField             deviceField79;
    private DeviceField             deviceField8;
    private DeviceField             deviceField80;
    private DeviceField             deviceField81;
    private DeviceField             deviceField82;
    private DeviceField             deviceField83;
    private DeviceField             deviceField84;
    private DeviceField             deviceField85;
    private DeviceField             deviceField86;
    private DeviceField             deviceField87;
    private DeviceField             deviceField88;
    private DeviceField             deviceField89;
    private DeviceField             deviceField9;
    private DeviceField             deviceField90;
    private DeviceField             deviceField91;
    private DeviceField             deviceField92;
    private DeviceField             deviceField93;
    private DeviceField             deviceField94;
    private DeviceField             deviceField95;
    private DeviceField             deviceField96;
    private DeviceField             deviceField97;
    private DeviceField             deviceField98;
    private DeviceField             deviceField99;
    private DeviceLabel             deviceLabel1;
    private DeviceLabel             deviceLabel10;
    private DeviceLabel             deviceLabel11;
    private DeviceLabel             deviceLabel12;
    private DeviceLabel             deviceLabel13;
    private DeviceLabel             deviceLabel14;
    private DeviceLabel             deviceLabel15;
    private DeviceLabel             deviceLabel16;
    private DeviceLabel             deviceLabel17;
    private DeviceLabel             deviceLabel18;
    private DeviceLabel             deviceLabel19;
    private DeviceLabel             deviceLabel2;
    private DeviceLabel             deviceLabel20;
    private DeviceLabel             deviceLabel21;
    private DeviceLabel             deviceLabel22;
    private DeviceLabel             deviceLabel23;
    private DeviceLabel             deviceLabel24;
    private DeviceLabel             deviceLabel25;
    private DeviceLabel             deviceLabel26;
    private DeviceLabel             deviceLabel27;
    private DeviceLabel             deviceLabel28;
    private DeviceLabel             deviceLabel29;
    private DeviceLabel             deviceLabel3;
    private DeviceLabel             deviceLabel30;
    private DeviceLabel             deviceLabel31;
    private DeviceLabel             deviceLabel32;
    private DeviceLabel             deviceLabel4;
    private DeviceLabel             deviceLabel5;
    private DeviceLabel             deviceLabel6;
    private DeviceLabel             deviceLabel7;
    private DeviceLabel             deviceLabel8;
    private DeviceLabel             deviceLabel9;
    private javax.swing.JPanel      jPanel1;
    private javax.swing.JPanel      jPanel10;
    private javax.swing.JPanel      jPanel11;
    private javax.swing.JPanel      jPanel12;
    private javax.swing.JPanel      jPanel13;
    private javax.swing.JPanel      jPanel14;
    private javax.swing.JPanel      jPanel15;
    private javax.swing.JPanel      jPanel16;
    private javax.swing.JPanel      jPanel17;
    private javax.swing.JPanel      jPanel18;
    private javax.swing.JPanel      jPanel19;
    private javax.swing.JPanel      jPanel2;
    private javax.swing.JPanel      jPanel20;
    private javax.swing.JPanel      jPanel21;
    private javax.swing.JPanel      jPanel22;
    private javax.swing.JPanel      jPanel23;
    private javax.swing.JPanel      jPanel24;
    private javax.swing.JPanel      jPanel25;
    private javax.swing.JPanel      jPanel26;
    private javax.swing.JPanel      jPanel27;
    private javax.swing.JPanel      jPanel28;
    private javax.swing.JPanel      jPanel29;
    private javax.swing.JPanel      jPanel3;
    private javax.swing.JPanel      jPanel30;
    private javax.swing.JPanel      jPanel31;
    private javax.swing.JPanel      jPanel32;
    private javax.swing.JPanel      jPanel33;
    private javax.swing.JPanel      jPanel34;
    private javax.swing.JPanel      jPanel35;
    private javax.swing.JPanel      jPanel36;
    private javax.swing.JPanel      jPanel37;
    private javax.swing.JPanel      jPanel38;
    private javax.swing.JPanel      jPanel39;
    private javax.swing.JPanel      jPanel4;
    private javax.swing.JPanel      jPanel40;
    private javax.swing.JPanel      jPanel41;
    private javax.swing.JPanel      jPanel5;
    private javax.swing.JPanel      jPanel6;
    private javax.swing.JPanel      jPanel7;
    private javax.swing.JPanel      jPanel8;
    private javax.swing.JPanel      jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;

    // End of variables declaration//GEN-END:variables
    /** Creates new form RFXDnbiSetup */
    public RFXDnbiSetup(){
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.setSize(700, 400);
        this.jPanel1 = new javax.swing.JPanel();
        this.deviceButtons1 = new DeviceButtons();
        this.jPanel2 = new javax.swing.JPanel();
        this.jPanel4 = new javax.swing.JPanel();
        this.deviceField1 = new DeviceField();
        this.deviceDispatch1 = new DeviceDispatch();
        this.jPanel5 = new javax.swing.JPanel();
        this.deviceField2 = new DeviceField();
        this.deviceField3 = new DeviceField();
        this.jPanel3 = new javax.swing.JPanel();
        this.jTabbedPane1 = new javax.swing.JTabbedPane();
        this.jPanel7 = new javax.swing.JPanel();
        this.jScrollPane1 = new javax.swing.JScrollPane();
        this.jPanel8 = new javax.swing.JPanel();
        this.jPanel9 = new javax.swing.JPanel();
        this.deviceChannel1 = new DeviceChannel();
        this.deviceLabel1 = new DeviceLabel();
        this.deviceField4 = new DeviceField();
        this.deviceField5 = new DeviceField();
        this.deviceField6 = new DeviceField();
        this.deviceField7 = new DeviceField();
        this.jPanel10 = new javax.swing.JPanel();
        this.deviceChannel2 = new DeviceChannel();
        this.deviceLabel2 = new DeviceLabel();
        this.deviceField8 = new DeviceField();
        this.deviceField9 = new DeviceField();
        this.deviceField10 = new DeviceField();
        this.deviceField11 = new DeviceField();
        this.jPanel11 = new javax.swing.JPanel();
        this.deviceChannel3 = new DeviceChannel();
        this.deviceLabel3 = new DeviceLabel();
        this.deviceField12 = new DeviceField();
        this.deviceField13 = new DeviceField();
        this.deviceField14 = new DeviceField();
        this.deviceField15 = new DeviceField();
        this.jPanel12 = new javax.swing.JPanel();
        this.deviceChannel4 = new DeviceChannel();
        this.deviceLabel4 = new DeviceLabel();
        this.deviceField16 = new DeviceField();
        this.deviceField17 = new DeviceField();
        this.deviceField18 = new DeviceField();
        this.deviceField19 = new DeviceField();
        this.jPanel13 = new javax.swing.JPanel();
        this.deviceChannel5 = new DeviceChannel();
        this.deviceLabel5 = new DeviceLabel();
        this.deviceField20 = new DeviceField();
        this.deviceField21 = new DeviceField();
        this.deviceField22 = new DeviceField();
        this.deviceField23 = new DeviceField();
        this.jPanel14 = new javax.swing.JPanel();
        this.deviceChannel6 = new DeviceChannel();
        this.deviceLabel6 = new DeviceLabel();
        this.deviceField24 = new DeviceField();
        this.deviceField25 = new DeviceField();
        this.deviceField26 = new DeviceField();
        this.deviceField27 = new DeviceField();
        this.jPanel15 = new javax.swing.JPanel();
        this.deviceChannel7 = new DeviceChannel();
        this.deviceLabel7 = new DeviceLabel();
        this.deviceField28 = new DeviceField();
        this.deviceField29 = new DeviceField();
        this.deviceField30 = new DeviceField();
        this.deviceField31 = new DeviceField();
        this.jPanel16 = new javax.swing.JPanel();
        this.deviceChannel8 = new DeviceChannel();
        this.deviceLabel8 = new DeviceLabel();
        this.deviceField32 = new DeviceField();
        this.deviceField33 = new DeviceField();
        this.deviceField34 = new DeviceField();
        this.deviceField35 = new DeviceField();
        this.jPanel17 = new javax.swing.JPanel();
        this.deviceChannel9 = new DeviceChannel();
        this.deviceLabel9 = new DeviceLabel();
        this.deviceField36 = new DeviceField();
        this.deviceField37 = new DeviceField();
        this.deviceField38 = new DeviceField();
        this.deviceField39 = new DeviceField();
        this.jPanel18 = new javax.swing.JPanel();
        this.deviceChannel10 = new DeviceChannel();
        this.deviceLabel10 = new DeviceLabel();
        this.deviceField40 = new DeviceField();
        this.deviceField41 = new DeviceField();
        this.deviceField42 = new DeviceField();
        this.deviceField43 = new DeviceField();
        this.jPanel19 = new javax.swing.JPanel();
        this.deviceChannel11 = new DeviceChannel();
        this.deviceLabel11 = new DeviceLabel();
        this.deviceField44 = new DeviceField();
        this.deviceField45 = new DeviceField();
        this.deviceField46 = new DeviceField();
        this.deviceField47 = new DeviceField();
        this.jPanel20 = new javax.swing.JPanel();
        this.deviceChannel12 = new DeviceChannel();
        this.deviceLabel12 = new DeviceLabel();
        this.deviceField48 = new DeviceField();
        this.deviceField49 = new DeviceField();
        this.deviceField50 = new DeviceField();
        this.deviceField51 = new DeviceField();
        this.jPanel21 = new javax.swing.JPanel();
        this.deviceChannel13 = new DeviceChannel();
        this.deviceLabel13 = new DeviceLabel();
        this.deviceField52 = new DeviceField();
        this.deviceField53 = new DeviceField();
        this.deviceField54 = new DeviceField();
        this.deviceField55 = new DeviceField();
        this.jPanel22 = new javax.swing.JPanel();
        this.deviceChannel14 = new DeviceChannel();
        this.deviceLabel14 = new DeviceLabel();
        this.deviceField56 = new DeviceField();
        this.deviceField57 = new DeviceField();
        this.deviceField58 = new DeviceField();
        this.deviceField59 = new DeviceField();
        this.jPanel23 = new javax.swing.JPanel();
        this.deviceChannel15 = new DeviceChannel();
        this.deviceLabel15 = new DeviceLabel();
        this.deviceField60 = new DeviceField();
        this.deviceField61 = new DeviceField();
        this.deviceField62 = new DeviceField();
        this.deviceField63 = new DeviceField();
        this.jPanel24 = new javax.swing.JPanel();
        this.deviceChannel16 = new DeviceChannel();
        this.deviceLabel16 = new DeviceLabel();
        this.deviceField64 = new DeviceField();
        this.deviceField65 = new DeviceField();
        this.deviceField66 = new DeviceField();
        this.deviceField67 = new DeviceField();
        this.jPanel41 = new javax.swing.JPanel();
        this.jScrollPane2 = new javax.swing.JScrollPane();
        this.jPanel6 = new javax.swing.JPanel();
        this.jPanel25 = new javax.swing.JPanel();
        this.deviceLabel17 = new DeviceLabel();
        this.deviceField68 = new DeviceField();
        this.deviceField69 = new DeviceField();
        this.jPanel26 = new javax.swing.JPanel();
        this.deviceLabel18 = new DeviceLabel();
        this.deviceField70 = new DeviceField();
        this.deviceField71 = new DeviceField();
        this.jPanel27 = new javax.swing.JPanel();
        this.deviceLabel19 = new DeviceLabel();
        this.deviceField72 = new DeviceField();
        this.deviceField73 = new DeviceField();
        this.jPanel28 = new javax.swing.JPanel();
        this.deviceLabel20 = new DeviceLabel();
        this.deviceField74 = new DeviceField();
        this.deviceField75 = new DeviceField();
        this.jPanel29 = new javax.swing.JPanel();
        this.deviceLabel21 = new DeviceLabel();
        this.deviceField76 = new DeviceField();
        this.deviceField77 = new DeviceField();
        this.jPanel30 = new javax.swing.JPanel();
        this.deviceLabel22 = new DeviceLabel();
        this.deviceField78 = new DeviceField();
        this.deviceField79 = new DeviceField();
        this.jPanel31 = new javax.swing.JPanel();
        this.deviceLabel23 = new DeviceLabel();
        this.deviceField80 = new DeviceField();
        this.deviceField81 = new DeviceField();
        this.jPanel32 = new javax.swing.JPanel();
        this.deviceLabel24 = new DeviceLabel();
        this.deviceField82 = new DeviceField();
        this.deviceField83 = new DeviceField();
        this.jPanel33 = new javax.swing.JPanel();
        this.deviceLabel25 = new DeviceLabel();
        this.deviceField84 = new DeviceField();
        this.deviceField85 = new DeviceField();
        this.jPanel34 = new javax.swing.JPanel();
        this.deviceLabel26 = new DeviceLabel();
        this.deviceField86 = new DeviceField();
        this.deviceField87 = new DeviceField();
        this.jPanel35 = new javax.swing.JPanel();
        this.deviceLabel27 = new DeviceLabel();
        this.deviceField88 = new DeviceField();
        this.deviceField89 = new DeviceField();
        this.jPanel36 = new javax.swing.JPanel();
        this.deviceLabel28 = new DeviceLabel();
        this.deviceField90 = new DeviceField();
        this.deviceField91 = new DeviceField();
        this.jPanel37 = new javax.swing.JPanel();
        this.deviceLabel29 = new DeviceLabel();
        this.deviceField92 = new DeviceField();
        this.deviceField93 = new DeviceField();
        this.jPanel38 = new javax.swing.JPanel();
        this.deviceLabel30 = new DeviceLabel();
        this.deviceField94 = new DeviceField();
        this.deviceField95 = new DeviceField();
        this.jPanel39 = new javax.swing.JPanel();
        this.deviceLabel31 = new DeviceLabel();
        this.deviceField96 = new DeviceField();
        this.deviceField97 = new DeviceField();
        this.jPanel40 = new javax.swing.JPanel();
        this.deviceLabel32 = new DeviceLabel();
        this.deviceField98 = new DeviceField();
        this.deviceField99 = new DeviceField();
        this.setDeviceProvider("localhost");
        this.setDeviceTitle("RFX Diagnostic Neutral Beam Injector");
        this.setDeviceType("RFXDnbi");
        this.jPanel1.setLayout(new java.awt.BorderLayout());
        this.jPanel1.add(this.deviceButtons1, java.awt.BorderLayout.SOUTH);
        this.jPanel2.setLayout(new java.awt.GridLayout(2, 0));
        this.jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceField1.setIdentifier("");
        this.deviceField1.setLabelString("Comment:");
        this.deviceField1.setNumCols(25);
        this.deviceField1.setOffsetNid(2);
        this.deviceField1.setTextOnly(true);
        this.jPanel4.add(this.deviceField1);
        this.jPanel4.add(this.deviceDispatch1);
        this.jPanel2.add(this.jPanel4);
        this.jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceField2.setIdentifier("");
        this.deviceField2.setLabelString("Name:");
        this.deviceField2.setNumCols(15);
        this.deviceField2.setOffsetNid(1);
        this.jPanel5.add(this.deviceField2);
        this.deviceField3.setIdentifier("");
        this.deviceField3.setLabelString("Trig. Source:");
        this.deviceField3.setNumCols(15);
        this.deviceField3.setOffsetNid(3);
        this.jPanel5.add(this.deviceField3);
        this.jPanel2.add(this.jPanel5);
        this.jPanel1.add(this.jPanel2, java.awt.BorderLayout.NORTH);
        this.jPanel3.setLayout(new java.awt.BorderLayout());
        this.jPanel7.setLayout(new java.awt.BorderLayout());
        this.jPanel8.setLayout(new java.awt.GridLayout(16, 0));
        this.jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel1.setLabelString("");
        this.deviceChannel1.setOffsetNid(5);
        this.deviceChannel1.setShowVal("");
        this.deviceChannel1.setUpdateIdentifier("");
        this.jPanel9.add(this.deviceChannel1);
        this.deviceLabel1.setIdentifier("");
        this.deviceLabel1.setLabelString("NONE");
        this.deviceLabel1.setNumCols(15);
        this.deviceLabel1.setOffsetNid(6);
        this.deviceLabel1.setPreferredWidth(60);
        this.jPanel9.add(this.deviceLabel1);
        this.deviceField4.setIdentifier("");
        this.deviceField4.setLabelString("Start");
        this.deviceField4.setNumCols(6);
        this.deviceField4.setOffsetNid(7);
        this.jPanel9.add(this.deviceField4);
        this.deviceField5.setIdentifier("");
        this.deviceField5.setLabelString("Stop");
        this.deviceField5.setNumCols(6);
        this.deviceField5.setOffsetNid(8);
        this.jPanel9.add(this.deviceField5);
        this.deviceField6.setIdentifier("");
        this.deviceField6.setLabelString("High");
        this.deviceField6.setNumCols(6);
        this.deviceField6.setOffsetNid(9);
        this.jPanel9.add(this.deviceField6);
        this.deviceField7.setIdentifier("");
        this.deviceField7.setLabelString("Low");
        this.deviceField7.setNumCols(6);
        this.deviceField7.setOffsetNid(10);
        this.jPanel9.add(this.deviceField7);
        this.jPanel8.add(this.jPanel9);
        this.jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel2.setLabelString("");
        this.deviceChannel2.setOffsetNid(11);
        this.deviceChannel2.setShowVal("");
        this.deviceChannel2.setUpdateIdentifier("");
        this.jPanel10.add(this.deviceChannel2);
        this.deviceLabel2.setLabelString("NONE");
        this.deviceLabel2.setNumCols(15);
        this.deviceLabel2.setOffsetNid(12);
        this.deviceLabel2.setPreferredWidth(60);
        this.jPanel10.add(this.deviceLabel2);
        this.deviceField8.setLabelString("Start");
        this.deviceField8.setNumCols(6);
        this.deviceField8.setOffsetNid(13);
        this.jPanel10.add(this.deviceField8);
        this.deviceField9.setLabelString("Stop");
        this.deviceField9.setNumCols(6);
        this.deviceField9.setOffsetNid(14);
        this.jPanel10.add(this.deviceField9);
        this.deviceField10.setLabelString("High");
        this.deviceField10.setNumCols(6);
        this.deviceField10.setOffsetNid(15);
        this.jPanel10.add(this.deviceField10);
        this.deviceField11.setLabelString("Low");
        this.deviceField11.setNumCols(6);
        this.deviceField11.setOffsetNid(16);
        this.jPanel10.add(this.deviceField11);
        this.jPanel8.add(this.jPanel10);
        this.jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel3.setLabelString("");
        this.deviceChannel3.setOffsetNid(17);
        this.deviceChannel3.setShowVal("");
        this.deviceChannel3.setUpdateIdentifier("");
        this.jPanel11.add(this.deviceChannel3);
        this.deviceLabel3.setLabelString("NONE");
        this.deviceLabel3.setNumCols(15);
        this.deviceLabel3.setOffsetNid(18);
        this.deviceLabel3.setPreferredWidth(60);
        this.jPanel11.add(this.deviceLabel3);
        this.deviceField12.setLabelString("Start");
        this.deviceField12.setNumCols(6);
        this.deviceField12.setOffsetNid(19);
        this.jPanel11.add(this.deviceField12);
        this.deviceField13.setLabelString("Stop");
        this.deviceField13.setNumCols(6);
        this.deviceField13.setOffsetNid(20);
        this.jPanel11.add(this.deviceField13);
        this.deviceField14.setLabelString("High");
        this.deviceField14.setNumCols(6);
        this.deviceField14.setOffsetNid(21);
        this.jPanel11.add(this.deviceField14);
        this.deviceField15.setLabelString("Low");
        this.deviceField15.setNumCols(6);
        this.deviceField15.setOffsetNid(22);
        this.jPanel11.add(this.deviceField15);
        this.jPanel8.add(this.jPanel11);
        this.jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel4.setLabelString("");
        this.deviceChannel4.setOffsetNid(23);
        this.deviceChannel4.setShowVal("");
        this.deviceChannel4.setUpdateIdentifier("");
        this.jPanel12.add(this.deviceChannel4);
        this.deviceLabel4.setLabelString("NONE");
        this.deviceLabel4.setNumCols(15);
        this.deviceLabel4.setOffsetNid(24);
        this.deviceLabel4.setPreferredWidth(60);
        this.jPanel12.add(this.deviceLabel4);
        this.deviceField16.setLabelString("Start");
        this.deviceField16.setNumCols(6);
        this.deviceField16.setOffsetNid(25);
        this.jPanel12.add(this.deviceField16);
        this.deviceField17.setLabelString("Stop");
        this.deviceField17.setNumCols(6);
        this.deviceField17.setOffsetNid(26);
        this.jPanel12.add(this.deviceField17);
        this.deviceField18.setLabelString("High");
        this.deviceField18.setNumCols(6);
        this.deviceField18.setOffsetNid(27);
        this.jPanel12.add(this.deviceField18);
        this.deviceField19.setLabelString("Low");
        this.deviceField19.setNumCols(6);
        this.deviceField19.setOffsetNid(28);
        this.jPanel12.add(this.deviceField19);
        this.jPanel8.add(this.jPanel12);
        this.jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel5.setLabelString("");
        this.deviceChannel5.setOffsetNid(29);
        this.deviceChannel5.setShowVal("");
        this.deviceChannel5.setUpdateIdentifier("");
        this.jPanel13.add(this.deviceChannel5);
        this.deviceLabel5.setLabelString("NONE");
        this.deviceLabel5.setNumCols(15);
        this.deviceLabel5.setOffsetNid(30);
        this.deviceLabel5.setPreferredWidth(60);
        this.jPanel13.add(this.deviceLabel5);
        this.deviceField20.setLabelString("Start");
        this.deviceField20.setNumCols(6);
        this.deviceField20.setOffsetNid(31);
        this.jPanel13.add(this.deviceField20);
        this.deviceField21.setLabelString("Stop");
        this.deviceField21.setNumCols(6);
        this.deviceField21.setOffsetNid(32);
        this.jPanel13.add(this.deviceField21);
        this.deviceField22.setLabelString("High");
        this.deviceField22.setNumCols(6);
        this.deviceField22.setOffsetNid(33);
        this.jPanel13.add(this.deviceField22);
        this.deviceField23.setLabelString("Low");
        this.deviceField23.setNumCols(6);
        this.deviceField23.setOffsetNid(34);
        this.jPanel13.add(this.deviceField23);
        this.jPanel8.add(this.jPanel13);
        this.jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel6.setLabelString("");
        this.deviceChannel6.setOffsetNid(35);
        this.deviceChannel6.setShowVal("");
        this.deviceChannel6.setUpdateIdentifier("");
        this.jPanel14.add(this.deviceChannel6);
        this.deviceLabel6.setLabelString("NONE");
        this.deviceLabel6.setNumCols(15);
        this.deviceLabel6.setOffsetNid(36);
        this.deviceLabel6.setPreferredWidth(60);
        this.jPanel14.add(this.deviceLabel6);
        this.deviceField24.setLabelString("Start");
        this.deviceField24.setNumCols(6);
        this.deviceField24.setOffsetNid(37);
        this.jPanel14.add(this.deviceField24);
        this.deviceField25.setLabelString("Stop");
        this.deviceField25.setNumCols(6);
        this.deviceField25.setOffsetNid(38);
        this.jPanel14.add(this.deviceField25);
        this.deviceField26.setLabelString("High");
        this.deviceField26.setNumCols(6);
        this.deviceField26.setOffsetNid(39);
        this.jPanel14.add(this.deviceField26);
        this.deviceField27.setLabelString("Low");
        this.deviceField27.setNumCols(6);
        this.deviceField27.setOffsetNid(40);
        this.jPanel14.add(this.deviceField27);
        this.jPanel8.add(this.jPanel14);
        this.jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel7.setLabelString("");
        this.deviceChannel7.setOffsetNid(41);
        this.deviceChannel7.setShowVal("");
        this.deviceChannel7.setUpdateIdentifier("");
        this.jPanel15.add(this.deviceChannel7);
        this.deviceLabel7.setLabelString("NONE");
        this.deviceLabel7.setNumCols(15);
        this.deviceLabel7.setOffsetNid(42);
        this.deviceLabel7.setPreferredWidth(60);
        this.jPanel15.add(this.deviceLabel7);
        this.deviceField28.setLabelString("Start");
        this.deviceField28.setNumCols(6);
        this.deviceField28.setOffsetNid(43);
        this.jPanel15.add(this.deviceField28);
        this.deviceField29.setLabelString("Stop");
        this.deviceField29.setNumCols(6);
        this.deviceField29.setOffsetNid(44);
        this.jPanel15.add(this.deviceField29);
        this.deviceField30.setLabelString("High");
        this.deviceField30.setNumCols(6);
        this.deviceField30.setOffsetNid(45);
        this.jPanel15.add(this.deviceField30);
        this.deviceField31.setLabelString("Low");
        this.deviceField31.setNumCols(6);
        this.deviceField31.setOffsetNid(46);
        this.jPanel15.add(this.deviceField31);
        this.jPanel8.add(this.jPanel15);
        this.jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel8.setLabelString("");
        this.deviceChannel8.setOffsetNid(47);
        this.deviceChannel8.setShowVal("");
        this.deviceChannel8.setUpdateIdentifier("");
        this.jPanel16.add(this.deviceChannel8);
        this.deviceLabel8.setLabelString("NONE");
        this.deviceLabel8.setNumCols(15);
        this.deviceLabel8.setOffsetNid(48);
        this.deviceLabel8.setPreferredWidth(60);
        this.jPanel16.add(this.deviceLabel8);
        this.deviceField32.setLabelString("Start");
        this.deviceField32.setNumCols(6);
        this.deviceField32.setOffsetNid(49);
        this.jPanel16.add(this.deviceField32);
        this.deviceField33.setLabelString("Stop");
        this.deviceField33.setNumCols(6);
        this.deviceField33.setOffsetNid(50);
        this.jPanel16.add(this.deviceField33);
        this.deviceField34.setLabelString("High");
        this.deviceField34.setNumCols(6);
        this.deviceField34.setOffsetNid(51);
        this.jPanel16.add(this.deviceField34);
        this.deviceField35.setLabelString("Low");
        this.deviceField35.setNumCols(6);
        this.deviceField35.setOffsetNid(52);
        this.jPanel16.add(this.deviceField35);
        this.jPanel8.add(this.jPanel16);
        this.jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel9.setLabelString("");
        this.deviceChannel9.setOffsetNid(53);
        this.deviceChannel9.setShowVal("");
        this.deviceChannel9.setUpdateIdentifier("");
        this.jPanel17.add(this.deviceChannel9);
        this.deviceLabel9.setLabelString("NONE");
        this.deviceLabel9.setNumCols(15);
        this.deviceLabel9.setOffsetNid(54);
        this.deviceLabel9.setPreferredWidth(60);
        this.jPanel17.add(this.deviceLabel9);
        this.deviceField36.setLabelString("Start");
        this.deviceField36.setNumCols(6);
        this.deviceField36.setOffsetNid(55);
        this.jPanel17.add(this.deviceField36);
        this.deviceField37.setLabelString("Stop");
        this.deviceField37.setNumCols(6);
        this.deviceField37.setOffsetNid(56);
        this.jPanel17.add(this.deviceField37);
        this.deviceField38.setLabelString("High");
        this.deviceField38.setNumCols(6);
        this.deviceField38.setOffsetNid(57);
        this.jPanel17.add(this.deviceField38);
        this.deviceField39.setLabelString("Low");
        this.deviceField39.setNumCols(6);
        this.deviceField39.setOffsetNid(58);
        this.jPanel17.add(this.deviceField39);
        this.jPanel8.add(this.jPanel17);
        this.jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel10.setLabelString("");
        this.deviceChannel10.setOffsetNid(59);
        this.deviceChannel10.setShowVal("");
        this.deviceChannel10.setUpdateIdentifier("");
        this.jPanel18.add(this.deviceChannel10);
        this.deviceLabel10.setLabelString("NONE");
        this.deviceLabel10.setNumCols(15);
        this.deviceLabel10.setOffsetNid(60);
        this.deviceLabel10.setPreferredWidth(60);
        this.jPanel18.add(this.deviceLabel10);
        this.deviceField40.setLabelString("Start");
        this.deviceField40.setNumCols(6);
        this.deviceField40.setOffsetNid(61);
        this.jPanel18.add(this.deviceField40);
        this.deviceField41.setLabelString("Stop");
        this.deviceField41.setNumCols(6);
        this.deviceField41.setOffsetNid(62);
        this.jPanel18.add(this.deviceField41);
        this.deviceField42.setLabelString("High");
        this.deviceField42.setNumCols(6);
        this.deviceField42.setOffsetNid(63);
        this.jPanel18.add(this.deviceField42);
        this.deviceField43.setLabelString("Low");
        this.deviceField43.setNumCols(6);
        this.deviceField43.setOffsetNid(64);
        this.jPanel18.add(this.deviceField43);
        this.jPanel8.add(this.jPanel18);
        this.jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel11.setLabelString("");
        this.deviceChannel11.setOffsetNid(65);
        this.deviceChannel11.setShowVal("");
        this.deviceChannel11.setUpdateIdentifier("");
        this.jPanel19.add(this.deviceChannel11);
        this.deviceLabel11.setLabelString("NONE");
        this.deviceLabel11.setNumCols(15);
        this.deviceLabel11.setOffsetNid(66);
        this.deviceLabel11.setPreferredWidth(60);
        this.jPanel19.add(this.deviceLabel11);
        this.deviceField44.setLabelString("Start");
        this.deviceField44.setNumCols(6);
        this.deviceField44.setOffsetNid(67);
        this.jPanel19.add(this.deviceField44);
        this.deviceField45.setLabelString("Stop");
        this.deviceField45.setNumCols(6);
        this.deviceField45.setOffsetNid(68);
        this.jPanel19.add(this.deviceField45);
        this.deviceField46.setLabelString("High");
        this.deviceField46.setNumCols(6);
        this.deviceField46.setOffsetNid(69);
        this.jPanel19.add(this.deviceField46);
        this.deviceField47.setLabelString("Low");
        this.deviceField47.setNumCols(6);
        this.deviceField47.setOffsetNid(70);
        this.jPanel19.add(this.deviceField47);
        this.jPanel8.add(this.jPanel19);
        this.jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel12.setLabelString("");
        this.deviceChannel12.setOffsetNid(71);
        this.deviceChannel12.setShowVal("");
        this.deviceChannel12.setUpdateIdentifier("");
        this.jPanel20.add(this.deviceChannel12);
        this.deviceLabel12.setLabelString("NONE");
        this.deviceLabel12.setNumCols(15);
        this.deviceLabel12.setOffsetNid(72);
        this.deviceLabel12.setPreferredWidth(60);
        this.jPanel20.add(this.deviceLabel12);
        this.deviceField48.setLabelString("Start");
        this.deviceField48.setNumCols(6);
        this.deviceField48.setOffsetNid(73);
        this.jPanel20.add(this.deviceField48);
        this.deviceField49.setLabelString("Stop");
        this.deviceField49.setNumCols(6);
        this.deviceField49.setOffsetNid(74);
        this.jPanel20.add(this.deviceField49);
        this.deviceField50.setLabelString("High");
        this.deviceField50.setNumCols(6);
        this.deviceField50.setOffsetNid(75);
        this.jPanel20.add(this.deviceField50);
        this.deviceField51.setLabelString("Low");
        this.deviceField51.setNumCols(6);
        this.deviceField51.setOffsetNid(76);
        this.jPanel20.add(this.deviceField51);
        this.jPanel8.add(this.jPanel20);
        this.jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel13.setLabelString("");
        this.deviceChannel13.setOffsetNid(77);
        this.deviceChannel13.setShowVal("");
        this.deviceChannel13.setUpdateIdentifier("");
        this.jPanel21.add(this.deviceChannel13);
        this.deviceLabel13.setLabelString("NONE");
        this.deviceLabel13.setNumCols(15);
        this.deviceLabel13.setOffsetNid(78);
        this.deviceLabel13.setPreferredWidth(60);
        this.jPanel21.add(this.deviceLabel13);
        this.deviceField52.setLabelString("Start");
        this.deviceField52.setNumCols(6);
        this.deviceField52.setOffsetNid(79);
        this.jPanel21.add(this.deviceField52);
        this.deviceField53.setLabelString("Stop");
        this.deviceField53.setNumCols(6);
        this.deviceField53.setOffsetNid(80);
        this.jPanel21.add(this.deviceField53);
        this.deviceField54.setLabelString("High");
        this.deviceField54.setNumCols(6);
        this.deviceField54.setOffsetNid(81);
        this.jPanel21.add(this.deviceField54);
        this.deviceField55.setLabelString("Low");
        this.deviceField55.setNumCols(6);
        this.deviceField55.setOffsetNid(82);
        this.jPanel21.add(this.deviceField55);
        this.jPanel8.add(this.jPanel21);
        this.jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel14.setLabelString("");
        this.deviceChannel14.setOffsetNid(83);
        this.deviceChannel14.setShowVal("");
        this.deviceChannel14.setUpdateIdentifier("");
        this.jPanel22.add(this.deviceChannel14);
        this.deviceLabel14.setLabelString("NONE");
        this.deviceLabel14.setNumCols(15);
        this.deviceLabel14.setOffsetNid(84);
        this.deviceLabel14.setPreferredWidth(60);
        this.jPanel22.add(this.deviceLabel14);
        this.deviceField56.setLabelString("Start");
        this.deviceField56.setNumCols(6);
        this.deviceField56.setOffsetNid(85);
        this.jPanel22.add(this.deviceField56);
        this.deviceField57.setLabelString("Stop");
        this.deviceField57.setNumCols(6);
        this.deviceField57.setOffsetNid(86);
        this.jPanel22.add(this.deviceField57);
        this.deviceField58.setLabelString("High");
        this.deviceField58.setNumCols(6);
        this.deviceField58.setOffsetNid(87);
        this.jPanel22.add(this.deviceField58);
        this.deviceField59.setLabelString("Low");
        this.deviceField59.setNumCols(6);
        this.deviceField59.setOffsetNid(88);
        this.jPanel22.add(this.deviceField59);
        this.jPanel8.add(this.jPanel22);
        this.jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel15.setLabelString("");
        this.deviceChannel15.setOffsetNid(89);
        this.deviceChannel15.setShowVal("");
        this.deviceChannel15.setUpdateIdentifier("");
        this.jPanel23.add(this.deviceChannel15);
        this.deviceLabel15.setLabelString("NONE");
        this.deviceLabel15.setNumCols(15);
        this.deviceLabel15.setOffsetNid(90);
        this.deviceLabel15.setPreferredWidth(60);
        this.jPanel23.add(this.deviceLabel15);
        this.deviceField60.setLabelString("Start");
        this.deviceField60.setNumCols(6);
        this.deviceField60.setOffsetNid(91);
        this.jPanel23.add(this.deviceField60);
        this.deviceField61.setLabelString("Stop");
        this.deviceField61.setNumCols(6);
        this.deviceField61.setOffsetNid(92);
        this.jPanel23.add(this.deviceField61);
        this.deviceField62.setLabelString("High");
        this.deviceField62.setNumCols(6);
        this.deviceField62.setOffsetNid(93);
        this.jPanel23.add(this.deviceField62);
        this.deviceField63.setLabelString("Low");
        this.deviceField63.setNumCols(6);
        this.deviceField63.setOffsetNid(94);
        this.jPanel23.add(this.deviceField63);
        this.jPanel8.add(this.jPanel23);
        this.jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceChannel16.setLabelString("");
        this.deviceChannel16.setOffsetNid(95);
        this.deviceChannel16.setShowVal("");
        this.deviceChannel16.setUpdateIdentifier("");
        this.jPanel24.add(this.deviceChannel16);
        this.deviceLabel16.setLabelString("NONE");
        this.deviceLabel16.setNumCols(15);
        this.deviceLabel16.setOffsetNid(96);
        this.deviceLabel16.setPreferredWidth(60);
        this.jPanel24.add(this.deviceLabel16);
        this.deviceField64.setLabelString("Start");
        this.deviceField64.setNumCols(6);
        this.deviceField64.setOffsetNid(97);
        this.jPanel24.add(this.deviceField64);
        this.deviceField65.setLabelString("Stop");
        this.deviceField65.setNumCols(6);
        this.deviceField65.setOffsetNid(98);
        this.jPanel24.add(this.deviceField65);
        this.deviceField66.setLabelString("High");
        this.deviceField66.setNumCols(6);
        this.deviceField66.setOffsetNid(99);
        this.jPanel24.add(this.deviceField66);
        this.deviceField67.setLabelString("Low");
        this.deviceField67.setNumCols(6);
        this.deviceField67.setOffsetNid(100);
        this.jPanel24.add(this.deviceField67);
        this.jPanel8.add(this.jPanel24);
        this.jScrollPane1.setViewportView(this.jPanel8);
        this.jPanel7.add(this.jScrollPane1, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("TIMER", this.jPanel7);
        this.jPanel41.setLayout(new java.awt.BorderLayout());
        this.jPanel6.setLayout(new java.awt.GridLayout(16, 0));
        this.jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel17.setIdentifier("");
        this.deviceLabel17.setLabelString("NONE");
        this.deviceLabel17.setNumCols(15);
        this.deviceLabel17.setOffsetNid(103);
        this.deviceLabel17.setPreferredWidth(60);
        this.jPanel25.add(this.deviceLabel17);
        this.deviceField68.setIdentifier("");
        this.deviceField68.setLabelString("Level");
        this.deviceField68.setNumCols(18);
        this.deviceField68.setOffsetNid(104);
        this.jPanel25.add(this.deviceField68);
        this.deviceField69.setIdentifier("");
        this.deviceField69.setLabelString("Coefficient");
        this.deviceField69.setNumCols(18);
        this.deviceField69.setOffsetNid(105);
        this.jPanel25.add(this.deviceField69);
        this.jPanel6.add(this.jPanel25);
        this.jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel18.setLabelString("NONE");
        this.deviceLabel18.setNumCols(15);
        this.deviceLabel18.setOffsetNid(107);
        this.deviceLabel18.setPreferredWidth(60);
        this.jPanel26.add(this.deviceLabel18);
        this.deviceField70.setLabelString("Level");
        this.deviceField70.setNumCols(18);
        this.deviceField70.setOffsetNid(108);
        this.jPanel26.add(this.deviceField70);
        this.deviceField71.setLabelString("Coefficient");
        this.deviceField71.setNumCols(18);
        this.deviceField71.setOffsetNid(109);
        this.jPanel26.add(this.deviceField71);
        this.jPanel6.add(this.jPanel26);
        this.jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel19.setLabelString("NONE");
        this.deviceLabel19.setNumCols(15);
        this.deviceLabel19.setOffsetNid(111);
        this.deviceLabel19.setPreferredWidth(60);
        this.jPanel27.add(this.deviceLabel19);
        this.deviceField72.setLabelString("Level");
        this.deviceField72.setNumCols(18);
        this.deviceField72.setOffsetNid(112);
        this.jPanel27.add(this.deviceField72);
        this.deviceField73.setLabelString("Coefficient");
        this.deviceField73.setNumCols(18);
        this.deviceField73.setOffsetNid(113);
        this.jPanel27.add(this.deviceField73);
        this.jPanel6.add(this.jPanel27);
        this.jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel20.setLabelString("NONE");
        this.deviceLabel20.setNumCols(15);
        this.deviceLabel20.setOffsetNid(115);
        this.deviceLabel20.setPreferredWidth(60);
        this.jPanel28.add(this.deviceLabel20);
        this.deviceField74.setLabelString("Level");
        this.deviceField74.setNumCols(18);
        this.deviceField74.setOffsetNid(116);
        this.jPanel28.add(this.deviceField74);
        this.deviceField75.setLabelString("Coefficient");
        this.deviceField75.setNumCols(18);
        this.deviceField75.setOffsetNid(117);
        this.jPanel28.add(this.deviceField75);
        this.jPanel6.add(this.jPanel28);
        this.jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel21.setLabelString("NONE");
        this.deviceLabel21.setNumCols(15);
        this.deviceLabel21.setOffsetNid(119);
        this.deviceLabel21.setPreferredWidth(60);
        this.jPanel29.add(this.deviceLabel21);
        this.deviceField76.setLabelString("Level");
        this.deviceField76.setNumCols(18);
        this.deviceField76.setOffsetNid(120);
        this.jPanel29.add(this.deviceField76);
        this.deviceField77.setLabelString("Coefficient");
        this.deviceField77.setNumCols(18);
        this.deviceField77.setOffsetNid(121);
        this.jPanel29.add(this.deviceField77);
        this.jPanel6.add(this.jPanel29);
        this.jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel22.setLabelString("NONE");
        this.deviceLabel22.setNumCols(15);
        this.deviceLabel22.setOffsetNid(123);
        this.deviceLabel22.setPreferredWidth(60);
        this.jPanel30.add(this.deviceLabel22);
        this.deviceField78.setLabelString("Level");
        this.deviceField78.setNumCols(18);
        this.deviceField78.setOffsetNid(124);
        this.jPanel30.add(this.deviceField78);
        this.deviceField79.setLabelString("Coefficient");
        this.deviceField79.setNumCols(18);
        this.deviceField79.setOffsetNid(125);
        this.jPanel30.add(this.deviceField79);
        this.jPanel6.add(this.jPanel30);
        this.jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel23.setLabelString("NONE");
        this.deviceLabel23.setNumCols(15);
        this.deviceLabel23.setOffsetNid(127);
        this.deviceLabel23.setPreferredWidth(60);
        this.jPanel31.add(this.deviceLabel23);
        this.deviceField80.setLabelString("Level");
        this.deviceField80.setNumCols(18);
        this.deviceField80.setOffsetNid(128);
        this.jPanel31.add(this.deviceField80);
        this.deviceField81.setLabelString("Coefficient");
        this.deviceField81.setNumCols(18);
        this.deviceField81.setOffsetNid(129);
        this.jPanel31.add(this.deviceField81);
        this.jPanel6.add(this.jPanel31);
        this.jPanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel24.setLabelString("NONE");
        this.deviceLabel24.setNumCols(15);
        this.deviceLabel24.setOffsetNid(131);
        this.deviceLabel24.setPreferredWidth(60);
        this.jPanel32.add(this.deviceLabel24);
        this.deviceField82.setLabelString("Level");
        this.deviceField82.setNumCols(18);
        this.deviceField82.setOffsetNid(132);
        this.jPanel32.add(this.deviceField82);
        this.deviceField83.setLabelString("Coefficient");
        this.deviceField83.setNumCols(18);
        this.deviceField83.setOffsetNid(133);
        this.jPanel32.add(this.deviceField83);
        this.jPanel6.add(this.jPanel32);
        this.jPanel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel25.setLabelString("NONE");
        this.deviceLabel25.setNumCols(15);
        this.deviceLabel25.setOffsetNid(135);
        this.deviceLabel25.setPreferredWidth(60);
        this.jPanel33.add(this.deviceLabel25);
        this.deviceField84.setLabelString("Level");
        this.deviceField84.setNumCols(18);
        this.deviceField84.setOffsetNid(136);
        this.jPanel33.add(this.deviceField84);
        this.deviceField85.setLabelString("Coefficient");
        this.deviceField85.setNumCols(18);
        this.deviceField85.setOffsetNid(137);
        this.jPanel33.add(this.deviceField85);
        this.jPanel6.add(this.jPanel33);
        this.jPanel34.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel26.setLabelString("NONE");
        this.deviceLabel26.setNumCols(15);
        this.deviceLabel26.setOffsetNid(139);
        this.deviceLabel26.setPreferredWidth(60);
        this.jPanel34.add(this.deviceLabel26);
        this.deviceField86.setLabelString("Level");
        this.deviceField86.setNumCols(18);
        this.deviceField86.setOffsetNid(140);
        this.jPanel34.add(this.deviceField86);
        this.deviceField87.setLabelString("Coefficient");
        this.deviceField87.setNumCols(18);
        this.deviceField87.setOffsetNid(141);
        this.jPanel34.add(this.deviceField87);
        this.jPanel6.add(this.jPanel34);
        this.jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel27.setLabelString("NONE");
        this.deviceLabel27.setNumCols(15);
        this.deviceLabel27.setOffsetNid(143);
        this.deviceLabel27.setPreferredWidth(60);
        this.jPanel35.add(this.deviceLabel27);
        this.deviceField88.setLabelString("Level");
        this.deviceField88.setNumCols(18);
        this.deviceField88.setOffsetNid(144);
        this.jPanel35.add(this.deviceField88);
        this.deviceField89.setLabelString("Coefficient");
        this.deviceField89.setNumCols(18);
        this.deviceField89.setOffsetNid(145);
        this.jPanel35.add(this.deviceField89);
        this.jPanel6.add(this.jPanel35);
        this.jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel28.setLabelString("NONE");
        this.deviceLabel28.setNumCols(15);
        this.deviceLabel28.setOffsetNid(147);
        this.deviceLabel28.setPreferredWidth(60);
        this.jPanel36.add(this.deviceLabel28);
        this.deviceField90.setLabelString("Level");
        this.deviceField90.setNumCols(18);
        this.deviceField90.setOffsetNid(148);
        this.jPanel36.add(this.deviceField90);
        this.deviceField91.setLabelString("Coefficient");
        this.deviceField91.setNumCols(18);
        this.deviceField91.setOffsetNid(149);
        this.jPanel36.add(this.deviceField91);
        this.jPanel6.add(this.jPanel36);
        this.jPanel37.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel29.setLabelString("NONE");
        this.deviceLabel29.setNumCols(15);
        this.deviceLabel29.setOffsetNid(151);
        this.deviceLabel29.setPreferredWidth(60);
        this.jPanel37.add(this.deviceLabel29);
        this.deviceField92.setLabelString("Level");
        this.deviceField92.setNumCols(18);
        this.deviceField92.setOffsetNid(152);
        this.jPanel37.add(this.deviceField92);
        this.deviceField93.setLabelString("Coefficient");
        this.deviceField93.setNumCols(18);
        this.deviceField93.setOffsetNid(153);
        this.jPanel37.add(this.deviceField93);
        this.jPanel6.add(this.jPanel37);
        this.jPanel38.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel30.setLabelString("NONE");
        this.deviceLabel30.setNumCols(15);
        this.deviceLabel30.setOffsetNid(155);
        this.deviceLabel30.setPreferredWidth(60);
        this.jPanel38.add(this.deviceLabel30);
        this.deviceField94.setLabelString("Level");
        this.deviceField94.setNumCols(18);
        this.deviceField94.setOffsetNid(156);
        this.jPanel38.add(this.deviceField94);
        this.deviceField95.setLabelString("Coefficient");
        this.deviceField95.setNumCols(18);
        this.deviceField95.setOffsetNid(157);
        this.jPanel38.add(this.deviceField95);
        this.jPanel6.add(this.jPanel38);
        this.jPanel39.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel31.setLabelString("NONE");
        this.deviceLabel31.setNumCols(15);
        this.deviceLabel31.setOffsetNid(159);
        this.deviceLabel31.setPreferredWidth(60);
        this.jPanel39.add(this.deviceLabel31);
        this.deviceField96.setLabelString("Level");
        this.deviceField96.setNumCols(18);
        this.deviceField96.setOffsetNid(160);
        this.jPanel39.add(this.deviceField96);
        this.deviceField97.setLabelString("Coefficient");
        this.deviceField97.setNumCols(18);
        this.deviceField97.setOffsetNid(161);
        this.jPanel39.add(this.deviceField97);
        this.jPanel6.add(this.jPanel39);
        this.jPanel40.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        this.deviceLabel32.setLabelString("NONE");
        this.deviceLabel32.setNumCols(15);
        this.deviceLabel32.setOffsetNid(163);
        this.deviceLabel32.setPreferredWidth(60);
        this.jPanel40.add(this.deviceLabel32);
        this.deviceField98.setLabelString("Level");
        this.deviceField98.setNumCols(18);
        this.deviceField98.setOffsetNid(164);
        this.jPanel40.add(this.deviceField98);
        this.deviceField99.setLabelString("Coefficient");
        this.deviceField99.setNumCols(18);
        this.deviceField99.setOffsetNid(165);
        this.jPanel40.add(this.deviceField99);
        this.jPanel6.add(this.jPanel40);
        this.jScrollPane2.setViewportView(this.jPanel6);
        this.jPanel41.add(this.jScrollPane2, java.awt.BorderLayout.CENTER);
        this.jTabbedPane1.addTab("ADC", this.jPanel41);
        this.jPanel3.add(this.jTabbedPane1, java.awt.BorderLayout.CENTER);
        this.jPanel1.add(this.jPanel3, java.awt.BorderLayout.CENTER);
        this.getContentPane().add(this.jPanel1, java.awt.BorderLayout.CENTER);
        this.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents
}
