import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import devicebeans.DeviceButtons;
import devicebeans.DeviceChannel;
import devicebeans.DeviceChoice;
import devicebeans.DeviceField;
import devicebeans.DeviceSetup;
import devicebeans.DeviceWave;
import devicebeans.DeviceWaveDisplay;

/**
 * <p>
 * Title:
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company:
 * </p>
 *
 * @author not attributable
 * @version 1.0
 */
public class RFXInverterSetupSetup extends DeviceSetup{
    /**
     *
     */
    private static final long serialVersionUID    = 3142598629047170505L;
    Border                    border1;
    BorderLayout              borderLayout1       = new BorderLayout();
    BorderLayout              borderLayout10      = new BorderLayout();
    BorderLayout              borderLayout11      = new BorderLayout();
    BorderLayout              borderLayout110     = new BorderLayout();
    BorderLayout              borderLayout111     = new BorderLayout();
    BorderLayout              borderLayout1110    = new BorderLayout();
    BorderLayout              borderLayout1111    = new BorderLayout();
    BorderLayout              borderLayout11110   = new BorderLayout();
    BorderLayout              borderLayout11111   = new BorderLayout();
    BorderLayout              borderLayout11112   = new BorderLayout();
    BorderLayout              borderLayout11113   = new BorderLayout();
    BorderLayout              borderLayout1118    = new BorderLayout();
    BorderLayout              borderLayout1119    = new BorderLayout();
    BorderLayout              borderLayout112     = new BorderLayout();
    BorderLayout              borderLayout113     = new BorderLayout();
    BorderLayout              borderLayout114     = new BorderLayout();
    BorderLayout              borderLayout115     = new BorderLayout();
    BorderLayout              borderLayout116     = new BorderLayout();
    BorderLayout              borderLayout117     = new BorderLayout();
    BorderLayout              borderLayout118     = new BorderLayout();
    BorderLayout              borderLayout119     = new BorderLayout();
    BorderLayout              borderLayout12      = new BorderLayout();
    BorderLayout              borderLayout13      = new BorderLayout();
    BorderLayout              borderLayout14      = new BorderLayout();
    BorderLayout              borderLayout15      = new BorderLayout();
    BorderLayout              borderLayout16      = new BorderLayout();
    BorderLayout              borderLayout17      = new BorderLayout();
    BorderLayout              borderLayout18      = new BorderLayout();
    BorderLayout              borderLayout19      = new BorderLayout();
    BorderLayout              borderLayout2       = new BorderLayout();
    BorderLayout              borderLayout3       = new BorderLayout();
    BorderLayout              borderLayout4       = new BorderLayout();
    BorderLayout              borderLayout5       = new BorderLayout();
    BorderLayout              borderLayout6       = new BorderLayout();
    BorderLayout              borderLayout7       = new BorderLayout();
    BorderLayout              borderLayout8       = new BorderLayout();
    BorderLayout              borderLayout9       = new BorderLayout();
    DeviceButtons             deviceButtons1      = new DeviceButtons();
    DeviceChannel             deviceChannel1      = new DeviceChannel();
    DeviceChannel             deviceChannel10     = new DeviceChannel();
    DeviceChannel             deviceChannel13     = new DeviceChannel();
    DeviceChannel             deviceChannel14     = new DeviceChannel();
    DeviceChannel             deviceChannel2      = new DeviceChannel();
    DeviceChannel             deviceChannel3      = new DeviceChannel();
    DeviceChannel             deviceChannel4      = new DeviceChannel();
    DeviceChannel             deviceChannel5      = new DeviceChannel();
    DeviceChannel             deviceChannel6      = new DeviceChannel();
    DeviceChannel             deviceChannel7      = new DeviceChannel();
    DeviceChannel             deviceChannel8      = new DeviceChannel();
    DeviceChannel             deviceChannel9      = new DeviceChannel();
    DeviceChoice              deviceChoice1       = new DeviceChoice();
    DeviceField               deviceField1        = new DeviceField();
    DeviceField               deviceField10       = new DeviceField();
    DeviceField               deviceField11       = new DeviceField();
    DeviceField               deviceField110      = new DeviceField();
    DeviceField               deviceField111      = new DeviceField();
    DeviceField               deviceField1110     = new DeviceField();
    DeviceField               deviceField1111     = new DeviceField();
    DeviceField               deviceField11110    = new DeviceField();
    DeviceField               deviceField11111    = new DeviceField();
    DeviceField               deviceField11112    = new DeviceField();
    DeviceField               deviceField11113    = new DeviceField();
    DeviceField               deviceField1118     = new DeviceField();
    DeviceField               deviceField1119     = new DeviceField();
    DeviceField               deviceField112      = new DeviceField();
    DeviceField               deviceField113      = new DeviceField();
    DeviceField               deviceField114      = new DeviceField();
    DeviceField               deviceField115      = new DeviceField();
    DeviceField               deviceField116      = new DeviceField();
    DeviceField               deviceField117      = new DeviceField();
    DeviceField               deviceField118      = new DeviceField();
    DeviceField               deviceField119      = new DeviceField();
    DeviceField               deviceField12       = new DeviceField();
    DeviceField               deviceField13       = new DeviceField();
    DeviceField               deviceField14       = new DeviceField();
    DeviceField               deviceField15       = new DeviceField();
    DeviceField               deviceField16       = new DeviceField();
    DeviceField               deviceField17       = new DeviceField();
    DeviceField               deviceField18       = new DeviceField();
    DeviceField               deviceField19       = new DeviceField();
    DeviceField               deviceField2        = new DeviceField();
    DeviceField               deviceField20       = new DeviceField();
    DeviceField               deviceField21       = new DeviceField();
    DeviceField               deviceField212      = new DeviceField();
    DeviceField               deviceField213      = new DeviceField();
    DeviceField               deviceField22       = new DeviceField();
    DeviceField               deviceField23       = new DeviceField();
    DeviceField               deviceField24       = new DeviceField();
    DeviceField               deviceField25       = new DeviceField();
    DeviceField               deviceField26       = new DeviceField();
    DeviceField               deviceField27       = new DeviceField();
    DeviceField               deviceField28       = new DeviceField();
    DeviceField               deviceField29       = new DeviceField();
    DeviceField               deviceField3        = new DeviceField();
    DeviceField               deviceField30       = new DeviceField();
    DeviceField               deviceField310      = new DeviceField();
    DeviceField               deviceField311      = new DeviceField();
    DeviceField               deviceField314      = new DeviceField();
    DeviceField               deviceField315      = new DeviceField();
    DeviceField               deviceField32       = new DeviceField();
    DeviceField               deviceField33       = new DeviceField();
    DeviceField               deviceField34       = new DeviceField();
    DeviceField               deviceField35       = new DeviceField();
    DeviceField               deviceField36       = new DeviceField();
    DeviceField               deviceField37       = new DeviceField();
    DeviceField               deviceField38       = new DeviceField();
    DeviceField               deviceField39       = new DeviceField();
    DeviceField               deviceField4        = new DeviceField();
    DeviceField               deviceField5        = new DeviceField();
    DeviceField               deviceField6        = new DeviceField();
    DeviceField               deviceField7        = new DeviceField();
    DeviceField               deviceField8        = new DeviceField();
    DeviceField               deviceField9        = new DeviceField();
    DeviceWave                deviceWave1         = new DeviceWave();
    DeviceWave                deviceWave10        = new DeviceWave();
    DeviceWave                deviceWave11        = new DeviceWave();
    DeviceWave                deviceWave110       = new DeviceWave();
    DeviceWave                deviceWave115       = new DeviceWave();
    DeviceWave                deviceWave116       = new DeviceWave();
    DeviceWave                deviceWave117       = new DeviceWave();
    DeviceWave                deviceWave118       = new DeviceWave();
    DeviceWave                deviceWave12        = new DeviceWave();
    DeviceWave                deviceWave13        = new DeviceWave();
    DeviceWave                deviceWave14        = new DeviceWave();
    DeviceWave                deviceWave15        = new DeviceWave();
    DeviceWave                deviceWave16        = new DeviceWave();
    DeviceWave                deviceWave17        = new DeviceWave();
    DeviceWave                deviceWave18        = new DeviceWave();
    DeviceWave                deviceWave19        = new DeviceWave();
    DeviceWave                deviceWave2         = new DeviceWave();
    DeviceWave                deviceWave3         = new DeviceWave();
    DeviceWave                deviceWave4         = new DeviceWave();
    DeviceWave                deviceWave5         = new DeviceWave();
    DeviceWave                deviceWave6         = new DeviceWave();
    DeviceWave                deviceWave7         = new DeviceWave();
    DeviceWave                deviceWave8         = new DeviceWave();
    DeviceWave                deviceWave9         = new DeviceWave();
    DeviceWaveDisplay         deviceWaveDisplay1  = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay10 = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay13 = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay14 = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay2  = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay3  = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay4  = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay5  = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay6  = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay7  = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay8  = new DeviceWaveDisplay();
    DeviceWaveDisplay         deviceWaveDisplay9  = new DeviceWaveDisplay();
    JLabel                    jLabel1             = new JLabel();
    JLabel                    jLabel10            = new JLabel();
    JLabel                    jLabel13            = new JLabel();
    JLabel                    jLabel14            = new JLabel();
    JLabel                    jLabel2             = new JLabel();
    JLabel                    jLabel3             = new JLabel();
    JLabel                    jLabel4             = new JLabel();
    JLabel                    jLabel5             = new JLabel();
    JLabel                    jLabel6             = new JLabel();
    JLabel                    jLabel7             = new JLabel();
    JLabel                    jLabel8             = new JLabel();
    JLabel                    jLabel9             = new JLabel();
    JPanel                    jPanel1             = new JPanel();
    JPanel                    jPanel10            = new JPanel();
    JPanel                    jPanel11            = new JPanel();
    JPanel                    jPanel110           = new JPanel();
    JPanel                    jPanel111           = new JPanel();
    JPanel                    jPanel1110          = new JPanel();
    JPanel                    jPanel1111          = new JPanel();
    JPanel                    jPanel11110         = new JPanel();
    JPanel                    jPanel11111         = new JPanel();
    JPanel                    jPanel111110        = new JPanel();
    JPanel                    jPanel111111        = new JPanel();
    JPanel                    jPanel111112        = new JPanel();
    JPanel                    jPanel111113        = new JPanel();
    JPanel                    jPanel111114        = new JPanel();
    JPanel                    jPanel111115        = new JPanel();
    JPanel                    jPanel111116        = new JPanel();
    JPanel                    jPanel111117        = new JPanel();
    JPanel                    jPanel1112          = new JPanel();
    JPanel                    jPanel1113          = new JPanel();
    JPanel                    jPanel1114          = new JPanel();
    JPanel                    jPanel1115          = new JPanel();
    JPanel                    jPanel1116          = new JPanel();
    JPanel                    jPanel1117          = new JPanel();
    JPanel                    jPanel1118          = new JPanel();
    JPanel                    jPanel1119          = new JPanel();
    JPanel                    jPanel112           = new JPanel();
    JPanel                    jPanel113           = new JPanel();
    JPanel                    jPanel114           = new JPanel();
    JPanel                    jPanel115           = new JPanel();
    JPanel                    jPanel116           = new JPanel();
    JPanel                    jPanel117           = new JPanel();
    JPanel                    jPanel118           = new JPanel();
    JPanel                    jPanel119           = new JPanel();
    JPanel                    jPanel12            = new JPanel();
    JPanel                    jPanel13            = new JPanel();
    JPanel                    jPanel14            = new JPanel();
    JPanel                    jPanel15            = new JPanel();
    JPanel                    jPanel16            = new JPanel();
    JPanel                    jPanel17            = new JPanel();
    JPanel                    jPanel18            = new JPanel();
    JPanel                    jPanel19            = new JPanel();
    JPanel                    jPanel2             = new JPanel();
    JPanel                    jPanel20            = new JPanel();
    JPanel                    jPanel21            = new JPanel();
    JPanel                    jPanel212           = new JPanel();
    JPanel                    jPanel213           = new JPanel();
    JPanel                    jPanel22            = new JPanel();
    JPanel                    jPanel23            = new JPanel();
    JPanel                    jPanel24            = new JPanel();
    JPanel                    jPanel25            = new JPanel();
    JPanel                    jPanel26            = new JPanel();
    JPanel                    jPanel27            = new JPanel();
    JPanel                    jPanel28            = new JPanel();
    JPanel                    jPanel29            = new JPanel();
    JPanel                    jPanel3             = new JPanel();
    JPanel                    jPanel4             = new JPanel();
    JPanel                    jPanel5             = new JPanel();
    JPanel                    jPanel6             = new JPanel();
    JPanel                    jPanel7             = new JPanel();
    JPanel                    jPanel8             = new JPanel();
    JPanel                    jPanel9             = new JPanel();
    JTabbedPane               jTabbedPane1        = new JTabbedPane();
    TitledBorder              titledBorder1;

    public RFXInverterSetupSetup(){
        try{
            this.jbInit();
        }catch(final Exception e){
            e.printStackTrace();
        }
    }

    private void jbInit() throws Exception {
        this.border1 = BorderFactory.createLineBorder(Color.white, 1);
        this.titledBorder1 = new TitledBorder(BorderFactory.createLineBorder(Color.white, 1), "Perturbation gain and preview");
        this.setWidth(800);
        this.setHeight(650);
        this.setDeviceType("RFXInverterSetup");
        this.setDeviceProvider("localhost");
        this.setDeviceTitle("EDA2 Inverter Setup");
        this.getContentPane().setLayout(this.borderLayout1);
        this.deviceField1.setOffsetNid(1);
        this.deviceField1.setTextOnly(true);
        this.deviceField1.setLabelString("Comment: ");
        this.deviceField1.setNumCols(20);
        this.deviceField1.setIdentifier("");
        this.deviceChannel1.setLabelString("On");
        this.deviceChannel1.setOffsetNid(5);
        this.deviceChannel1.setUpdateIdentifier("");
        this.deviceChannel1.setShowVal("");
        this.jPanel2.setLayout(this.borderLayout2);
        this.deviceField30.setOffsetNid(3);
        this.deviceField30.setTextOnly(true);
        this.deviceField30.setLabelString("Control");
        this.deviceField30.setIdentifier("");
        this.deviceField30.setEditable(false);
        this.deviceField30.setDisplayEvaluated(true);
        this.deviceField32.setOffsetNid(18);
        this.deviceField32.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField32.setIdentifier("");
        this.deviceField32.setEditable(false);
        this.jPanel4.setLayout(this.borderLayout3);
        this.deviceField3.setOffsetNid(22);
        this.deviceField3.setLabelString("Phase (rad.):");
        this.deviceField3.setNumCols(4);
        this.deviceField3.setIdentifier("");
        this.jLabel1.setText("Perturbation:");
        this.deviceField20.setOffsetNid(21);
        this.deviceField20.setLabelString("Freq. (Hz)");
        this.deviceField20.setNumCols(4);
        this.deviceField20.setIdentifier("");
        this.deviceField4.setOffsetNid(20);
        this.deviceField4.setLabelString("Amp.:");
        this.deviceField4.setNumCols(4);
        this.deviceField4.setIdentifier("");
        this.deviceField2.setOffsetNid(23);
        this.deviceField2.setLabelString("Start Time:");
        this.deviceField2.setNumCols(4);
        this.deviceField2.setIdentifier("");
        this.deviceWave2.setOffsetNid(6);
        this.deviceWave2.setMinYVisible(true);
        this.deviceWave2.setIdentifier("");
        this.deviceWave2.setUpdateExpression("");
        this.deviceWave2.setPrefHeight(100);
        this.jPanel5.setBorder(this.titledBorder1);
        this.jPanel5.setLayout(this.borderLayout4);
        this.deviceWaveDisplay1.setOffsetNid(17);
        this.deviceWave1.setOffsetNid(11);
        this.deviceWave1.setMaxYVisible(true);
        this.deviceWave1.setIdentifier("");
        this.deviceWave1.setUpdateExpression("");
        this.deviceField33.setIdentifier("");
        this.deviceField33.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField33.setOffsetNid(37);
        this.deviceField33.setEditable(false);
        this.deviceField5.setIdentifier("");
        this.deviceField5.setNumCols(4);
        this.deviceField5.setLabelString("Phase (rad.):");
        this.deviceField5.setOffsetNid(41);
        this.jPanel6.setLayout(this.borderLayout6);
        this.deviceChannel2.setLabelString("On");
        this.deviceChannel2.setOffsetNid(24);
        this.deviceChannel2.setUpdateIdentifier("");
        this.deviceChannel2.setShowVal("");
        this.jLabel2.setText("Perturbation:");
        this.deviceWave3.setOffsetNid(25);
        this.deviceWave3.setMinYVisible(true);
        this.deviceWave3.setIdentifier("");
        this.deviceWave3.setUpdateExpression("");
        this.deviceWave3.setPrefHeight(100);
        this.deviceField6.setOffsetNid(39);
        this.deviceField6.setLabelString("Amp.:");
        this.deviceField6.setNumCols(4);
        this.deviceField6.setIdentifier("");
        this.deviceWave4.setOffsetNid(30);
        this.deviceWave4.setMaxYVisible(true);
        this.deviceWave4.setIdentifier("");
        this.deviceWave4.setUpdateExpression("");
        this.jPanel8.setLayout(this.borderLayout5);
        this.deviceField21.setOffsetNid(40);
        this.deviceField21.setLabelString("Freq. (Hz)");
        this.deviceField21.setNumCols(4);
        this.deviceField21.setIdentifier("");
        this.jPanel9.setBorder(this.titledBorder1);
        this.jPanel9.setLayout(this.borderLayout7);
        this.deviceWaveDisplay2.setOffsetNid(36);
        this.deviceField7.setOffsetNid(42);
        this.deviceField7.setLabelString("Start Time:");
        this.deviceField7.setNumCols(4);
        this.deviceField7.setIdentifier("");
        this.deviceField34.setIdentifier("");
        this.deviceField34.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField34.setOffsetNid(56);
        this.deviceField34.setEditable(false);
        this.deviceField8.setIdentifier("");
        this.deviceField8.setNumCols(4);
        this.deviceField8.setLabelString("Phase (rad.):");
        this.deviceField8.setOffsetNid(60);
        this.jPanel10.setLayout(this.borderLayout9);
        this.deviceChannel3.setLabelString("On");
        this.deviceChannel3.setOffsetNid(43);
        this.deviceChannel3.setUpdateIdentifier("");
        this.deviceChannel3.setShowVal("");
        this.jLabel3.setText("Perturbation:");
        this.deviceWave5.setOffsetNid(44);
        this.deviceWave5.setMinYVisible(true);
        this.deviceWave5.setIdentifier("");
        this.deviceWave5.setUpdateExpression("");
        this.deviceWave5.setPrefHeight(100);
        this.deviceField9.setOffsetNid(58);
        this.deviceField9.setLabelString("Amp.:");
        this.deviceField9.setNumCols(4);
        this.deviceField9.setIdentifier("");
        this.deviceWave6.setOffsetNid(49);
        this.deviceWave6.setMaxYVisible(true);
        this.deviceWave6.setIdentifier("");
        this.deviceWave6.setUpdateExpression("");
        this.jPanel12.setLayout(this.borderLayout8);
        this.deviceField22.setOffsetNid(59);
        this.deviceField22.setLabelString("Freq. (Hz)");
        this.deviceField22.setNumCols(4);
        this.deviceField22.setIdentifier("");
        this.jPanel13.setBorder(this.titledBorder1);
        this.jPanel13.setLayout(this.borderLayout10);
        this.deviceWaveDisplay3.setOffsetNid(55);
        this.deviceField10.setOffsetNid(61);
        this.deviceField10.setLabelString("Start Time:");
        this.deviceField10.setNumCols(4);
        this.deviceField10.setIdentifier("");
        this.deviceField35.setIdentifier("");
        this.deviceField35.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField35.setOffsetNid(75);
        this.deviceField35.setEditable(false);
        this.deviceField11.setIdentifier("");
        this.deviceField11.setNumCols(4);
        this.deviceField11.setLabelString("Phase (rad.):");
        this.deviceField11.setOffsetNid(79);
        this.jPanel14.setLayout(this.borderLayout12);
        this.deviceChannel4.setLabelString("On");
        this.deviceChannel4.setOffsetNid(62);
        this.deviceChannel4.setUpdateIdentifier("");
        this.deviceChannel4.setShowVal("");
        this.jLabel4.setText("Perturbation:");
        this.deviceWave7.setOffsetNid(63);
        this.deviceWave7.setMinYVisible(true);
        this.deviceWave7.setIdentifier("");
        this.deviceWave7.setUpdateExpression("");
        this.deviceWave7.setPrefHeight(100);
        this.deviceField12.setOffsetNid(77);
        this.deviceField12.setLabelString("Amp.:");
        this.deviceField12.setNumCols(4);
        this.deviceField12.setIdentifier("");
        this.deviceWave8.setOffsetNid(68);
        this.deviceWave8.setMaxYVisible(true);
        this.deviceWave8.setIdentifier("");
        this.deviceWave8.setUpdateExpression("");
        this.jPanel16.setLayout(this.borderLayout11);
        this.deviceField23.setOffsetNid(78);
        this.deviceField23.setLabelString("Freq. (Hz)");
        this.deviceField23.setNumCols(4);
        this.deviceField23.setIdentifier("");
        this.jPanel17.setBorder(this.titledBorder1);
        this.jPanel17.setLayout(this.borderLayout13);
        this.deviceWaveDisplay4.setOffsetNid(74);
        this.deviceField13.setOffsetNid(80);
        this.deviceField13.setLabelString("Start Time:");
        this.deviceField13.setNumCols(4);
        this.deviceField13.setIdentifier("");
        this.deviceField36.setIdentifier("");
        this.deviceField36.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField36.setOffsetNid(94);
        this.deviceField36.setEditable(false);
        this.deviceField14.setIdentifier("");
        this.deviceField14.setNumCols(4);
        this.deviceField14.setLabelString("Phase (rad.):");
        this.deviceField14.setOffsetNid(98);
        this.jPanel18.setLayout(this.borderLayout15);
        this.deviceChannel5.setLabelString("On");
        this.deviceChannel5.setOffsetNid(81);
        this.deviceChannel5.setUpdateIdentifier("");
        this.deviceChannel5.setShowVal("");
        this.jLabel5.setText("Perturbation:");
        this.deviceWave9.setOffsetNid(82);
        this.deviceWave9.setMinYVisible(true);
        this.deviceWave9.setIdentifier("");
        this.deviceWave9.setUpdateExpression("");
        this.deviceWave9.setPrefHeight(100);
        this.deviceField15.setOffsetNid(96);
        this.deviceField15.setLabelString("Amp.:");
        this.deviceField15.setNumCols(4);
        this.deviceField15.setIdentifier("");
        this.deviceWave10.setOffsetNid(87);
        this.deviceWave10.setMaxYVisible(true);
        this.deviceWave10.setIdentifier("");
        this.deviceWave10.setUpdateExpression("");
        this.jPanel110.setLayout(this.borderLayout14);
        this.deviceField24.setOffsetNid(97);
        this.deviceField24.setLabelString("Freq. (Hz)");
        this.deviceField24.setNumCols(4);
        this.deviceField24.setIdentifier("");
        this.jPanel111.setBorder(this.titledBorder1);
        this.jPanel111.setLayout(this.borderLayout16);
        this.deviceWaveDisplay5.setOffsetNid(93);
        this.deviceField16.setOffsetNid(99);
        this.deviceField16.setLabelString("Start Time:");
        this.deviceField16.setNumCols(4);
        this.deviceField16.setIdentifier("");
        this.deviceField37.setIdentifier("");
        this.deviceField37.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField37.setOffsetNid(113);
        this.deviceField37.setEditable(false);
        this.deviceField17.setIdentifier("");
        this.deviceField17.setNumCols(4);
        this.deviceField17.setLabelString("Phase (rad.):");
        this.deviceField17.setOffsetNid(117);
        this.jPanel112.setLayout(this.borderLayout18);
        this.deviceChannel6.setLabelString("On");
        this.deviceChannel6.setOffsetNid(100);
        this.deviceChannel6.setUpdateIdentifier("");
        this.deviceChannel6.setShowVal("");
        this.jLabel6.setText("Perturbation:");
        this.deviceWave11.setOffsetNid(101);
        this.deviceWave11.setMinYVisible(true);
        this.deviceWave11.setIdentifier("");
        this.deviceWave11.setUpdateExpression("");
        this.deviceWave11.setPrefHeight(100);
        this.deviceField18.setOffsetNid(115);
        this.deviceField18.setLabelString("Amp.:");
        this.deviceField18.setNumCols(4);
        this.deviceField18.setIdentifier("");
        this.deviceWave12.setOffsetNid(106);
        this.deviceWave12.setMaxYVisible(true);
        this.deviceWave12.setIdentifier("");
        this.deviceWave12.setUpdateExpression("");
        this.jPanel114.setLayout(this.borderLayout17);
        this.deviceField25.setOffsetNid(116);
        this.deviceField25.setLabelString("Freq. (Hz)");
        this.deviceField25.setNumCols(4);
        this.deviceField25.setIdentifier("");
        this.jPanel115.setBorder(this.titledBorder1);
        this.jPanel115.setLayout(this.borderLayout19);
        this.deviceWaveDisplay6.setOffsetNid(112);
        this.deviceField19.setOffsetNid(118);
        this.deviceField19.setLabelString("Start Time:");
        this.deviceField19.setNumCols(4);
        this.deviceField19.setIdentifier("");
        this.deviceField38.setIdentifier("");
        this.deviceField38.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField38.setOffsetNid(132);
        this.deviceField38.setEditable(false);
        this.deviceField110.setIdentifier("");
        this.deviceField110.setNumCols(4);
        this.deviceField110.setLabelString("Phase (rad.):");
        this.deviceField110.setOffsetNid(136);
        this.jPanel116.setLayout(this.borderLayout111);
        this.deviceChannel7.setLabelString("On");
        this.deviceChannel7.setOffsetNid(119);
        this.deviceChannel7.setUpdateIdentifier("");
        this.deviceChannel7.setShowVal("");
        this.jLabel7.setText("Perturbation:");
        this.deviceWave13.setOffsetNid(120);
        this.deviceWave13.setMinYVisible(true);
        this.deviceWave13.setIdentifier("");
        this.deviceWave13.setUpdateExpression("");
        this.deviceWave13.setPrefHeight(100);
        this.deviceField111.setOffsetNid(134);
        this.deviceField111.setLabelString("Amp.:");
        this.deviceField111.setNumCols(4);
        this.deviceField111.setIdentifier("");
        this.deviceWave14.setOffsetNid(125);
        this.deviceWave14.setMaxYVisible(true);
        this.deviceWave14.setIdentifier("");
        this.deviceWave14.setUpdateExpression("");
        this.jPanel118.setLayout(this.borderLayout110);
        this.deviceField26.setOffsetNid(135);
        this.deviceField26.setLabelString("Freq. (Hz)");
        this.deviceField26.setNumCols(4);
        this.deviceField26.setIdentifier("");
        this.jPanel119.setBorder(this.titledBorder1);
        this.jPanel119.setLayout(this.borderLayout112);
        this.deviceWaveDisplay7.setOffsetNid(131);
        this.deviceField112.setOffsetNid(137);
        this.deviceField112.setLabelString("Start Time:");
        this.deviceField112.setNumCols(4);
        this.deviceField112.setIdentifier("");
        this.deviceField39.setIdentifier("");
        this.deviceField39.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField39.setOffsetNid(151);
        this.deviceField39.setEditable(false);
        this.deviceField113.setIdentifier("");
        this.deviceField113.setNumCols(4);
        this.deviceField113.setLabelString("Phase (rad.):");
        this.deviceField113.setOffsetNid(155);
        this.jPanel1110.setLayout(this.borderLayout114);
        this.deviceChannel8.setLabelString("On");
        this.deviceChannel8.setOffsetNid(138);
        this.deviceChannel8.setUpdateIdentifier("");
        this.deviceChannel8.setShowVal("");
        this.jLabel8.setText("Perturbation:");
        this.deviceWave15.setOffsetNid(139);
        this.deviceWave15.setMinYVisible(true);
        this.deviceWave15.setIdentifier("");
        this.deviceWave15.setUpdateExpression("");
        this.deviceWave15.setPrefHeight(100);
        this.deviceField114.setOffsetNid(153);
        this.deviceField114.setLabelString("Amp.:");
        this.deviceField114.setNumCols(4);
        this.deviceField114.setIdentifier("");
        this.deviceWave16.setOffsetNid(144);
        this.deviceWave16.setMaxYVisible(true);
        this.deviceWave16.setIdentifier("");
        this.deviceWave16.setUpdateExpression("");
        this.jPanel1112.setLayout(this.borderLayout113);
        this.deviceField27.setOffsetNid(154);
        this.deviceField27.setLabelString("Freq. (Hz)");
        this.deviceField27.setNumCols(4);
        this.deviceField27.setIdentifier("");
        this.jPanel1113.setBorder(this.titledBorder1);
        this.jPanel1113.setLayout(this.borderLayout115);
        this.deviceWaveDisplay8.setOffsetNid(150);
        this.deviceField115.setOffsetNid(156);
        this.deviceField115.setLabelString("Start Time:");
        this.deviceField115.setNumCols(4);
        this.deviceField115.setIdentifier("");
        this.deviceField310.setIdentifier("");
        this.deviceField310.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField310.setOffsetNid(170);
        this.deviceField310.setEditable(false);
        this.deviceField116.setIdentifier("");
        this.deviceField116.setNumCols(4);
        this.deviceField116.setLabelString("Phase (rad.):");
        this.deviceField116.setOffsetNid(174);
        this.jPanel1114.setLayout(this.borderLayout117);
        this.deviceChannel9.setLabelString("On");
        this.deviceChannel9.setOffsetNid(157);
        this.deviceChannel9.setUpdateIdentifier("");
        this.deviceChannel9.setShowVal("");
        this.jLabel9.setText("Perturbation:");
        this.deviceWave17.setOffsetNid(158);
        this.deviceWave17.setMinYVisible(true);
        this.deviceWave17.setIdentifier("");
        this.deviceWave17.setUpdateExpression("");
        this.deviceWave17.setPrefHeight(100);
        this.deviceField117.setOffsetNid(172);
        this.deviceField117.setLabelString("Amp.:");
        this.deviceField117.setNumCols(4);
        this.deviceField117.setIdentifier("");
        this.deviceWave18.setOffsetNid(163);
        this.deviceWave18.setMaxYVisible(true);
        this.deviceWave18.setIdentifier("");
        this.deviceWave18.setUpdateExpression("");
        this.jPanel1116.setLayout(this.borderLayout116);
        this.deviceField28.setOffsetNid(173);
        this.deviceField28.setLabelString("Freq. (Hz)");
        this.deviceField28.setNumCols(4);
        this.deviceField28.setIdentifier("");
        this.jPanel1117.setBorder(this.titledBorder1);
        this.jPanel1117.setLayout(this.borderLayout118);
        this.deviceWaveDisplay9.setOffsetNid(169);
        this.deviceField118.setOffsetNid(175);
        this.deviceField118.setLabelString("Start Time:");
        this.deviceField118.setNumCols(4);
        this.deviceField118.setIdentifier("");
        this.deviceField311.setIdentifier("");
        this.deviceField311.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField311.setOffsetNid(189);
        this.deviceField311.setEditable(false);
        this.deviceField119.setIdentifier("");
        this.deviceField119.setNumCols(4);
        this.deviceField119.setLabelString("Phase (rad.):");
        this.deviceField119.setOffsetNid(193);
        this.jPanel1118.setLayout(this.borderLayout1110);
        this.deviceChannel10.setLabelString("On");
        this.deviceChannel10.setOffsetNid(176);
        this.deviceChannel10.setUpdateIdentifier("");
        this.deviceChannel10.setShowVal("");
        this.jLabel10.setText("Perturbation:");
        this.deviceWave19.setOffsetNid(177);
        this.deviceWave19.setMinYVisible(true);
        this.deviceWave19.setIdentifier("");
        this.deviceWave19.setUpdateExpression("");
        this.deviceWave19.setPrefHeight(100);
        this.deviceField1110.setOffsetNid(191);
        this.deviceField1110.setLabelString("Amp.:");
        this.deviceField1110.setNumCols(4);
        this.deviceField1110.setIdentifier("");
        this.deviceWave110.setOffsetNid(182);
        this.deviceWave110.setMaxYVisible(true);
        this.deviceWave110.setIdentifier("");
        this.deviceWave110.setUpdateExpression("");
        this.jPanel11110.setLayout(this.borderLayout119);
        this.deviceField29.setOffsetNid(192);
        this.deviceField29.setLabelString("Freq. (Hz)");
        this.deviceField29.setNumCols(4);
        this.deviceField29.setIdentifier("");
        this.jPanel11111.setBorder(this.titledBorder1);
        this.jPanel11111.setLayout(this.borderLayout1111);
        this.deviceWaveDisplay10.setOffsetNid(188);
        this.deviceField1111.setOffsetNid(194);
        this.deviceField1111.setLabelString("Start Time:");
        this.deviceField1111.setNumCols(4);
        this.deviceField1111.setIdentifier("");
        this.deviceField314.setIdentifier("");
        this.deviceField314.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField314.setOffsetNid(208);
        this.deviceField314.setEditable(false);
        this.deviceField1118.setIdentifier("");
        this.deviceField1118.setNumCols(4);
        this.deviceField1118.setLabelString("Phase (rad.):");
        this.deviceField1118.setOffsetNid(212);
        this.jPanel111110.setLayout(this.borderLayout1119);
        this.deviceChannel13.setLabelString("On");
        this.deviceChannel13.setOffsetNid(195);
        this.deviceChannel13.setUpdateIdentifier("");
        this.deviceChannel13.setShowVal("");
        this.jLabel13.setText("Perturbation:");
        this.deviceWave115.setOffsetNid(196);
        this.deviceWave115.setMinYVisible(true);
        this.deviceWave115.setIdentifier("");
        this.deviceWave115.setUpdateExpression("");
        this.deviceWave115.setPrefHeight(100);
        this.deviceField1119.setOffsetNid(210);
        this.deviceField1119.setLabelString("Amp.:");
        this.deviceField1119.setNumCols(4);
        this.deviceField1119.setIdentifier("");
        this.deviceWave116.setOffsetNid(201);
        this.deviceWave116.setMaxYVisible(true);
        this.deviceWave116.setIdentifier("");
        this.deviceWave116.setUpdateExpression("");
        this.jPanel111112.setLayout(this.borderLayout1118);
        this.deviceField212.setOffsetNid(211);
        this.deviceField212.setLabelString("Freq. (Hz)");
        this.deviceField212.setNumCols(4);
        this.deviceField212.setIdentifier("");
        this.jPanel111113.setBorder(this.titledBorder1);
        this.jPanel111113.setLayout(this.borderLayout11110);
        this.deviceWaveDisplay13.setOffsetNid(207);
        this.deviceField11110.setOffsetNid(213);
        this.deviceField11110.setLabelString("Start Time:");
        this.deviceField11110.setNumCols(4);
        this.deviceField11110.setIdentifier("");
        this.deviceField315.setIdentifier("");
        this.deviceField315.setLabelString("ITH_INV_END_FORCE: ");
        this.deviceField315.setOffsetNid(227);
        this.deviceField315.setEditable(false);
        this.deviceField11111.setIdentifier("");
        this.deviceField11111.setNumCols(4);
        this.deviceField11111.setLabelString("Phase (rad.):");
        this.deviceField11111.setOffsetNid(231);
        this.jPanel111114.setLayout(this.borderLayout11112);
        this.deviceChannel14.setLabelString("On");
        this.deviceChannel14.setOffsetNid(214);
        this.deviceChannel14.setUpdateIdentifier("");
        this.deviceChannel14.setShowVal("");
        this.jLabel14.setText("Perturbation:");
        this.deviceWave117.setOffsetNid(215);
        this.deviceWave117.setMinYVisible(true);
        this.deviceWave117.setIdentifier("");
        this.deviceWave117.setUpdateExpression("");
        this.deviceWave117.setPrefHeight(215);
        this.deviceField11112.setOffsetNid(229);
        this.deviceField11112.setLabelString("Amp.:");
        this.deviceField11112.setNumCols(4);
        this.deviceField11112.setIdentifier("");
        this.deviceWave118.setOffsetNid(220);
        this.deviceWave118.setMaxYVisible(true);
        this.deviceWave118.setIdentifier("");
        this.deviceWave118.setUpdateExpression("");
        this.jPanel111116.setLayout(this.borderLayout11111);
        this.deviceField213.setOffsetNid(230);
        this.deviceField213.setLabelString("Freq. (Hz)");
        this.deviceField213.setNumCols(4);
        this.deviceField213.setIdentifier("");
        this.jPanel111117.setBorder(this.titledBorder1);
        this.jPanel111117.setLayout(this.borderLayout11113);
        this.deviceWaveDisplay14.setOffsetNid(226);
        this.deviceField11113.setOffsetNid(232);
        this.deviceField11113.setLabelString("Start Time:");
        this.deviceField11113.setNumCols(4);
        this.deviceField11113.setIdentifier("");
        this.deviceChoice1.setChoiceIntValues(new int[]{1, 2, 3, 4, 5, 6, 7, 8, 9});
        this.deviceChoice1.setChoiceFloatValues(null);
        this.deviceChoice1.setConvert(true);
        this.deviceChoice1.setOffsetNid(233);
        this.deviceChoice1.setLabelString("Pert. Form: ");
        this.deviceChoice1.setChoiceItems(new String[]{"COSINE", "TRIANGLE", "SQUARE", "SAWTOOTH RIGHT", "SAWTOOTH LEFT", "SAWTOOTH RIGHT UP", "SAWTOOTH LEFT UP", "SAWTOOTH RIGHT DOWN", "SAWTOOTH LEFT DOWN"});
        this.deviceChoice1.setUpdateIdentifier("");
        this.deviceChoice1.setIdentifier("");
        this.getContentPane().add(this.jPanel1, BorderLayout.NORTH);
        this.jPanel1.add(this.deviceField1, null);
        this.jPanel1.add(this.deviceField30, null);
        this.jPanel1.add(this.deviceChoice1, null);
        this.getContentPane().add(this.deviceButtons1, BorderLayout.SOUTH);
        this.getContentPane().add(this.jTabbedPane1, BorderLayout.CENTER);
        this.jTabbedPane1.add(this.deviceChannel1, "1");
        this.deviceChannel1.add(this.jPanel2, BorderLayout.CENTER);
        this.jPanel2.add(this.jPanel20, BorderLayout.NORTH);
        this.jPanel20.add(this.deviceField32, null);
        this.jPanel2.add(this.jPanel4, BorderLayout.SOUTH);
        this.jPanel3.add(this.jLabel1, null);
        this.jPanel3.add(this.deviceField4, null);
        this.jPanel3.add(this.deviceField20, null);
        this.jPanel3.add(this.deviceField3, null);
        this.jPanel3.add(this.deviceField2, null);
        this.jPanel4.add(this.deviceWave2, BorderLayout.NORTH);
        this.jPanel4.add(this.jPanel3, BorderLayout.SOUTH);
        this.jPanel2.add(this.jPanel5, BorderLayout.CENTER);
        this.jPanel5.add(this.deviceWaveDisplay1, BorderLayout.EAST);
        this.jPanel5.add(this.deviceWave1, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel2, "2");
        this.deviceChannel2.add(this.jPanel8, BorderLayout.CENTER);
        this.jPanel8.add(this.jPanel21, BorderLayout.NORTH);
        this.jPanel21.add(this.deviceField33, null);
        this.jPanel8.add(this.jPanel6, BorderLayout.SOUTH);
        this.jPanel6.add(this.deviceWave3, BorderLayout.NORTH);
        this.jPanel6.add(this.jPanel7, BorderLayout.SOUTH);
        this.jPanel7.add(this.jLabel2, null);
        this.jPanel7.add(this.deviceField6, null);
        this.jPanel7.add(this.deviceField21, null);
        this.jPanel7.add(this.deviceField5, null);
        this.jPanel7.add(this.deviceField7, null);
        this.jPanel8.add(this.jPanel9, BorderLayout.CENTER);
        this.jPanel9.add(this.deviceWaveDisplay2, BorderLayout.EAST);
        this.jPanel9.add(this.deviceWave4, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel3, "3");
        this.deviceChannel3.add(this.jPanel12, BorderLayout.CENTER);
        this.jPanel12.add(this.jPanel22, BorderLayout.NORTH);
        this.jPanel22.add(this.deviceField34, null);
        this.jPanel12.add(this.jPanel10, BorderLayout.SOUTH);
        this.jPanel10.add(this.deviceWave5, BorderLayout.NORTH);
        this.jPanel10.add(this.jPanel11, BorderLayout.SOUTH);
        this.jPanel11.add(this.jLabel3, null);
        this.jPanel11.add(this.deviceField9, null);
        this.jPanel11.add(this.deviceField22, null);
        this.jPanel11.add(this.deviceField8, null);
        this.jPanel11.add(this.deviceField10, null);
        this.jPanel12.add(this.jPanel13, BorderLayout.CENTER);
        this.jPanel13.add(this.deviceWaveDisplay3, BorderLayout.EAST);
        this.jPanel13.add(this.deviceWave6, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel4, "4");
        this.deviceChannel4.add(this.jPanel16, BorderLayout.CENTER);
        this.jPanel16.add(this.jPanel23, BorderLayout.NORTH);
        this.jPanel23.add(this.deviceField35, null);
        this.jPanel16.add(this.jPanel14, BorderLayout.SOUTH);
        this.jPanel14.add(this.deviceWave7, BorderLayout.NORTH);
        this.jPanel14.add(this.jPanel15, BorderLayout.SOUTH);
        this.jPanel15.add(this.jLabel4, null);
        this.jPanel15.add(this.deviceField12, null);
        this.jPanel15.add(this.deviceField23, null);
        this.jPanel15.add(this.deviceField11, null);
        this.jPanel15.add(this.deviceField13, null);
        this.jPanel16.add(this.jPanel17, BorderLayout.CENTER);
        this.jPanel17.add(this.deviceWaveDisplay4, BorderLayout.EAST);
        this.jPanel17.add(this.deviceWave8, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel5, "5");
        this.deviceChannel5.add(this.jPanel110, BorderLayout.CENTER);
        this.jPanel110.add(this.jPanel24, BorderLayout.NORTH);
        this.jPanel24.add(this.deviceField36, null);
        this.jPanel110.add(this.jPanel18, BorderLayout.SOUTH);
        this.jPanel18.add(this.deviceWave9, BorderLayout.NORTH);
        this.jPanel18.add(this.jPanel19, BorderLayout.SOUTH);
        this.jPanel19.add(this.jLabel5, null);
        this.jPanel19.add(this.deviceField15, null);
        this.jPanel19.add(this.deviceField24, null);
        this.jPanel19.add(this.deviceField14, null);
        this.jPanel19.add(this.deviceField16, null);
        this.jPanel110.add(this.jPanel111, BorderLayout.CENTER);
        this.jPanel111.add(this.deviceWaveDisplay5, BorderLayout.EAST);
        this.jPanel111.add(this.deviceWave10, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel6, "6");
        this.deviceChannel6.add(this.jPanel114, BorderLayout.CENTER);
        this.jPanel114.add(this.jPanel25, BorderLayout.NORTH);
        this.jPanel25.add(this.deviceField37, null);
        this.jPanel114.add(this.jPanel112, BorderLayout.SOUTH);
        this.jPanel112.add(this.deviceWave11, BorderLayout.NORTH);
        this.jPanel112.add(this.jPanel113, BorderLayout.SOUTH);
        this.jPanel113.add(this.jLabel6, null);
        this.jPanel113.add(this.deviceField18, null);
        this.jPanel113.add(this.deviceField25, null);
        this.jPanel113.add(this.deviceField17, null);
        this.jPanel113.add(this.deviceField19, null);
        this.jPanel114.add(this.jPanel115, BorderLayout.CENTER);
        this.jPanel115.add(this.deviceWaveDisplay6, BorderLayout.EAST);
        this.jPanel115.add(this.deviceWave12, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel7, "7");
        this.deviceChannel7.add(this.jPanel118, BorderLayout.CENTER);
        this.jPanel118.add(this.jPanel26, BorderLayout.NORTH);
        this.jPanel26.add(this.deviceField38, null);
        this.jPanel118.add(this.jPanel116, BorderLayout.SOUTH);
        this.jPanel116.add(this.deviceWave13, BorderLayout.NORTH);
        this.jPanel116.add(this.jPanel117, BorderLayout.SOUTH);
        this.jPanel117.add(this.jLabel7, null);
        this.jPanel117.add(this.deviceField111, null);
        this.jPanel117.add(this.deviceField26, null);
        this.jPanel117.add(this.deviceField110, null);
        this.jPanel117.add(this.deviceField112, null);
        this.jPanel118.add(this.jPanel119, BorderLayout.CENTER);
        this.jPanel119.add(this.deviceWaveDisplay7, BorderLayout.EAST);
        this.jPanel119.add(this.deviceWave14, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel8, "8");
        this.deviceChannel8.add(this.jPanel1112, BorderLayout.CENTER);
        this.jPanel1112.add(this.jPanel27, BorderLayout.NORTH);
        this.jPanel27.add(this.deviceField39, null);
        this.jPanel1112.add(this.jPanel1110, BorderLayout.SOUTH);
        this.jPanel1110.add(this.deviceWave15, BorderLayout.NORTH);
        this.jPanel1110.add(this.jPanel1111, BorderLayout.SOUTH);
        this.jPanel1111.add(this.jLabel8, null);
        this.jPanel1111.add(this.deviceField114, null);
        this.jPanel1111.add(this.deviceField27, null);
        this.jPanel1111.add(this.deviceField113, null);
        this.jPanel1111.add(this.deviceField115, null);
        this.jPanel1112.add(this.jPanel1113, BorderLayout.CENTER);
        this.jPanel1113.add(this.deviceWaveDisplay8, BorderLayout.EAST);
        this.jPanel1113.add(this.deviceWave16, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel9, "9");
        this.deviceChannel9.add(this.jPanel1116, BorderLayout.CENTER);
        this.jPanel1116.add(this.jPanel28, BorderLayout.NORTH);
        this.jPanel28.add(this.deviceField310, null);
        this.jPanel1116.add(this.jPanel1114, BorderLayout.SOUTH);
        this.jPanel1114.add(this.deviceWave17, BorderLayout.NORTH);
        this.jPanel1114.add(this.jPanel1115, BorderLayout.SOUTH);
        this.jPanel1115.add(this.jLabel9, null);
        this.jPanel1115.add(this.deviceField117, null);
        this.jPanel1115.add(this.deviceField28, null);
        this.jPanel1115.add(this.deviceField116, null);
        this.jPanel1115.add(this.deviceField118, null);
        this.jPanel1116.add(this.jPanel1117, BorderLayout.CENTER);
        this.jPanel1117.add(this.deviceWaveDisplay9, BorderLayout.EAST);
        this.jPanel1117.add(this.deviceWave18, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel10, "10");
        this.deviceChannel10.add(this.jPanel11110, BorderLayout.CENTER);
        this.jPanel11110.add(this.jPanel29, BorderLayout.NORTH);
        this.jPanel29.add(this.deviceField311, null);
        this.jPanel11110.add(this.jPanel1118, BorderLayout.SOUTH);
        this.jPanel1118.add(this.deviceWave19, BorderLayout.NORTH);
        this.jPanel1118.add(this.jPanel1119, BorderLayout.SOUTH);
        this.jPanel1119.add(this.jLabel10, null);
        this.jPanel1119.add(this.deviceField1110, null);
        this.jPanel1119.add(this.deviceField29, null);
        this.jPanel1119.add(this.deviceField119, null);
        this.jPanel1119.add(this.deviceField1111, null);
        this.jPanel11110.add(this.jPanel11111, BorderLayout.CENTER);
        this.jPanel11111.add(this.deviceWaveDisplay10, BorderLayout.EAST);
        this.jPanel11111.add(this.deviceWave110, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel13, "11");
        this.deviceChannel13.add(this.jPanel111112, BorderLayout.CENTER);
        this.jPanel111112.add(this.jPanel212, BorderLayout.NORTH);
        this.jPanel212.add(this.deviceField314, null);
        this.jPanel111112.add(this.jPanel111110, BorderLayout.SOUTH);
        this.jPanel111110.add(this.deviceWave115, BorderLayout.NORTH);
        this.jPanel111110.add(this.jPanel111111, BorderLayout.SOUTH);
        this.jPanel111111.add(this.jLabel13, null);
        this.jPanel111111.add(this.deviceField1119, null);
        this.jPanel111111.add(this.deviceField212, null);
        this.jPanel111111.add(this.deviceField1118, null);
        this.jPanel111111.add(this.deviceField11110, null);
        this.jPanel111112.add(this.jPanel111113, BorderLayout.CENTER);
        this.jPanel111113.add(this.deviceWaveDisplay13, BorderLayout.EAST);
        this.jPanel111113.add(this.deviceWave116, BorderLayout.WEST);
        this.jTabbedPane1.add(this.deviceChannel14, "12");
        this.deviceChannel14.add(this.jPanel111116, BorderLayout.CENTER);
        this.jPanel111116.add(this.jPanel213, BorderLayout.NORTH);
        this.jPanel213.add(this.deviceField315, null);
        this.jPanel111116.add(this.jPanel111114, BorderLayout.SOUTH);
        this.jPanel111114.add(this.deviceWave117, BorderLayout.NORTH);
        this.jPanel111114.add(this.jPanel111115, BorderLayout.SOUTH);
        this.jPanel111115.add(this.jLabel14, null);
        this.jPanel111115.add(this.deviceField11112, null);
        this.jPanel111115.add(this.deviceField213, null);
        this.jPanel111115.add(this.deviceField11111, null);
        this.jPanel111115.add(this.deviceField11113, null);
        this.jPanel111116.add(this.jPanel111117, BorderLayout.CENTER);
        this.jPanel111117.add(this.deviceWaveDisplay14, BorderLayout.EAST);
        this.jPanel111117.add(this.deviceWave118, BorderLayout.WEST);
    }
}
