/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class local_localDatabase */

#ifndef _Included_localDatabase
#define _Included_localDatabase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     local_localDatabase
 * Method:    addDevice
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lmds/NidData;
 */
  JNIEXPORT jobject JNICALL Java_local_localDatabase_addDevice(JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     local_localDatabase
 * Method:    addNode
 * Signature: (Ljava/lang/String;I)Lmds/NidData;
 */
  JNIEXPORT jobject JNICALL Java_local_localDatabase_addNode(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     local_localDatabase
 * Method:    close
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_close(JNIEnv *, jobject);

/*
 * Class:     local_localDatabase
 * Method:    executeDelete
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_executeDelete(JNIEnv *, jobject);

/*
 * Class:     local_localDatabase
 * Method:    getData
 * Signature: (Lmds/NidData;)Lmds/Data;
 */
  JNIEXPORT jobject JNICALL Java_local_localDatabase_getData(JNIEnv *, jobject, jobject);

/*
 * Class:     local_localDatabase
 * Method:    getDefault
 * Signature: ()Lmds/NidData;
 */
  JNIEXPORT jobject JNICALL Java_local_localDatabase_getDefault(JNIEnv *, jobject);

 /*
  * Class:     local_localDatabase
  * Method:    getFlags
  * Signature: (Lmds/NidData;)I;
  */
  JNIEXPORT jint JNICALL Java_local_localDatabase_getFlags(JNIEnv *, jobject, jobject);

/*
 * Class:     local_localDatabase
 * Method:    getInfo
 * Signature: (Lmds/NidData;)Lmds/NodeInfo;
 */
  JNIEXPORT jobject JNICALL Java_local_localDatabase_getInfo(JNIEnv *, jobject, jobject);

/*
 * Class:     local_localDatabase
 * Method:    getMembers
 * Signature: (Lmds/NidData;)[Lmds/NidData;
 */
  JNIEXPORT jobjectArray JNICALL Java_local_localDatabase_getMembers(JNIEnv *, jobject, jobject);

/*
 * Class:     local_localDatabase
 * Method:    getSons
 * Signature: (Lmds/Data/NidData;)[Lmds/Data/NidData;
 */
  JNIEXPORT jobjectArray JNICALL Java_local_localDatabase_getSons(JNIEnv *, jobject, jobject);

  /*
  * Class:     local_localDatabase
  * Method:    getTags
  * Signature: (Lmds/Data/NidData;)[Ljava/lang/String;
  */
  JNIEXPORT jobjectArray JNICALL Java_local_localDatabase_getTags(JNIEnv *, jobject, jobject);

  /*
 * Class:     local_localDatabase
 * Method:    isOn
 * Signature: (Lmds/Data/NidData;)Z
 */
  JNIEXPORT jboolean JNICALL Java_local_localDatabase_isOn(JNIEnv *, jobject, jobject);

/*
 * Class:     local_localDatabase
 * Method:    open
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_open(JNIEnv *, jobject);

/*
 * Class:     local_localDatabase
 * Method:    putData
 * Signature: (Lmds/Data/NidData;Lmds/Data;)V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_putData(JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     local_localDatabase
 * Method:    quit
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_quit(JNIEnv *, jobject);

/*
 * Class:     local_localDatabase
 * Method:    renameNode
 * Signature: (Lmds/Data/NidData;Ljava/lang/String;)V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_renameNode(JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     local_localDatabase
 * Method:    resolve
 * Signature: (Lmds/Data/PathData;)Lmds/NidData;
 */
  JNIEXPORT jobject JNICALL Java_local_localDatabase_resolve(JNIEnv *, jobject, jobject);

/*
 * Class:     local_localDatabase
 * Method:    setDefault
 * Signature: (Lmds/Data/NidData;)V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_setDefault(JNIEnv *, jobject, jobject);

/*
 * Class:     local_localDatabase
 * Method:    setOn
 * Signature: (Lmds/Data/NidData;Z)V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_setOn(JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     local_localDatabase
 * Method:    setTags
 * Signature: (Lmds/Data/NidData;[Ljava/lang/String;)V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_setTags(JNIEnv *, jobject, jobject, jobjectArray);

/*
* Class:     local_localDatabase
* Method:    setFlags
* Signature: (Lmds/Data/NidData;I;)
*/
JNIEXPORT void JNICALL Java_local_localDatabase_setFlags(JNIEnv *, jobject, jobject, jint);
/*
* Class:     local_localDatabase
* Method:    clearFlags
* Signature: (Lmds/Data/NidData;I;)
*/
JNIEXPORT void JNICALL Java_local_localDatabase_clearFlags(JNIEnv *, jobject, jobject, jint);

 /*
 * Class:     local_localDatabase
 * Method:    startDelete
 * Signature: ([Lmds/Data/NidData;)[Lmds/NidData;
 */
  JNIEXPORT jobjectArray JNICALL Java_local_localDatabase_startDelete
      (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     local_localDatabase
 * Method:    write
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_local_localDatabase_write(JNIEnv *, jobject);

/*
 * Class:     local_localDatabase
 * Method:    restoreContext
 * Signature: ()I
 */
 JNIEXPORT jint JNICALL Java_local_localDatabase_saveContext(JNIEnv * env, jobject obj) {

/*
 * Class:     local_localDatabase
 * Method:    restoreContext
 * Signature: ()V
 */
 JNIEXPORT void JNICALL Java_local_localDatabase_restoreContext(JNIEnv * env, jobject obj, void *context) {


#ifdef __cplusplus
}
#endif
#endif
