/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class local_localDataProvider */

#ifndef _Included_local_localDataProvider
#define _Included_local_localDataProvider
#ifdef __cplusplus
extern "C" {
#endif
#undef local_localDataProvider_RESAMPLE_TRESHOLD
#define local_localDataProvider_RESAMPLE_TRESHOLD 1000000000i64
#undef local_localDataProvider_MAX_PIXELS
#define local_localDataProvider_MAX_PIXELS 2000L
/*
 * Class:     local_localDataProvider
 * Method:    NativeIsSegmentedNode
 * Signature: (Ljava/lang/String;)Z
 */
  JNIEXPORT jboolean JNICALL Java_local_localDataProvider_NativeIsSegmentedNode(JNIEnv *, jclass, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetSegment
 * Signature: (Ljava/lang/String;II)[B
 */
  JNIEXPORT jbyteArray JNICALL Java_local_localDataProvider_NativeGetSegment(JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetAllFrames
 * Signature: (Ljava/lang/String;II)[B
 */
  JNIEXPORT jbyteArray JNICALL Java_local_localDataProvider_NativeGetAllFrames(JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetInfo
 * Signature: (Ljava/lang/String;Z)[I
 */
  JNIEXPORT jintArray JNICALL Java_local_localDataProvider_NativeGetInfo(JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetSegmentTimes
 * Signature: (Ljava/lang/String;Ljava/lang/String;FF)[F
 */
  JNIEXPORT jfloatArray JNICALL Java_local_localDataProvider_NativeGetSegmentTimes(JNIEnv *, jclass, jstring, jstring, jfloat, jfloat);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetAllTimes
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[F
 */
  JNIEXPORT jfloatArray JNICALL Java_local_localDataProvider_NativeGetAllTimes(JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetSegmentIdxs
 * Signature: (Ljava/lang/String;FF)[I
 */
  JNIEXPORT jintArray JNICALL Java_local_localDataProvider_NativeGetSegmentIdxs(JNIEnv *, jclass, jstring, jfloat, jfloat);

/*
 * Class:     local_localDataProvider
 * Method:    NativeSetEnvironmentSpecific
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
  JNIEXPORT void JNICALL Java_local_localDataProvider_NativeSetEnvironmentSpecific(JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeUpdate
 * Signature: (Ljava/lang/String;J)V
 */
  JNIEXPORT void JNICALL Java_local_localDataProvider_NativeUpdate(JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_local_localDataProvider_NativeGetString(JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetFloat
 * Signature: (Ljava/lang/String;)F
 */
  JNIEXPORT jfloat JNICALL Java_local_localDataProvider_NativeGetFloat(JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetLongArray
 * Signature: (Ljava/lang/String;)[J
 */
  JNIEXPORT jlongArray JNICALL Java_local_localDataProvider_NativeGetLongArray(JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetFloatArray
 * Signature: (Ljava/lang/String;)[F
 */
  JNIEXPORT jfloatArray JNICALL Java_local_localDataProvider_NativeGetFloatArray(JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetDoubleArray
 * Signature: (Ljava/lang/String;)[D
 */
  JNIEXPORT jdoubleArray JNICALL Java_local_localDataProvider_NativeGetDoubleArray(JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetIntArray
 * Signature: (Ljava/lang/String;)[I
 */
  JNIEXPORT jintArray JNICALL Java_local_localDataProvider_NativeGetIntArray(JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetByteArray
 * Signature: (Ljava/lang/String;)[B
 */
  JNIEXPORT jbyteArray JNICALL Java_local_localDataProvider_NativeGetByteArray(JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeErrorString
 * Signature: ()Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_local_localDataProvider_NativeErrorString(JNIEnv *, jobject);

/*
 * Class:     local_localDataProvider
 * Method:    NativeRegisterEvent
 * Signature: (Ljava/lang/String;I)I
 */
  JNIEXPORT jint JNICALL Java_local_localDataProvider_NativeRegisterEvent(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     local_localDataProvider
 * Method:    NativeUnregisterEvent
 * Signature: (I)V
 */
  JNIEXPORT void JNICALL Java_local_localDataProvider_NativeUnregisterEvent(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
